### PR TITLE
Upgrade the version of @fluentui/dom-utilities 

### PR DESCRIPTION
**Pull request by Annniee1**
Upgrade the version of @fluentui/dom-utilities from ^1.1.1 to ^2.2.3
We are using @fluentui/react-northstar in our repo . It pulls @fluentui/dom-utilities@^1.1.1 and we want upgraded version of @fluentui/dom-utilities i.e >2.2.3. We are getting **_Multiple versions of @fluentui/dom-utilities found_** error while doing the bundle for our package.,

## Related Issue(s)

* Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/20221afa1c8dde9afe17a278ddcc0a8a9a4817e2'>20221afa1c8dde9afe17a278ddcc0a8a9a4817e2</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by ling1726** [comment]
@Annniee1 you'll need to update the version in react-northstar too since the version bump should be consistent 

https://github.com/microsoft/fluentui/blob/696615b6a369e288a44ffa70f212593057709e6e/packages/fluentui/react-northstar/package.json#L10

If you try that I'd be interested to see if the CI still passes. AFAIR I attempted this and found out that there were breaking changes that would need to be addressed in northstar.

**Pull request closed without merging**
