### PR TITLE
BREAKING: Update string unions to `spinal-case`

### LINKED ISSUE #22697: Update all string union types to use `spinal-case`
Per #22596 we need to update all string union types to use `spinal-case`. Currently there is a mix and several components use `camelCase`

~NOTE: this is recommended as a breaking change as part of the move from RC to stable however, it can be done in a non-breaking way by adding `spinal-case` where needed, keeping the `camelCase` and marking the `camelCase` as deprecated.~

We're going ahead with the breaking change.

## List of changes to make

- [x] Avatar
    - [x] AvatarNamedColor
- [x] Badge
    - [x] PresenceBadgeStatus
- [x] Combobox
    - [x] Combobox.types appearance
    - [x] ComboButton.types apperance
- [x] Input
    - [x] appearance
- [x] Radio
    - [x] RadioGroup.types layout
- [x] Select
    - [x] appearance
- [x] SpinButton
    - [x] appearance
- [x] Tabster
    - [x] useFocusableGroup: tabBehavior
- [x] Textarea
    - [x] appearance

Related #22130

### PR DESCRIPTION
**Pull request by spmonahan**
BREAKING

## Current Behavior

String unions sometimes use `camelCase`

## New Behavior

All string unions use `spinal-case`

## Related Issue(s)
#22596

Fixes #22697

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |     Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                Change |
| :----------------------------------------------------------------------------------------- | ---------------------------: | --------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr> | `45.314 kB`<br />`13.175 kB` | `45.33 kB`<br />`13.182 kB` | `16 B` <br />`7 B`  |

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f43f5fa45ce881e096177e26f54072a7a2a562d5'>f43f5fa45ce881e096177e26f54072a7a2a562d5</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/Avatar-mount_base.html">1108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/Avatar-mount.html">1067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/Button-mount_base.html">653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/Button-mount.html">687</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProvider-mount_base.html">2246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProvider-mount.html">2223</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-mount_base.html">327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-mount.html">341</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">287</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">394</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">369</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/MakeStyles-mount_base.html">1874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23001/perf-test-react-components/MakeStyles-mount.html">1894</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by GeoffCoxMSFT — CHANGES_REQUESTED** [review]
Blocking until we are ready to merge breaking changes.

**Review by behowell — APPROVED** [review]

**Review by sopranopillow — APPROVED** [review]

**Comment by spmonahan** [comment]
> Card looks good 👍🏻
> 
> As a suggestion for next time, by following the past component migrations we can have smaller more digestible PRs. Another benefit is splitting the work load across the teams that hold the component knowledge.

Thanks for looking!

In general I agree that smaller PRs are better but in this case I felt that it was simpler to include the change in a single PR because it's a single topic and we want to be careful about when breaking changes are merged and that's easier to keep track of with fewer PRs.

**Pull request merged**
