### PR TITLE
fix: update validationState tokens for Progress

### PR DESCRIPTION
**Pull request by tomi-msft**
This PR updates the `validationState` tokens for `Progress`. They were previously foreground tokens, when they should be background.

### CODE REVIEW

**Review by khmakoto — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/Avatar-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/Avatar-mount.html">1279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/Button-mount_base.html">923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/Button-mount.html">934</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProvider-mount_base.html">1496</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProvider-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-mount_base.html">569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-mount.html">589</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">545</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">565</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">580</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/MakeStyles-mount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/MakeStyles-mount.html">1964</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/SpinButton-mount_base.html">2322</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25664/perf-test-react-components/SpinButton-mount.html">2306</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                |   Baseline (minified/GZIP) |                          PR |                                                                                                 Change |
| :----------------------------------------------------------------------------------------------- | -------------------------: | --------------------------: | -----------------------------------------------------------------------------------------------------: |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/Progress.fixture.js'>Progress</abbr> | `13.536 kB`<br />`5.11 kB` | `13.536 kB`<br />`5.107 kB` | <br />`-3 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.951 kB`<br />`17.675 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.958 kB`<br />`52.988 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.456 kB`<br />`11.029 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b75de6cbb07fae634938821eb1afef450e1e46ef'>b75de6cbb07fae634938821eb1afef450e1e46ef</a></sub>
<div id="bundleSizeComment9423"/>

**Review by sopranopillow — APPROVED** [review]

**Pull request merged**
