### PR TITLE
Remove active focus styles from Chevron because link already has them

### LINKED ISSUE #21971: Nested Nav links rendering incorrectly - two highlight bars
### Environment Information

- **Package version(s)**: @fluentui/react 8.57.1
- **Browser and OS versions**: Edge Version 99.0.1150.30 (Official build) (64-bit), Chrome Version 99.0.4844.51 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

      <Nav
        groups={[
          {
            links: [
              {
                name: "Top",
                url: '',
                key: "key1",
                links: [{
                  name: "Level 1",
                  url: '',
                  key: "key33",
                  links: [{
                    name: "Level 2",
                    url: '',
                    key: "key333",
                    target: "_blank",
                    links: [{
                      name: "Level 3",
                      url: '',
                      key: "key3333",
                    }],
                  }],
                },
                ]
              }
            ],
          },
        ]}
      />

#### Actual behavior:

image

Also loses the icon if present (all of the items should have an icon):

image

#### Expected behavior:

Link is showing two blue bars, expected 1 blue bar
Only happens on nested links with children, not top level (ie Top and Level 3 are okay, Level 1 and Level 2 show this behaviour)

### Priorities and help requested:

Either a fix or a styling workaround

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low): Normal

Products/sites affected: (if applicable)

Nav components with nested links

### PR DESCRIPTION
**Pull request by micahgodbolt**
Fixes #21971

before 

image

after 

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8ae039c29850b41be8c05ab0b54c0d4f1a340c3f'>8ae039c29850b41be8c05ab0b54c0d4f1a340c3f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/BaseButton-mount_base.html">1044</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/BaseButton-mount.html">1015</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Breadcrumb-mount_base.html">2824</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Breadcrumb-mount.html">2850</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Checkbox-mount_base.html">1669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Checkbox-mount.html">1655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/CheckboxBase-mount_base.html">1386</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/CheckboxBase-mount.html">1448</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ChoiceGroup-mount_base.html">5219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ChoiceGroup-mount.html">5263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ComboBox-mount_base.html">1026</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ComboBox-mount.html">1029</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/CommandBar-mount_base.html">10821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/CommandBar-mount.html">10786</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ContextualMenu-mount_base.html">11153</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ContextualMenu-mount.html">11361</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DefaultButton-mount_base.html">1255</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DefaultButton-mount.html">1249</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRow-mount_base.html">4043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRow-mount.html">4139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRowFast-mount_base.html">4007</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRowFast-mount.html">3997</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRowNoStyles-mount_base.html">3815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DetailsRowNoStyles-mount.html">3823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Dialog-mount_base.html">2373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Dialog-mount.html">2328</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DocumentCardTitle-mount_base.html">177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/DocumentCardTitle-mount.html">171</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Dropdown-mount_base.html">3528</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Dropdown-mount.html">3609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/FocusTrapZone-mount_base.html">1981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/FocusTrapZone-mount.html">1849</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/FocusZone-mount_base.html">1844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/FocusZone-mount.html">1852</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/IconButton-mount_base.html">2028</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/IconButton-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Label-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Label-mount.html">376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Layer-mount_base.html">3172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Layer-mount.html">3153</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Link-mount_base.html">484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Link-mount.html">484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/MenuButton-mount_base.html">1595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/MenuButton-mount.html">1632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/MessageBar-mount_base.html">2256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/MessageBar-mount.html">2189</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Nav-mount_base.html">3441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Nav-mount.html">3457</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/OverflowSet-mount_base.html">1147</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/OverflowSet-mount.html">1149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Panel-mount_base.html">2294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Panel-mount.html">2233</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Persona-mount_base.html">1048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Persona-mount.html">1082</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Pivot-mount_base.html">1521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Pivot-mount.html">1546</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/PrimaryButton-mount_base.html">1352</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/PrimaryButton-mount.html">1391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Rating-mount_base.html">8378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Rating-mount.html">8310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SearchBox-mount_base.html">1455</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SearchBox-mount.html">1446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Shimmer-mount_base.html">2664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Shimmer-mount.html">2736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Slider-mount_base.html">2032</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Slider-mount.html">2047</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SpinButton-mount_base.html">5324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SpinButton-mount.html">5237</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Spinner-mount_base.html">444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Spinner-mount.html">453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SplitButton-mount_base.html">3360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SplitButton-mount.html">3618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Stack-mount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Stack-mount.html">571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/StackWithIntrinsicChildren-mount_base.html">2557</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/StackWithIntrinsicChildren-mount.html">2551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/StackWithTextChildren-mount_base.html">5834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/StackWithTextChildren-mount.html">5817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SwatchColorPicker-mount_base.html">12239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/SwatchColorPicker-mount.html">12376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TagPicker-mount_base.html">2951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TagPicker-mount.html">2872</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TeachingBubble-mount_base.html">88287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TeachingBubble-mount.html">88128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Text-mount_base.html">487</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Text-mount.html">436</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TextField-mount_base.html">1478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/TextField-mount.html">1497</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-mount_base.html">1214</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-mount.html">1248</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-virtual-rerender_base.html">661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-virtual-rerender.html">647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1990</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1963</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Toggle-mount_base.html">830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/Toggle-mount.html">850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/buttonNative-mount_base.html">132</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22514/perf-test/buttonNative-mount.html">137</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
Talked to ODSP Designer and he can't think of any reason the chevron would need an active/selected state.

**Review by sopranopillow — APPROVED** [review]
Looks nice!

**Pull request merged**
