### PR TITLE
List: Re-initialize on mount in React 18.

### LINKED ISSUE #29880: [Bug]: List virtualization won't work in Strict mode
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:                                                      
    OS: Windows 10 10.0.19045                                  
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.18 GB / 31.69 GB                                 
  Browsers:                                                    
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.44)  
    Internet Explorer: 11.0.19041.3570
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/m-verbakel-eshgro/pen/WNPMaGN

## Actual Behavior
When rendering a list with virtualization enabled _in strict mode_, the next page is not rendered.

## Expected Behavior
Rendering a list with virtualization enabled _in strict mode_ behaves the same as a list with virtualization enabled _without strict mode_.

## Cause
Strict mode renders the component twice. To do this, the component is unmounted and then remounted. In [List.componentWillUnmount](https://github.com/microsoft/fluentui/blob/1a26dc71a18fed4b842ec6b551189da2d0c389b2/packages/react/src/components/List/List.tsx#L394), a dispose is called on the `EventGroup`. However, since the `EventGroup` is only instantiated in the constructor, the disposed `EventGroup` is reused when `componentDidMount` is called again. Hence, the event listeners for scrolling are added, but they immediately return [because their group is disposed](https://github.com/microsoft/fluentui/blob/873b079e8c57fc139366d6ab57d9070abd81865a/packages/utilities/src/EventGroup.ts#L207).

This seems to be related to https://github.com/microsoft/fluentui/issues/28230#issuecomment-1593363167.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by mhverbakel**
Fixes #29880.

Better approach now. Moving async AND event to componentDidMount will make sure they are instantiated each time the component is mounted (which is twice in R18 strict)

### CODE REVIEW

**Comment by mhverbakel** [comment]
@microsoft-github-policy-service agree company="Eshgro"

**Comment by spmonahan** [comment]
Thanks for the PR @mhverbakel !

@ThomasMichon I'd appreciate your review on this as it's a substantive change to List behavior.

**Review by ThomasMichon — APPROVED** [review]

**Review by spmonahan — APPROVED** [review]

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b6766ba321b57331266f3f391d7274c77730459d'>b6766ba321b57331266f3f391d7274c77730459d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/BaseButton-mount_base.html">627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/BaseButton-mount.html">642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Breadcrumb-mount_base.html">1649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Breadcrumb-mount.html">1670</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Checkbox-mount_base.html">1661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Checkbox-mount.html">1677</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/CheckboxBase-mount_base.html">1486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/CheckboxBase-mount.html">1498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ChoiceGroup-mount_base.html">3013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ChoiceGroup-mount.html">2961</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ComboBox-mount_base.html">652</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ComboBox-mount.html">662</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/CommandBar-mount_base.html">6215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/CommandBar-mount.html">6229</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ContextualMenu-mount_base.html">11758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ContextualMenu-mount.html">12026</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DefaultButton-mount_base.html">762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DefaultButton-mount.html">774</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRow-mount_base.html">2193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRow-mount.html">2210</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRowFast-mount_base.html">2163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRowFast-mount.html">2197</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRowNoStyles-mount_base.html">2077</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DetailsRowNoStyles-mount.html">2056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Dialog-mount_base.html">2623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Dialog-mount.html">2639</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DocumentCardTitle-mount_base.html">216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/DocumentCardTitle-mount.html">222</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Dropdown-mount_base.html">1969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Dropdown-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/FocusTrapZone-mount_base.html">1165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/FocusTrapZone-mount.html">1168</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/FocusZone-mount_base.html">1076</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/FocusZone-mount.html">1065</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-mount_base.html">42016</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-mount.html">42292</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-virtual-rerender_base.html">18070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-virtual-rerender.html">19999</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">51321</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedList-virtual-rerender-with-unmount.html">51246</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-mount_base.html">225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-mount.html">223</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-virtual-rerender_base.html">211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-virtual-rerender.html">208</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">229</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/IconButton-mount_base.html">1088</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/IconButton-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Label-mount_base.html">346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Label-mount.html">330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Layer-mount_base.html">2746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Layer-mount.html">2738</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Link-mount_base.html">395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Link-mount.html">398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/MenuButton-mount_base.html">945</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/MenuButton-mount.html">965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/MessageBar-mount_base.html">21296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/MessageBar-mount.html">21374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Nav-mount_base.html">1972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Nav-mount.html">1919</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/OverflowSet-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/OverflowSet-mount.html">764</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Panel-mount_base.html">2019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Panel-mount.html">1748</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Persona-mount_base.html">732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Persona-mount.html">743</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Pivot-mount_base.html">877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Pivot-mount.html">881</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/PrimaryButton-mount_base.html">860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/PrimaryButton-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Rating-mount_base.html">4591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Rating-mount.html">4698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SearchBox-mount_base.html">962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SearchBox-mount.html">903</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Shimmer-mount_base.html">1857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Shimmer-mount.html">1890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Slider-mount_base.html">1307</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Slider-mount.html">1328</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SpinButton-mount_base.html">2909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SpinButton-mount.html">2867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Spinner-mount_base.html">388</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Spinner-mount.html">380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SplitButton-mount_base.html">1834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SplitButton-mount.html">1860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Stack-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Stack-mount.html">404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/StackWithIntrinsicChildren-mount_base.html">870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/StackWithIntrinsicChildren-mount.html">861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/StackWithTextChildren-mount_base.html">2676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/StackWithTextChildren-mount.html">2651</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SwatchColorPicker-mount_base.html">6264</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/SwatchColorPicker-mount.html">6216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/TagPicker-mount_base.html">1463</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/TagPicker-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Text-mount_base.html">369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Text-mount.html">373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/TextField-mount_base.html">915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/TextField-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-mount.html">839</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-virtual-rerender_base.html">588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-virtual-rerender.html">579</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Toggle-mount_base.html">603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/Toggle-mount.html">609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/buttonNative-mount_base.html">199</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29881/perf-test/buttonNative-mount.html">184</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by spmonahan** [comment]
@mhverbakel Looks like some tests are failing: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=328378&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5&l=19720

**Comment by mhverbakel** [comment]
@spmonahan I fixed the tests in d38349bd637c9a4dc443a997901df56885395e9e, however, I could not find the reason why those lines were there in the first place. I've looked at the history of the file, trying to figure out what they originally meant.

These lines were there from the start, and without them, everything works just fine. My assumption is that `componentDidMount` did some heavy work that was unnecessary for the tests, and this was just a performance improvement.

**Pull request merged**
