### PR TITLE
Tablist : added aria-orientation attribute

### LINKED ISSUE #23964: [Bug]: Vertical TabList missing aria-orientation="vertical" attribute
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-tablist--default

## Repro steps
1. Visit the [TabList component storybook documentation page ](https://react.fluentui.dev/?path=/docs/components-tablist--default).
2. Find the "Vertical" story of the TabList component.
3. Inspect the code of the tablist element.

## Actual Behavior
The element with the role="tablist" is missing the aria-orientation="vertical" attribute.

## Expected Behavior
The tablist element should have the aria-orientation="vertical" attribute set.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by kkakroo**
## Previous Behavior
Tablist was missing `aria-orientation` attribute

## New Behavior
Added `aria-orientation` attribute to `vertical` and `horizontal` variants of tablist

## Related Issue(s)

- Fixes #23964

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `67.994 kB`<br />`18.395 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `207.4 kB`<br />`57.516 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `38.819 kB`<br />`12.351 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.446 kB`<br />`2.185 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/34dec1d344736ea7be694d29c9429c40f5cb6c9e'>34dec1d344736ea7be694d29c9429c40f5cb6c9e</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Avatar-mount_base.html">1074</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Avatar-mount.html">1050</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Button-mount_base.html">668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Button-mount.html">688</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Field-mount_base.html">1893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Field-mount.html">1901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProvider-mount_base.html">1405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProvider-mount.html">1425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-mount_base.html">354</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-mount.html">365</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">314</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">407</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">369</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/InfoButton-mount_base.html">247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/InfoButton-mount.html">262</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/MakeStyles-mount_base.html">1553</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/MakeStyles-mount.html">1556</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Persona-mount_base.html">2703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/Persona-mount.html">2708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/SpinButton-mount_base.html">2356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27315/perf-test-react-components/SpinButton-mount.html">2406</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by GeoffCoxMSFT — APPROVED** [review]

**Comment by GeoffCoxMSFT** [comment]
@kkakroo - Thank you so much for fixing this issue!

**Pull request merged**
