### PR TITLE
Remove explicit blocking of Alt key for keytip start sequence

### PR DESCRIPTION
**Pull request by kelseyyoung**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

When writing keytips initially we had blocked the recognition of the "Alt" key because that is reserved for putting focus on the top bar of the browser. However there are users of Keytips that are writing their app in an Electron application that looks and behaves like a native desktop app. In native desktop apps the default key for keytips is just "Alt", and because they don't run in a traditional browser they won't have any issues using it

#### Focus areas to test

Tested that with removing these lines that you can specify "Alt" to start your keytips. If done in a traditional browser this will "break" in the sense that keytips will appear but focus will also go to the browser top bar, meaning the user can't interact with keytips

### CODE REVIEW

**Comment by kelseyyoung** [comment]
When I run "yarn change" from the root it shows that I have changes in like 20 packages, and that there is also already a change file for office-ui-fabric-react. Not sure what I should do here? yarn clean maybe?

**Comment by ecraig12345** [comment]
@kelseyyoung You probably need to update the URL for your `upstream` remote to microsoft/fluentui.

**Comment by kelseyyoung** [comment]
@ecraig12345 any chance you could take a look at this?

**Comment by ecraig12345** [comment]
@kelseyyoung I don't really know anything about keytips and their expected behavior--so maybe get @jspurlin to review instead? (looks like he's worked on this in the past)

**Pull request merged**
