### PR TITLE
ContextualMenu: Add prop that allows users to wrap a custom tooltip around each menu item button

### LINKED ISSUE #19862: When ToolTipHost is wrapping a button's context menu items, a tool tip is not always shown
Note:
Reopening issue https://github.com/microsoft/fluentui/issues/15512. 
We are getting pushbacks from accessibility team on that - https://dev.azure.com/kusto/Kusto/_workitems/edit/1045. 

When wrapping a button's sub items with ToolTipHost no tool tip is shown when changing focus with the keyboard and also when hovering over the first context item for the first time.

## Environment Information
* Package version(s): 7.93.0 and 7.142.1
* Browser and OS versions: Edge 86

## Please provide a reproduction of the bug in a codepen:
https://codepen.io/izlisbon/pen/zYBrByg

**Actual behavior**:
* ToolTip is not shown on first hover
* ToolTip is not shown when changing focus with keyboard

**Expected behavior**:
* Tooltip should always be shown on hover.
* Tooltip should show when changing focus with keyboard (This is an accessibility requirement and it works fine on the button itself)

## Priorities and help requested:
Are you willing to submit a PR to fix? (Yes, No) - No

**Requested priority**: (Blocking, High, Normal, Low) - High just because most accessibility bugs are high.

**Products/sites affected**: (if applicable)
https://dataexplorer.azure.com/clusters/help/databases/Samples?query=H4sIAAAAAAAAA3POL8tMMbSMT8tJLOGqUShJzE5VMDQAAEp2jSoWAAAA

Click run and then open the Expand View button:

### PR DESCRIPTION
**Pull request by TristanWatanabe**
Please verify that:
* [x] Code is up-to-date with the `master` branch
* [x] Your changes are covered by tests (if possible)
* [x] You've run `yarn change` locally

## Current Behavior

- There's currently no appropriate way to wrap each menu item in a `ContextualMenu` in a custom tooltip. Using the current `contextualMenuItemAs` prop overrides the children of the menu item button and doesn't include the button itself. This results in the tooltip not rendering when a menu item button receives keyboard focus. 

- ### Tooltip doesnt render on keyboard focus: 
ContextualMenuTooltipBefore

## New Behavior:
- A new prop called `onRenderContextualMenuItem` is now added to enable consumers to wrap the contextual menu item button in a tooltip. Now, when a menu item receives keyboard focus, the tooltip is rendered appropriately.

- ### Tooltip now renders on keyboard focus: 
ContextualMenuTooltipAfter

## Related Issue(s)

Fixes #19862

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0b7d30b6ecb6f20d2ac4d4edbfb327a8f8f915a0'>0b7d30b6ecb6f20d2ac4d4edbfb327a8f8f915a0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Avatar-mount_base.html">876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Avatar-mount.html">893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/BaseButton-mount_base.html">943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/BaseButton-mount.html">952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Breadcrumb-mount_base.html">2631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Breadcrumb-mount.html">2677</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ButtonNext-mount_base.html">471</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ButtonNext-mount.html">477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Checkbox-mount_base.html">1527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Checkbox-mount.html">1559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/CheckboxBase-mount_base.html">1327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/CheckboxBase-mount.html">1311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ChoiceGroup-mount_base.html">4837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ChoiceGroup-mount.html">4768</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ComboBox-mount_base.html">981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ComboBox-mount.html">1001</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/CommandBar-mount_base.html">10180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/CommandBar-mount.html">10247</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ContextualMenu-mount_base.html">8400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ContextualMenu-mount.html">8325</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DefaultButton-mount_base.html">1145</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DefaultButton-mount.html">1166</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRow-mount_base.html">3701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRow-mount.html">3702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRowFast-mount_base.html">3758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRowFast-mount.html">3724</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRowNoStyles-mount_base.html">3544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DetailsRowNoStyles-mount.html">3534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Dialog-mount_base.html">2235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Dialog-mount.html">2220</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DocumentCardTitle-mount_base.html">191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/DocumentCardTitle-mount.html">168</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Dropdown-mount_base.html">3270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Dropdown-mount.html">3215</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderNext-mount_base.html">1851</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderNext-mount.html">1896</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-mount_base.html">170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-mount.html">161</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-virtual-rerender.html">111</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">202</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">200</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FocusTrapZone-mount_base.html">1872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FocusTrapZone-mount.html">1882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FocusZone-mount_base.html">1816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/FocusZone-mount.html">1797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/IconButton-mount_base.html">1758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/IconButton-mount.html">1784</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Label-mount_base.html">364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Label-mount.html">374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Layer-mount_base.html">3035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Layer-mount.html">2975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Link-mount_base.html">517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Link-mount.html">494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MakeStyles-mount_base.html">1714</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MakeStyles-mount.html">1702</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MenuButton-mount_base.html">1498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MenuButton-mount.html">1489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MessageBar-mount_base.html">2007</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/MessageBar-mount.html">2036</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Nav-mount_base.html">3309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Nav-mount.html">3309</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/OverflowSet-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/OverflowSet-mount.html">1128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Panel-mount_base.html">2180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Panel-mount.html">2162</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Persona-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Persona-mount.html">855</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Pivot-mount_base.html">1452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Pivot-mount.html">1437</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/PrimaryButton-mount_base.html">1356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/PrimaryButton-mount.html">1310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Rating-mount_base.html">7603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Rating-mount.html">7640</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SearchBox-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SearchBox-mount.html">1356</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Shimmer-mount_base.html">2547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Shimmer-mount.html">2541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Slider-mount_base.html">1980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Slider-mount.html">1977</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SpinButton-mount_base.html">5095</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SpinButton-mount.html">5089</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Spinner-mount_base.html">477</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Spinner-mount.html">443</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SplitButton-mount_base.html">3168</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SplitButton-mount.html">3141</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Stack-mount_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Stack-mount.html">544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/StackWithIntrinsicChildren-mount_base.html">2299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/StackWithIntrinsicChildren-mount.html">2297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/StackWithTextChildren-mount_base.html">5249</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/StackWithTextChildren-mount.html">5278</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SwatchColorPicker-mount_base.html">11496</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/SwatchColorPicker-mount.html">11504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TagPicker-mount_base.html">2614</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TagPicker-mount.html">2644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TeachingBubble-mount_base.html">13372</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TeachingBubble-mount.html">13309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Text-mount_base.html">460</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Text-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TextField-mount_base.html">1426</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/TextField-mount.html">1437</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-mount_base.html">1210</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-mount.html">1212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-virtual-rerender_base.html">649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-virtual-rerender.html">641</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1897</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Toggle-mount_base.html">835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/Toggle-mount.html">828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/buttonNative-mount_base.html">153</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21707/perf-test/buttonNative-mount.html">153</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
Using `contextualMenuItemAs`, can't you import the `ContextualMenuItem` and then create a custom MenuItem?

```tsx
const CustomMenuItem = (props) => {
  <TooltipHost><ContextualMenuItem {...props}/> </TooltipHost>
}
```

If the above is possible, I don't think we should add more to the API surface. 

Typically 'onRender' functions are used for parts of the component that aren't exported, so a user wouldn't have access to. thingAs is used when the `thing` is exported and could be wrapped, or replaced.

**Comment by TristanWatanabe** [comment]
> Using `contextualMenuItemAs`, can't you import the `ContextualMenuItem` and then create a custom MenuItem?
> 
> ```tsx
> const CustomMenuItem = (props) => {
>   <TooltipHost><ContextualMenuItem {...props}/> </TooltipHost>
> }
> ```
> 
> If the above is possible, I don't think we should add more to the API surface.


@micahgodbolt Doing the above unfortunately doesn't work (codepen [here ](contextualmenuitemas) demonstrating that implementation). This is because `contextualMenuItemAs`  is being passed as a prop to the `ContextualMenuButton` (passed as `commonProps` [here](https://github.com/microsoft/fluentui/blob/24fa2b03d52a750aeec7fbfd3d8bba1fcb2d4fe3/packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx#L1068)) and being rendered as a child. In order for the `ContextualMenuButton` to render the tooltip on keyboard focus, the button itself needs to be wrapped in a `TooltipHost` which is what adding this prop would do.

**Review by micahgodbolt — APPROVED** [review]

**Pull request merged**
