### PR TITLE
chore (CI): delete Screener workflows

### PR DESCRIPTION
**Pull request by TristanWatanabe**
## Changes:
- deletes github `Screener` workflow files so `Screener` to permanently stop running it in the repo.

## Related Issue(s)

* Part of #25078

### CODE REVIEW

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25977&commitId=a156725d47e2a954cbca0bdca65f3417532eac8d&env=prod)

✅ There was 2 screenshots added, 0 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/BaseButton-mount_base.html">1164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/BaseButton-mount.html">1211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Breadcrumb-mount_base.html">3009</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Breadcrumb-mount.html">3012</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Checkbox-mount_base.html">2648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Checkbox-mount.html">2617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/CheckboxBase-mount_base.html">2330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/CheckboxBase-mount.html">2330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ChoiceGroup-mount_base.html">4480</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ChoiceGroup-mount.html">4492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ComboBox-mount_base.html">1248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ComboBox-mount.html">1208</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/CommandBar-mount_base.html">9676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/CommandBar-mount.html">9667</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ContextualMenu-mount_base.html">10916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ContextualMenu-mount.html">10889</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DefaultButton-mount_base.html">1356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DefaultButton-mount.html">1421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRow-mount_base.html">3575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRow-mount.html">3506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRowFast-mount_base.html">3569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRowFast-mount.html">3663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRowNoStyles-mount_base.html">3408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DetailsRowNoStyles-mount.html">3430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Dialog-mount_base.html">3073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Dialog-mount.html">2967</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DocumentCardTitle-mount_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/DocumentCardTitle-mount.html">528</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Dropdown-mount_base.html">3113</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Dropdown-mount.html">3219</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/FocusTrapZone-mount_base.html">1988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/FocusTrapZone-mount.html">1956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/FocusZone-mount_base.html">1923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/FocusZone-mount.html">1943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-mount_base.html">1939</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-mount.html">2129</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-virtual-rerender_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-virtual-rerender.html">1131</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedList-virtual-rerender-with-unmount.html">1682</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-mount_base.html">598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-mount.html">565</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-virtual-rerender_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-virtual-rerender.html">536</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">565</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">554</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/IconButton-mount_base.html">1929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/IconButton-mount.html">1893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Label-mount_base.html">749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Label-mount.html">742</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Layer-mount_base.html">4305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Layer-mount.html">4431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Link-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Link-mount.html">821</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/MenuButton-mount_base.html">1665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/MenuButton-mount.html">1664</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/MessageBar-mount_base.html">2381</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/MessageBar-mount.html">2540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Nav-mount_base.html">3163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Nav-mount.html">3247</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/OverflowSet-mount_base.html">1378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/OverflowSet-mount.html">1294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Panel-mount_base.html">2467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Panel-mount.html">2547</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Persona-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Persona-mount.html">1330</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Pivot-mount_base.html">1657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Pivot-mount.html">1627</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/PrimaryButton-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/PrimaryButton-mount.html">1504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Rating-mount_base.html">6591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Rating-mount.html">7027</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SearchBox-mount_base.html">1464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SearchBox-mount.html">1490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Shimmer-mount_base.html">2691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Shimmer-mount.html">2705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Slider-mount_base.html">2043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Slider-mount.html">1974</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SpinButton-mount_base.html">4629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SpinButton-mount.html">4534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Spinner-mount_base.html">791</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Spinner-mount.html">815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SplitButton-mount_base.html">3005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SplitButton-mount.html">3117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Stack-mount_base.html">830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Stack-mount.html">816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/StackWithIntrinsicChildren-mount_base.html">2357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/StackWithIntrinsicChildren-mount.html">2316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/StackWithTextChildren-mount_base.html">4626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/StackWithTextChildren-mount.html">4850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SwatchColorPicker-mount_base.html">10109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/SwatchColorPicker-mount.html">10256</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TagPicker-mount_base.html">2602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TagPicker-mount.html">2588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TeachingBubble-mount_base.html">84019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TeachingBubble-mount.html">85120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Text-mount_base.html">735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Text-mount.html">785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TextField-mount_base.html">1554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/TextField-mount.html">1548</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-mount_base.html">1489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-mount.html">1539</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-virtual-rerender_base.html">1068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-virtual-rerender.html">1026</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Toggle-mount_base.html">1091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/Toggle-mount.html">1073</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/buttonNative-mount_base.html">521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25977/perf-test/buttonNative-mount.html">541</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
