### PR TITLE
bugfix: enables Escape to dismiss alert Dialog

### LINKED ISSUE #28010: [Bug]:  Enable Escape to dismiss alert Dialog
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In the alert Dialog variant, it should be possible to dismiss the dialog using the Escape key. This would be in accord with the [alert dialog example implemented by W3C](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/examples/alertdialog/).

### Have you discussed this feature with our team

_No response_

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by bsunderhus**
## Previous Behavior

1. an alert dialog would not close on Escape key press

## New Behavior

1. an alert dialog now closes on Escape key press
2. change wrongly named file `useDialogTrigger.styles.ts`

## Related Issue(s)

- Fixes #28010

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `65.162 kB`<br />`17.952 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `210.365 kB`<br />`58.697 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `36.395 kB`<br />`11.996 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |   `92.072 kB`<br />`27.46 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.473 kB`<br />`2.196 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5809e04461b488016393f68d0c809d5b43eb93db'>5809e04461b488016393f68d0c809d5b43eb93db</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by ling1726 — APPROVED** [review]

**Comment by goamn** [comment]
@bsunderhus @ling1726 Why is the Escape key allowed to close the Dialog with modalType="alert"? This doesn't make sense to me. Now there is no way to create a Dialog that can not be closed. Alert was the only modalType to prevent the Dialog from closing and forcing a user to take an action. Both Modal or non-Modal allow the user to close the Dialog. Also now the documentary is invalid, please see below:
image

**Comment by bsunderhus** [comment]
> Also now the documentary is invalid

Hey there @goamn, you're completely right, I'll see to create an issue to update the documentation!

> Why is the Escape key allowed to close the Dialog with modalType="alert"? This doesn't make sense to me.

This change is due to [WAI-ARIA alertdialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/)  compliance, an alert dialog has no such feature! you should always be able to close a dialog by pressing the `Escape` button.

> Now there is no way to create a Dialog that can not be closed. Alert was the only modalType to prevent the Dialog from closing and forcing a user to take an action. Both Modal or non-Modal allow the user to close the Dialog.

You can still control the opening state and avoid opening on `Escape`  by using the controlled version of a dialog:

https://codesandbox.io/s/sad-star-c7ytcs?file=/example.tsx

**Comment by goamn** [comment]
Hello, ok thank you, at least there is a second way :)

**Pull request merged**
