### PR TITLE
fix: dependency mismatch after 9.2.0 release

### PR DESCRIPTION
**Pull request by ling1726**

### CODE REVIEW

**Review by Hotell — APPROVED** [review]

**Comment by Hotell** [comment]
what caused this ? if it's a new issue can you create issue for that ? ty

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `192.699 kB`<br />`52.786 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.688 kB`<br />`10.736 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/ee4a8be0d0831a6615f878f98db6a97cc61a802d'>ee4a8be0d0831a6615f878f98db6a97cc61a802d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/Avatar-mount_base.html">1293</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/Avatar-mount.html">1327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/Button-mount_base.html">953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/Button-mount.html">960</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProvider-mount_base.html">1578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProvider-mount.html">1571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-mount_base.html">611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-mount.html">630</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">586</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">617</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/MakeStyles-mount_base.html">1904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/MakeStyles-mount.html">1916</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/SpinButton-mount_base.html">2583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24206/perf-test-react-components/SpinButton-mount.html">2615</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by ling1726** [comment]
@Hotell  created issue #24207

**Pull request merged**
