### PR TITLE
feat: adds react-dialog to react-components unstable

### PR DESCRIPTION
**Pull request by bsunderhus**
## Current Behavior

Adds `Dialog` components to `react-components` unstable

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `190.54 kB`<br />`52.487 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `32.036 kB`<br />`10.577 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    | `83.707 kB`<br />`25.013 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/1a68474f2cb95050402b4d6ada8288114c3a2233'>1a68474f2cb95050402b4d6ada8288114c3a2233</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/Avatar-mount_base.html">1312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/Avatar-mount.html">1336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/Button-mount_base.html">899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/Button-mount.html">903</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProvider-mount_base.html">1573</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProvider-mount.html">1593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-mount_base.html">628</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-mount.html">621</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">594</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">628</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/MakeStyles-mount_base.html">1926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/MakeStyles-mount.html">1922</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/SpinButton-mount_base.html">2636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24140/perf-test-react-components/SpinButton-mount.html">2624</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by ling1726 — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Comment by layershifter** [comment]
image

As my comment was not addressed (https://github.com/microsoft/fluentui/pull/23963#discussion_r932428474) now `Dialog` appears under stable components 🙀 @bsunderhus please fix it before a potential release will happen...

**Comment by bsunderhus** [comment]
Thx for the heads up @layershifter! I'll look into this immediately!

**Pull request merged**
