### PR TITLE
chore: ignore more patterns for lage --since resolution

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

- changes to codeowners or some docs within `.github/` will trigger pipeline for all repo

## New Behavior

- changes for codeowners etc will not trigger any build tasks on PR pipeline

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Avatar-mount_base.html">1254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Avatar-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Button-mount_base.html">910</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Button-mount.html">902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProvider-mount_base.html">1500</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProvider-mount.html">1479</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-mount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-mount.html">575</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">547</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">574</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/MakeStyles-mount_base.html">1965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/MakeStyles-mount.html">1960</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Persona-mount_base.html">2802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/Persona-mount.html">2785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/SpinButton-mount_base.html">2334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test-react-components/SpinButton-mount.html">2334</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount_base.html">2300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount.html">2559</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/BaseButton-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/BaseButton-mount.html">1477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Breadcrumb-mount_base.html">3522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Breadcrumb-mount.html">3506</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Checkbox-mount_base.html">3178</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Checkbox-mount.html">3212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/CheckboxBase-mount_base.html">2835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/CheckboxBase-mount.html">2862</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ChoiceGroup-mount_base.html">5458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ChoiceGroup-mount.html">5437</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ComboBox-mount_base.html">1487</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ComboBox-mount.html">1472</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/CommandBar-mount_base.html">11055</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/CommandBar-mount.html">11337</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ContextualMenu-mount_base.html">12162</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ContextualMenu-mount.html">12167</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DefaultButton-mount_base.html">1703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DefaultButton-mount.html">1705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRow-mount_base.html">4274</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRow-mount.html">4410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRowFast-mount_base.html">4323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRowFast-mount.html">4350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRowNoStyles-mount_base.html">4118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DetailsRowNoStyles-mount.html">4110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Dialog-mount_base.html">3608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Dialog-mount.html">3677</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DocumentCardTitle-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/DocumentCardTitle-mount.html">652</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Dropdown-mount_base.html">3869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Dropdown-mount.html">3871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/FocusTrapZone-mount_base.html">2281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/FocusTrapZone-mount.html">2269</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/FocusZone-mount_base.html">2210</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/FocusZone-mount.html">2252</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount_base.html">2300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount.html">2559</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-virtual-rerender_base.html">1321</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-virtual-rerender.html">1333</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedList-virtual-rerender-with-unmount.html">1934</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-mount_base.html">645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-mount.html">626</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-virtual-rerender_base.html">646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-virtual-rerender.html">621</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">630</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">667</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/IconButton-mount_base.html">2304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/IconButton-mount.html">2276</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Label-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Label-mount.html">878</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Layer-mount_base.html">5018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Layer-mount.html">5070</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Link-mount_base.html">975</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Link-mount.html">930</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/MenuButton-mount_base.html">2060</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/MenuButton-mount.html">2024</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/MessageBar-mount_base.html">2652</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/MessageBar-mount.html">2700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Nav-mount_base.html">4288</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Nav-mount.html">3910</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/OverflowSet-mount_base.html">1553</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/OverflowSet-mount.html">1548</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Panel-mount_base.html">2972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Panel-mount.html">3008</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Persona-mount_base.html">1541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Persona-mount.html">1586</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Pivot-mount_base.html">1950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Pivot-mount.html">1914</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/PrimaryButton-mount_base.html">1788</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/PrimaryButton-mount.html">1796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Rating-mount_base.html">8560</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Rating-mount.html">8665</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SearchBox-mount_base.html">1834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SearchBox-mount.html">1813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Shimmer-mount_base.html">3367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Shimmer-mount.html">3473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Slider-mount_base.html">2467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Slider-mount.html">2517</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SpinButton-mount_base.html">5589</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SpinButton-mount.html">5660</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Spinner-mount_base.html">932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Spinner-mount.html">942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SplitButton-mount_base.html">3702</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SplitButton-mount.html">3723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Stack-mount_base.html">963</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Stack-mount.html">966</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/StackWithIntrinsicChildren-mount_base.html">2956</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/StackWithIntrinsicChildren-mount.html">2956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/StackWithTextChildren-mount_base.html">6208</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/StackWithTextChildren-mount.html">6205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SwatchColorPicker-mount_base.html">12586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/SwatchColorPicker-mount.html">12861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TagPicker-mount_base.html">3206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TagPicker-mount.html">3319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TeachingBubble-mount_base.html">94531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TeachingBubble-mount.html">98944</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Text-mount_base.html">943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Text-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TextField-mount_base.html">2036</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/TextField-mount.html">1945</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-mount_base.html">1972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-mount.html">1917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-virtual-rerender_base.html">1318</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-virtual-rerender.html">1336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2621</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Toggle-mount_base.html">1357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/Toggle-mount.html">1360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/buttonNative-mount_base.html">674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26140/perf-test/buttonNative-mount.html">661</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
