### PR TITLE
Change question issue template to a link

### PR DESCRIPTION
**Pull request by micahgodbolt**
This creates an 'issue template' that is simply a link 

image

### CODE REVIEW

**Comment by micahgodbolt** [comment]
delete the other 'question' entry after this is in

**Comment by ecraig12345** [comment]
Can you just delete the question template in this PR too?

**Comment by micahgodbolt** [comment]
i just created the file via the github gui :D not sure how i can add that deletion onto this

**Comment by micahgodbolt** [comment]
ok...i'll stop being lazy and I cloned the repo, deleted the file, pushed

**Comment by micahgodbolt** [comment]
feel free to change this to whatever you like...i just saw this link example and thought it was a MUCH better approach to what we're doing here

**Comment by ecraig12345** [comment]
I updated the link to also mention that we have Teams for MS employees (I think that's important to call out).

One remaining question, what tag should people use? The old question template suggests 2 or 3 different ones, and I'm not sure which (if any) are being actively monitored.

**Comment by micahgodbolt** [comment]
https://stackoverflow.com/questions/tagged/office-ui-fabric-react is at 91 


https://stackoverflow.com/questions/tagged/fluent-ui is at 63

Seems fluent-ui would be safe moving forward

**Comment by micahgodbolt** [comment]
closing this down. feel free to re-open merge/ or use this approach in the future.

**Pull request closed without merging**
