### PR TITLE
Update section header type

### PR DESCRIPTION
**Pull request by tabrumle**
sectionProps limits the title prop to a string. This prevents sending any additional properties to the title.

A while ago, there was a PR to apply html div properties specified on itemProps of a an IContextualMenuItem element to the surrounding div of the section header.

This PR makes parity with that.

Focus areas to test
Titles still render on contextual menus

This is a resubmit of #14069

### CODE REVIEW

**Comment by tabrumle** [comment]
@joschect I had to resubmit the PR as I don't have access to Matt branch to resolve the merge conflicts

**Comment by tomi-msft** [comment]
As part of our version 8 release we need folks to port changes to this component to the react-next package as well. Could you make this change in react-next as well?

**Comment by tabrumle** [comment]
@tomi-msft 

> As part of our version 8 release we need folks to port changes to this component to the react-next package as well. Could you make this change in react-next as well?

Made the relevant changes and pushed

**Review by khmakoto — CHANGES_REQUESTED** [review]
Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

**Review by joschect — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
