### PR TITLE
Update ci.json

### PR DESCRIPTION
**Pull request by dzearing**
Testing ci again.

### CODE REVIEW

**Comment by lbogdan** [comment]
Hello @dzearing ,

First of all, sorry for the inconvenience of disabling CodeSandbox CI builds on this repository, it was overloading our build servers. We re-enabled it in the meanwhile, but there's currently a build error when running `build:min`
```
office-ui-fabric-react: [6:39:20 PM] x src/components/Slider/Slider.test.tsx:12:30 - error TS2307: Cannot find module '@fluentui/react-conformance'.
office-ui-fabric-react: 12 import { isConformant } from '@fluentui/react-conformance';
office-ui-fabric-react:                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I could reproduce that locally, and taking a look at the build script

https://github.com/microsoft/fluentui/blob/785bb938355c341229996fcd3c6e51445de5d336/package.json#L14

the error happens because the `@fluentui/react-conformance` package is `private`

https://github.com/microsoft/fluentui/blob/785bb938355c341229996fcd3c6e51445de5d336/packages/react-conformance/package.json#L5

I tried removing the `private` field locally (I guess I could've also build it manually) and building again, but now I get into another error
```
@uifabric/api-docs: Loading /root/temp/fluentui/packages/styling/dist/styling.api.json
@uifabric/api-docs: [12:36:42 PM] x Error detected while running 'generate-json'
@uifabric/api-docs: [12:36:42 PM] x ------------------------------------
@uifabric/api-docs: [12:36:42 PM] x Error: Input file not found: /root/temp/fluentui/packages/styling/dist/styling.api.json
```

and there's indeed no `packages/styling/dist` folder.

**Comment by lbogdan** [comment]
Also, is there a way to lower the build scope even more? I see lots of apps, tests, the website, docs, which I guess are not really required, but take a lot of time to build.

**Comment by dzearing** [comment]
@lbogdan I think the min-build should avoid building all the unnecessaries - no tests, linting, esm. This PR adjusts to only build non-private modules, however that's causing the build break.

**Comment by dzearing** [comment]
Closing this one in favor of #13793.

**Pull request closed without merging**
