### PR TITLE
feat(DetailsList): Support custom group header checkbox

### LINKED ISSUE #13144: DetailsList onRenderCheckbox is not effective for group headers
### Environment Information

- **Package version(s)**: latest (7.113.1)
- **Browser and OS versions**: latest Chrome, MacOS

### Please provide a reproduction of the bug in a codepen:

I simply modified the DetailsList Grouped example, adding `onRenderCheckbox`:

https://codepen.io/breezewish/pen/ZEbjxOR

#### Actual behavior:

Group headers are not rendered by `onRenderCheckbox`, like below:

image

#### Expected behavior:

Expect all checkboxes are rendered by `onRenderCheckbox`.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes if I have time

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by breeswish**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13144
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This PR adds `onRenderGroupHeaderCheckbox` to `DetailsList` to allow customizing the group header checkbox.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by JustSlone** [comment]
Assigning to code owner @dzearing to review

**Comment by JustSlone** [comment]
@ThomasMichon do you have any concerns taking this PR in DetailsList? it looks reasonable. 

@breeswish the PR will need to be updated per the conflicts with master

**Review by ecraig12345 — APPROVED** [review]
Not Thomas :) but I originally suggested this change in response to an issue, and it looks okay to me. Really all it's doing is exposing a previously-added GroupedList prop through DetailsList.

**Review by khmakoto — DISMISSED** [review]
Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

**Comment by breeswish** [comment]
@khmakoto  Thanks for the information! Since I'm also quite busy recently I will postpone conflicts resolution to weeks later after you have migrated the code base.

**Comment by layershifter** [comment]
@khmakoto what is a resolution there? Should be a new PR opened or we can target `7.0` branch?

**Comment by khmakoto** [comment]
Thanks for the ping @layershifter, I think this can now go into master without problems, I'll dismiss my request for changes.

**Comment by layershifter** [comment]
@breeswish can you please solve merge conflicts? 🐱

**Comment by Onokaev** [comment]
Hi @ecraig12345. Are there plans to merge this PR?

**Comment by maxosp** [comment]
Hi @ecraig12345, I think we are still waiting for merging this PR :) Or onRenderGroupHeaderCheckbox was already added to DetailsList props?

**Pull request closed without merging**
