### PR TITLE
Removing TextCommons type in @fluentui/react-text

### PR DESCRIPTION
**Pull request by khmakoto**
## PR Description

This PR removes the `Commons` type pattern in the types for our `Text` component.

## Related Issue(s)

Fixes part of #22862

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                        |    Baseline (minified/GZIP) |                          PR |                                                                                                Change |
| :------------------------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | ----------------------------------------------------------------------------------------------------: |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>   | `10.894 kB`<br />`4.285 kB` |  `10.894 kB`<br />`4.29 kB` | <br />`5 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr> | `14.212 kB`<br />`4.707 kB` | `14.212 kB`<br />`4.712 kB` | <br />`5 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `58.983 kB`<br />`16.92 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `54.268 kB`<br />`15.663 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.783 kB`<br />`3.313 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `9.351 kB`<br />`3.832 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.755 kB`<br />`3.337 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `179.701 kB`<br />`50.147 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.066 kB`<br />`11.089 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2116a7b72e7056fd92d5f88b394e7c62e8788421'>2116a7b72e7056fd92d5f88b394e7c62e8788421</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/Avatar-mount_base.html">926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/Avatar-mount.html">871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/Button-mount_base.html">598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/Button-mount.html">555</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProvider-mount_base.html">2020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProvider-mount.html">1995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-mount_base.html">286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-mount.html">266</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">219</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">288</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/MakeStyles-mount_base.html">1594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22971/perf-test-react-components/MakeStyles-mount.html">1435</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by andrefcdias — CHANGES_REQUESTED** [review]
Please keep the PR focused on task as the type changes are unreadable because the ordering.
I can address the other changes in a separate PR.

**Review by andrefcdias — APPROVED** [review]
LGMT, thanks for the changes 👍🏻

**Pull request merged**
