### PR TITLE
docs/examples: rename deprecated 'name' property to 'text' to avoid disappearing link upon filtering 🪄

### PR DESCRIPTION
**Pull request by whalderman**
[Link](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu#:~:text=ContextualMenu%20with%20custom%20rendered%20menu%20list%20that%20renders%20a%20search%20box%20to%20filter%20menu%20items) for quick reference.
Upon filtering, the "Link click" item in the menu is removed permanently.

### CODE REVIEW

**Comment by whalderman** [comment]
[Link](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu#:~:text=ContextualMenu%20with%20custom%20rendered%20menu%20list%20that%20renders%20a%20search%20box%20to%20filter%20menu%20items) for quick reference.
Upon filtering, the "Link click" item in the menu is removed permanently.

**Comment by sopranopillow** [comment]
Seems like after writing again on the filter and deleting the text items come back.

**Comment by sopranopillow** [comment]
Hi @whalderman, for some strange reason your PR is failing. I have the exact same PR (#22771) and it does work. If you are interested in contributing, I would recommend maybe closing this PR and opening a new one? I can merge in the draft PR if you don't want to work on this one anymore.

**Comment by whalderman** [comment]
Hi @sopranopillow - no worries, feel free to just use #22771 👍

**Pull request closed without merging**
