### PR TITLE
fix(tooltiphost): Show V8 tooltips correctly in react 18 strict mode

### LINKED ISSUE #28230: [Bug]: V8 Tooltips not shown in React 18/StrictMode
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 20.60 GB / 47.76 GB
  Browsers:
    Chrome: 114.0.5735.111
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent8-react18-tooltip-yxzvl3

### Bug Description

Opening a new bug since #25534 was auto-closed

## Actual Behavior
In React 18 with strict mode, no tooltips are shown on hover.

## Expected Behavior
Tooltips should be shown correctly whether or not we're using strict mode

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by andyrooger**
## Previous Behavior

In react 18, strict mode, tooltips are not shown when hovering over the `TooltipHost`. The reason is that when mounting, the component instance is:
- Constructed (async object is created)
- Mounted
- Unmounted (async object is disposed)
- Remounted

At this point async operations do nothing because the async object is still disposed. So any tooltip show delay means the toggle never triggers.

## New Behavior

`Async` object is recreated on mount rather than constructor.

Tooltips show up on hover

## Related Issue(s)

- Fixes #28230

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/89f6b7c0835aca7ce29aff3c9a22ace4eb1b01d5'>89f6b7c0835aca7ce29aff3c9a22ace4eb1b01d5</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/BaseButton-mount_base.html">621</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/BaseButton-mount.html">652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Breadcrumb-mount_base.html">1672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Breadcrumb-mount.html">1695</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Checkbox-mount_base.html">1669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Checkbox-mount.html">1679</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/CheckboxBase-mount_base.html">1461</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/CheckboxBase-mount.html">1475</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ChoiceGroup-mount_base.html">2916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ChoiceGroup-mount.html">2937</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ComboBox-mount_base.html">683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ComboBox-mount.html">650</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/CommandBar-mount_base.html">6142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/CommandBar-mount.html">6099</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ContextualMenu-mount_base.html">10884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ContextualMenu-mount.html">11610</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DefaultButton-mount_base.html">752</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DefaultButton-mount.html">761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRow-mount_base.html">2207</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRow-mount.html">2185</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRowFast-mount_base.html">2229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRowFast-mount.html">2150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRowNoStyles-mount_base.html">2002</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DetailsRowNoStyles-mount.html">2051</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Dialog-mount_base.html">2635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Dialog-mount.html">2770</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DocumentCardTitle-mount_base.html">233</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/DocumentCardTitle-mount.html">220</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Dropdown-mount_base.html">1952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Dropdown-mount.html">1986</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/FocusTrapZone-mount_base.html">1152</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/FocusTrapZone-mount.html">1107</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/FocusZone-mount_base.html">1065</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/FocusZone-mount.html">1066</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-mount_base.html">41329</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-mount.html">41321</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-virtual-rerender_base.html">17770</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-virtual-rerender.html">19883</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50887</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedList-virtual-rerender-with-unmount.html">50887</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-mount_base.html">229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-mount.html">218</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-virtual-rerender_base.html">197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-virtual-rerender.html">206</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">224</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/IconButton-mount_base.html">1063</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/IconButton-mount.html">1079</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Label-mount_base.html">314</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Label-mount.html">331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Layer-mount_base.html">2722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Layer-mount.html">2721</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Link-mount_base.html">382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Link-mount.html">396</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/MenuButton-mount_base.html">953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/MenuButton-mount.html">892</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/MessageBar-mount_base.html">21359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/MessageBar-mount.html">21363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Nav-mount_base.html">1977</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Nav-mount.html">1960</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/OverflowSet-mount_base.html">767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/OverflowSet-mount.html">778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Panel-mount_base.html">1745</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Panel-mount.html">1798</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Persona-mount_base.html">738</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Persona-mount.html">751</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Pivot-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Pivot-mount.html">854</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/PrimaryButton-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/PrimaryButton-mount.html">822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Rating-mount_base.html">4664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Rating-mount.html">4675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SearchBox-mount_base.html">920</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SearchBox-mount.html">910</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Shimmer-mount_base.html">1892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Shimmer-mount.html">1841</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Slider-mount_base.html">1309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Slider-mount.html">1310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SpinButton-mount_base.html">2875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SpinButton-mount.html">2829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Spinner-mount_base.html">388</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Spinner-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SplitButton-mount_base.html">1791</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SplitButton-mount.html">1865</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Stack-mount_base.html">402</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Stack-mount.html">410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/StackWithIntrinsicChildren-mount_base.html">863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/StackWithIntrinsicChildren-mount.html">849</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/StackWithTextChildren-mount_base.html">2605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/StackWithTextChildren-mount.html">2599</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SwatchColorPicker-mount_base.html">6013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/SwatchColorPicker-mount.html">6149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/TagPicker-mount_base.html">1466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/TagPicker-mount.html">1452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Text-mount_base.html">387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Text-mount.html">375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/TextField-mount_base.html">951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/TextField-mount.html">939</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-mount_base.html">812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-mount.html">819</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-virtual-rerender_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-virtual-rerender.html">583</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Toggle-mount_base.html">592</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/Toggle-mount.html">593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/buttonNative-mount_base.html">197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28232/perf-test/buttonNative-mount.html">190</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by behowell — APPROVED** [review]
Thanks for the fix!

**Comment by andyrooger** [comment]
@behowell Thanks for reviewing. Is there anything waiting on me in order to merge this or is it just a case of waiting until you guys are ready? I have another very similar PR open for pickers, too.

**Comment by behowell** [comment]
Apologies, this fell off my radar. I'll update the branch and re-run the builds to make sure everything is still green, then I can merge it.

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Pull request merged**
