### PR TITLE
Azure Theme: Danger button and indeterminate checkbox

### PR DESCRIPTION
**Pull request by Jacqueline-ms**
### Check box (indeterminate)
Before
image

Centered the indeterminate box
image

### Danger button 
Denoted by `<PrimaryButton className="danger" />` or `<DefaultButton className="danger" />` _only_ in Azure Theme.

##### Light theme (all states)
rest
image

hover
image

pressed / focus
image

#### Dark theme
image

#### High contrast themes follow the same rules as regular buttons, according to Azure KO SDK

High contrast light (rest & hover)
image

High contrast dark (rest & hover)
image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/135655c2e9e32b5d50610d17792768ba0cb4e65e'>135655c2e9e32b5d50610d17792768ba0cb4e65e</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by Jacqueline-ms** [comment]
@GeoffCoxMSFT Hey Geoff, any thoughts on how this "danger button" is being implemented for the Azure Portal?

**Comment by Jacqueline-ms** [comment]
Checked with Fluent & Azure Framework Pms/designers for "danger" terminology and implementation (Eric, Manny).

**Review by robtaft-ms — APPROVED** [review]
I looked through this, and discussed with Jackie.  This looks good!

**Comment by Jacqueline-ms** [comment]
Going to cherry pick before deleting branch.

**Pull request merged**
