### PR TITLE
fix: Trigger addition of isFocusVisible classname only when Fluent elements are focused

### LINKED ISSUE #23378: [Bug]: useFocusRects code triggers on keyboard/mouse behavior outside of Fluent components
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 16.29 GB / 31.90 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53), ChromiumDev (91.0.838.3)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/kelseyyoung/pen/qBxKaEp

## Actual Behavior
In the codepen linked there are two Fluent Buttons followed by non-Fluent HTML elements. Buttons include the code from useFocusRects/the `<FocusRects>` component  in BaseButton.tsx

```
    return (
      <>
        {Content}
        <FocusRects />
      </>
    );
```

This code will toggle two classnames on the body element of the page, `ms-Fabric--isFocusVisible` and `ms-Fabric--isFocusHidden`, when toggling between mouse and "focus keyboard" events. However, these handlers are attached to the window, and so this code fires on events not using Fluent components. To mimic this behavior in the codepen, the repro steps are:

1. Place your mouse cursor inside the input box via click
2. Hit the right or left arrow key
3. Observe the classname on the body of the codepen changes the classname

(Gif below shows the classname changing while toggling between mouse clicks and arrow keys)

useFocusRects

Changing this classname causes a style recalculation in the browser despite these events happening on non-Fluent components. If no Fluent components are involved, the code in useFocusRects shouldn't need to fire

## Expected Behavior
We believe the behavior of useFocusRects could change in these ways, or other equivalent solutions:

1. Constrain its behavior to only trigger on events where Fluent components are involved (either by default or 
2. Attach the classnames to a more scoped element instead of the body of the entire document

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

Currently, `useFocusRects` will toggle between two classnames attached on the body element of the page, `ms-Fabric--isFocusVisible` and `ms-Fabric--isFocusHidden`. The two states are toggled via event listeners on the window, making the focus rectangles visible on keydown and making them hidden on mousedown and pointerdown. Because the listeners are attached to the window, however, this code fires on events not using Fluent components, which can cause a big style recalculation in the browser despite these events happening on non-Fluent components.

__The classname changes when switching between mouse and keyboard on non-Fluent elements:__

useFocusRects

### Change 1: Scoping change to make focus visible only on interaction with Fluent components

This PR changes the way in which `useFocusRects` works. It stills hides the focus rectangles on mousedown and pointerdown, but only makes them visible again when a keyboard interaction made a Fluent component gain focus. We do this by recording the last interaction and checking if it was a keyboard interaction on a focus event. This focus event is bound to the element whose `ref` is passed to `useFocusRects` or `FocusRects` so that we constrain the change in visibility to happen only on interaction with Fluent elements. If no `ref` is passed, then we bound the focus event to the `window` instead.

This in turn means that, as long as you pass a `ref` in every call of `useFocusRects` or `FocusRects`, there shouldn't be any big style recalculations happening because of the use of this functionality when dealing with non-Fluent elements.

__The classname no longer changes when switching between mouse and keyboard on non-Fluent elements:__

useFocusRects

_Note:_ This change makes use of the assumption that `onMouseDown`, `onKeyboardDown` and `onPointerDown` events fire before `onFocus` is fired. As far as I know, while HTML5 has a [recommendation on event loops](https://html.spec.whatwg.org/multipage/webappapis.html#event-loops), it is up to the browser implementation to determine which events will be grouped together and processed in order, as well as the priority given to any particular type of event. This could make this particular solution not work for all browsers. However, it works as expected on the following browsers I tested: Chrome, Edge and Firefox on Windows 11. I'd need someone else to test Safari since I don't have access to a MacOS machine.

---

### Change 2: Targetting focus visibility classnames to parent of element instead of body

Additionally, we've added changes so that the focus visibility classnames can be attached to the parent of the element whose `ref` is passed in instead of the `body`. This makes it so that when the class name changes the style recalculation is scoped to the elements below that parent, making the recalculations, in some cases, much less than they'd be if the classnames were attached to the body. The drawback of this approach is that you now have the possibility of having multiple elements with the focus visibility classnames, with a similar number of event listeners for each one of these.

Since this change is more ambitious than the other one and actually changes where the classnames are targetted, this is being gated behind a `FabricConfig` option on the window called `applyFocusClassNamesToTarget`. We can discuss if this should be the other way around and for this to be the default and have an option to turn back the old way of doing things, but in general I feel that there should be a way to opt-in/opt-out of this new mode.

__The classnames are attached to the parents of Fluent elements, not to the body:__

useFocusRects

## Related Issue(s)

Fixes #23378

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/63ab03fa7a9b3d02204147ea5356b8f78751df42'>63ab03fa7a9b3d02204147ea5356b8f78751df42</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by jspurlin** [comment]
An additional thought I just had is: could we to use some selector that utilizes `:focus-within` to apply the styling and let the browser handle everything? The question I comes up at that point: why is keyboard focus styling different than mouse focus styling and is there really need to show focus with two different styles depending on how that focus was set? If we could simplify that, it would allow us to run 0 javascript to get the styling

**Comment by khmakoto** [comment]
> 
An additional thought I just had is: could we to use some selector that utilizes :focus-within to apply the styling and let the browser handle everything? The question I comes up at that point: why is keyboard focus styling different than mouse focus styling and is there really need to show focus with two different styles depending on how that focus was set? If we could simplify that, it would allow us to run 0 javascript to get the styling

I think the main argument against that is that you don't want focus styles to appear when clicking on certain controls, the prime example being a button, where you don't want focus styles to linger after pressing it. That is a pretty strong design choice that I think will be difficult to argue about with designers.

**Comment by jspurlin** [comment]
Hmm, if focus is actually going to the button, I don't think it's unreasonable that the focus rect be visible always. It's a completely different scenario if focus is taken somewhere else when a button is executed (e.g. because that's what the consumer wanted) in which case the button would no longer be focused and hence would not have a focus rect. I feel like there's an argument that the presence of the focus rect help users (especially AT users) regardless of if they are interacting with the app via mouse, keyboard, touch, or AT.

On a related note, why would the browser feel like it's necessary to show the focus rect around a button when it is clicked (and has focus), and why do we feel like we need/want a different behavior?

---
In reply to: [1178034170](https://github.com/microsoft/fluentui/pull/23825#issuecomment-1178034170) [](http://example.com/codeflow?ancestors=1178034170,1178034170)

**Comment by khmakoto** [comment]
> Hmm, if focus is actually going to the button, I don't think it's unreasonable that the focus rect be visible always. It's a completely different scenario if focus is taken somewhere else when a button is executed (e.g. because that's what the consumer wanted) in which case the button would no longer be focused and hence would not have a focus rect. I feel like there's an argument that the presence of the focus rect helps users (especially AT users) regardless of if they are interacting with the app via mouse, keyboard, touch, or AT.
>
> On a related note, why does the browser feel like it's necessary to show the focus rect around a button when it does and why do we feel like we need/want a different behavior?

We can certainly talk with design about this and see where we can get, though I feel like that is a longer conversation that shouldn't stop these improvements we're trying to make right now.

**Comment by khmakoto** [comment]
Regarding this:

> Tying this to the rootref means that you do a check like rootRef.contains(target) (portals may need additional work to take into account) to see if it isFluentElement (e.g. inside the rootRef)

I don't think this is actually needed, since if we bind the focus event listeners to the `rootRef` we guarantee that if the `onFocus` callback is called the target is within the element that was passed as `rootRef` because of event bubbling.

**Comment by jspurlin** [comment]
True, although we should make sure we think through the blur case as well because while that will fire when an element is being blurred, focus may or may not be staying inside of the `rootRef`

---
In reply to: [1181216734](https://github.com/microsoft/fluentui/pull/23825#issuecomment-1181216734) [](http://example.com/codeflow?ancestors=1181216734,1181216734)

**Comment by jspurlin** [comment]
Are you planning on taking this approach in this PR? Looking at the most recent iteration (iteration 7) I see that everything is still being hooked up to the window object

---
In reply to: [1181897157](https://github.com/microsoft/fluentui/pull/23825#issuecomment-1181897157) [](http://example.com/codeflow?ancestors=1181897157,1181216734,1181216734)

**Comment by jspurlin** [comment]
Agreed, following up separately from this PR sounds good

---
In reply to: [1181214430](https://github.com/microsoft/fluentui/pull/23825#issuecomment-1181214430) [](http://example.com/codeflow?ancestors=1181214430,1181214430)

**Comment by jspurlin** [comment]
It looks like `useFocusRects` still calls `getWindow(rootRef?.current)` which I believe will return the window and hence the handlers will be hooked up to the window vs the rootRef

---
In reply to: [1182059004](https://github.com/microsoft/fluentui/pull/23825#issuecomment-1182059004) [](http://example.com/codeflow?ancestors=1182059004,1182059004)

**Pull request closed without merging**
