### PR TITLE
[1 of N] [Size optimization] Compress charting bundle size by mangling variable names

### PR DESCRIPTION
**Pull request by srmukher**
Obfuscating variable names for Tree component in charting library which reduces the packaged bundle size for charting to 462 KiB (2 KiB reduction from master).
This is required for following scenarios:
- showcase the minified bundle size (via react-charting.min.js) of the charting library as published on various external bundle measuring tools like 
https://bundlephobia.com/package/@fluentui/react-charting@5
This is used by potential consumers to choose between our charting library or the other.

We hoped to reduce the size of each component even before bundling, but that did not happen. 

Scenario: Compress, minify and mangle the min.js generated for react-charting components (taking one component at a time).

Approaches: 
1. Enabling mangling for all functions of all components: This resulted in maximum minification of the min.js to 353 KiB from 477 KiB. However, this can be enabled only when it is ensured that enabling mangling individually for each component does not regress anything.
2. Enabling mangling only for Tree Chart Component: This resulted minification of the min.js by 2 KiB. This approach is taken in this PR.

Validations:

Following charts have been validated in an html file pointing to a minified js:
1. TreeChart three layer:
image

2. TreeChart three layer compact:
image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/be3a3d59d5c30f75d55c739548d576594ddf5c53'>be3a3d59d5c30f75d55c739548d576594ddf5c53</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by Hotell** [comment]
not really sure how this reduces bundle size of charting package ?

- we dont bundle packages for npm because tree shaking issues https://unpkg.com/browse/@fluentui/react-charting@5.19.18/lib-commonjs/
- good opportunity to add monosize for charting cc @AtishayMsft 
  - see for more context https://github.com/microsoft/fluentui/issues/27933

**Comment by srmukher** [comment]
> not really sure how this reduces bundle size of charting package ?
> 
> * we dont bundle packages for npm because tree shaking issues https://unpkg.com/browse/@fluentui/react-charting@5.19.18/lib-commonjs/
> * good opportunity to add monosize for charting cc @AtishayMsft
>   
>   * see for more context [[Feature]: migrate v8,v0 from EOL size-auditor to monosize #27933](https://github.com/microsoft/fluentui/issues/27933)

Hi @Hotell, we are just modifying the sizes for the individual components (here Tree Chart only). For the monosize part, we already have this in our list of work items.

**Review by AtishayMsft — APPROVED** [review]

**Comment by Hotell** [comment]
> Hi @Hotell, we are just modifying the sizes for the individual components (here Tree Chart only). For the monosize part, we already have this in our list of work items.

the PR title is misleading, as you're "reducing" ( i cannot verify based on this PR) only output of bundle that will be deployed per PR https://fluentuipr.z22.web.core.windows.net/pull/30392/react-charting/demo/index.html and probably here ? https://developer.microsoft.com/en-us/fluentui#/controls/web/treechart

I'd recommend to mirror your [changeset descriptions](https://developer.microsoft.com/en-us/fluentui#/controls/web/treechart) aligned with PR title if possible to avoid confusion. Also PR title is used as merge commit to master - the more descriptive the better.

hope it makes sense. ty

**Review by Hotell — APPROVED** [review]

**Comment by AtishayMsft** [comment]
@Hotell Thanks for showing interest in this change.
This is one of many improvements planned to improve the size footprint of the charting controls. We are starting with a relatively new component TreeChart. As we explore more and learn, we will share details in form of a RFC.
Your valuable inputs are welcome. Looking forward for a more performant fluent framework.

@srmukher Let us add more details about the scenario, approach, validations done and observations. More folks in the team might be interested to use this approach to optimize size.

**Review by AtishayMsft — CHANGES_REQUESTED** [review]
Uncovered more insights for this change. Team is continuing to explore.

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
