### PR TITLE
chore: trigger manual bump and changelog generation to fix broken master

### PR DESCRIPTION
**Pull request by Hotell**
## New Behavior

commands used: 

`yarn beachball bump -b master --access public --no-fetch --no-publish --no-push --no-git-tags --verbose --config ./scripts/beachball/release-vNext.config.js`

followed by

`yarn nx workspace-generator dependency-mismatch`

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |   `64.09 kB`<br />`17.544 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `201.941 kB`<br />`56.241 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `35.049 kB`<br />`11.533 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |    `23.89 kB`<br />`7.246 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/InputField.fixture.js'>InputField</abbr>                                                                             |  `33.626 kB`<br />`10.099 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.324 kB`<br />`2.129 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `44.079 kB`<br />`12.356 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButtonField.fixture.js'>SpinButtonField</abbr>                                                              |  `53.015 kB`<br />`14.806 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4af9156bc869948b12610689f15b2a778aa690ca'>4af9156bc869948b12610689f15b2a778aa690ca</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Avatar-mount_base.html">1668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Avatar-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Button-mount_base.html">1118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Button-mount.html">1129</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Field-mount_base.html">2600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Field-mount.html">2565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProvider-mount_base.html">1996</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProvider-mount.html">1981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-mount_base.html">707</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-mount.html">713</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">667</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">752</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">725</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/InfoButton-mount_base.html">651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/InfoButton-mount.html">631</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/MakeStyles-mount_base.html">2299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/MakeStyles-mount.html">2296</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Persona-mount_base.html">4134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/Persona-mount.html">3856</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/SpinButton-mount_base.html">3316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26877/perf-test-react-components/SpinButton-mount.html">3247</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by JustSlone — APPROVED** [review]
Checked version numbers against what was published on NPM

**Review by micahgodbolt — APPROVED** [review]

**Review by Mitch-At-Work — APPROVED** [review]
Virtualizer is correctly bumped as pre-release still.

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
