### PR TITLE
Adds Tests For Fluent Menu Button Web Component

### PR DESCRIPTION
**Pull request by halerankin**
Adds Tests For Fluent Menu Button Web Component

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8c3c3b2fbc9cf08609ae30d5f9fd2dddfaef3b0c'>8c3c3b2fbc9cf08609ae30d5f9fd2dddfaef3b0c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Review by brianchristopherbrady — APPROVED** [review]

**Comment by miroslavstastny** [comment]
Reports flaky test:
```
  3 flaky
    [chromium] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
    [firefox] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
    [webkit] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
```

and lint warnings
```
packages/web-components/src/menu-button/menu-button.spec.ts
  284:29  warning  Avoid having conditionals in tests  playwright/no-conditional-in-test
  284:29  warning  Avoid having conditionals in tests  playwright/no-conditional-in-test
```

**Comment by halerankin** [comment]
> Reports flaky test:
> 
> ```
>   3 flaky
>     [chromium] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
>     [firefox] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
>     [webkit] › src/menu-button/menu-button.spec.ts:25:3 › Menu Button › should set the `disabled` attribute on the internal control 
> ```
> 
> and lint warnings
> 
> ```
> packages/web-components/src/menu-button/menu-button.spec.ts
>   284:29  warning  Avoid having conditionals in tests  playwright/no-conditional-in-test
>   284:29  warning  Avoid having conditionals in tests  playwright/no-conditional-in-test
> ```

Fixed tests. Passes linter.

**Comment by JustSlone** [comment]
@halerankin closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
