### PR TITLE
Adds Tests For Fluent Toggle Button Web Component

### PR DESCRIPTION
**Pull request by halerankin**
Adds Tests For Fluent Menu Button Web Component

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8c3c3b2fbc9cf08609ae30d5f9fd2dddfaef3b0c'>8c3c3b2fbc9cf08609ae30d5f9fd2dddfaef3b0c</a></sub>
<div id="bundleSizeComment9423"/>

**Review by miroslavstastny — COMMENTED** [review]
Reports flaky/failed test:
```
  1 failed
    [webkit] › src/toggle-button/toggle-button.spec.ts:25:3 › Toggle Button › should set the `disabled` attribute on the internal control 
  4 flaky
    [chromium] › src/toggle-button/toggle-button.spec.ts:25:3 › Toggle Button › should set the `disabled` attribute on the internal control 
    [firefox] › src/toggle-button/toggle-button.spec.ts:25:3 › Toggle Button › should set the `disabled` attribute on the internal control 
    [firefox] › src/toggle-button/toggle-button.spec.ts:118:3 › Toggle Button › should set `aria-pressed` on the internal button when clicked 
    [webkit] › src/toggle-button/toggle-button.spec.ts:118:3 › Toggle Button › should set `aria-pressed` on the internal button when clicked 
```

and lint warnings
```
packages/web-components/src/toggle-button/toggle-button.spec.ts
  233:5   warning  'control' is assigned a value but never used  @typescript-eslint/no-unused-vars
  375:29  warning  Avoid having conditionals in tests            playwright/no-conditional-in-test
  375:29  warning  Avoid having conditionals in tests            playwright/no-conditional-in-test
```

**Comment by JustSlone** [comment]
@halerankin closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
