### PR TITLE
Fixed error cleared in DatePicker.base.tsx._validateTextInput

### PR DESCRIPTION
**Pull request by michaelmajgaard**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Fixed a bug in the DatePicker causing an existing validation error to be cleared when tabbing through the component.
Added a DatePicker test verifying the fix.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12602)

### CODE REVIEW

**Comment by michaelmajgaard** [comment]
Looking at the failed tests now.

**Comment by lorejoh12** [comment]
Maybe I'm missing something obvious, but you need to add the new DatePicker story to the example page, right? I'm not seeing them show up on the test page. :)

DatePickerPage.tsx
https://github.com/microsoft/fluentui/blob/master/packages/date-time/src/components/DatePicker/DatePickerPage.tsx

**Comment by michaelmajgaard** [comment]
> 
> 
> Maybe I'm missing something obvious, but you need to add the new DatePicker story to the example page, right? I'm not seeing them show up on the test page. :)
> 
> DatePickerPage.tsx
> https://github.com/microsoft/fluentui/blob/master/packages/date-time/src/components/DatePicker/DatePickerPage.tsx

No, you're absolutely right. I didn't realise these stories where the ones shown on the test page. I'll get this fixed. :)

**Comment by michaelmajgaard** [comment]
Don't merge this yet. Need to fix a story.

**Comment by michaelmajgaard** [comment]
> 
> 
> Don't merge this yet. Need to fix a story.

Replaced the story with a test instead. Can be merged now.

**Comment by micahgodbolt** [comment]
@lorejoh12  signed off. i'll merge

**Pull request merged**
