### PR TITLE
fix(Components): add Focus Zone wrapper

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Some components missed the `unstable_wrapWithFocusZone` wrapper when converted to RFC. This PR adds revert that adding the wrapper in the proper components. 

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/13093)

### CODE REVIEW

**Comment by jurokapsiar** [comment]
Please add changelog before merging

**Comment by layershifter** [comment]
If it's a case I suggest to add wrapper everywhere (as it was before) and test it via additional test `isConformant()`.

**Comment by assuncaocharles** [comment]
> If it's a case I suggest to add wrapper everywhere (as it was before) and test it via additional test `isConformant()`.

@layershifter All components on this PR are already tested by `isConformant` your suggestion is to go through all FC and wrap them with FZ?

**Comment by layershifter** [comment]
Yep, let's move this discussion to offline and decide.

**Pull request merged**
