### PR TITLE
react-tabs: Added aria role and attrs to panel story

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Changes
- Added tabpanel role to tab panels in story
- Added aria-labelledby to tab panels in story
- Added ids to the tabs in story

## Issues

Updates #21594

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f2f0c0d6ea55c51a1e12d5d0385d91e1414f5025'>f2f0c0d6ea55c51a1e12d5d0385d91e1414f5025</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/Avatar-mount_base.html">1092</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/Avatar-mount.html">1113</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/Button-mount_base.html">677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/Button-mount.html">661</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProvider-mount_base.html">2226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProvider-mount.html">2255</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-mount_base.html">334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-mount.html">326</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">253</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">292</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">389</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">354</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/MakeStyles-mount_base.html">1869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22903/perf-test-react-components/MakeStyles-mount.html">1844</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by micahgodbolt** [comment]
ran this through with narrator and don't hear any connection between tab panel and tab above.

**Review by smhigley — APPROVED** [review]
I only tested with NVDA and Narrator, but it works for me with both.

@micahgodbolt you might need to bump up the verbosity for Narrator to hear it.

**Pull request merged**
