### PR TITLE
feat(react-infobutton): Add inline prop to InfoButton and make it inline by default

### LINKED ISSUE #28217: [Bug]: Make InfoLabel popup inline by default
### Library

React Components / v9 (@fluentui/react-components)

### Are you reporting Accessibility issue?

yes

### Bug Description

This issue suggests accessibility related improvements for the InfoLabel v9 component, documents the pros and cons of available solutions, infers recommended solution, and provides place for possible further discussion.

### aria-owns

The aria-owns attribute is set on the InfoLabel element that encloses the trigger button, referring to the popup which is placed at the end of the DOM. This ensures the popup is relocated within the accessibility tree to the position after the trigger button.

#### Pros

* Since the popup is placed at the end of the DOM, allows overflow: hidden to be used on the InfoLabel's parent element without hiding the overflowing content of the popup.
* In case no close button is provided in the popup, does not leave the users trapped within, letting them escape freely to the popup surrounding content. Therefore, it is in effect much like the [disclosure pattern][Disclosure].
* Is more consistent with the visual presentation, because the popup will be likely visually closer to a tooltip than to a modal dialog which obscures/hide the surrounding content.

#### Cons

* Since the popup is placed at the end of the DOM, requires Tab and Shift + Tab key press override to mimic the behavior as if the Tab or Shift + Tab was pressed at the position after the trigger button. This overide could possibly be implemented internally by the component using tabster.
* The aria-owns attribute is not supported by Safari on both macOS and iOS.

### Focus trap

Upon InfoLabel popup open, the focus is moved into the popup which is placed at the end of the DOM, and the rest of the page  is hidden for the screen readers using the aria-hidden attribute, trapping the user within the popup.

#### Pros

* Makes it clear what are the boundaries of the popup. Is therefore more suitable for complex popups that have a close button.
* Allows overflow:hidden to be used on the InfoLabel parent element without hiding the overflowing content of the popup.

#### Cons

* When focus is programmaticaly moved into the popup that has a focus trap, voiceOver cursor in some scenarios fails to be placed on the desired element, the success being dependant on the trigger button surrounding elements and elements below the popup.
Is less consistent with the visual presentation, because the popup will be likely visually closer to a tooltip than to a modal dialog which obscures/hide the surrounding content.

### Inline

The InfoLabel popup is placed in the DOM right after the trigger button.

#### Pros

* In case no close button is provided in the popup, does not leave the users trapped within, letting them escape freely to the popup surrounding content. Therefore, it is in effect much like the [disclosure pattern][Disclosure].
* Is more consistent with the visual presentation, because the popup will be likely visually closer to a tooltip than to a modal dialog which obscures/hide the surrounding content.
* NO problems with browser or screen reader support.

#### cons

* When overflow: hidden is used on the InfoLabel's parent element, the overflowing content of the popup becomes hidden.

## Conclusion

Currently, the InfoLabel component uses the aria-owns approach as the default. This issue suggests the inline approach as the new default solution, while also providing guidance and examples as to when the aria-owns and focus trap approaches might be more suitable.

[Disclosure]: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

InfoButton used default settings for Popover surface, therefore rendering it on a portal.

## New Behavior

InfoButton's Popover surface now renders inline allowing tabbing out of it and getting access to the rest of the dom.

## Related Issue(s)

- Fixes #28217

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">57</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">59</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Avatar-mount_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Avatar-mount.html">584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Button-mount_base.html">283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Button-mount.html">289</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Field-mount_base.html">1034</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Field-mount.html">1047</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProvider-mount_base.html">638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProvider-mount.html">630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-mount_base.html">77</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-mount.html">72</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">57</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">59</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">67</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">62</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/InfoButton-mount_base.html">9</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/InfoButton-mount.html">6</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/MakeStyles-mount_base.html">842</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/MakeStyles-mount.html">859</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Persona-mount_base.html">1650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/Persona-mount.html">1596</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/SpinButton-mount_base.html">1322</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28605/perf-test-react-components/SpinButton-mount.html">1269</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                      |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :----------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr> | `131.335 kB`<br />`40.311 kB` | `131.365 kB`<br />`40.324 kB` | `30 B` <br />`13 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoLabel.fixture.js'>InfoLabel</abbr>   |  `134.94 kB`<br />`41.443 kB` |  `134.97 kB`<br />`41.456 kB` | `30 B` <br />`13 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `67.576 kB`<br />`18.225 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `213.085 kB`<br />`59.114 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `36.409 kB`<br />`12.003 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |     `6.48 kB`<br />`2.203 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5a4b16715e8e929f11d8113f710e578ca73acaa6'>5a4b16715e8e929f11d8113f710e578ca73acaa6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by sopranopillow** [comment]
Do not merge until #28613 is merged

**Review by behowell — CHANGES_REQUESTED** [review]
This change LGTM, but per @sopranopillow 's comment, we're waiting to merge it until https://github.com/microsoft/fluentui/pull/28613 is resolved. Going to mark it as changes requested and hold off merging for now.

**Comment by sopranopillow** [comment]
@behowell #28613 has been merged, so this is good to go :)

**Review by behowell — APPROVED** [review]

**Pull request merged**
