### PR TITLE
docs: improve Toolbar docs examples

### PR DESCRIPTION
**Pull request by chpalac**
### Overview 

Fix: #25156

Improve current stories for `Toolbar`, making more realistic examples.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/Avatar-mount_base.html">1330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/Avatar-mount.html">1316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/Button-mount_base.html">944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/Button-mount.html">935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProvider-mount_base.html">1607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProvider-mount.html">1587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-mount_base.html">638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-mount.html">621</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">596</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">621</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/MakeStyles-mount_base.html">1909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/MakeStyles-mount.html">1935</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/SpinButton-mount_base.html">2572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25269/perf-test-react-components/SpinButton-mount.html">2569</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by bsunderhus — APPROVED** [review]
Would be nice to also add some description to every one of those stories

**Comment by ling1726** [comment]
image

There is no ToolbarMenuItem 🙈

image

We plan to introduce radios, so this guidance doesn't really make sense since we don't want users to apply roles unless necessary

image

Does this happen with the v9 menu ?

**Comment by chpalac** [comment]
@ling1726 The first 2 points I removed here: https://github.com/microsoft/fluentui/pull/25269/commits/07ca1761c27c9fbc31c0b96c72d1e686bdd094e6

For the last one, it does happen with V9 Toolbar/Menu:

lvbLffMPpC

**Comment by ling1726** [comment]
> For the last one, it does happen with V9 Toolbar/Menu:

Does it? you're not using any `onClick` handlers in either the `ToolbarDefault` or the `ToolbarOverflow` examples. The example your showed as gif does show focus outlines because you are using the mouse. When using the keyboard this is what I see
msedge_DjG2POCzHj

**Comment by chpalac** [comment]
@ling1726 Gotcha, removed here https://github.com/microsoft/fluentui/pull/25269/commits/636cca468a9dc5da31d4fac5d95979ee4e202d91

**Comment by chpalac** [comment]
@ling1726 if no other comments, good to merge?

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
