### PR TITLE
Remove Dropdown HeaderMessage background

### PR DESCRIPTION
**Pull request by Hirse**
Remove styling for background of Dropdown headerMessage, which is broken in Dark and Contrast themes
image image

image image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4b82dac0f1bcecba8cda7309c01eb98a3b7de46c'>4b82dac0f1bcecba8cda7309c01eb98a3b7de46c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
DropdownManyItemsPerf.default | [749](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DropdownManyItemsPerf.default.html) | [664](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.13:1
RadioGroupMinimalPerf.default | [481](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [431](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.12:1
VideoMinimalPerf.default | [708](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/VideoMinimalPerf.default.html) | [631](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.12:1
FlexMinimalPerf.default | [308](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/FlexMinimalPerf.default.html) | [278](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.11:1
GridMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/GridMinimalPerf.default.html) | [318](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.09:1
RefMinimalPerf.default | [273](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RefMinimalPerf.default.html) | [252](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.08:1
AvatarMinimalPerf.default | [188](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AvatarMinimalPerf.default.html) | [176](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
ChatMinimalPerf.default | [760](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatMinimalPerf.default.html) | [716](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.06:1
StatusMinimalPerf.default | [719](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/StatusMinimalPerf.default.html) | [677](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.06:1
AlertMinimalPerf.default | [277](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AlertMinimalPerf.default.html) | [264](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.05:1
BoxMinimalPerf.default | [340](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/BoxMinimalPerf.default.html) | [325](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
ChatWithPopoverPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatWithPopoverPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.05:1
HeaderSlotsPerf.default | [792](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/HeaderSlotsPerf.default.html) | [751](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.05:1
SkeletonMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SkeletonMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.05:1
DropdownMinimalPerf.default | [3225](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DropdownMinimalPerf.default.html) | [3092](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.04:1
FormMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/FormMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [518](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListMinimalPerf.default.html) | [500](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
MenuMinimalPerf.default | [881](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/MenuMinimalPerf.default.html) | [845](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.04:1
TooltipMinimalPerf.default | [1091](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TooltipMinimalPerf.default.html) | [1047](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.04:1
AttachmentMinimalPerf.default | [146](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AttachmentMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1215](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1184](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LayoutMinimalPerf.default.html) | [344](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [169](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/PortalMinimalPerf.default.html) | [164](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [1748](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SliderMinimalPerf.default.html) | [1695](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
CarouselMinimalPerf.default | [471](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CarouselMinimalPerf.default.html) | [464](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [377](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LabelMinimalPerf.default.html) | [371](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [4405](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4338](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
AccordionMinimalPerf.default | [146](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AccordionMinimalPerf.default.html) | [144](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [541](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AnimationMinimalPerf.default.html) | [537](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1504](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1490](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5960](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5891](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
ListWith60ListItems.default | [660](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListWith60ListItems.default.html) | [651](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1757](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1742](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
IconMinimalPerf.default | [591](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/IconMinimalPerf.default.html) | [588](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [562](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CardMinimalPerf.default.html) | [560](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CardMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4150](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/EmbedMinimalPerf.default.html) | [4155](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ImageMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ImageMinimalPerf.default.html) | [376](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1:1
LoaderMinimalPerf.default | [675](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LoaderMinimalPerf.default.html) | [675](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1:1
RosterPerf.default | [1136](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RosterPerf.default.html) | [1132](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/RosterPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1236](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1242](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
TextMinimalPerf.default | [333](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TextMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TextMinimalPerf.default_base.html) | 1:1
ChatDuplicateMessagesPerf.default | [288](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [291](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.99:1
DialogMinimalPerf.default | [816](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DialogMinimalPerf.default.html) | [824](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DividerMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [542](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListNestedPerf.default.html) | [545](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
TableManyItemsPerf.default | [1929](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TableManyItemsPerf.default.html) | [1954](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TableMinimalPerf.default.html) | [403](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [1072](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1094](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.98:1
CheckboxMinimalPerf.default | [2733](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2791](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.98:1
ProviderMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ProviderMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [479](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TextAreaMinimalPerf.default.html) | [491](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
ButtonMinimalPerf.default | [162](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonMinimalPerf.default.html) | [167](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.97:1
ToolbarMinimalPerf.default | [937](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ToolbarMinimalPerf.default.html) | [967](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.97:1
InputMinimalPerf.default | [1314](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/InputMinimalPerf.default.html) | [1367](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.96:1
PopupMinimalPerf.default | [619](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/PopupMinimalPerf.default.html) | [646](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.96:1
CustomToolbarPrototype.default | [2704](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CustomToolbarPrototype.default.html) | [2806](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.96:1
ButtonSlotsPerf.default | [549](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonSlotsPerf.default.html) | [581](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.94:1
TreeWith60ListItems.default | [182](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TreeWith60ListItems.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.93:1
ListCommonPerf.default | [630](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListCommonPerf.default.html) | [694](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ListCommonPerf.default_base.html) | 0.91:1
TreeMinimalPerf.default | [812](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TreeMinimalPerf.default.html) | [891](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.91:1
SegmentMinimalPerf.default | [328](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SegmentMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.89:1
HeaderMinimalPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/HeaderMinimalPerf.default.html) | [399](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.86:1
ReactionMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ReactionMinimalPerf.default.html) | [411](https://fluentuipr.z22.web.core.windows.net/pull/22758/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.85:1

</details><div id="perfComment9424"/>

**Review by ling1726 — APPROVED** [review]
LGTM but please add a screener test, I see that none have failed 😱😱

**Review by miroslavstastny — APPROVED** [review]

**Comment by Hirse** [comment]
> LGTM but please add a screener test, I see that none have failed 😱😱

@ling1726 Added a test. Can you review again once the build is ready?

**Review by jurokapsiar — APPROVED** [review]

**Pull request merged**
