### PR TITLE
chore(react-jsx-runtime): move up NODE_ENV check in warnIfElementTypeIsInvalid

### PR DESCRIPTION
**Pull request by wfwf1997**
## Previous Behavior

The `NODE_ENV` check occurs at the end. Since there's no `/*#__PURE__*/` annotation in `react-is.production.min.js`, and a bundler (e.g. webpack) cannot determine that function `isValidElementType` has no side effects neither, the expression in `if` will be preserved in a production build. And `react-is` will also be bundled into the final product.

## New Behavior

The `NODE_ENV` check is done at first, and the following checks are get shortcut if the first condition evaluates to `false`. In a production build, the expression could thus be fully optimized and `react-is` will not be included.

### CODE REVIEW

**Review by bsunderhus — APPROVED** [review]
Thx for the PR @wfwf1997 , great catch!

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Avatar-mount_base.html">645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Avatar-mount.html">621</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Button-mount_base.html">311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Button-mount.html">314</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Field-mount_base.html">1124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Field-mount.html">1113</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProvider-mount_base.html">700</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProvider-mount.html">729</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-mount_base.html">75</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-mount.html">85</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">59</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">67</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">78</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">66</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/MakeStyles-mount_base.html">854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/MakeStyles-mount.html">853</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Persona-mount_base.html">1733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/Persona-mount.html">1675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/SpinButton-mount_base.html">1375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29886/perf-test-react-components/SpinButton-mount.html">1354</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                     Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `93.591 kB`<br />`28.552 kB` |  `93.224 kB`<br />`28.468 kB` |  `-367 B` <br />`-84 B`  |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `84.293 kB`<br />`23.456 kB` |  `83.926 kB`<br />`23.362 kB` |  `-367 B` <br />`-94 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `50.534 kB`<br />`15.923 kB` |  `50.167 kB`<br />`15.836 kB` |  `-367 B` <br />`-87 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |   `20.064 kB`<br />`7.894 kB` |     `19.696 kB`<br />`7.8 kB` |  `-368 B` <br />`-94 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |   `65.19 kB`<br />`20.259 kB` |  `64.823 kB`<br />`20.176 kB` |  `-367 B` <br />`-83 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `27.264 kB`<br />`8.808 kB` |   `26.897 kB`<br />`8.713 kB` |  `-367 B` <br />`-95 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `28.165 kB`<br />`9.101 kB` |   `27.798 kB`<br />`9.013 kB` |  `-367 B` <br />`-88 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |    `25.67 kB`<br />`9.313 kB` |    `25.303 kB`<br />`9.22 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |  `40.074 kB`<br />`11.292 kB` |  `39.707 kB`<br />`11.207 kB` |  `-367 B` <br />`-85 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `47.43 kB`<br />`12.787 kB` |  `47.063 kB`<br />`12.691 kB` |  `-367 B` <br />`-96 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `44.848 kB`<br />`12.668 kB` |  `44.481 kB`<br />`12.569 kB` |  `-367 B` <br />`-99 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `52.862 kB`<br />`14.254 kB` |  `52.495 kB`<br />`14.166 kB` |  `-367 B` <br />`-88 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `57.122 kB`<br />`13.194 kB` |  `56.754 kB`<br />`13.104 kB` |  `-368 B` <br />`-90 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `93.574 kB`<br />`27.101 kB` |  `93.207 kB`<br />`27.001 kB` | `-367 B` <br />`-100 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `88.398 kB`<br />`25.603 kB` |  `88.031 kB`<br />`25.501 kB` | `-367 B` <br />`-102 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |   `13.423 kB`<br />`5.481 kB` |   `13.056 kB`<br />`5.388 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `15.666 kB`<br />`6.235 kB` |   `15.299 kB`<br />`6.143 kB` |  `-367 B` <br />`-92 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |   `14.374 kB`<br />`5.854 kB` |   `14.007 kB`<br />`5.757 kB` |  `-367 B` <br />`-97 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |  `34.424 kB`<br />`11.829 kB` |  `34.057 kB`<br />`11.732 kB` |  `-367 B` <br />`-97 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `92.437 kB`<br />`30.132 kB` |    `92.07 kB`<br />`30.04 kB` |  `-367 B` <br />`-92 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `90.858 kB`<br />`29.794 kB` |  `90.491 kB`<br />`29.701 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `70.184 kB`<br />`20.225 kB` |  `69.816 kB`<br />`20.132 kB` |  `-368 B` <br />`-93 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `208.306 kB`<br />`59.569 kB` | `207.938 kB`<br />`59.476 kB` |  `-368 B` <br />`-93 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `42.468 kB`<br />`14.059 kB` |  `42.101 kB`<br />`13.957 kB` | `-367 B` <br />`-102 B`  |
| <samp>react-datepicker-compat</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker Compat</abbr>                                                          | `213.533 kB`<br />`59.648 kB` | `213.166 kB`<br />`59.546 kB` | `-367 B` <br />`-102 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `95.172 kB`<br />`28.425 kB` |  `94.805 kB`<br />`28.321 kB` | `-367 B` <br />`-104 B`  |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `21.179 kB`<br />`7.839 kB` |   `20.812 kB`<br />`7.742 kB` |  `-367 B` <br />`-97 B`  |
| <samp>react-field</samp> <br /> <abbr title='bundle-size/Field.fixture.js'>Field</abbr>                                                                                       |   `22.788 kB`<br />`8.639 kB` |   `22.419 kB`<br />`8.541 kB` |  `-369 B` <br />`-98 B`  |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `16.096 kB`<br />`6.317 kB` |   `15.728 kB`<br />`6.225 kB` |  `-368 B` <br />`-92 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `131.767 kB`<br />`41.438 kB` | `131.399 kB`<br />`41.359 kB` |  `-368 B` <br />`-79 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoLabel.fixture.js'>InfoLabel</abbr>                                                                          | `135.453 kB`<br />`42.586 kB` | `135.086 kB`<br />`42.496 kB` |  `-367 B` <br />`-90 B`  |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `27.247 kB`<br />`9.194 kB` |   `26.879 kB`<br />`9.097 kB` |  `-368 B` <br />`-97 B`  |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/DevRuntime.fixture.js'>JSX Dev Runtime</abbr>                                                                  |     `4.14 kB`<br />`1.741 kB` |    `3.775 kB`<br />`1.644 kB` |  `-365 B` <br />`-97 B`  |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Runtime.fixture.js'>JSX Runtime</abbr>                                                                         |    `4.734 kB`<br />`1.983 kB` |    `4.369 kB`<br />`1.879 kB` | `-365 B` <br />`-104 B`  |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |   `14.508 kB`<br />`5.857 kB` |   `14.141 kB`<br />`5.764 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |     `17.4 kB`<br />`6.977 kB` |   `17.033 kB`<br />`6.884 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `141.122 kB`<br />`43.283 kB` | `140.755 kB`<br />`43.189 kB` |  `-367 B` <br />`-94 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `143.808 kB`<br />`43.788 kB` | `143.441 kB`<br />`43.693 kB` |  `-367 B` <br />`-95 B`  |
| <samp>react-message-bar</samp> <br /> <abbr title='bundle-size/Default.fixture.js'>MessageBar (all components)</abbr>                                                         |    `25.54 kB`<br />`9.102 kB` |   `25.173 kB`<br />`9.005 kB` |  `-367 B` <br />`-97 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `57.425 kB`<br />`17.798 kB` |  `57.058 kB`<br />`17.711 kB` |  `-367 B` <br />`-87 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |   `120.5 kB`<br />`37.958 kB` | `120.133 kB`<br />`37.851 kB` | `-367 B` <br />`-107 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>                                                                        |   `17.788 kB`<br />`6.986 kB` |     `17.42 kB`<br />`6.89 kB` |  `-368 B` <br />`-96 B`  |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |    `23.008 kB`<br />`8.48 kB` |   `22.641 kB`<br />`8.384 kB` |  `-367 B` <br />`-96 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `31.437 kB`<br />`10.314 kB` |   `31.07 kB`<br />`10.218 kB` |  `-367 B` <br />`-96 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |    `15.704 kB`<br />`6.35 kB` |   `15.337 kB`<br />`6.258 kB` |  `-367 B` <br />`-92 B`  |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |  `28.968 kB`<br />`10.269 kB` |  `28.601 kB`<br />`10.176 kB` |  `-367 B` <br />`-93 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `38.52 kB`<br />`12.646 kB` |   `38.153 kB`<br />`12.54 kB` | `-367 B` <br />`-106 B`  |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `37.133 kB`<br />`11.856 kB` |  `36.766 kB`<br />`11.757 kB` |  `-367 B` <br />`-99 B`  |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `23.762 kB`<br />`8.556 kB` |    `23.394 kB`<br />`8.46 kB` |  `-368 B` <br />`-96 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |  `33.902 kB`<br />`10.944 kB` |  `33.535 kB`<br />`10.849 kB` |  `-367 B` <br />`-95 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 | `154.297 kB`<br />`43.454 kB` | `153.928 kB`<br />`43.363 kB` |  `-369 B` <br />`-91 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                                                            |   `44.112 kB`<br />`13.81 kB` |  `43.744 kB`<br />`13.714 kB` |  `-368 B` <br />`-96 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `127.517 kB`<br />`34.792 kB` |  `127.15 kB`<br />`34.689 kB` | `-367 B` <br />`-103 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |  `72.696 kB`<br />`19.959 kB` |  `72.328 kB`<br />`19.866 kB` |  `-368 B` <br />`-93 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |  `71.303 kB`<br />`19.562 kB` |  `70.935 kB`<br />`19.468 kB` |  `-368 B` <br />`-94 B`  |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/InteractionTag.fixture.js'>InteractionTag</abbr>                                                                      |   `15.618 kB`<br />`6.152 kB` |   `15.251 kB`<br />`6.062 kB` |  `-367 B` <br />`-90 B`  |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/tag.fixture.js'>Tag</abbr>                                                                                            |   `30.341 kB`<br />`9.505 kB` |   `29.974 kB`<br />`9.408 kB` |  `-367 B` <br />`-97 B`  |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/TagGroup.fixture.js'>TagGroup</abbr>                                                                                  |  `74.422 kB`<br />`22.269 kB` |  `74.055 kB`<br />`22.168 kB` | `-367 B` <br />`-101 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `17.065 kB`<br />`6.645 kB` |   `16.697 kB`<br />`6.553 kB` |  `-368 B` <br />`-92 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `20.237 kB`<br />`6.965 kB` |    `19.87 kB`<br />`6.873 kB` |  `-367 B` <br />`-92 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                              |  `31.306 kB`<br />`10.549 kB` |  `30.939 kB`<br />`10.451 kB` |  `-367 B` <br />`-98 B`  |
| <samp>react-timepicker-compat-preview</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr>                                                         |   `93.834 kB`<br />`31.42 kB` |  `93.467 kB`<br />`31.326 kB` |  `-367 B` <br />`-94 B`  |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr>                                                                   |  `93.346 kB`<br />`27.986 kB` |  `92.978 kB`<br />`27.893 kB` |  `-368 B` <br />`-93 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `53.173 kB`<br />`18.712 kB` |   `52.806 kB`<br />`18.62 kB` |  `-367 B` <br />`-92 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                     |          Size (minified/GZIP) |
| --------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-calendar-compat</samp> <br /> <abbr title='bundle-size/Calendar.fixture.js'>Calendar Compat</abbr>        | `141.973 kB`<br />`36.998 kB` |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Classic.fixture.js'>Classic Pragma</abbr>              |       `1.049 kB`<br />`531 B` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> |    `6.822 kB`<br />`2.311 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/29bddb19fbcf2f63711e9b5153b02066172dce9d'>29bddb19fbcf2f63711e9b5153b02066172dce9d</a></sub>
<div id="bundleSizeComment9423"/>

**Pull request merged**
