### PR TITLE
chore: bump storybook to 6.5.15

### PR DESCRIPTION
**Pull request by micahgodbolt**
Bumping storybook to latest to fix bug in MDX deep links

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/55c6dc163ae17faa2fe843447cf47ac207a99141'>55c6dc163ae17faa2fe843447cf47ac207a99141</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26259&commitId=46fc7b3926a1a3d35a8d541a6d6f011e959b3248&env=prod)

✅ There was 0 screenshots added, 2 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount_base.html">2376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount.html">2957</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/BaseButton-mount_base.html">1536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/BaseButton-mount.html">1519</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Breadcrumb-mount_base.html">3664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Breadcrumb-mount.html">3694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Checkbox-mount_base.html">3379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Checkbox-mount.html">3364</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/CheckboxBase-mount_base.html">3001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/CheckboxBase-mount.html">3034</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ChoiceGroup-mount_base.html">5765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ChoiceGroup-mount.html">5790</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ComboBox-mount_base.html">1607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ComboBox-mount.html">1618</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/CommandBar-mount_base.html">11851</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/CommandBar-mount.html">11922</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ContextualMenu-mount_base.html">13527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ContextualMenu-mount.html">13452</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DefaultButton-mount_base.html">1757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DefaultButton-mount.html">1750</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRow-mount_base.html">4618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRow-mount.html">4607</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRowFast-mount_base.html">4582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRowFast-mount.html">4611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRowNoStyles-mount_base.html">4410</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DetailsRowNoStyles-mount.html">4504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Dialog-mount_base.html">3896</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Dialog-mount.html">3870</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DocumentCardTitle-mount_base.html">701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/DocumentCardTitle-mount.html">709</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Dropdown-mount_base.html">4454</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Dropdown-mount.html">4075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/FocusTrapZone-mount_base.html">2532</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/FocusTrapZone-mount.html">2546</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/FocusZone-mount_base.html">2432</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/FocusZone-mount.html">2530</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount_base.html">2376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount.html">2957</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-virtual-rerender_base.html">1437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-virtual-rerender.html">1454</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">2156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedList-virtual-rerender-with-unmount.html">2125</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-mount_base.html">686</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-mount.html">715</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-virtual-rerender_base.html">671</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-virtual-rerender.html">674</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">697</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/IconButton-mount_base.html">2444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/IconButton-mount.html">2473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Label-mount_base.html">898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Label-mount.html">888</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Layer-mount_base.html">5491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Layer-mount.html">5489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Link-mount_base.html">1019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Link-mount.html">1044</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/MenuButton-mount_base.html">2166</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/MenuButton-mount.html">2181</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/MessageBar-mount_base.html">2867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/MessageBar-mount.html">2926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Nav-mount_base.html">4214</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Nav-mount.html">4174</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/OverflowSet-mount_base.html">1699</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/OverflowSet-mount.html">1700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Panel-mount_base.html">3196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Panel-mount.html">3211</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Persona-mount_base.html">1664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Persona-mount.html">1657</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Pivot-mount_base.html">2011</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Pivot-mount.html">2100</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/PrimaryButton-mount_base.html">1952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/PrimaryButton-mount.html">1946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Rating-mount_base.html">9183</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Rating-mount.html">9568</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SearchBox-mount_base.html">1973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SearchBox-mount.html">2011</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Shimmer-mount_base.html">3684</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Shimmer-mount.html">3777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Slider-mount_base.html">2752</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Slider-mount.html">2658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SpinButton-mount_base.html">6070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SpinButton-mount.html">5959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Spinner-mount_base.html">1001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Spinner-mount.html">983</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SplitButton-mount_base.html">4046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SplitButton-mount.html">3970</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Stack-mount_base.html">1028</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Stack-mount.html">1064</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/StackWithIntrinsicChildren-mount_base.html">3346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/StackWithIntrinsicChildren-mount.html">3045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/StackWithTextChildren-mount_base.html">6435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/StackWithTextChildren-mount.html">6480</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SwatchColorPicker-mount_base.html">13610</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/SwatchColorPicker-mount.html">13431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TagPicker-mount_base.html">3292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TagPicker-mount.html">3357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TeachingBubble-mount_base.html">102337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TeachingBubble-mount.html">102005</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Text-mount_base.html">982</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Text-mount.html">1010</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TextField-mount_base.html">2023</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/TextField-mount.html">2037</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-mount.html">1907</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-virtual-rerender_base.html">1349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-virtual-rerender.html">1363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Toggle-mount_base.html">1393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/Toggle-mount.html">1388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/buttonNative-mount_base.html">671</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26259/perf-test/buttonNative-mount.html">650</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by Hotell — APPROVED** [review]

**Pull request merged**
