### PR TITLE
Add JSDoc for tabster focus indicator selector

### PR DESCRIPTION
**Pull request by NotWoods**
## Previous Behavior

No docs

## New Behavior
Docs!

When I was working with this function it wasn't clear what the default value was. I added JSDoc with a `@default` tag.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/27c3cfe8a95bd26541c7c47ad2fd7fbc8ea332df'>27c3cfe8a95bd26541c7c47ad2fd7fbc8ea332df</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by ling1726** [comment]
> Docs!

Best PR description

You'll need to do the following steps to get CI to pass

* run `yarn change` and choose the changetype `none` or `patch`
* yarn `yarn workspace @fluentui/react-tabster build` and check in the api.md file changes

**Review by Hotell — APPROVED** [review]

**Comment by Hotell** [comment]
> > Docs!
> 
> Best PR description
> 
> You'll need to do the following steps to get CI to pass
> 
> * run `yarn change` and choose the changetype `none` or `patch`
> * yarn `yarn workspace @fluentui/react-tabster build` and check in the api.md file changes

make sure to follow these @NotWoods 🙏

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Avatar-mount_base.html">1334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Avatar-mount.html">1353</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Button-mount_base.html">955</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Button-mount.html">953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Field-mount_base.html">2055</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Field-mount.html">2065</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProvider-mount_base.html">1690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProvider-mount.html">1644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-mount_base.html">633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-mount.html">642</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">592</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">641</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/InfoButton-mount_base.html">566</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/InfoButton-mount.html">572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/MakeStyles-mount_base.html">1893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/MakeStyles-mount.html">1906</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Persona-mount_base.html">3115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/Persona-mount.html">3028</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/SpinButton-mount_base.html">2459</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27041/perf-test-react-components/SpinButton-mount.html">2453</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by bsunderhus — APPROVED** [review]
LGTM

**Pull request merged**
