### PR TITLE
feat: Table Column Reordering DnD

### PR DESCRIPTION
**Pull request by george-cz**
This PR introduces a Table state that enables column Drag'n'Drop.

This is super early stage, just a concept to validate API approach and determine next steps.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7bf995b3b64f3ffb07291fc6f7efedb00611f2de'>7bf995b3b64f3ffb07291fc6f7efedb00611f2de</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Avatar-mount_base.html">1709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Avatar-mount.html">1656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Button-mount_base.html">1139</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Button-mount.html">1123</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Field-mount_base.html">2598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Field-mount.html">2576</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProvider-mount_base.html">1991</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProvider-mount.html">1984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-mount_base.html">728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-mount.html">720</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">677</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">726</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/InfoButton-mount_base.html">642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/InfoButton-mount.html">635</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/MakeStyles-mount_base.html">2259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/MakeStyles-mount.html">2327</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Persona-mount_base.html">3913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/Persona-mount.html">3904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/SpinButton-mount_base.html">3135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26983/perf-test-react-components/SpinButton-mount.html">3111</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by layershifter** [comment]
Closing for housekeeping 🏡

**Pull request closed without merging**
