### PR TITLE
Set cursor=pointer for the searchbox preview dismiss button

### PR DESCRIPTION
**Pull request by syphe**
This feels to me like desirable behaviour, keen on getting opinions on whether this needs to be behind a prop toggle or applied 100% like currently in this PR

## Previous Behavior

Hover on the clear button on searchbox preview does not change the cursor

image

## New Behavior

When hovering on the clear button on the searchbox, the cursor changes to the hand/pointer

image

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by spmonahan** [comment]
This is the behavior of Fluent's buttons and dismiss is a button so this makes sense to me. However, the design spec doesn't show this either way so I want to ask our designers. Can you post before and after screen shots with the cursor please?

**Comment by spmonahan** [comment]
You'll also need to add a change file by running `yarn change` locally and committing the generated file.

**Comment by syphe** [comment]
> 



> This is the behavior of Fluent's buttons and dismiss is a button so this makes sense to me. However, the design spec doesn't show this either way so I want to ask our designers. Can you post before and after screen shots with the cursor please?

Have added before/after shots, potato quality because had to use Xbox gamebar to record the cursor :) also added a patch note

**Review by spmonahan — APPROVED** [review]

**Review by smhigley — APPROVED** [review]

**Pull request merged**
