### PR TITLE
adding lines in vertical stacked bar chart complex combo chart

### LINKED ISSUE #15550: add complex combo chart
we need to add the new chart which is 

complex combo chart

below is the figma
https://www.figma.com/file/BJaI0aMC0jXuwsJaGofqM7/Visualizations-(PS-%2B-CFR)?node-id=112%3A4903

This is nothing but adding lines in the vertical stacked bar chart

for more info please refer
https://office.visualstudio.com/OC/_queries/edit/4461315/

### PR DESCRIPTION
**Pull request by shivasai09**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15550
- [x] Include a change request file using `$ yarn change`

#### Description of changes

added the new feature which is complex combo chart.

nothing but adding lines to the vertical stacked bar chart

hosted at
http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/15551/merge/charting/dist/index.html#/examples/VerticalStackedBarChart

#### Focus areas to test
vertical stacked bar chart

### CODE REVIEW

**Comment by khmakoto** [comment]
Now that we're publishing beta versions of 8.0 please also port this to the master branch once it merges.

**Review by Raghurk — APPROVED** [review]

**Comment by shivasai09** [comment]
@khmakoto how to port it? , now it is merged to 7.0

**Comment by khmakoto** [comment]
@shivasai09 you should open a PR with the cherry-picked changes from this but to the master branch.

**Comment by shivasai09** [comment]
@khmakoto  is there any documentation on how to cherry-pick this branch and open a PR against the master,

or do we have to create a other branch and manually add all the changes in this branch and open a pr against the master..

how to proceed?

**Comment by khmakoto** [comment]
@shivasai09 [here's](https://www.atlassian.com/git/tutorials/cherry-pick) a good guide to git cherry pick.

**Pull request merged**
