### PR TITLE
More friendly behavior when GroupedList header is too long

### LINKED ISSUE #21275: More friendly behavior when GroupedList header is too long.
#### Describe the feature that you would like added
1. The header of `GroupedList` should show '...' when it is too long, which says "overflow" of "ms-GroupHeader-title" should be "hidden"
2. The icon should not shrink, which says "flexShrink" of "ms-GroupHeader-expand" should be 0

It makes more sense and the style has been set to 
```
white-space: nowrap;
text-overflow: ellipsis;
```
It appears that `overflow: "hidden"` is forgotten?

#### What component or utility would this be added to

packages/react/src/components/GroupedList/GroupHeader.styles.ts

### PR DESCRIPTION
**Pull request by ShuiRuTian**
## Current Behavior

image

## New Behavior
image

## Related Issue(s)

Fixes #21275

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/605d53a436a9dfb24075fdb39bb4c4823ee0b9ba'>605d53a436a9dfb24075fdb39bb4c4823ee0b9ba</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Avatar-mount_base.html">1361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Avatar-mount.html">1316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/BaseButton-mount_base.html">1358</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/BaseButton-mount.html">1402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Breadcrumb-mount_base.html">3249</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Breadcrumb-mount.html">3229</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ButtonNext-mount_base.html">846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ButtonNext-mount.html">807</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Checkbox-mount_base.html">2010</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Checkbox-mount.html">2039</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/CheckboxBase-mount_base.html">1771</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/CheckboxBase-mount.html">1785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ChoiceGroup-mount_base.html">5697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ChoiceGroup-mount.html">5653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ComboBox-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ComboBox-mount.html">1453</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/CommandBar-mount_base.html">11429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/CommandBar-mount.html">11433</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ContextualMenu-mount_base.html">12761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ContextualMenu-mount.html">12646</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DefaultButton-mount_base.html">1660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DefaultButton-mount.html">1659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRow-mount_base.html">4594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRow-mount.html">4540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRowFast-mount_base.html">4598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRowFast-mount.html">4582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRowNoStyles-mount_base.html">4380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DetailsRowNoStyles-mount.html">4397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Dialog-mount_base.html">2793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Dialog-mount.html">2734</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DocumentCardTitle-mount_base.html">533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/DocumentCardTitle-mount.html">473</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Dropdown-mount_base.html">4048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Dropdown-mount.html">4106</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderNext-mount_base.html">2269</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderNext-mount.html">2311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-mount_base.html">462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-mount.html">454</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-virtual-rerender.html">422</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">496</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">500</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FocusTrapZone-mount_base.html">2259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FocusTrapZone-mount.html">2302</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FocusZone-mount_base.html">2332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/FocusZone-mount.html">2298</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/IconButton-mount_base.html">2356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/IconButton-mount.html">2378</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Label-mount_base.html">697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Label-mount.html">706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Layer-mount_base.html">3653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Layer-mount.html">3566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Link-mount_base.html">852</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Link-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MakeStyles-mount_base.html">2079</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MakeStyles-mount.html">2024</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MenuButton-mount_base.html">2091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MenuButton-mount.html">2045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MessageBar-mount_base.html">2591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/MessageBar-mount.html">2593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Nav-mount_base.html">4133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Nav-mount.html">4073</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/OverflowSet-mount_base.html">1545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/OverflowSet-mount.html">1570</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Panel-mount_base.html">2687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Panel-mount.html">2694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Persona-mount_base.html">1273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Persona-mount.html">1308</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Pivot-mount_base.html">1995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Pivot-mount.html">1963</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/PrimaryButton-mount_base.html">1809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/PrimaryButton-mount.html">1843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Rating-mount_base.html">9533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Rating-mount.html">9535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SearchBox-mount_base.html">1916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SearchBox-mount.html">1877</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Shimmer-mount_base.html">3199</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Shimmer-mount.html">3165</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Slider-mount_base.html">2458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Slider-mount.html">2484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SpinButton-mount_base.html">6340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SpinButton-mount.html">6016</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Spinner-mount_base.html">761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Spinner-mount.html">774</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SplitButton-mount_base.html">3967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SplitButton-mount.html">3943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Stack-mount_base.html">888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Stack-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/StackWithIntrinsicChildren-mount_base.html">3081</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/StackWithIntrinsicChildren-mount.html">3100</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/StackWithTextChildren-mount_base.html">6605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/StackWithTextChildren-mount.html">6613</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SwatchColorPicker-mount_base.html">13312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/SwatchColorPicker-mount.html">13274</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TagPicker-mount_base.html">3410</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TagPicker-mount.html">3355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TeachingBubble-mount_base.html">104211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TeachingBubble-mount.html">106241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Text-mount_base.html">807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Text-mount.html">787</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TextField-mount_base.html">1888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/TextField-mount.html">1915</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-mount_base.html">1527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-mount.html">1574</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-virtual-rerender_base.html">985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-virtual-rerender.html">981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2372</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Toggle-mount_base.html">1218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/Toggle-mount.html">1195</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/buttonNative-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22020/perf-test/buttonNative-mount.html">459</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
This change modifies the snapshots we use to test the dom structure of the component. Run 'test' in the package and commit the new snapshots.

**Comment by ShuiRuTian** [comment]
@micahgodbolt Sorry for asking, I have run
`yarn` in root,
`yarn buildto ./packages/react` in root,
`yarn run test` in `{root}/packages/react`
But it says 
```
● Validation Error:

  Module null in the snapshotSerializers option was not found.
         <rootDir> is: D:\MyRepo\fluentui\packages\react

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```
Did I miss something?

**Comment by micahgodbolt** [comment]
@ShuiRuTian ah my bad. in fluentui/react package we have a single `yarn update-snapshots` command for that.

**Review by spmonahan — APPROVED** [review]

**Comment by spmonahan** [comment]
@ShuiRuTian Thank you for your contribution to Fluent UI!

**Pull request merged**
