### PR TITLE
Update sectionProps' title props to also be a IContextualMenuItem to keep parity with passing down itemProps

### PR DESCRIPTION
**Pull request by makopch-ms**
sectionProps limits the title prop to a string.  This prevents sending any additional properties to the title.

A while ago, there was a PR to apply html div properties specified on itemProps of a an IContextualMenuItem element to the surrounding div of the section header.

This PR makes parity with that.

#### Focus areas to test

Titles still render on contextual menus

### CODE REVIEW

**Comment by makopch-ms** [comment]
@jspurlin @SavannahBourgeois

**Comment by makopch-ms** [comment]
@joschect @xugao Could you please take a look at this PR?

**Comment by tabrumle** [comment]
@joschect @xugao ping on this

**Review by joschect — APPROVED** [review]

**Review by khmakoto — CHANGES_REQUESTED** [review]
Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

**Comment by khmakoto** [comment]
Closing since #15123 has been merged.

**Pull request closed without merging**
