### PR TITLE
A11y: Fix aria attribute for page number and add correct role

### PR DESCRIPTION
**Pull request by amreladawy**
Run FastPass on Paginating control. 
It will report an error that aria-selected is a wrong attribute for page number button. The correct attribute is aria-checked. Also, added role radio to reflect the correct role of this pagination.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked

## Previous Behavior

The pagination buttons have the wrong aria attribute and fail a11y test tool by Microsoft.

## New Behavior

The buttons have the correct aria-checked and correct role

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Review by behowell — APPROVED** [review]

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d54dc8a1c10f8123413fe018e607cee9cffe2199'>d54dc8a1c10f8123413fe018e607cee9cffe2199</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Pull request merged**
