### PR TITLE
Azure Theme  bug fixes for DetailsList with Link, and ChoiceGroup with Icon/Image

### PR DESCRIPTION
**Pull request by Jacqueline-ms**
## Previous Behavior

Choicegroup with icon / image bug

DetailsList selected and selected+hover link is not passing accessibility 

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b6766ba321b57331266f3f391d7274c77730459d'>b6766ba321b57331266f3f391d7274c77730459d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Review by robtaft-ms — APPROVED** [review]
Thank you, this looks good.

**Review by mhdahman — APPROVED** [review]

**Review by spmonahan — APPROVED** [review]
Approving to unblock merging

**Pull request merged**
