### PR TITLE
chore(scripts): move index.ts to `/tasks` to follow sub-folder domain packaging

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

`@fluentui/scripts` is being used as one package for everything (but in reality exposes only just-scripts tasks)

## New Behavior

`@fluentui/scripts` doesn't provide any api. its index is moved to proper domain boundary which is `/tasks`. 

NOTE: this is the last step for "packaging" scripts sub-folders which will enable us to introduce proper packages

## Diff
```diff
-import { preset, task } from '@fluentui/scripts';
+import { preset, task } from '@fluentui/scripts/tasks';
```

## Related Issue(s)

* Fixes partially https://github.com/microsoft/fluentui/issues/24349

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/20221afa1c8dde9afe17a278ddcc0a8a9a4817e2'>20221afa1c8dde9afe17a278ddcc0a8a9a4817e2</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Avatar-mount_base.html">1634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Avatar-mount.html">1604</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Button-mount_base.html">1123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Button-mount.html">1146</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProvider-mount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProvider-mount.html">1970</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-mount_base.html">749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-mount.html">776</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">734</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">765</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/MakeStyles-mount_base.html">2342</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/MakeStyles-mount.html">2307</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Persona-mount_base.html">3627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/Persona-mount.html">3547</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/SpinButton-mount_base.html">3046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test-react-components/SpinButton-mount.html">3121</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26110&commitId=97b2ce28fdb82e3c8b24093315f0b0f43de888f2&env=prod)

✅ There was 0 screenshots added, 2 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount_base.html">2208</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount.html">2614</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/BaseButton-mount_base.html">1380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/BaseButton-mount.html">1446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Breadcrumb-mount_base.html">3421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Breadcrumb-mount.html">3430</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Checkbox-mount_base.html">3116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Checkbox-mount.html">3119</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/CheckboxBase-mount_base.html">2839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/CheckboxBase-mount.html">2779</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ChoiceGroup-mount_base.html">5389</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ChoiceGroup-mount.html">5334</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ComboBox-mount_base.html">1444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ComboBox-mount.html">1504</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/CommandBar-mount_base.html">11020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/CommandBar-mount.html">11020</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ContextualMenu-mount_base.html">12069</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ContextualMenu-mount.html">12196</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DefaultButton-mount_base.html">1654</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DefaultButton-mount.html">1666</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRow-mount_base.html">4355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRow-mount.html">4258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRowFast-mount_base.html">4229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRowFast-mount.html">4276</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRowNoStyles-mount_base.html">4197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DetailsRowNoStyles-mount.html">4131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Dialog-mount_base.html">3718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Dialog-mount.html">3862</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DocumentCardTitle-mount_base.html">677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/DocumentCardTitle-mount.html">716</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Dropdown-mount_base.html">3848</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Dropdown-mount.html">4043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/FocusTrapZone-mount_base.html">2260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/FocusTrapZone-mount.html">2363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/FocusZone-mount_base.html">2222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/FocusZone-mount.html">2304</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount_base.html">2208</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount.html">2614</a></td>
            <td>2</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-virtual-rerender_base.html">1381</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-virtual-rerender.html">1292</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedList-virtual-rerender-with-unmount.html">1947</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-mount_base.html">656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-mount.html">701</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-virtual-rerender_base.html">627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-virtual-rerender.html">633</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">641</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/IconButton-mount_base.html">2329</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/IconButton-mount.html">2310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Label-mount_base.html">872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Label-mount.html">847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Layer-mount_base.html">5075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Layer-mount.html">5035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Link-mount_base.html">976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Link-mount.html">977</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/MenuButton-mount_base.html">2015</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/MenuButton-mount.html">2053</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/MessageBar-mount_base.html">2666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/MessageBar-mount.html">2760</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Nav-mount_base.html">3965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Nav-mount.html">4042</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/OverflowSet-mount_base.html">1635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/OverflowSet-mount.html">1549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Panel-mount_base.html">3124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Panel-mount.html">3135</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Persona-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Persona-mount.html">1595</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Pivot-mount_base.html">1922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Pivot-mount.html">2018</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/PrimaryButton-mount_base.html">1822</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/PrimaryButton-mount.html">1851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Rating-mount_base.html">8751</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Rating-mount.html">8714</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SearchBox-mount_base.html">1821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SearchBox-mount.html">1851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Shimmer-mount_base.html">3413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Shimmer-mount.html">3435</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Slider-mount_base.html">2483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Slider-mount.html">2504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SpinButton-mount_base.html">5681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SpinButton-mount.html">5588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Spinner-mount_base.html">897</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Spinner-mount.html">912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SplitButton-mount_base.html">3766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SplitButton-mount.html">3874</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Stack-mount_base.html">1009</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Stack-mount.html">1012</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/StackWithIntrinsicChildren-mount_base.html">3090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/StackWithIntrinsicChildren-mount.html">2940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/StackWithTextChildren-mount_base.html">6170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/StackWithTextChildren-mount.html">6082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SwatchColorPicker-mount_base.html">12443</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/SwatchColorPicker-mount.html">12490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TagPicker-mount_base.html">3230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TagPicker-mount.html">3224</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TeachingBubble-mount_base.html">92019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TeachingBubble-mount.html">90016</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Text-mount_base.html">960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Text-mount.html">944</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TextField-mount_base.html">1934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/TextField-mount.html">1869</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-mount_base.html">1754</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-mount.html">1889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-virtual-rerender_base.html">1222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-virtual-rerender.html">1232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Toggle-mount_base.html">1273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/Toggle-mount.html">1305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/buttonNative-mount_base.html">613</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26110/perf-test/buttonNative-mount.html">660</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by TristanWatanabe — APPROVED** [review]

**Review by sopranopillow — APPROVED** [review]

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
