### PR TITLE
fix(react-aria): Updating scrollIntoView to support ancestral scroll parents + scrollMargin computed styles

### PR DESCRIPTION
**Pull request by stevencomsft**
## Previous Behavior

If using Listbox as a standalone in a scroll container, the scrollIntoView logic doesn't work as it only looks at the listbox parent directly, and not any ancestral scroll containers. Additionally, it does not take into account the scrollMargin styling set on Options

## New Behavior

Listboxes will now recursively find their first scrollable parent and take scrollMargin values into account when calculating scrollTo values

Tested with new unit tests and manual tests using existing storybook entries for combobox

[Combobox option scrolling demo](https://github.com/microsoft/fluentui/assets/105799836/b2f01385-ebd1-4401-8dc5-d859d661a305
)

[Listbox option scrolling demo](https://github.com/microsoft/fluentui/assets/105799836/a795d472-570b-4c1a-91d9-6b7ad00de519
)

[Listbox option scrolling demo with filter offset and scrollMargins demo](https://github.com/microsoft/fluentui/assets/105799836/209b48b7-e427-4e26-b53b-99e383c03f67
)

### CODE REVIEW

**Comment by stevencomsft** [comment]
This is an additional fix to go along with #31140 to make Listbox work better as a standalone component

**Review by ling1726 — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Avatar-mount_base.html">767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Avatar-mount.html">752</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Button-mount_base.html">363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Button-mount.html">362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Field-mount_base.html">1329</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Field-mount.html">1273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProvider-mount_base.html">869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProvider-mount.html">914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-mount_base.html">144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-mount.html">142</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">49</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">48</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">137</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/MakeStyles-mount_base.html">1066</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/MakeStyles-mount.html">1055</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Persona-mount_base.html">2205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/Persona-mount.html">2083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/SpinButton-mount_base.html">1738</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/SpinButton-mount.html">1720</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/SwatchPicker-mount_base.html">2093</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31158/perf-test-react-components/SwatchPicker-mount.html">2131</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `103.128 kB`<br />`33.283 kB` | `103.58 kB`<br />`33.44 kB` | `452 B` <br />`157 B` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `104.606 kB`<br />`33.244 kB` | `105.052 kB`<br />`33.394 kB` | `446 B` <br />`150 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.096 MB`<br />`265.999 kB` | `1.097 MB`<br />`266.16 kB` | `449 B` <br />`161 B` |
| <samp>react-tag-picker-preview</samp> <br /> <abbr title='bundle-size/Package.fixture.js'>@fluentui/react-tag-picker-preview - package</abbr> | `185.641 kB`<br />`54.844 kB` | `186.09 kB`<br />`55.008 kB` | `449 B` <br />`164 B` |
| <samp>react-timepicker-compat</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `105.149 kB`<br />`34.653 kB` | `105.6 kB`<br />`34.784 kB` | `451 B` <br />`131 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `100.94 kB`<br />`30.574 kB` |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr> | `83.737 kB`<br />`23.475 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr> | `50.175 kB`<br />`15.944 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr> | `19.702 kB`<br />`7.794 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr> | `64.829 kB`<br />`20.272 kB` |
| <samp>react-breadcrumb</samp> <br /> <abbr title='bundle-size/index.fixture.js'>@fluentui/react-breadcrumb - package</abbr> | `116.817 kB`<br />`32.173 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr> | `39.513 kB`<br />`11.17 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr> | `46.874 kB`<br />`12.662 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr> | `44.292 kB`<br />`12.544 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr> | `52.306 kB`<br />`14.135 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr> | `56.558 kB`<br />`13.068 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr> | `103.992 kB`<br />`29.35 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr> | `97.003 kB`<br />`27.61 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr> | `13.971 kB`<br />`5.626 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr> | `16.214 kB`<br />`6.386 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr> | `14.015 kB`<br />`5.752 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `71.104 kB`<br />`20.52 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `221.098 kB`<br />`62.406 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `43.591 kB`<br />`14.356 kB` |
| <samp>react-datepicker-compat</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker Compat</abbr> | `227.367 kB`<br />`63.503 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr> | `100.478 kB`<br />`30.071 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr> | `139.602 kB`<br />`43.628 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoLabel.fixture.js'>InfoLabel</abbr> | `143.417 kB`<br />`44.844 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr> | `153.638 kB`<br />`46.013 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu  (including selectable components)</abbr> | `156.324 kB`<br />`46.568 kB` |
| <samp>react-message-bar</samp> <br /> <abbr title='bundle-size/Default.fixture.js'>MessageBar (all components)</abbr> | `24.204 kB`<br />`8.983 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr> | `57.066 kB`<br />`17.821 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr> | `127.849 kB`<br />`40.049 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `7.944 kB`<br />`2.588 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr> | `168.508 kB`<br />`46.729 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr> | `45.324 kB`<br />`14.116 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr> | `137.912 kB`<br />`37.14 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr> | `76.328 kB`<br />`20.545 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr> | `74.971 kB`<br />`20.148 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/InteractionTag.fixture.js'>InteractionTag</abbr> | `15.299 kB`<br />`6.08 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/tag.fixture.js'>Tag</abbr> | `29.092 kB`<br />`9.418 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/TagGroup.fixture.js'>TagGroup</abbr> | `82.044 kB`<br />`24.39 kB` |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr> | `98.381 kB`<br />`29.706 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/dfcce5778a439feb180a4b1d33088068fd17caa5'>dfcce5778a439feb180a4b1d33088068fd17caa5</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Pull request merged**
