### PR TITLE
Fix typos in webpack integration instructions

### PR DESCRIPTION
**Pull request by Ahmed-Elkholy**
## Current Behavior

Some typos in the webpack integration instructions.

## New Behavior

1- Removed extra filename entry in webpack.config.js
2- Import fluentCard and fluentButton instead of fastCard and fastButton respectively

### CODE REVIEW

**Comment by chrisdholt** [comment]
@Ahmed-Elkholy Can you run the change command from the root to generate a change file for this? It doesn't effect distributed packages, so a change type of "none" should suffice. Thanks!

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0174dfc96d5ea925268fb3f51efaa6373ecabcc6'>0174dfc96d5ea925268fb3f51efaa6373ecabcc6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by Ahmed-Elkholy** [comment]
@chrisdholt Done!

**Comment by chrisdholt** [comment]
Screener seems to be timing out. @Hotell as FYI, I'm going to bypass and merge. Every other check has passed and this doesn't touch anything but mdx for our storybook.

**Pull request merged**
