### PR TITLE
Incorrect tense

### PR DESCRIPTION
**Pull request by dapinitial**
"Colors are using sparingly" should read: "Colors are used sparingly..." I also added the word `are` to the sentence.

I think there may be some punctuation errors in this paragraph as well (with the use of commas).

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12058)

### CODE REVIEW

**Comment by xugao** [comment]
@dapinitial - you need to run `yarn change` from the root to generate a change file

**Comment by dapinitial** [comment]
I will. I forked a copy and will run it. I was simply using the edit icon in the documentation and the GitHub interface to edit the markdown. I found a ton of errors today that I’d like to help remedy but I have moved onto other things for the moment

**Comment by aneeshack4** [comment]
@dapinitial do you want to close and reopen this once you've resolved the errors & are able to commit the change files?

**Comment by dapinitial** [comment]
Yes and I have some more. I’m in Tahoe but I’ll be back Tuesday. I just tried the edit feature in GitHub but I see I need to fork clone and then run yarn. Is this correct?

**Comment by aneeshack4** [comment]
@dapinitial Yes, you'll have to fork clone - it's recommended you maintain a local master and branch off that for each PR

**Comment by aneeshack4** [comment]
@dapinitial any update on this?

**Comment by dapinitial** [comment]
Just came back from Tahoe. I have some work to catch up on   /finish up today and tomorrow and then I can get this project up. There were other typos I noticed so I will start from the top down and address each as a read the docs.

**Pull request merged**
