### PR TITLE
BREAKING: change `smaller` size to `extra-small`

### PR DESCRIPTION
**Pull request by ling1726**
## ⚠️ Breaking change

Changes the `smaller` size to `extra-small` to be consistent with other size ramps in the library

## Previous Behavior

```tsx
<Table size="smaller">
{/* ...rest */}
</Table>
```

## New Behavior

```tsx
<Table size="extra-small">
{/* ...rest */}
</Table>
```

## Related Issue(s)

* Addresses #25706

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.951 kB`<br />`17.675 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `190.427 kB`<br />`53.087 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.456 kB`<br />`11.029 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d2a957c632af5cc995b4582a3b8e8f075139df7b'>d2a957c632af5cc995b4582a3b8e8f075139df7b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/Avatar-mount_base.html">1285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/Avatar-mount.html">1296</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/Button-mount_base.html">928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/Button-mount.html">927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProvider-mount_base.html">1492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProvider-mount.html">1482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-mount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-mount.html">570</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">537</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">571</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/MakeStyles-mount_base.html">1959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/MakeStyles-mount.html">1984</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/SpinButton-mount_base.html">2337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25713/perf-test-react-components/SpinButton-mount.html">2355</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 6 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25713&commitId=31fc79a7b720f3c4cdf26d28fddf89f88f5c5005&env=prod)

✅ There was 2 screenshots added, 2 screenshots removed, 1747 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 6 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+active+badge.normal.chromium.png|9| Changed|
|Avatar Converged.size+active+ring-shadow.normal.chromium.png|15| Changed|
|Table layout flex.size - extra small.chromium.png|0| Added|
|Table layout table.size - extra small.chromium.png|0| Added|
|Table layout flex.size - smaller.chromium.png|0| Removed|
|Table layout table.size - smaller.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 6 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25713&commitId=d0fb3c1d5d1e24b6455d70ec48186667ca352054&env=prod)

✅ There was 2 screenshots added, 2 screenshots removed, 1747 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 6 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+active+badge.normal.chromium.png|10| Changed|
|Avatar Converged.size+active+ring-shadow.normal.chromium.png|13| Changed|
|Table layout flex.size - extra small.chromium.png|0| Added|
|Table layout table.size - extra small.chromium.png|0| Added|
|Table layout flex.size - smaller.chromium.png|0| Removed|
|Table layout table.size - smaller.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
