### PR TITLE
update react-positioning to use latest floating ui dev tools to take latest fix

### PR DESCRIPTION
**Pull request by micahgodbolt**

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `4.447 kB`<br />`1.853 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             | `34.616 kB`<br />`7.317 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `19.287 kB`<br />`5.498 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `180 B`<br />`160 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/a493617d5c710d78246d315e67fa7eb2d7b6b9f9'>a493617d5c710d78246d315e67fa7eb2d7b6b9f9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AccordionMinimalPerf.default | [86](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AccordionMinimalPerf.default.html) | [77](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.12:1
ChatWithPopoverPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatWithPopoverPerf.default.html) | [183](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.09:1
ButtonMinimalPerf.default | [93](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonMinimalPerf.default.html) | [86](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
ProviderMinimalPerf.default | [214](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ProviderMinimalPerf.default.html) | [199](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.08:1
FlexMinimalPerf.default | [158](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/FlexMinimalPerf.default.html) | [148](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.07:1
InputMinimalPerf.default | [558](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/InputMinimalPerf.default.html) | [523](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.07:1
CarouselMinimalPerf.default | [269](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CarouselMinimalPerf.default.html) | [254](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.06:1
ReactionMinimalPerf.default | [225](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ReactionMinimalPerf.default.html) | [213](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.06:1
RefMinimalPerf.default | [112](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RefMinimalPerf.default.html) | [106](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.06:1
TextAreaMinimalPerf.default | [287](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TextAreaMinimalPerf.default.html) | [270](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [90](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TreeWith60ListItems.default.html) | [85](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
MenuButtonMinimalPerf.default | [972](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [925](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.05:1
AttachmentSlotsPerf.default | [641](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AttachmentSlotsPerf.default.html) | [618](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [325](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonSlotsPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
RadioGroupMinimalPerf.default | [267](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [257](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.04:1
SegmentMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SegmentMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.04:1
SkeletonMinimalPerf.default | [202](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SkeletonMinimalPerf.default.html) | [194](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.04:1
TableManyItemsPerf.default | [1137](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TableManyItemsPerf.default.html) | [1089](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [234](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TableMinimalPerf.default.html) | [224](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/HeaderSlotsPerf.default.html) | [458](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [725](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [707](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LayoutMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
PopupMinimalPerf.default | [352](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/PopupMinimalPerf.default.html) | [341](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
SplitButtonMinimalPerf.default | [2321](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [2262](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.03:1
CustomToolbarPrototype.default | [1493](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CustomToolbarPrototype.default.html) | [1452](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.03:1
BoxMinimalPerf.default | [196](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/BoxMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
CheckboxMinimalPerf.default | [1187](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CheckboxMinimalPerf.default.html) | [1168](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DialogMinimalPerf.default.html) | [437](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
EmbedMinimalPerf.default | [1916](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/EmbedMinimalPerf.default.html) | [1871](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.02:1
FormMinimalPerf.default | [224](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/FormMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.02:1
ListCommonPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListCommonPerf.default.html) | [383](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListCommonPerf.default_base.html) | 1.02:1
ProviderMergeThemesPerf.default | [649](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [638](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.02:1
TreeMinimalPerf.default | [481](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TreeMinimalPerf.default.html) | [472](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [220](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ImageMinimalPerf.default.html) | [218](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
ListNestedPerf.default | [332](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListNestedPerf.default.html) | [330](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListNestedPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [189](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LoaderMinimalPerf.default.html) | [188](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
RosterPerf.default | [1538](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RosterPerf.default.html) | [1517](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/RosterPerf.default_base.html) | 1.01:1
PortalMinimalPerf.default | [85](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/PortalMinimalPerf.default.html) | [84](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TextMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [531](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ToolbarMinimalPerf.default.html) | [526](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AnimationMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [643](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [643](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [1434](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DropdownMinimalPerf.default.html) | [1441](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [210](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/HeaderMinimalPerf.default.html) | [209](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
AttachmentMinimalPerf.default | [81](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AttachmentMinimalPerf.default.html) | [82](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.99:1
AvatarMinimalPerf.default | [108](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AvatarMinimalPerf.default.html) | [109](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.99:1
ChatDuplicateMessagesPerf.default | [152](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [154](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.99:1
SliderMinimalPerf.default | [739](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SliderMinimalPerf.default.html) | [746](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.99:1
TooltipMinimalPerf.default | [1250](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TooltipMinimalPerf.default.html) | [1267](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [3497](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DatepickerMinimalPerf.default.html) | [3578](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.98:1
DividerMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DividerMinimalPerf.default.html) | [204](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.98:1
MenuMinimalPerf.default | [485](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/MenuMinimalPerf.default.html) | [496](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.98:1
StatusMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/StatusMinimalPerf.default.html) | [387](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/IconMinimalPerf.default.html) | [378](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.98:1
CardMinimalPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CardMinimalPerf.default.html) | [310](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.97:1
ChatMinimalPerf.default | [425](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatMinimalPerf.default.html) | [438](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.97:1
DropdownManyItemsPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DropdownManyItemsPerf.default.html) | [408](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.96:1
LabelMinimalPerf.default | [212](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LabelMinimalPerf.default.html) | [221](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.96:1
ListWith60ListItems.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListWith60ListItems.default.html) | [364](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.96:1
ListMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListMinimalPerf.default.html) | [319](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.95:1
VideoMinimalPerf.default | [427](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/VideoMinimalPerf.default.html) | [450](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.95:1
AlertMinimalPerf.default | [152](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AlertMinimalPerf.default.html) | [161](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.94:1
GridMinimalPerf.default | [179](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/GridMinimalPerf.default.html) | [192](https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Comment by micahgodbolt** [comment]
Seems that `devtools` has changed from a function to a type export in 0.0.3

image

**Review by ling1726 — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Avatar-mount_base.html">663</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Avatar-mount.html">655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Button-mount_base.html">313</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Button-mount.html">300</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Field-mount_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Field-mount.html">1132</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProvider-mount_base.html">691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProvider-mount.html">692</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-mount_base.html">83</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-mount.html">83</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">60</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">67</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">85</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">79</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/MakeStyles-mount_base.html">871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/MakeStyles-mount.html">856</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Persona-mount_base.html">1764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/Persona-mount.html">1739</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/SpinButton-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30235/perf-test-react-components/SpinButton-mount.html">1399</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Pull request merged**
