### PR TITLE
Fix Storybook Publish

### PR DESCRIPTION
**Pull request by levithomason**
## Current Behavior

🚨 `yarn chromatic` fails to build Storybook.

## New Behavior

 ✅  `yarn chromatic` builds and releases Storybook. The `npx` script was using an outdated `chromatic` package.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
oh good, it wasn't just me :D

**Review by micahgodbolt — APPROVED** [review]

**Comment by levithomason** [comment]
Yea, seems it was timing out because we were 1 major version behind. We're live again:

https://aka.ms/fluentui-storybook

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `165.697 kB`<br />`46.873 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.489 kB`<br />`10.636 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0f3e58e289514a5b8dc1eddbb70a720112b48df0'>0f3e58e289514a5b8dc1eddbb70a720112b48df0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Avatar-mount_base.html">909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Avatar-mount.html">898</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/BaseButton-mount_base.html">960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/BaseButton-mount.html">926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Breadcrumb-mount_base.html">2640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Breadcrumb-mount.html">2655</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ButtonNext-mount_base.html">522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ButtonNext-mount.html">519</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Checkbox-mount_base.html">1579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Checkbox-mount.html">1543</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/CheckboxBase-mount_base.html">1338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/CheckboxBase-mount.html">1301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ChoiceGroup-mount_base.html">4829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ChoiceGroup-mount.html">4788</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ComboBox-mount_base.html">1009</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ComboBox-mount.html">980</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/CommandBar-mount_base.html">10214</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/CommandBar-mount.html">10230</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ContextualMenu-mount_base.html">16327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ContextualMenu-mount.html">16620</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DefaultButton-mount_base.html">1170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DefaultButton-mount.html">1163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRow-mount_base.html">3749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRow-mount.html">3734</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRowFast-mount_base.html">3893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRowFast-mount.html">3735</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRowNoStyles-mount_base.html">3523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DetailsRowNoStyles-mount.html">3547</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Dialog-mount_base.html">2625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Dialog-mount.html">2622</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DocumentCardTitle-mount_base.html">189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/DocumentCardTitle-mount.html">177</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Dropdown-mount_base.html">3257</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Dropdown-mount.html">3317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderNext-mount_base.html">1890</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderNext-mount.html">1866</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-mount_base.html">160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-mount.html">178</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-virtual-rerender.html">133</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">207</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FocusTrapZone-mount_base.html">1866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FocusTrapZone-mount.html">1803</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FocusZone-mount_base.html">1889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/FocusZone-mount.html">1931</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/IconButton-mount_base.html">1782</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/IconButton-mount.html">1804</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Label-mount_base.html">368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Label-mount.html">380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Layer-mount_base.html">3048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Layer-mount.html">3075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Link-mount_base.html">502</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Link-mount.html">502</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MakeStyles-mount_base.html">1721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MakeStyles-mount.html">1718</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MenuButton-mount_base.html">1504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MenuButton-mount.html">1489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MessageBar-mount_base.html">2031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/MessageBar-mount.html">2023</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Nav-mount_base.html">3323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Nav-mount.html">3303</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/OverflowSet-mount_base.html">1143</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/OverflowSet-mount.html">1172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Panel-mount_base.html">2523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Panel-mount.html">2531</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Persona-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Persona-mount.html">885</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Pivot-mount_base.html">1465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Pivot-mount.html">1458</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/PrimaryButton-mount_base.html">1360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/PrimaryButton-mount.html">1327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Rating-mount_base.html">7762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Rating-mount.html">7697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SearchBox-mount_base.html">1400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SearchBox-mount.html">1346</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Shimmer-mount_base.html">2566</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Shimmer-mount.html">2547</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Slider-mount_base.html">1953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Slider-mount.html">1982</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SpinButton-mount_base.html">5180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SpinButton-mount.html">5051</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Spinner-mount_base.html">463</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Spinner-mount.html">466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SplitButton-mount_base.html">3185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SplitButton-mount.html">3194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Stack-mount_base.html">549</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Stack-mount.html">528</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/StackWithIntrinsicChildren-mount_base.html">2251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/StackWithIntrinsicChildren-mount.html">2308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/StackWithTextChildren-mount_base.html">5253</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/StackWithTextChildren-mount.html">5242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SwatchColorPicker-mount_base.html">11467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/SwatchColorPicker-mount.html">11435</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TagPicker-mount_base.html">2630</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TagPicker-mount.html">2752</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TeachingBubble-mount_base.html">13234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TeachingBubble-mount.html">13284</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Text-mount_base.html">447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Text-mount.html">456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TextField-mount_base.html">1414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/TextField-mount.html">1419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-mount_base.html">1270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-mount.html">1239</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-virtual-rerender_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-virtual-rerender.html">642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1919</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Toggle-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/Toggle-mount.html">853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/buttonNative-mount_base.html">149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21587/perf-test/buttonNative-mount.html">155</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

**Pull request merged**
