### PR TITLE
Tabster: update tabster dependency

### PR DESCRIPTION
**Pull request by spmonahan**
## Current Behavior

Tabster dependency is ^1.3.3

## New Behavior

Tabster dependency is ^1.4.0

### CODE REVIEW

**Comment by Hotell** [comment]
is this related to upcoming release ? or what was the need ? just curious/cautios as @andrefcdias run into some issues that tabster introduced some kind of breaking changes. 

From consumer perspective  this should not have any effect as we use carets for 3rd party deps.

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/Avatar-mount_base.html">934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/Avatar-mount.html">850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/Button-mount_base.html">545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/Button-mount.html">567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProvider-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProvider-mount.html">1819</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-mount_base.html">282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-mount.html">254</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">244</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">279</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/MakeStyles-mount_base.html">1488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test-react-components/MakeStyles-mount.html">1553</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                      Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `73.734 kB`<br />`22.498 kB` |   `74.226 kB`<br />`22.67 kB` |    `492 B` <br />`172 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `59.002 kB`<br />`16.923 kB` |  `60.742 kB`<br />`17.403 kB` |  `1.74 kB` <br />`480 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `54.287 kB`<br />`15.672 kB` |  `56.027 kB`<br />`16.141 kB` |  `1.74 kB` <br />`469 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `180.516 kB`<br />`50.358 kB` |  `180.81 kB`<br />`50.474 kB` |    `294 B` <br />`116 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `110.519 kB`<br />`33.649 kB` | `111.012 kB`<br />`33.848 kB` |    `493 B` <br />`199 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `113.694 kB`<br />`34.118 kB` | `114.187 kB`<br />`34.314 kB` |    `493 B` <br />`196 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `101.158 kB`<br />`30.817 kB` | `103.063 kB`<br />`31.296 kB` | `1.905 kB` <br />`479 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>                           |   `2.936 kB`<br />`1.212 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                         | `45.608 kB`<br />`13.312 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                            |  `21.002 kB`<br />`6.628 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                              |  `21.915 kB`<br />`6.933 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                            |  `22.246 kB`<br />`6.672 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                         |   `33.06 kB`<br />`9.098 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                         | `39.987 kB`<br />`10.354 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                 |  `35.243 kB`<br />`9.847 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                               | `42.597 kB`<br />`11.169 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                             | `43.991 kB`<br />`10.034 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `7.793 kB`<br />`3.327 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `9.363 kB`<br />`3.841 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |    `7.765 kB`<br />`3.35 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox</abbr>                                                   | `60.792 kB`<br />`20.778 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `34.078 kB`<br />`11.098 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                      |   `15.55 kB`<br />`5.595 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                            |  `10.235 kB`<br />`4.036 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                            |  `22.174 kB`<br />`7.304 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                            |   `8.546 kB`<br />`3.574 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                              |  `11.422 kB`<br />`4.648 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                    |  `10.792 kB`<br />`4.124 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                         |    `6.272 kB`<br />`2.17 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                              |   `23.21 kB`<br />`8.084 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                       |  `14.127 kB`<br />`5.299 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                            | `29.468 kB`<br />`10.091 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                  |  `13.651 kB`<br />`5.484 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                         |  `17.132 kB`<br />`6.365 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                         |  `25.557 kB`<br />`8.266 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                             | `41.865 kB`<br />`11.861 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                      |  `17.795 kB`<br />`5.951 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                         |  `25.439 kB`<br />`8.247 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                             |  `10.904 kB`<br />`4.298 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                           |  `14.224 kB`<br />`4.719 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                   |  `21.218 kB`<br />`7.176 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                             |           `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                       |  `31.363 kB`<br />`7.043 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                     |  `19.806 kB`<br />`5.699 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                      | `42.939 kB`<br />`14.782 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                            |         `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d1b79b83dbffbc0242d8f463715741efec9bf5dd'>d1b79b83dbffbc0242d8f463715741efec9bf5dd</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/BaseButton-mount_base.html">762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/BaseButton-mount.html">781</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Breadcrumb-mount_base.html">2435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Breadcrumb-mount.html">2390</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Checkbox-mount_base.html">1277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Checkbox-mount.html">1301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/CheckboxBase-mount_base.html">1073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/CheckboxBase-mount.html">1067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ChoiceGroup-mount_base.html">4057</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ChoiceGroup-mount.html">4096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ComboBox-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ComboBox-mount.html">843</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/CommandBar-mount_base.html">9171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/CommandBar-mount.html">9171</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ContextualMenu-mount_base.html">10191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ContextualMenu-mount.html">10016</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DefaultButton-mount_base.html">980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DefaultButton-mount.html">978</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRow-mount_base.html">3340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRow-mount.html">3329</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRowFast-mount_base.html">3260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRowFast-mount.html">3319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRowNoStyles-mount_base.html">3122</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DetailsRowNoStyles-mount.html">3162</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Dialog-mount_base.html">1972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Dialog-mount.html">1968</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DocumentCardTitle-mount_base.html">150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/DocumentCardTitle-mount.html">145</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Dropdown-mount_base.html">2829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Dropdown-mount.html">2879</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/FocusTrapZone-mount_base.html">1596</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/FocusTrapZone-mount.html">1600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/FocusZone-mount_base.html">1574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/FocusZone-mount.html">1556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/IconButton-mount_base.html">1490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/IconButton-mount.html">1522</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Label-mount_base.html">302</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Label-mount.html">294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Layer-mount_base.html">2563</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Layer-mount.html">2549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Link-mount_base.html">412</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Link-mount.html">397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/MenuButton-mount_base.html">1285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/MenuButton-mount.html">1286</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/MessageBar-mount_base.html">1814</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/MessageBar-mount.html">1885</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Nav-mount_base.html">2833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Nav-mount.html">2855</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/OverflowSet-mount_base.html">958</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/OverflowSet-mount.html">948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Panel-mount_base.html">1846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Panel-mount.html">1894</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Persona-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Persona-mount.html">860</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Pivot-mount_base.html">1213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Pivot-mount.html">1257</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/PrimaryButton-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/PrimaryButton-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Rating-mount_base.html">6638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Rating-mount.html">6626</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SearchBox-mount_base.html">1136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SearchBox-mount.html">1101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Shimmer-mount_base.html">2201</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Shimmer-mount.html">2135</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Slider-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Slider-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SpinButton-mount_base.html">4357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SpinButton-mount.html">4332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Spinner-mount_base.html">364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Spinner-mount.html">375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SplitButton-mount_base.html">2749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SplitButton-mount.html">2755</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Stack-mount_base.html">451</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Stack-mount.html">454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/StackWithIntrinsicChildren-mount_base.html">1949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/StackWithIntrinsicChildren-mount.html">1959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/StackWithTextChildren-mount_base.html">4497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/StackWithTextChildren-mount.html">4491</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SwatchColorPicker-mount_base.html">9921</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/SwatchColorPicker-mount.html">10031</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TagPicker-mount_base.html">2295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TagPicker-mount.html">2339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TeachingBubble-mount_base.html">84918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TeachingBubble-mount.html">84229</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Text-mount_base.html">365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Text-mount.html">361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TextField-mount_base.html">1221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/TextField-mount.html">1238</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-mount_base.html">1010</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-mount.html">1033</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-virtual-rerender_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-virtual-rerender.html">561</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Toggle-mount_base.html">688</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/Toggle-mount.html">687</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/buttonNative-mount_base.html">106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23109/perf-test/buttonNative-mount.html">115</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by spmonahan** [comment]
> is this related to upcoming release ? or what was the need ? just curious/cautios as @andrefcdias run into some issues that tabster introduced some kind of breaking changes.
> 
> From consumer perspective this should not have any effect as we use carets for 3rd party deps.

I had a partner ask about getting this change into the non-breaking RC release: https://github.com/microsoft/tabster/pull/146

**Review by Hotell — APPROVED** [review]

**Review by miroslavstastny — APPROVED** [review]

**Pull request merged**
