### PR TITLE
docs(public-docsite): update getting started with CRA

### PR DESCRIPTION
**Pull request by kubkon**
Cherry-pick of #16629.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/BaseButton-mount_base.html">1046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/BaseButton-mount.html">1006</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Breadcrumb-mount_base.html">44961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Breadcrumb-mount.html">43703</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Checkbox-mount_base.html">1664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Checkbox-mount.html">1685</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/CheckboxBase-mount_base.html">1439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/CheckboxBase-mount.html">1414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ChoiceGroup-mount_base.html">5360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ChoiceGroup-mount.html">5440</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ComboBox-mount_base.html">997</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ComboBox-mount.html">962</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/CommandBar-mount_base.html">8160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/CommandBar-mount.html">8176</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ContextualMenu-mount_base.html">12862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/ContextualMenu-mount.html">13084</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DefaultButton-mount_base.html">1144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DefaultButton-mount.html">1172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRow-mount_base.html">3951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRow-mount.html">3689</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRowFast-mount_base.html">4177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRowFast-mount.html">4209</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRowNoStyles-mount_base.html">3499</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DetailsRowNoStyles-mount.html">3730</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Dialog-mount_base.html">1659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Dialog-mount.html">1557</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DocumentCardTitle-mount_base.html">2138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/DocumentCardTitle-mount.html">2016</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Dropdown-mount_base.html">2847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Dropdown-mount.html">2887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/FocusTrapZone-mount_base.html">1837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/FocusTrapZone-mount.html">1818</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/FocusZone-mount_base.html">1985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/FocusZone-mount.html">1910</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/IconButton-mount_base.html">1942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/IconButton-mount.html">1957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Label-mount_base.html">357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Label-mount.html">359</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Layer-mount_base.html">2194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Layer-mount.html">2131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Link-mount_base.html">487</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Link-mount.html">482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/MenuButton-mount_base.html">1620</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/MenuButton-mount.html">1629</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/MessageBar-mount_base.html">2304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/MessageBar-mount.html">2346</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Nav-mount_base.html">3473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Nav-mount.html">3694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/OverflowSet-mount_base.html">1452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/OverflowSet-mount.html">1447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Panel-mount_base.html">1458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Panel-mount.html">1483</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Persona-mount_base.html">846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Persona-mount.html">874</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Pivot-mount_base.html">1534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Pivot-mount.html">1454</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/PrimaryButton-mount_base.html">1357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/PrimaryButton-mount.html">1414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Rating-mount_base.html">7916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Rating-mount.html">7855</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SearchBox-mount_base.html">1308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SearchBox-mount.html">1319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Shimmer-mount_base.html">2723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Shimmer-mount.html">2710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Slider-mount_base.html">1501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Slider-mount.html">1514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SpinButton-mount_base.html">5187</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SpinButton-mount.html">5101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Spinner-mount_base.html">434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Spinner-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SplitButton-mount_base.html">3431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SplitButton-mount.html">3563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Stack-mount_base.html">568</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Stack-mount.html">547</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/StackWithIntrinsicChildren-mount.html">1667</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/StackWithTextChildren-mount_base.html">5323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/StackWithTextChildren-mount.html">5283</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SwatchColorPicker-mount_base.html">10602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/SwatchColorPicker-mount.html">10494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TagPicker-mount_base.html">2798</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TagPicker-mount.html">2925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TeachingBubble-mount_base.html">53171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TeachingBubble-mount.html">52882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Text-mount_base.html">467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Text-mount.html">454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TextField-mount_base.html">1503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/TextField-mount.html">1461</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Toggle-mount_base.html">871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/Toggle-mount.html">911</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/button-mount_base.html">104</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16659/merge/perf-test/button-mount.html">103</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ecraig12345 — APPROVED** [review]
LGTM though you'll need a change file for this package in 7.0. (This package doesn't actually need to be published now but I keep forgetting/not having time to disable it...)

**Comment by ecraig12345** [comment]
@kubkon reminder to add a change file to this PR

**Comment by ecraig12345** [comment]
Closing since it's less relevant now that we're on v8

**Pull request closed without merging**
