### PR TITLE
feat: Release react-combobox as stable

### PR DESCRIPTION
**Pull request by smhigley**
Adds `Combobox` and `Dropdown` to stable components :)

### CODE REVIEW

**Review by behowell — APPROVED** [review]

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `82.678 kB`<br />`26.408 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                    | `79.037 kB`<br />`26.159 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `81.346 kB`<br />`26.144 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/21a34685cddbbae6531152e9f3393e237ba7b92c'>21a34685cddbbae6531152e9f3393e237ba7b92c</a></sub>
<div id="bundleSizeComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Review by micahgodbolt — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Avatar-mount_base.html">1556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Avatar-mount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Button-mount_base.html">1109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Button-mount.html">1103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProvider-mount_base.html">1906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProvider-mount.html">1930</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-mount_base.html">731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-mount.html">745</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">692</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">736</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">733</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/InfoButton-mount_base.html">660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/InfoButton-mount.html">669</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/MakeStyles-mount_base.html">2201</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/MakeStyles-mount.html">2244</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Persona-mount_base.html">3499</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/Persona-mount.html">3543</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/SpinButton-mount_base.html">2971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26518/perf-test-react-components/SpinButton-mount.html">2989</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by ParadimeWeb** [comment]
It does not work with react 8. Fatal error!

image

**Comment by spmonahan** [comment]
@ParadimeWeb can you open a [bug report](https://github.com/microsoft/fluentui/issues/new?assignees=&labels=Type%3A+Bug+%F0%9F%90%9B%2CNeeds%3A+Triage+%F0%9F%94%8D&template=bug-report.yml&title=%5BBug%5D%3A+) for your issue?

**Pull request merged**
