### PR TITLE
fix(react-jsx-runtime): make /jsx-runtime compatible with Webpack 4

### PR DESCRIPTION
**Pull request by layershifter**
## Previous Behavior

Builds with Webpack 4 fail 💥 

```
Hash: 7f9e492661ae86af63e7
Version: webpack 4.47.0
Time: 1072ms
Built at: 09/11/2023 8:14:42 PM
 1 asset
Entrypoint main = main.js
 [4] (webpack)/buildin/global.js 472 bytes {0} [built]
[21] ./src/index.js + 52 modules 338 KiB {0} [built]
     | ./src/index.js 357 bytes [built]
     |     + 52 hidden modules
    + 377 hidden modules

ERROR in ./node_modules/@fluentui/react-menu/lib/components/MenuDivider/renderMenuDivider.js
Module not found: Error: Can't resolve '@fluentui/react-jsx-runtime/jsx-runtime' in '/Users/olfedias/WebstormProjects/test-html-webpack/node_modules/@fluentui/react-menu/lib/components/MenuDivider'
 @ ./node_modules/@fluentui/react-menu/lib/components/MenuDivider/renderMenuDivider.js 1:81-151 8:25-29
 @ ./node_modules/@fluentui/react-menu/lib/components/MenuDivider/index.js
 @ ./node_modules/@fluentui/react-menu/lib/MenuDivider.js
 @ ./node_modules/@fluentui/react-menu/lib/index.js
 @ ./src/index.js
```

## New Behavior

Builds are passing with Webpack 4 and other tooling 🟢 

The PR does the same trick as `/unstable` in `@fluentui/react-components`. The trick is to create a fake `package.json`, so tooling that does not support export maps will properly resolve things.

The PR adds entrypoints for `/jsx-runtime` & `/jsx-dev-runtime`.

### Webpack 4

<details>

```
yarn run v1.22.19
warning package.json: No license field
$ /Users/olfedias/WebstormProjects/test-html-webpack/node_modules/.bin/webpack
Hash: b53c5100c63974f31bd7
Version: webpack 4.47.0
Time: 3017ms
Built at: 09/11/2023 8:04:22 PM
  Asset     Size  Chunks                    Chunk Names
main.js  499 KiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
 [4] (webpack)/buildin/global.js 472 bytes {0} [built]
[22] ./src/index.js + 58 modules 341 KiB {0} [built]
     | ./src/index.js 357 bytes [built]
     |     + 58 hidden modules
    + 378 hidden modules
Done in 15.16s.

```

</details>

### Webpack 5

<details>

```
  yarn run v1.22.19
warning package.json: No license field
$ /Users/olfedias/WebstormProjects/test-html-webpack/node_modules/.bin/webpack
asset main.js 471 KiB [emitted] [big] (name: main)
orphan modules 10.7 MiB [orphan] 432 modules
runtime modules 1.98 KiB 5 modules
cacheable modules 478 KiB
  modules by path ./node_modules/react/ 7.98 KiB
    modules by path ./node_modules/react/*.js 404 bytes 2 modules
    modules by path ./node_modules/react/cjs/*.js 7.59 KiB 2 modules
  modules by path ./node_modules/react-dom/ 130 KiB
    ./node_modules/react-dom/index.js 1.33 KiB [built] [code generated]
    ./node_modules/react-dom/cjs/react-dom.production.min.js 129 KiB [built] [code generated]
  modules by path ./node_modules/scheduler/ 4.33 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.14 KiB [built] [code generated]
  ./src/index.js + 52 modules 336 KiB [built] [code generated]
webpack 5.88.2 compiled successfully in 1374 ms
Done in 3.03s.
```

</details>

### Jest 29

<details>

```
yarn run v1.22.19
warning package.json: No license field
$ /Users/olfedias/WebstormProjects/test-html-webpack/node_modules/.bin/jest
PASS src/index.test.js
  ✓ renders without crashing (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.848 s, estimated 2 s
Ran all test suites.
Done in 1.35s.
```

</details>

### Vite 4

<details>

```
yarn run v1.22.19
warning package.json: No license field
$ /Users/olfedias/WebstormProjects/test-html-webpack/node_modules/.bin/vite build
vite v4.4.9 building for production...
transforming...
✓ 458 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                  0.12 kB │ gzip:  0.11 kB
dist/assets/index-1d8d1a9b.js  218.40 kB │ gzip: 69.14 kB
✓ built in 1.42s
Done in 1.69s.
```

</details>

### Typescript 5.2

✅

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount_base.html">11</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount.html">12</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Avatar-mount_base.html">616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Avatar-mount.html">616</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Button-mount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Button-mount.html">317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Field-mount_base.html">1120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Field-mount.html">1122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProvider-mount_base.html">691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProvider-mount.html">673</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-mount_base.html">76</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-mount.html">79</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">61</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">72</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">76</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">74</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount_base.html">11</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount.html">12</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/MakeStyles-mount_base.html">862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/MakeStyles-mount.html">866</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Persona-mount_base.html">1714</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/Persona-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/SpinButton-mount_base.html">1353</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29129/perf-test-react-components/SpinButton-mount.html">1401</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                   |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> |  `91.384 kB`<br />`27.926 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                             |   `25.793 kB`<br />`8.348 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                               |   `26.694 kB`<br />`8.658 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                             |     `24.75 kB`<br />`8.96 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                          |  `39.469 kB`<br />`10.758 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                          |  `46.824 kB`<br />`12.259 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                  |  `43.896 kB`<br />`12.025 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                |  `51.922 kB`<br />`13.596 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                              |  `56.557 kB`<br />`12.667 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>          |  `89.925 kB`<br />`27.453 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                       |    `19.704 kB`<br />`7.38 kB` |
| <samp>react-field</samp> <br /> <abbr title='bundle-size/Field.fixture.js'>Field</abbr>                                             |   `21.036 kB`<br />`8.091 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                             |    `14.62 kB`<br />`5.869 kB` |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Classic.fixture.js'>Classic Pragma</abbr>                            |       `1.072 kB`<br />`544 B` |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/DevRuntime.fixture.js'>JSX Dev Runtime</abbr>                        |     `2.775 kB`<br />`1.29 kB` |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Runtime.fixture.js'>JSX Runtime</abbr>                               |    `3.293 kB`<br />`1.529 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                             |   `13.036 kB`<br />`5.405 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                               |   `15.902 kB`<br />`6.506 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                |  `139.629 kB`<br />`43.01 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>   | `142.365 kB`<br />`43.541 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                       | `118.701 kB`<br />`37.361 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                        |   `21.258 kB`<br />`7.937 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                       |   `22.292 kB`<br />`8.113 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                              |   `15.644 kB`<br />`6.223 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                            |   `18.817 kB`<br />`6.546 kB` |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr>                         |  `91.601 kB`<br />`27.394 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                       |   `51.154 kB`<br />`18.06 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5894f6b7c66621e2da61d792bfb9ba1215797cec'>5894f6b7c66621e2da61d792bfb9ba1215797cec</a></sub>
<div id="bundleSizeComment9423"/>

**Review by jurokapsiar — APPROVED** [review]

**Review by miroslavstastny — APPROVED** [review]
Would appreciate more details for Webpack 4 in the PR description:
image

**Comment by layershifter** [comment]
@miroslavstastny oops, updated 👍

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by khmakoto — APPROVED** [review]

**Review by sopranopillow — APPROVED** [review]

**Review by TristanWatanabe — APPROVED** [review]

**Pull request merged**
