### PR TITLE
fix(utilities): `@types/react` should be optional

### PR DESCRIPTION
**Pull request by tido64**
## Previous Behavior

`@types/react` should be optional because not all consumers use TypeScript.

## New Behavior

`@types/react` should now be marked as optional

## Related Issue(s)

n/a

### CODE REVIEW

**Comment by fabricteam** [comment]
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Review by kelset — APPROVED** [review]

**Comment by tido64** [comment]
@behowell: Can you have a look at this when you have some time?

**Comment by layershifter** [comment]
@tido64 this is not only for this package. Almost every package in this repo has such dependencies. Would you mind to create an issue for this, so we can handle this properly?

Closing PR for housekeeping, but if it's relevant - feel free to re-open 👍

**Comment by tido64** [comment]
@layershifter I'd be happy to fix up all the packages if we reopen this?

**Comment by layershifter** [comment]
@tido64 IMO this problem requires some discussion and the agreement, so it would be great to have an issue first.

**Comment by tido64** [comment]
Gotcha, filed it here: https://github.com/microsoft/fluentui/issues/32292

**Pull request closed without merging**
