### PR TITLE
BREAKING: Remove context exports from react-components

### PR DESCRIPTION
**Pull request by ling1726**
In order to provider proper encapsulation and allow us to change
internals more easily, this PR removes exports of context objects from
react-components. In cases where contexts were removed, the export was
replaced with a specific provider component and hook to use the context
value.

Follows from #22300

## Current Behavior
Some contexts are exported from react-components

```tsx
import { MenuContext } from '@fluentui/react-components`

<MenuContext value={...}</MenuContext />
React.useContext(MenuContext);
```

## New Behavior

Only context providers and hooks are exported in place of contexts

```tsx
import { MenunProvider, useMenuContext_unstable } from '@fluentui/react-components`

<MenuContext value={...}</MenuContext />
useMenuContext_unstable()
```

## Related Issue(s)

Addresses partially #22300

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `73.734 kB`<br />`22.498 kB` |   `73.759 kB`<br />`22.51 kB` | `25 B` <br />`12 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `179.667 kB`<br />`50.151 kB` | `179.706 kB`<br />`50.167 kB` | `39 B` <br />`16 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `101.158 kB`<br />`30.817 kB` |  `101.172 kB`<br />`30.82 kB` |  `14 B` <br />`3 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `29.468 kB`<br />`10.091 kB` |  `29.482 kB`<br />`10.097 kB` |  `14 B` <br />`6 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `13.651 kB`<br />`5.484 kB` |   `13.664 kB`<br />`5.486 kB` |  `13 B` <br />`2 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                         | `45.608 kB`<br />`13.312 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `34.078 kB`<br />`11.098 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b7fc187b2691b1fe4cb49ad228602e8d6ce3c552'>b7fc187b2691b1fe4cb49ad228602e8d6ce3c552</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/Avatar-mount_base.html">1103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/Avatar-mount.html">1089</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/Button-mount_base.html">657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/Button-mount.html">658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProvider-mount_base.html">2251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProvider-mount.html">2229</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-mount_base.html">330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-mount.html">336</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">287</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">359</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/MakeStyles-mount_base.html">1885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23085/perf-test-react-components/MakeStyles-mount.html">1872</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by spmonahan — CHANGES_REQUESTED** [review]
Just putting a block on this so we can coordinate breaking merges

**Review by layershifter — APPROVED** [review]

**Review by behowell — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

**Comment by spmonahan** [comment]
> @ling1726 react-tabs exports TabListContextValues and TabListContextValue (I think I followed what Menu was doing at the time). Do those also need to be updated?

@GeoffCoxMSFT Yes it should be updated. Can you make a separate PR with that change?

**Comment by ling1726** [comment]
> @ling1726 react-tabs exports TabListContextValues and TabListContextValue (I think I followed what Menu was doing at the time). Do those also need to be updated?

@GeoffCoxMSFT I will work on some automation to ban that, so it will need to be done sooner or later, current PR objective is to remove them from react-components export since that is our public API surface

**Pull request merged**
