### PR TITLE
chore(react-datepicker): Scaffold package

### LINKED ISSUE #26227: DatePicker: Scaffold react-datepicker package
Issue to track scaffolding of the packages `react-datepicker` and `react-calendar`. There are still considerations to whether we will add `react-calendar` or have all calendar components live in `react-datepicker`.

### PR DESCRIPTION
**Pull request by sopranopillow**
This PR creates the package for `react-datepicker`, this is the outcome of just running `yarn create-package` and 
adding two more codeowners.

## Related Issue(s)

* Fixes #26227

### CODE REVIEW

**Review by JustSlone — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `3.182 kB`<br />`1.308 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             | `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/87dc68c62fc7796a2ffbe04ce9fe9aecc240286f'>87dc68c62fc7796a2ffbe04ce9fe9aecc240286f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Avatar-mount_base.html">1261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Avatar-mount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Button-mount_base.html">914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Button-mount.html">914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProvider-mount_base.html">1497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProvider-mount.html">1490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-mount_base.html">571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-mount.html">578</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">539</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">546</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">573</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/MakeStyles-mount_base.html">1969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/MakeStyles-mount.html">1979</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Persona-mount_base.html">2776</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/Persona-mount.html">2793</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/SpinButton-mount_base.html">2324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test-react-components/SpinButton-mount.html">2383</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26286&commitId=cbe8bf6d58a5abdeddd7f6c6f6126464d9188c36&env=prod)

✅ There was 0 screenshots added, 2 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/BaseButton-mount_base.html">1190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/BaseButton-mount.html">1211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Breadcrumb-mount_base.html">2823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Breadcrumb-mount.html">2824</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Checkbox-mount_base.html">2660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Checkbox-mount.html">2637</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/CheckboxBase-mount_base.html">2344</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/CheckboxBase-mount.html">2362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ChoiceGroup-mount_base.html">4284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ChoiceGroup-mount.html">4260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ComboBox-mount_base.html">1157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ComboBox-mount.html">1193</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/CommandBar-mount_base.html">9300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/CommandBar-mount.html">9663</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ContextualMenu-mount_base.html">10042</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ContextualMenu-mount.html">10079</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DefaultButton-mount_base.html">1355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DefaultButton-mount.html">1355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRow-mount_base.html">3371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRow-mount.html">3354</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRowFast-mount_base.html">3353</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRowFast-mount.html">3331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRowNoStyles-mount_base.html">3205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DetailsRowNoStyles-mount.html">3231</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Dialog-mount_base.html">2973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Dialog-mount.html">2901</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DocumentCardTitle-mount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/DocumentCardTitle-mount.html">575</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Dropdown-mount_base.html">3161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Dropdown-mount.html">3176</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/FocusTrapZone-mount_base.html">1963</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/FocusTrapZone-mount.html">1928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/FocusZone-mount_base.html">1882</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/FocusZone-mount.html">1922</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-mount_base.html">1817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-mount.html">2040</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-virtual-rerender_base.html">1091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-virtual-rerender.html">1099</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1619</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedList-virtual-rerender-with-unmount.html">1576</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-mount_base.html">568</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-mount.html">568</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-virtual-rerender_base.html">533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-virtual-rerender.html">535</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">563</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">572</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/IconButton-mount_base.html">1782</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/IconButton-mount.html">1790</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Label-mount_base.html">761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Label-mount.html">756</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Layer-mount_base.html">4184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Layer-mount.html">4189</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Link-mount_base.html">864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Link-mount.html">843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/MenuButton-mount_base.html">1609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/MenuButton-mount.html">1594</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/MessageBar-mount_base.html">2327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/MessageBar-mount.html">2313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Nav-mount_base.html">3035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Nav-mount.html">3061</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/OverflowSet-mount_base.html">1400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/OverflowSet-mount.html">1396</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Panel-mount_base.html">2516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Panel-mount.html">2562</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Persona-mount_base.html">1275</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Persona-mount.html">1280</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Pivot-mount_base.html">1536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Pivot-mount.html">1484</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/PrimaryButton-mount_base.html">1484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/PrimaryButton-mount.html">1489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Rating-mount_base.html">6922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Rating-mount.html">6936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SearchBox-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SearchBox-mount.html">1490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Shimmer-mount_base.html">2898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Shimmer-mount.html">2889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Slider-mount_base.html">2118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Slider-mount.html">2114</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SpinButton-mount_base.html">4560</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SpinButton-mount.html">4245</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Spinner-mount_base.html">822</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Spinner-mount.html">828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SplitButton-mount_base.html">2822</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SplitButton-mount.html">2836</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Stack-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Stack-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/StackWithIntrinsicChildren-mount_base.html">2248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/StackWithIntrinsicChildren-mount.html">2235</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/StackWithTextChildren-mount_base.html">4913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/StackWithTextChildren-mount.html">4890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SwatchColorPicker-mount_base.html">9477</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/SwatchColorPicker-mount.html">9399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TagPicker-mount_base.html">2326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TagPicker-mount.html">2302</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TeachingBubble-mount_base.html">73896</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TeachingBubble-mount.html">73731</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Text-mount_base.html">804</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Text-mount.html">812</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TextField-mount_base.html">1525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/TextField-mount.html">1536</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-mount_base.html">1444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-mount.html">1435</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-virtual-rerender_base.html">1141</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-virtual-rerender.html">1135</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1999</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2010</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Toggle-mount_base.html">1131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/Toggle-mount.html">1128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/buttonNative-mount_base.html">527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26286/perf-test/buttonNative-mount.html">534</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Pull request merged**
