### PR TITLE
chore: remove screener dependencies and various screener removal cleanups

### PR DESCRIPTION
**Pull request by TristanWatanabe**
## Changes:
- removes `screener-storybook` dependency from monorepo `package.json` and updates `yarn.lock` file.
- removes `convert` script from v8 and v9 VR tests packages since it's no longer needed.
- renames `screener:build` script to `vr:build` and `test:component` to `vr:test` across v0, v8 and v9. Renames are also reflected in the `runpublishscreenshot` template file used by the 1JS VR tool.
- various nit renames of `screener` to `storywright`.
- removals of unneeded usage of `screener-storybook` in a couple of packages.

## Related Issue(s)

* Part of #25078

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c12218d1b3f86d2db62131490dc04651821c334b'>c12218d1b3f86d2db62131490dc04651821c334b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Avatar-mount_base.html">1530</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Avatar-mount.html">1617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Button-mount_base.html">1185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Button-mount.html">1120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProvider-mount_base.html">1912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProvider-mount.html">2044</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-mount_base.html">773</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-mount.html">763</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">710</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">763</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/MakeStyles-mount_base.html">2258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/MakeStyles-mount.html">2253</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Persona-mount_base.html">3579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/Persona-mount.html">3484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/SpinButton-mount_base.html">3093</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test-react-components/SpinButton-mount.html">3028</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/BaseButton-mount_base.html">1484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/BaseButton-mount.html">1481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Breadcrumb-mount_base.html">3723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Breadcrumb-mount.html">3513</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Checkbox-mount_base.html">3150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Checkbox-mount.html">3182</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/CheckboxBase-mount_base.html">2876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/CheckboxBase-mount.html">2951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ChoiceGroup-mount_base.html">5744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ChoiceGroup-mount.html">5524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ComboBox-mount_base.html">1582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ComboBox-mount.html">1587</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/CommandBar-mount_base.html">11660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/CommandBar-mount.html">12112</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ContextualMenu-mount_base.html">13526</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ContextualMenu-mount.html">13359</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DefaultButton-mount_base.html">1657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DefaultButton-mount.html">1806</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRow-mount_base.html">4425</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRow-mount.html">4504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRowFast-mount_base.html">4685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRowFast-mount.html">4387</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRowNoStyles-mount_base.html">4244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DetailsRowNoStyles-mount.html">4342</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Dialog-mount_base.html">3877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Dialog-mount.html">3866</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DocumentCardTitle-mount_base.html">733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/DocumentCardTitle-mount.html">735</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Dropdown-mount_base.html">3907</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Dropdown-mount.html">3895</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/FocusTrapZone-mount_base.html">2351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/FocusTrapZone-mount.html">2525</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/FocusZone-mount_base.html">2497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/FocusZone-mount.html">2533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-mount_base.html">2309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-mount.html">2642</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-virtual-rerender_base.html">1465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-virtual-rerender.html">1431</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">2111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedList-virtual-rerender-with-unmount.html">2076</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-mount_base.html">702</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-mount.html">711</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-virtual-rerender_base.html">670</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-virtual-rerender.html">685</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">719</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">727</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/IconButton-mount_base.html">2429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/IconButton-mount.html">2391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Label-mount_base.html">881</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Label-mount.html">872</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Layer-mount_base.html">5462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Layer-mount.html">5326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Link-mount_base.html">986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Link-mount.html">994</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/MenuButton-mount_base.html">2128</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/MenuButton-mount.html">2156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/MessageBar-mount_base.html">2753</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/MessageBar-mount.html">2837</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Nav-mount_base.html">4072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Nav-mount.html">4060</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/OverflowSet-mount_base.html">1705</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/OverflowSet-mount.html">1699</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Panel-mount_base.html">3194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Panel-mount.html">3085</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Persona-mount_base.html">1700</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Persona-mount.html">1651</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Pivot-mount_base.html">2044</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Pivot-mount.html">1950</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/PrimaryButton-mount_base.html">1924</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/PrimaryButton-mount.html">1950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Rating-mount_base.html">8888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Rating-mount.html">8847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SearchBox-mount_base.html">1807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SearchBox-mount.html">1906</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Shimmer-mount_base.html">3525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Shimmer-mount.html">3638</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Slider-mount_base.html">2654</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Slider-mount.html">2595</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SpinButton-mount_base.html">5744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SpinButton-mount.html">5828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Spinner-mount_base.html">1003</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Spinner-mount.html">937</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SplitButton-mount_base.html">3956</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SplitButton-mount.html">3763</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Stack-mount_base.html">1035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Stack-mount.html">1061</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/StackWithIntrinsicChildren-mount_base.html">2995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/StackWithIntrinsicChildren-mount.html">2884</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/StackWithTextChildren-mount_base.html">6002</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/StackWithTextChildren-mount.html">5970</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SwatchColorPicker-mount_base.html">13045</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/SwatchColorPicker-mount.html">13102</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TagPicker-mount_base.html">3344</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TagPicker-mount.html">3388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TeachingBubble-mount_base.html">105926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TeachingBubble-mount.html">106331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Text-mount_base.html">959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Text-mount.html">968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TextField-mount_base.html">2070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/TextField-mount.html">1928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-mount_base.html">1951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-mount.html">1962</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-virtual-rerender_base.html">1324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-virtual-rerender.html">1379</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2652</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2805</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Toggle-mount_base.html">1383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/Toggle-mount.html">1390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/buttonNative-mount_base.html">688</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26070/perf-test/buttonNative-mount.html">666</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Review by layershifter — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
