### PR TITLE
Move CredScanSuppression file to root so 1ESPT output task picks it up

### PR DESCRIPTION
**Pull request by dannyvv**
It seems the config location in yaml was not picked up by output task only the sources scan task.
Then with the backouts and restores it looks like I messed up and ended up in a state where the credcan file was in the .ado folder instead of the root and not in the configuration either.

This PR addresses that mistake.

### CODE REVIEW

**Review by Hotell — APPROVED** [review]

**Review by TristanWatanabe — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Avatar-mount_base.html">641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Avatar-mount.html">628</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Button-mount_base.html">305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Button-mount.html">326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Field-mount_base.html">1112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Field-mount.html">1130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProvider-mount_base.html">686</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProvider-mount.html">701</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-mount_base.html">84</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-mount.html">88</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">62</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">77</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">79</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/MakeStyles-mount_base.html">863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/MakeStyles-mount.html">868</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Persona-mount_base.html">1775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/Persona-mount.html">1719</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/SpinButton-mount_base.html">1382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test-react-components/SpinButton-mount.html">1365</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/BaseButton-mount_base.html">634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/BaseButton-mount.html">620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Breadcrumb-mount_base.html">1690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Breadcrumb-mount.html">1639</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Checkbox-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Checkbox-mount.html">1668</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/CheckboxBase-mount_base.html">1470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/CheckboxBase-mount.html">1508</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ChoiceGroup-mount_base.html">2974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ChoiceGroup-mount.html">2978</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ComboBox-mount_base.html">660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ComboBox-mount.html">662</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/CommandBar-mount_base.html">6301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/CommandBar-mount.html">6256</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ContextualMenu-mount_base.html">12527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ContextualMenu-mount.html">12304</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DefaultButton-mount_base.html">765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DefaultButton-mount.html">763</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRow-mount_base.html">2171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRow-mount.html">2200</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRowFast-mount_base.html">2224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRowFast-mount.html">2212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRowNoStyles-mount_base.html">2023</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DetailsRowNoStyles-mount.html">2056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Dialog-mount_base.html">2612</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Dialog-mount.html">2675</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DocumentCardTitle-mount_base.html">230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/DocumentCardTitle-mount.html">219</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Dropdown-mount_base.html">2000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Dropdown-mount.html">1984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/FocusTrapZone-mount_base.html">1116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/FocusTrapZone-mount.html">1129</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/FocusZone-mount_base.html">1073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/FocusZone-mount.html">1043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-mount_base.html">41667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-mount.html">41830</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-virtual-rerender_base.html">17797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-virtual-rerender.html">20032</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedList-virtual-rerender-with-unmount.html">51170</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-mount_base.html">230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-mount.html">228</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-virtual-rerender_base.html">205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-virtual-rerender.html">214</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">231</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/IconButton-mount_base.html">1107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/IconButton-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Label-mount_base.html">336</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Label-mount.html">332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Layer-mount_base.html">2692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Layer-mount.html">2753</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Link-mount_base.html">391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Link-mount.html">405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/MenuButton-mount_base.html">959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/MenuButton-mount.html">956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/MessageBar-mount_base.html">21230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/MessageBar-mount.html">21390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Nav-mount_base.html">1975</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Nav-mount.html">1996</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/OverflowSet-mount_base.html">765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/OverflowSet-mount.html">789</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Panel-mount_base.html">2080</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Panel-mount.html">1774</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Persona-mount_base.html">746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Persona-mount.html">753</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Pivot-mount_base.html">913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Pivot-mount.html">866</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/PrimaryButton-mount_base.html">858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/PrimaryButton-mount.html">842</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Rating-mount_base.html">4722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Rating-mount.html">4706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SearchBox-mount_base.html">934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SearchBox-mount.html">899</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Shimmer-mount_base.html">1916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Shimmer-mount.html">1882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Slider-mount_base.html">1324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Slider-mount.html">1313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SpinButton-mount_base.html">2911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SpinButton-mount.html">2916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Spinner-mount_base.html">396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Spinner-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SplitButton-mount_base.html">1794</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SplitButton-mount.html">1820</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Stack-mount_base.html">408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Stack-mount.html">410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/StackWithIntrinsicChildren-mount_base.html">858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/StackWithIntrinsicChildren-mount.html">843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/StackWithTextChildren-mount_base.html">2575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/StackWithTextChildren-mount.html">2608</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SwatchColorPicker-mount_base.html">6140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/SwatchColorPicker-mount.html">6132</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/TagPicker-mount_base.html">1459</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/TagPicker-mount.html">1478</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Text-mount_base.html">371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Text-mount.html">371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/TextField-mount_base.html">928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/TextField-mount.html">941</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-mount_base.html">851</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-mount.html">847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-virtual-rerender_base.html">584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-virtual-rerender.html">590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1264</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Toggle-mount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/Toggle-mount.html">620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/buttonNative-mount_base.html">188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29722/perf-test/buttonNative-mount.html">191</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Pull request merged**
