### PR TITLE
init: @fluentui/react-list package

### PR DESCRIPTION
**Pull request by ling1726**
Autogenerated package boilerplate

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `2.836 kB`<br />`1.209 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             | `29.676 kB`<br />`6.604 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `18.492 kB`<br />`5.296 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/38c344976e3f3b0f005c6803a529b03f0df0f11c'>38c344976e3f3b0f005c6803a529b03f0df0f11c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">347</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/Avatar-mount_base.html">905</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/Avatar-mount.html">908</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/Button-mount_base.html">523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/Button-mount.html">549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProvider-mount_base.html">1856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProvider-mount.html">1895</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-mount_base.html">254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-mount.html">240</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">224</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">347</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/MakeStyles-mount_base.html">1537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-react-components/MakeStyles-mount.html">1528</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
AlertMinimalPerf.default | [227](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AlertMinimalPerf.default.html) | [224](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.01:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AlertMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
LayoutMinimalPerf.default | [324](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LayoutMinimalPerf.default.html) | [256](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.27:1
CardMinimalPerf.default | [507](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CardMinimalPerf.default.html) | [412](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.23:1
GridMinimalPerf.default | [288](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/GridMinimalPerf.default.html) | [243](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.19:1
ButtonSlotsPerf.default | [465](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonSlotsPerf.default.html) | [402](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.16:1
AttachmentMinimalPerf.default | [125](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AttachmentMinimalPerf.default.html) | [109](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.15:1
AvatarMinimalPerf.default | [177](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AvatarMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.14:1
ProviderMergeThemesPerf.default | [1106](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [970](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.14:1
ReactionMinimalPerf.default | [307](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ReactionMinimalPerf.default.html) | [273](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.12:1
VideoMinimalPerf.default | [571](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/VideoMinimalPerf.default.html) | [508](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.12:1
SliderMinimalPerf.default | [1469](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SliderMinimalPerf.default.html) | [1322](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.11:1
ChatDuplicateMessagesPerf.default | [246](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [228](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.08:1
RosterPerf.default | [908](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RosterPerf.default.html) | [841](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RosterPerf.default_base.html) | 1.08:1
EmbedMinimalPerf.default | [3477](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/EmbedMinimalPerf.default.html) | [3260](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.07:1
TextMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TextMinimalPerf.default.html) | [276](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.07:1
CustomToolbarPrototype.default | [2291](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CustomToolbarPrototype.default.html) | [2153](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [947](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AttachmentSlotsPerf.default.html) | [898](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
ButtonMinimalPerf.default | [145](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonMinimalPerf.default.html) | [138](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.05:1
ItemLayoutMinimalPerf.default | [1025](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [975](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.05:1
ListMinimalPerf.default | [440](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListMinimalPerf.default.html) | [423](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
PortalMinimalPerf.default | [147](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/PortalMinimalPerf.default.html) | [141](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [201](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RefMinimalPerf.default.html) | [194](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
SegmentMinimalPerf.default | [258](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SegmentMinimalPerf.default.html) | [249](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.04:1
AnimationMinimalPerf.default | [462](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AnimationMinimalPerf.default.html) | [450](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
ChatMinimalPerf.default | [628](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatMinimalPerf.default.html) | [611](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/FormMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [723](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/MenuMinimalPerf.default.html) | [699](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
PopupMinimalPerf.default | [532](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/PopupMinimalPerf.default.html) | [515](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [580](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/StatusMinimalPerf.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
ListWith60ListItems.default | [548](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListWith60ListItems.default.html) | [537](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
SkeletonMinimalPerf.default | [291](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SkeletonMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [291](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/HeaderMinimalPerf.default.html) | [287](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1091](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/InputMinimalPerf.default.html) | [1077](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ListNestedPerf.default | [441](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListNestedPerf.default.html) | [437](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListNestedPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3548](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3512](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TableMinimalPerf.default.html) | [341](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [672](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TreeMinimalPerf.default.html) | [664](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
TreeWith60ListItems.default | [139](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TreeWith60ListItems.default.html) | [138](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [2526](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DropdownMinimalPerf.default.html) | [2536](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [311](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LabelMinimalPerf.default.html) | [312](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ListCommonPerf.default | [537](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListCommonPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
BoxMinimalPerf.default | [275](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/BoxMinimalPerf.default.html) | [280](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.98:1
DatepickerMinimalPerf.default | [4699](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4782](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.98:1
DialogMinimalPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DialogMinimalPerf.default.html) | [658](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.98:1
DividerMinimalPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DividerMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.98:1
CheckboxMinimalPerf.default | [2132](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2207](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.97:1
DropdownManyItemsPerf.default | [568](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DropdownManyItemsPerf.default.html) | [583](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.97:1
HeaderSlotsPerf.default | [613](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/HeaderSlotsPerf.default.html) | [635](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.97:1
ProviderMinimalPerf.default | [322](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ProviderMinimalPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.97:1
TextAreaMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TextAreaMinimalPerf.default.html) | [423](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.97:1
ToolbarMinimalPerf.default | [808](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ToolbarMinimalPerf.default.html) | [831](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [503](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/IconMinimalPerf.default.html) | [524](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.96:1
MenuButtonMinimalPerf.default | [1321](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1388](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.95:1
ChatWithPopoverPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatWithPopoverPerf.default.html) | [315](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.94:1
RadioGroupMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [357](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.94:1
ButtonOverridesMissPerf.default | [1112](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1192](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.93:1
TableManyItemsPerf.default | [1514](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TableManyItemsPerf.default.html) | [1623](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.93:1
TooltipMinimalPerf.default | [843](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TooltipMinimalPerf.default.html) | [906](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.93:1
FlexMinimalPerf.default | [212](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/FlexMinimalPerf.default.html) | [230](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.92:1
ImageMinimalPerf.default | [277](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ImageMinimalPerf.default.html) | [303](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.91:1
LoaderMinimalPerf.default | [504](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LoaderMinimalPerf.default.html) | [568](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.89:1
CarouselMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CarouselMinimalPerf.default.html) | [410](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.86:1
AccordionMinimalPerf.default | [105](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AccordionMinimalPerf.default.html) | [123](https://fluentuipr.z22.web.core.windows.net/pull/22308/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.85:1

</details><div id="perfComment9424"/>

**Comment by ecraig12345** [comment]
What kind of list is this intended for?

**Comment by ling1726** [comment]
> What kind of list is this intended for?

It's an intersection of the features of the v0 `List` component and the `BasicList` and `DetailsList` that does not involve table semantics

**Review by Hotell — APPROVED** [review]

**Pull request merged**
