### PR TITLE
feat: Add `appearance` prop to `TableRow`

### PR DESCRIPTION
**Pull request by ling1726**
Selectable rows can have an optional brand or neutral background. In order avoid coupling to any selection in the primitives these are introduced as an `appearance` prop.

Selection stories have been updated to use the new prop.

Brand

image

Neutral

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b28db2e0992abde340cbbe103350060ff8c60c36'>b28db2e0992abde340cbbe103350060ff8c60c36</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/Avatar-mount_base.html">1272</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/Avatar-mount.html">1287</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/Button-mount_base.html">922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/Button-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProvider-mount_base.html">1518</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProvider-mount.html">1487</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-mount_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-mount.html">585</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">545</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">583</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/MakeStyles-mount_base.html">2001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/MakeStyles-mount.html">1999</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/SpinButton-mount_base.html">2304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25192/perf-test-react-components/SpinButton-mount.html">2325</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by layershifter** [comment]
Can you please add a screenshot to show how it looks? As you updated all (?) selectable examples: is it really optional? Or should it be `selected` prop instead?

**Comment by ling1726** [comment]
> Can you please add a screenshot to show how it looks? As you updated all (?) selectable examples: is it really optional? Or should it be `selected` prop instead?

according to design language this should not be optional but since we want to keep primitives as primitives, this was the best way I could manage. There is no 'obligation' in primitives to have a selectable table row. 

I definitely moving forward with a `DataGrid` component and baking this stuff in is the way to go

**Review by layershifter — APPROVED** [review]

**Review by bsunderhus — APPROVED** [review]

**Pull request merged**
