### PR TITLE
docs: move AvatarGroup to preview components

### LINKED ISSUE #23186: [Bug]: AvatarGroup docs should be moved to Preview components
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
v9 docs site
```

### Are you reporting Accessibility issue?

no

### Reproduction

v9 docs site

## Actual Behavior
AvatarGroup is in the main set of components

## Expected Behavior
AvatarGroup should be in the Preview components

### Logs

_No response_

### Requested priority

High

### Products/sites affected

v9 docs site

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #23186.

This PR does the following:
* Adds Preview to `AvatarGroup` stories.
* Adds `.beta` to the name of `AvatarGroup.stories.tsx` so it's skipped from the v9 docsite.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |   `45.588 kB`<br />`13.32 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `181.156 kB`<br />`50.603 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.078 kB`<br />`11.098 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/303947a3e3687058c902a9a8bee1ecd1f19a92c8'>303947a3e3687058c902a9a8bee1ecd1f19a92c8</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/Avatar-mount_base.html">1082</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/Avatar-mount.html">1106</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/Button-mount_base.html">675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/Button-mount.html">670</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProvider-mount_base.html">2261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProvider-mount.html">2189</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-mount_base.html">327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-mount.html">329</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">293</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">366</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/MakeStyles-mount_base.html">1870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23216/perf-test-react-components/MakeStyles-mount.html">1830</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by spmonahan** [comment]
> Not sure about it even there, may be it's better to hide it at all.

Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.

**Comment by sopranopillow** [comment]
> 

Yeah, I think it should be hidden for sure.

**Comment by layershifter** [comment]
> > Not sure about it even there, may be it's better to hide it at all.
> 
> Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.

Do you know how to do this properly? I can just delete the file, but would like to have a better option.

**Comment by spmonahan** [comment]
> > > Not sure about it even there, may be it's better to hide it at all.
> > 
> > 
> > Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.
> 
> Do you know how to do this properly? I can just delete the file, but would like to have a better option.

I _think_ usually this is handled by setting `private: true` in package.json but that isn't an option in this case because we need to have Avatar in the docs. @micahgodbolt , do you know of a way we can exclude AvatarGroup from Storybook?

**Comment by sopranopillow** [comment]
> > > > Not sure about it even there, may be it's better to hide it at all.
> > > 
> > > 
> > > Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.
> > 
> > 
> > Do you know how to do this properly? I can just delete the file, but would like to have a better option.
> 
> I _think_ usually this is handled by setting `private: true` in package.json but that isn't an option in this case because we need to have Avatar in the docs. @micahgodbolt , do you know of a way we can exclude AvatarGroup from Storybook?

After talking to Micah, I think we'll have to remove the exports of `AvatarGroup` in the index of `react-avatar`. v9's docsite imports everything from the package so I think that should do it.

**Comment by sopranopillow** [comment]
> > > > > Not sure about it even there, may be it's better to hide it at all.
> > > > 
> > > > 
> > > > Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.
> > > 
> > > 
> > > Do you know how to do this properly? I can just delete the file, but would like to have a better option.
> > 
> > 
> > I _think_ usually this is handled by setting `private: true` in package.json but that isn't an option in this case because we need to have Avatar in the docs. @micahgodbolt , do you know of a way we can exclude AvatarGroup from Storybook?
> 
> After talking to Micah, I think we'll have to remove the exports of `AvatarGroup` in the index of `react-avatar`. v9's docsite imports everything from the package so I think that should do it.

@layershifter  Actually on second thought, we can just add .beta to `AvatarGroup.stories.beta.tsx` and add that to `.storybook/main.js`. Micah recommended this and seems like a better solution to not mess with the index file. Let me know if you want to go ahead do it in this PR or I can make a follow up one to fix that.

**Comment by spmonahan** [comment]
> @layershifter Actually on second thought, we can just add .beta to `AvatarGroup.stories.beta.tsx` and add that to `.storybook/main.js`. Micah recommended this and seems like a better solution to not mess with the index file. Let me know if you want to go ahead do it in this PR or I can make a follow up one to fix that.

Would the addition to `.storybook/main.js` be a change to exclude `.stories.beta.tsx` files?

**Comment by sopranopillow** [comment]
> > @layershifter Actually on second thought, we can just add .beta to `AvatarGroup.stories.beta.tsx` and add that to `.storybook/main.js`. Micah recommended this and seems like a better solution to not mess with the index file. Let me know if you want to go ahead do it in this PR or I can make a follow up one to fix that.
> 
> Would the addition to `.storybook/main.js` be a change to exclude `.stories.beta.tsx` files?

It would be to add it so that when running `yarn start` inside the package you still get all the stories. The docsite will ignore the .beta.tsx and so it won't be shown. The docsite will look only for `.stories.tsx`.

**Comment by layershifter** [comment]
> > > > > > Not sure about it even there, may be it's better to hide it at all.
> > > > > 
> > > > > 
> > > > > Since it's not exported from `@fluentui/react-components/unstable` we should probably hide it entirely until it's added there.
> > > > 
> > > > 
> > > > Do you know how to do this properly? I can just delete the file, but would like to have a better option.
> > > 
> > > 
> > > I _think_ usually this is handled by setting `private: true` in package.json but that isn't an option in this case because we need to have Avatar in the docs. @micahgodbolt , do you know of a way we can exclude AvatarGroup from Storybook?
> > 
> > 
> > After talking to Micah, I think we'll have to remove the exports of `AvatarGroup` in the index of `react-avatar`. v9's docsite imports everything from the package so I think that should do it.
> 
> @layershifter Actually on second thought, we can just add .beta to `AvatarGroup.stories.beta.tsx` and add that to `.storybook/main.js`. Micah recommended this and seems like a better solution to not mess with the index file. Let me know if you want to go ahead do it in this PR or I can make a follow up one to fix that.

Feel free to do changes and close my PR then 😉

**Review by smhigley — APPROVED** [review]

**Pull request merged**
