### PR TITLE
Updated tabster package related test cases snapshots

### PR DESCRIPTION
**Pull request by v-baambati**

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/cf3323ee23dee7c931f6a8860ea32810eaddcbd1'>cf3323ee23dee7c931f6a8860ea32810eaddcbd1</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by v-baambati** [comment]
Closing this PR as this no more required.

**Pull request closed without merging**
