### PR TITLE
chore(tokens): package stub

### PR DESCRIPTION
**Pull request by miroslavstastny**
Create empty `@fluentui/tokens` package, prerequisite for #25966.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/905b3b2e74e472bd2d9cb825c0dc12d3dee4aa46'>905b3b2e74e472bd2d9cb825c0dc12d3dee4aa46</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Avatar-mount_base.html">1657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Avatar-mount.html">1632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Button-mount_base.html">1119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Button-mount.html">1135</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProvider-mount_base.html">1994</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProvider-mount.html">1943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-mount_base.html">706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-mount.html">699</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">659</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">705</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">707</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/MakeStyles-mount_base.html">2257</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/MakeStyles-mount.html">2244</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Persona-mount_base.html">3887</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/Persona-mount.html">3849</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/SpinButton-mount_base.html">3244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test-react-components/SpinButton-mount.html">3223</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [🕵 FluentUI-v0 Open the Visual Regressions report to inspect the 1 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26039&commitId=540ae73e4e533919f81350ecb7a0db5bc19024d0&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1259 screenshots unchanged, 0 screenshots with different dimensions and 1 screenshots with visible difference.


  <details><summary><b>unknown</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Reaction.Reaction Group Example.chromium.png|165| Changed|

</details>


<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/BaseButton-mount_base.html">1552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/BaseButton-mount.html">1571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Breadcrumb-mount_base.html">3810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Breadcrumb-mount.html">3865</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Checkbox-mount_base.html">3550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Checkbox-mount.html">3497</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/CheckboxBase-mount_base.html">3172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/CheckboxBase-mount.html">3242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ChoiceGroup-mount_base.html">5957</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ChoiceGroup-mount.html">6133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ComboBox-mount_base.html">1595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ComboBox-mount.html">1578</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/CommandBar-mount_base.html">12302</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/CommandBar-mount.html">12636</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ContextualMenu-mount_base.html">14426</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ContextualMenu-mount.html">15052</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DefaultButton-mount_base.html">1872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DefaultButton-mount.html">1912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRow-mount_base.html">4807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRow-mount.html">4853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRowFast-mount_base.html">4869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRowFast-mount.html">4940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRowNoStyles-mount_base.html">4588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DetailsRowNoStyles-mount.html">4677</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Dialog-mount_base.html">4054</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Dialog-mount.html">4074</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DocumentCardTitle-mount_base.html">726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/DocumentCardTitle-mount.html">718</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Dropdown-mount_base.html">4400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Dropdown-mount.html">4407</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/FocusTrapZone-mount_base.html">2672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/FocusTrapZone-mount.html">2612</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/FocusZone-mount_base.html">2466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/FocusZone-mount.html">2563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-mount_base.html">2510</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-mount.html">2958</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-virtual-rerender_base.html">1464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-virtual-rerender.html">1451</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">2240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedList-virtual-rerender-with-unmount.html">2203</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-mount_base.html">735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-mount.html">705</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-virtual-rerender_base.html">695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-virtual-rerender.html">668</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">701</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/IconButton-mount_base.html">2727</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/IconButton-mount.html">2521</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Label-mount_base.html">944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Label-mount.html">941</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Layer-mount_base.html">5744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Layer-mount.html">5681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Link-mount_base.html">1084</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Link-mount.html">1071</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/MenuButton-mount_base.html">2203</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/MenuButton-mount.html">2187</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/MessageBar-mount_base.html">3079</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/MessageBar-mount.html">3043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Nav-mount_base.html">4371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Nav-mount.html">4432</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/OverflowSet-mount_base.html">1772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/OverflowSet-mount.html">1813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Panel-mount_base.html">3333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Panel-mount.html">3290</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Persona-mount_base.html">1698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Persona-mount.html">1694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Pivot-mount_base.html">2075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Pivot-mount.html">2104</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/PrimaryButton-mount_base.html">2076</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/PrimaryButton-mount.html">2079</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Rating-mount_base.html">9691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Rating-mount.html">9720</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SearchBox-mount_base.html">2007</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SearchBox-mount.html">1946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Shimmer-mount_base.html">3983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Shimmer-mount.html">3874</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Slider-mount_base.html">2748</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Slider-mount.html">2746</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SpinButton-mount_base.html">6140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SpinButton-mount.html">6131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Spinner-mount_base.html">1041</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Spinner-mount.html">1019</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SplitButton-mount_base.html">4136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SplitButton-mount.html">4164</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Stack-mount_base.html">1125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Stack-mount.html">1124</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/StackWithIntrinsicChildren-mount_base.html">3213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/StackWithIntrinsicChildren-mount.html">3350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/StackWithTextChildren-mount_base.html">6766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/StackWithTextChildren-mount.html">6881</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SwatchColorPicker-mount_base.html">13875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/SwatchColorPicker-mount.html">13853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TagPicker-mount_base.html">3457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TagPicker-mount.html">3446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TeachingBubble-mount_base.html">112110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TeachingBubble-mount.html">110287</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Text-mount_base.html">1015</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Text-mount.html">1019</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TextField-mount_base.html">2116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/TextField-mount.html">2151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-mount_base.html">1968</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-mount.html">1957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-virtual-rerender_base.html">1404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-virtual-rerender.html">1376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2880</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Toggle-mount_base.html">1476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/Toggle-mount.html">1454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/buttonNative-mount_base.html">673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26039/perf-test/buttonNative-mount.html">697</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
