### PR TITLE
Adds onDismiss callback when clear button is clicked on SearchBox preview

### PR DESCRIPTION
**Pull request by syphe**
## Previous Behavior

Without the onDismiss callback, the component itself silently clears its own state of 'value', but if the consumer provides its own `value` prop, then this clear action does nothing.

## New Behavior

When the clear button is clicked, the onDismiss callback is called, allowing the consumer to clear its own `value` state.

## Related Issue(s)

- Fixes #
#29034

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/405ee3cf4d5bcaae806448be6c497927d4f1730b'>405ee3cf4d5bcaae806448be6c497927d4f1730b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by smhigley — COMMENTED** [review]
Good catch that we didn't have a callback for clearing the value! My first thought is that this should probably be an `onChange` event with `value: ''` in the event data.

My reasoning for that is we want the clear button to be similar to the browser/native input clear, which isn't exposed to authors directly. The other reason is that we don't expose that button to keyboard users b/c it's supposed to be fully identical to doing ctrl+A then delete. That's just my gut feeling though, I need to think about it more.

Do you have a use case where someone using the clear button needs to be differentiated from selecting + deleting text?

**Comment by syphe** [comment]
> Good catch that we didn't have a callback for clearing the value! My first thought is that this should probably be an `onChange` event with `value: ''` in the event data.
> 
> My reasoning for that is we want the clear button to be similar to the browser/native input clear, which isn't exposed to authors directly. The other reason is that we don't expose that button to keyboard users b/c it's supposed to be fully identical to doing ctrl+A then delete. That's just my gut feeling though, I need to think about it more.
> 
> Do you have a use case where someone using the clear button needs to be differentiated from selecting + deleting text?

Sure, I can modify this to trigger an onChange, we hit the problem because we are consuming the component and setting `value` prop from our component, so immediately noticed the clear issue.

We don't personally care about the differentiation of use cases, in fact the only reason I added the `reason` property to the data type was that it looked a bit lonely adding an empty type :)

**Comment by syphe** [comment]
> > Good catch that we didn't have a callback for clearing the value! My first thought is that this should probably be an `onChange` event with `value: ''` in the event data.
> > My reasoning for that is we want the clear button to be similar to the browser/native input clear, which isn't exposed to authors directly. The other reason is that we don't expose that button to keyboard users b/c it's supposed to be fully identical to doing ctrl+A then delete. That's just my gut feeling though, I need to think about it more.
> > Do you have a use case where someone using the clear button needs to be differentiated from selecting + deleting text?
> 
> Sure, I can modify this to trigger an onChange, we hit the problem because we are consuming the component and setting `value` prop from our component, so immediately noticed the clear issue.
> 
> We don't personally care about the differentiation of use cases, in fact the only reason I added the `reason` property to the data type was that it looked a bit lonely adding an empty type :)

Ok, I've given up on the `onChange` suggestion. After banging my head against the wall on this for some time, I've come to the conclusion that we will be fighting against react's internal functionality, and whatever solution that will dispatch a `onChange` event back to the consumer will be a hack. Essentially you can't just dispatch a `change` event, as react-dom gobbles this up internally, if you were to try and simulate what a user would do when they clear the box, you would be creating an event with type `input`, and ensuring inputType is `deleteContentBackward`, this would technically generate a `change` event to then be triggered by react, however there is no public api (that I can see) that lets you construct an `input` event in this way

Have also considered using `onInput` and providing a custom event, and this does work, however similarly, it involves lots of bending over backwards by the consumer to inspect the `e.detail` property of the initial event, which seems counter-productive.

So my thoughts are that the code as it stands will be the most descriptive solution to the problem, as onDismiss conveys a clear message to the consumer. Another option that could be considered, would be to provide an additional callback in props that would essentially emulate the `onChange` callback, but with a different name so we aren't expected to hack our own event into the mix

**Comment by smhigley** [comment]
haha I get not wanting a lonely data object 😆.

Re: the onChange thing -- we definitely wouldn't want to spoof a native change event. Instead, we'd directly call the `onChange` prop if it was passed in. Our `onChange` handlers are already different from native event handlers, in that they have a second data argument which contains the value in the case of Input and SearchBox:

```ts
const handleDismissClick = useEventCallback((event: React.MouseEvent<HTMLSpanElement>) => {
    if (isResolvedShorthand(dismiss)) {
      dismiss.onClick?.(event);
    }
    props.onChange?.(event, { value: '' }); // this is the new line
    setValue('');
  });
```

The one catch is that you'll also have to update the typings for `onChange` in `SearchBoxProps` to include the MouseEvent as an event type. We do something similar in other components where multiple types of events can result in the same action (e.g. in SpinButton, where the value can be changed in multiple ways: https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.types.ts#L146-L150)

**Comment by syphe** [comment]
> haha I get not wanting a lonely data object 😆.
> 
> Re: the onChange thing -- we definitely wouldn't want to spoof a native change event. Instead, we'd directly call the `onChange` prop if it was passed in. Our `onChange` handlers are already different from native event handlers, in that they have a second data argument which contains the value in the case of Input and SearchBox:
> 
> ```ts
> const handleDismissClick = useEventCallback((event: React.MouseEvent<HTMLSpanElement>) => {
>     if (isResolvedShorthand(dismiss)) {
>       dismiss.onClick?.(event);
>     }
>     props.onChange?.(event, { value: '' }); // this is the new line
>     setValue('');
>   });
> ```
> 
> The one catch is that you'll also have to update the typings for `onChange` in `SearchBoxProps` to include the MouseEvent as an event type. We do something similar in other components where multiple types of events can result in the same action (e.g. in SpinButton, where the value can be changed in multiple ways: https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.types.ts#L146-L150)

Thanks Sarah, I hadn't thought of overloading the onChange callback, but now after doing so it was quite painless. I'm happy with the changes now, nice and succinct and get the job done easily

**Review by smhigley — APPROVED** [review]

**Comment by jichen2-c** [comment]
Hi @syphe could you help to update when the change will be merged?

**Comment by sgowri3** [comment]
Hi! is this PR merged already? Still not able to clear the value in Controlled SearchBox because neither of the 2 solutions discussed are not reflected. Can you please look into this?

**Comment by spmonahan** [comment]
> Hi @syphe ! is this PR merged already? Still not able to clear the value in Controlled SearchBox because neither of the 2 solutions discussed are not reflected. Can you please look into this?

It's not merged, yet. I've updated the branch with master and it's set to merge once the build successfully completes.

**Comment by syphe** [comment]
> Hi @syphe ! is this PR merged already? Still not able to clear the value in Controlled SearchBox because neither of the 2 solutions discussed are not reflected. Can you please look into this?

It seems to be stuck and needs @spmonahan  or @smhigley to merge it manually I think, even with auto-merge enabled it doesn't seem to be closing.

**Comment by spmonahan** [comment]
> > Hi @syphe ! is this PR merged already? Still not able to clear the value in Controlled SearchBox because neither of the 2 solutions discussed are not reflected. Can you please look into this?
> 
> It seems to be stuck and needs @spmonahan or @smhigley to merge it manually I think, even with auto-merge enabled it doesn't seem to be closing.

This is available from `@fluentui/react-search-preview@0.1.44`

**Comment by nanivijay** [comment]
I don't see the `onDismiss` calllback function even after updating to `0.1.44`

**Pull request merged**
