### PR TITLE
chore: update esbuild to v0.14.51

### PR DESCRIPTION
**Pull request by bsunderhus**
Updates version from dependencies:

1. `esbuild` to 0.14.51
2. `esbuild-loader` to 2.20.0

Reason: this version of `esbuild` adds support for the [new "automatic" JSX runtime from React 17+](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Avatar-mount_base.html">638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Avatar-mount.html">592</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Button-mount_base.html">311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Button-mount.html">316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Field-mount_base.html">1119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Field-mount.html">1072</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProvider-mount_base.html">673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProvider-mount.html">670</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-mount_base.html">74</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-mount.html">81</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">59</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">66</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">63</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">70</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/InfoButton-mount_base.html">13</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/InfoButton-mount.html">8</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/MakeStyles-mount_base.html">862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/MakeStyles-mount.html">851</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Persona-mount_base.html">1725</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/Persona-mount.html">1655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/SpinButton-mount_base.html">1327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test-react-components/SpinButton-mount.html">1357</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/BaseButton-mount_base.html">637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/BaseButton-mount.html">617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Breadcrumb-mount_base.html">1676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Breadcrumb-mount.html">1677</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Checkbox-mount_base.html">1696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Checkbox-mount.html">1676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/CheckboxBase-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/CheckboxBase-mount.html">1452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ChoiceGroup-mount_base.html">2941</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ChoiceGroup-mount.html">2921</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ComboBox-mount_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ComboBox-mount.html">611</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/CommandBar-mount_base.html">6239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/CommandBar-mount.html">6101</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ContextualMenu-mount_base.html">11608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ContextualMenu-mount.html">11656</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DefaultButton-mount_base.html">754</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DefaultButton-mount.html">762</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRow-mount_base.html">2159</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRow-mount.html">2139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRowFast-mount_base.html">2149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRowFast-mount.html">2204</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRowNoStyles-mount_base.html">1965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DetailsRowNoStyles-mount.html">1998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Dialog-mount_base.html">2562</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Dialog-mount.html">2598</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DocumentCardTitle-mount_base.html">227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/DocumentCardTitle-mount.html">216</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Dropdown-mount_base.html">1933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Dropdown-mount.html">1965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/FocusTrapZone-mount_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/FocusTrapZone-mount.html">1105</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/FocusZone-mount_base.html">1086</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/FocusZone-mount.html">1063</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-mount_base.html">40874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-mount.html">40929</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-virtual-rerender_base.html">19766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-virtual-rerender.html">19503</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">49655</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedList-virtual-rerender-with-unmount.html">49737</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-mount_base.html">219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-mount.html">215</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-virtual-rerender_base.html">198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-virtual-rerender.html">205</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">221</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/IconButton-mount_base.html">1085</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/IconButton-mount.html">1080</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Label-mount_base.html">333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Label-mount.html">338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Layer-mount_base.html">2726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Layer-mount.html">2693</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Link-mount_base.html">383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Link-mount.html">383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/MenuButton-mount_base.html">933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/MenuButton-mount.html">918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/MessageBar-mount_base.html">21245</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/MessageBar-mount.html">21148</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Nav-mount_base.html">1965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Nav-mount.html">1922</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/OverflowSet-mount_base.html">786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/OverflowSet-mount.html">766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Panel-mount_base.html">1729</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Panel-mount.html">1768</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Persona-mount_base.html">730</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Persona-mount.html">743</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Pivot-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Pivot-mount.html">856</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/PrimaryButton-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/PrimaryButton-mount.html">824</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Rating-mount_base.html">4603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Rating-mount.html">4535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SearchBox-mount_base.html">892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SearchBox-mount.html">893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Shimmer-mount_base.html">1838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Shimmer-mount.html">1822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Slider-mount_base.html">1308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Slider-mount.html">1314</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SpinButton-mount_base.html">2844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SpinButton-mount.html">2923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Spinner-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Spinner-mount.html">399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SplitButton-mount_base.html">1808</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SplitButton-mount.html">1832</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Stack-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Stack-mount.html">406</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/StackWithIntrinsicChildren-mount_base.html">841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/StackWithIntrinsicChildren-mount.html">857</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/StackWithTextChildren-mount_base.html">2602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/StackWithTextChildren-mount.html">2618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SwatchColorPicker-mount_base.html">6060</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/SwatchColorPicker-mount.html">6112</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/TagPicker-mount_base.html">1425</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/TagPicker-mount.html">1439</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Text-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Text-mount.html">370</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/TextField-mount_base.html">911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/TextField-mount.html">889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-mount_base.html">818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-mount.html">836</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-virtual-rerender_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-virtual-rerender.html">585</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1291</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Toggle-mount_base.html">613</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/Toggle-mount.html">591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/buttonNative-mount_base.html">190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28809/perf-test/buttonNative-mount.html">194</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Review by marcosmoura — APPROVED** [review]

**Pull request merged**
