### PR TITLE
ScrollablePane/Sticky: Allow remounting for react 18 strict mode

### LINKED ISSUE #24987: [Bug]: ScrollablePane and Sticky do not work consistently when running with hot reload
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.05 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

_No response_

### Reproduction

https://github.com/Kerryliu/Test123

## Steps to reproduce
- Create a new react project with https://create-react-app.dev/docs/getting-started
- Install fluentUI with yarn: ` yarn add @fluentui/react`
- `yarn start` with code in the codepen.  
- Sticky isn't sticking.  (sometimes tweaking the style in the div breaks/fixes, and I don't know why)

## Actual Behavior
- Sticky should stick but doesn't.  This only occurs when running with `yarn start`.  
- Unable to reproduce when serving a prod build (`yarn build` + `yarn serve`).  
- Unable to reproduce issue in codepen.  (https://codepen.io/berrykerry789/pen/RwyQwax)
- Might be specific to React 18, which I know isn't officially supported. Seems to work fine with React 17.  

## Expected Behavior
- Sticky should stick regardless of running with a dev build or prod build.  

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by andyrooger**
## Previous Behavior

When running in React 18 Strict Mode, Sticky components in a ScrollablePane aren't sticky.

Strict mode remounts the component on creation, at which point async methods and event handlers are disposed.

## New Behavior

Sticky in the configuration above is now actually sticky.

Async and event objects are created in componentDidMount rather than the constructor so they can be safely remounted.

## Related Issue(s)

- Fixes #24987

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c10400fdaf7ff1beef85051ce38b2c6c52b4e2e2'>c10400fdaf7ff1beef85051ce38b2c6c52b4e2e2</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/BaseButton-mount_base.html">608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/BaseButton-mount.html">644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Breadcrumb-mount_base.html">1659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Breadcrumb-mount.html">1678</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Checkbox-mount_base.html">1682</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Checkbox-mount.html">1666</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/CheckboxBase-mount_base.html">1468</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/CheckboxBase-mount.html">1484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ChoiceGroup-mount_base.html">2952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ChoiceGroup-mount.html">2952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ComboBox-mount_base.html">661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ComboBox-mount.html">642</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/CommandBar-mount_base.html">6192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/CommandBar-mount.html">6290</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ContextualMenu-mount_base.html">12333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ContextualMenu-mount.html">12221</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DefaultButton-mount_base.html">737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DefaultButton-mount.html">743</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRow-mount_base.html">2183</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRow-mount.html">2156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRowFast-mount_base.html">2153</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRowFast-mount.html">2188</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRowNoStyles-mount_base.html">1984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DetailsRowNoStyles-mount.html">2015</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Dialog-mount_base.html">2764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Dialog-mount.html">2780</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DocumentCardTitle-mount_base.html">222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/DocumentCardTitle-mount.html">232</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Dropdown-mount_base.html">1955</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Dropdown-mount.html">1962</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/FocusTrapZone-mount_base.html">1090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/FocusTrapZone-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/FocusZone-mount_base.html">1051</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/FocusZone-mount.html">1091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-mount_base.html">41414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-mount.html">41341</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-virtual-rerender_base.html">19843</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-virtual-rerender.html">19691</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedList-virtual-rerender-with-unmount.html">50645</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-mount_base.html">212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-mount.html">219</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-virtual-rerender_base.html">198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-virtual-rerender.html">202</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">220</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">226</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/IconButton-mount_base.html">1048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/IconButton-mount.html">1103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Label-mount_base.html">332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Label-mount.html">332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Layer-mount_base.html">2726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Layer-mount.html">2668</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Link-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Link-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/MenuButton-mount_base.html">946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/MenuButton-mount.html">928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/MessageBar-mount_base.html">21262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/MessageBar-mount.html">21215</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Nav-mount_base.html">1969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Nav-mount.html">1939</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/OverflowSet-mount_base.html">792</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/OverflowSet-mount.html">796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Panel-mount_base.html">1732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Panel-mount.html">1778</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Persona-mount_base.html">735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Persona-mount.html">745</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Pivot-mount_base.html">857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Pivot-mount.html">872</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/PrimaryButton-mount_base.html">835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/PrimaryButton-mount.html">862</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Rating-mount_base.html">4504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Rating-mount.html">4607</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SearchBox-mount_base.html">897</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SearchBox-mount.html">903</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Shimmer-mount_base.html">1863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Shimmer-mount.html">1841</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Slider-mount_base.html">1316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Slider-mount.html">1317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SpinButton-mount_base.html">2866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SpinButton-mount.html">2837</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Spinner-mount_base.html">398</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Spinner-mount.html">394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SplitButton-mount_base.html">1849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SplitButton-mount.html">1835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Stack-mount_base.html">418</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Stack-mount.html">426</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/StackWithIntrinsicChildren-mount_base.html">864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/StackWithIntrinsicChildren-mount.html">880</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/StackWithTextChildren-mount_base.html">2629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/StackWithTextChildren-mount.html">2587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SwatchColorPicker-mount_base.html">6078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/SwatchColorPicker-mount.html">6108</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/TagPicker-mount_base.html">1416</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/TagPicker-mount.html">1404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Text-mount_base.html">379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Text-mount.html">373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/TextField-mount_base.html">938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/TextField-mount.html">920</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-mount_base.html">836</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-mount.html">815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-virtual-rerender_base.html">588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-virtual-rerender.html">589</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1278</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1253</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Toggle-mount_base.html">607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/Toggle-mount.html">618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/buttonNative-mount_base.html">189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28487/perf-test/buttonNative-mount.html">193</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by andyrooger** [comment]
Strict mode demo from comments in the bug, with the code from this PR: https://codesandbox.io/s/elastic-tree-79cprh?file=/src/index.js

**Pull request merged**
