### PR TITLE
Dropdown: Underlined and borderless dropdown 

### LINKED ISSUE #10694: Underlined and borderless Dropdown
#### Describe the feature that you would like added

I would like to add an underlined and borderless version of the Dropdown component

#### What component or utility would this be added to

<Dropdown />

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

We are building out a form with basic inputs. We use the underlined and borderless TextField for text input like name and email. For country and DoB, we use the Dropdown component. However, we try to match the design between the two inputs but Dropdown doesn't have an underlined and borderless variant.

Underlined and borderless TextField:
image

Underlined and borderless Dropdown:
image

If the dev team doesn't see any problem of adding a new variant to the Dropdown. I'm more than happy to start a PR to add it in.

### PR DESCRIPTION
**Pull request by step-lee**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #10694
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Add an underlined and borderless version of the Dropdown component.
Most style change and interface update

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12808)

### CODE REVIEW

**Comment by joschect** [comment]
@step-lee Thanks for submitting this change! This looks great. Just to verify did you test this in High contrast mode?

**Comment by joschect** [comment]
@ecraig12345 Do you have any opinions about underline?

**Comment by ecraig12345** [comment]
@joschect It's definitely in the designs, just nobody had gotten around to implementing it. You should get one of the designers to look this over and ensure it matches the designs.

@step-lee Can you please add a screener test for this scenario in `apps/vr-tests/src/stories/Dropdown.stories.tsx`?

**Comment by step-lee** [comment]
@joschect No I didn't run it in high contract mode. I'll do a accessibility pass on it

@ecraig12345 I see it on the figma file. I'm going to change the behavior to match the design. After I modify the look. I'll add a screener test.
image

**Comment by mbest** [comment]
We have a design for this as well. Any way this can be added?

**Comment by ecraig12345** [comment]
@mbest This is something we'd like to add, but no one from the core team has time to do it right now. If someone from your team (or @step-lee who made this PR) has time to finish implementing it we'd certainly accept the contribution.

**Pull request closed without merging**
