### PR TITLE
MenuPopover should have overflow styles when using autoSize

### PR DESCRIPTION
**Pull request by ling1726**
## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                 |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :-------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>              | `126.501 kB`<br />`38.723 kB` | `126.718 kB`<br />`38.816 kB` | `217 B` <br />`93 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr> |  `129.57 kB`<br />`39.237 kB` | `129.787 kB`<br />`39.329 kB` | `217 B` <br />`92 B`  |

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2958df9fc9f756e4b9c42f41b4678810b83ab903'>2958df9fc9f756e4b9c42f41b4678810b83ab903</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Avatar-mount_base.html">1662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Avatar-mount.html">1663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Button-mount_base.html">1133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Button-mount.html">1190</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Field-mount_base.html">2737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Field-mount.html">2559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProvider-mount_base.html">2116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProvider-mount.html">1992</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-mount_base.html">721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-mount.html">701</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">711</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">680</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">770</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/InfoButton-mount_base.html">637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/InfoButton-mount.html">622</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/MakeStyles-mount_base.html">2290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/MakeStyles-mount.html">2245</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Persona-mount_base.html">4041</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/Persona-mount.html">3950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/SpinButton-mount_base.html">3249</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26922/perf-test-react-components/SpinButton-mount.html">3241</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by ling1726** [comment]
Closing in favour of #26868

**Pull request closed without merging**
