### PR TITLE
User/debarman/testing/vrtool generic

### PR DESCRIPTION
**Pull request by Devjoyti-Barman**
## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by tudorpopams** [comment]
Hello @Devjoyti-Barman , can you please give us more context about this PR?

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Avatar-mount_base.html">909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Avatar-mount.html">915</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Button-mount_base.html">584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Button-mount.html">588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Field-mount_base.html">1663</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Field-mount.html">1623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProvider-mount_base.html">1181</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProvider-mount.html">1180</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-mount_base.html">300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-mount.html">315</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">282</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">297</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/InfoButton-mount_base.html">205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/InfoButton-mount.html">207</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/MakeStyles-mount_base.html">1334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/MakeStyles-mount.html">1314</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Persona-mount_base.html">2234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/Persona-mount.html">2212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/SpinButton-mount_base.html">1987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test-react-components/SpinButton-mount.html">1993</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/BaseButton-mount_base.html">988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/BaseButton-mount.html">984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Breadcrumb-mount_base.html">2371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Breadcrumb-mount.html">2408</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Checkbox-mount_base.html">2226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Checkbox-mount.html">2205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/CheckboxBase-mount_base.html">1988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/CheckboxBase-mount.html">1982</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ChoiceGroup-mount_base.html">3842</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ChoiceGroup-mount.html">3871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ComboBox-mount_base.html">1049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ComboBox-mount.html">1040</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/CommandBar-mount_base.html">8330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/CommandBar-mount.html">8297</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ContextualMenu-mount_base.html">18244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ContextualMenu-mount.html">18019</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DefaultButton-mount_base.html">1146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DefaultButton-mount.html">1179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRow-mount_base.html">3073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRow-mount.html">3075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRowFast-mount_base.html">3149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRowFast-mount.html">3090</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRowNoStyles-mount_base.html">2811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DetailsRowNoStyles-mount.html">2848</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Dialog-mount_base.html">3446</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Dialog-mount.html">3384</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DocumentCardTitle-mount_base.html">452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/DocumentCardTitle-mount.html">447</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Dropdown-mount_base.html">2765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Dropdown-mount.html">2766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/FocusTrapZone-mount_base.html">1666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/FocusTrapZone-mount.html">1656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/FocusZone-mount_base.html">1624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/FocusZone-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-mount_base.html">50700</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-mount.html">59212</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-virtual-rerender_base.html">24429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-virtual-rerender.html">24651</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">76759</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedList-virtual-rerender-with-unmount.html">76562</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-mount_base.html">473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-mount.html">458</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-virtual-rerender_base.html">431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-virtual-rerender.html">415</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">460</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/IconButton-mount_base.html">1597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/IconButton-mount.html">1593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Label-mount_base.html">572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Label-mount.html">575</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Layer-mount_base.html">3745</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Layer-mount.html">3715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Link-mount_base.html">660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Link-mount.html">646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/MenuButton-mount_base.html">1432</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/MenuButton-mount.html">1423</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/MessageBar-mount_base.html">28810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/MessageBar-mount.html">29046</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Nav-mount_base.html">2720</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Nav-mount.html">2724</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/OverflowSet-mount_base.html">1143</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/OverflowSet-mount.html">1139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Panel-mount_base.html">2133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Panel-mount.html">2283</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Persona-mount_base.html">1078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Persona-mount.html">1092</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Pivot-mount_base.html">1320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Pivot-mount.html">1348</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/PrimaryButton-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/PrimaryButton-mount.html">1252</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Rating-mount_base.html">5801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Rating-mount.html">5959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SearchBox-mount_base.html">1254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SearchBox-mount.html">1255</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Shimmer-mount_base.html">2391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Shimmer-mount.html">2474</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Slider-mount_base.html">1762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Slider-mount.html">1888</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SpinButton-mount_base.html">3914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SpinButton-mount.html">3927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Spinner-mount_base.html">648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Spinner-mount.html">657</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SplitButton-mount_base.html">2656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SplitButton-mount.html">2640</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Stack-mount_base.html">665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Stack-mount.html">663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/StackWithIntrinsicChildren-mount_base.html">1262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/StackWithIntrinsicChildren-mount.html">1265</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/StackWithTextChildren-mount_base.html">3415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/StackWithTextChildren-mount.html">3430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SwatchColorPicker-mount_base.html">8421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/SwatchColorPicker-mount.html">8454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/TagPicker-mount_base.html">2172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/TagPicker-mount.html">2120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Text-mount_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Text-mount.html">632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/TextField-mount_base.html">1334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/TextField-mount.html">1302</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-mount_base.html">1245</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-mount.html">1241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-virtual-rerender_base.html">894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-virtual-rerender.html">887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1826</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Toggle-mount_base.html">898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/Toggle-mount.html">908</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/buttonNative-mount_base.html">414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27329/perf-test/buttonNative-mount.html">415</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by Devjoyti-Barman** [comment]
Hello world

**Pull request closed without merging**
