### PR TITLE
Update V9 ComponentCommons type to ComponentCommonsUnstable 

### PR DESCRIPTION
**Pull request by micahgodbolt**
We plan to deprecate and get rid of the commons type, and while the commons type is not exported from react-components, it is exported from the individual component. Following the same 'unstable' function approach we took for some of our unstable functions, this change informs downstream users that this type could change in the future.

Could also change this to XCommonsDeprecated too, but this works fine and is consistent.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/1c2a4410205d3c86bc885fb74d6aede75d9bd99d'>1c2a4410205d3c86bc885fb74d6aede75d9bd99d</a></sub>
<div id="bundleSizeComment9423"/>

**Review by smhigley — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Avatar-mount_base.html">896</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Avatar-mount.html">945</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/BaseButton-mount_base.html">968</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/BaseButton-mount.html">1002</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Breadcrumb-mount_base.html">2782</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Breadcrumb-mount.html">2703</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ButtonNext-mount_base.html">535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ButtonNext-mount.html">551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Checkbox-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Checkbox-mount.html">1588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/CheckboxBase-mount_base.html">1322</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/CheckboxBase-mount.html">1354</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ChoiceGroup-mount_base.html">4894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ChoiceGroup-mount.html">4957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ComboBox-mount_base.html">1003</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ComboBox-mount.html">1017</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/CommandBar-mount_base.html">10648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/CommandBar-mount.html">10751</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ContextualMenu-mount_base.html">8717</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ContextualMenu-mount.html">8865</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DefaultButton-mount_base.html">1213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DefaultButton-mount.html">1216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRow-mount_base.html">3823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRow-mount.html">3830</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRowFast-mount_base.html">3835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRowFast-mount.html">3938</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRowNoStyles-mount_base.html">3657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DetailsRowNoStyles-mount.html">3630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Dialog-mount_base.html">2691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Dialog-mount.html">2684</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DocumentCardTitle-mount_base.html">181</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/DocumentCardTitle-mount.html">205</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Dropdown-mount_base.html">3351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Dropdown-mount.html">3313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderNext-mount_base.html">1927</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderNext-mount.html">1936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-mount_base.html">173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-mount.html">182</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-virtual-rerender.html">116</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">225</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FocusTrapZone-mount_base.html">1838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FocusTrapZone-mount.html">1865</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FocusZone-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/FocusZone-mount.html">1822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/IconButton-mount_base.html">1780</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/IconButton-mount.html">1829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Label-mount_base.html">363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Label-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Layer-mount_base.html">3137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Layer-mount.html">3091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Link-mount_base.html">505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Link-mount.html">508</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MakeStyles-mount_base.html">1761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MakeStyles-mount.html">1764</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MenuButton-mount_base.html">1587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MenuButton-mount.html">1553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MessageBar-mount_base.html">2094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/MessageBar-mount.html">2118</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Nav-mount_base.html">3424</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Nav-mount.html">3391</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/OverflowSet-mount_base.html">1172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/OverflowSet-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Panel-mount_base.html">2606</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Panel-mount.html">2609</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Persona-mount_base.html">914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Persona-mount.html">925</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Pivot-mount_base.html">1477</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Pivot-mount.html">1466</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/PrimaryButton-mount_base.html">1379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/PrimaryButton-mount.html">1309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Rating-mount_base.html">7937</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Rating-mount.html">7813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SearchBox-mount_base.html">1414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SearchBox-mount.html">1386</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Shimmer-mount_base.html">2635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Shimmer-mount.html">2636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Slider-mount_base.html">2064</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Slider-mount.html">2040</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SpinButton-mount_base.html">5140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SpinButton-mount.html">5164</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Spinner-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Spinner-mount.html">468</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SplitButton-mount_base.html">3276</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SplitButton-mount.html">3231</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Stack-mount_base.html">532</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Stack-mount.html">543</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/StackWithIntrinsicChildren-mount_base.html">2357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/StackWithIntrinsicChildren-mount.html">2387</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/StackWithTextChildren-mount_base.html">5404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/StackWithTextChildren-mount.html">5350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SwatchColorPicker-mount_base.html">11669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/SwatchColorPicker-mount.html">11796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TagPicker-mount_base.html">2778</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TagPicker-mount.html">2763</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TeachingBubble-mount_base.html">13712</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TeachingBubble-mount.html">13623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Text-mount_base.html">464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Text-mount.html">475</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TextField-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/TextField-mount.html">1487</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-mount_base.html">1257</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-mount.html">1303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-virtual-rerender_base.html">631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-virtual-rerender.html">677</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1891</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1979</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Toggle-mount_base.html">873</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/Toggle-mount.html">858</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/buttonNative-mount_base.html">150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21607/perf-test/buttonNative-mount.html">139</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

**Review by layershifter — APPROVED** [review]

**Comment by Hotell** [comment]
so what was already done for react-components suite is to get rid of those type as part of public API surface. 


I'd suggest to be consistent with our patterns public apis thus rather then rename, I'd remove all the exports from packages as was done https://github.com/microsoft/fluentui/pull/21195.

**Comment by micahgodbolt** [comment]
We're going to stick with this approach for a couple reasons. 
1. it gives visibility to the underlined API within the api.md files
2. some components rely on the type being exported, and reworking them would cause a lot of unnecessary churn

**Comment by Hotell** [comment]
> it gives visibility to the underlined API within the api.md files. Changes made to the Commons type should still be tracked in API extractor.

💡 To provide better context for reviewers, this is current output of api-extractor for `*Commons` within `react-button`

```
// @file etc/react-button.api.md

// @public (undocumented)
export type ButtonCommons = {
    appearance?: 'primary' | 'outline' | 'subtle' | 'transparent';
    block: boolean;
    disabledFocusable: boolean;
    disabled: boolean;
    iconPosition?: 'before' | 'after';
    shape: 'rounded' | 'circular' | 'square';
    size: 'small' | 'medium' | 'large';
};

// @public (undocumented)
export type ButtonProps = ComponentProps<ButtonSlots> & Partial<ButtonCommons>;
```

if we don't export `*Common` type from underlying package we'll get following:

```
// Warning: (ae-forgotten-export) The symbol "ButtonCommons" needs to be exported by the entry point index.d.ts
//
// @public (undocumented)
export type ButtonProps = ComponentProps<ButtonSlots> & Partial<ButtonCommons>;
```

This output **might be an issue indeed**. To better answer that, we should  answer following questions:
- which consumer do rely on the provided api.md and how does it affect them
- how are we processing changes in the api.md (besides failing build if generated output doesn't match implementation)
- react-components as a main source of truth for vNext doesn't exposes underlying packages API details at all besides exported tokens. How is this affecting consumers ?

Last but not least, our **codebase contains inconsistencies already regarding how we approach exporting types.**

Following packages contain `Warning: (ae-forgotten-export)` violation:
- react-menu
- react-positioning
- react-utilities
- react-text
- style-utilities (v8)
- web-components

> Some components (like Button) rely on the type being exported

Not sure I follow. I guess you're referring to using `ButtonCommons` across all button-* components?
image


If that's the case, it is ok as the import statement uses deep import anyways which doesn't affects public API, thus this is not an issue

**Comment by micahgodbolt** [comment]
@Hotell ButtonCommons is used in other button type files

https://github.com/microsoft/fluentui/blob/9ba6686abf03fcc410fb70de185370e80098ffb0/packages/react-button/src/components/CompoundButton/CompoundButton.types.ts#L2

```tsx
import type { ComponentProps, ComponentState, Slot } from '@fluentui/react-utilities';
import type { ButtonCommons, ButtonSlots, ButtonState } from '../Button/Button.types';

export type CompoundButtonSlots = ButtonSlots & {
...
};

export type CompoundButtonProps = ComponentProps<Partial<CompoundButtonSlots>> & Partial<ButtonCommons>;

export type CompoundButtonState = ComponentState<CompoundButtonSlots> &
  Omit<ButtonState, keyof ButtonSlots | 'components'>;
```

**Comment by micahgodbolt** [comment]
Closing this PR down and going with the approach in #21660

**Pull request closed without merging**
