### PR TITLE
Fix 27482: ProgressBar has an optional state variable 

### LINKED ISSUE #27482: [Bug]: ProgressBar has an optional state variable
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.51 GB / 31.90 GB
```

### Are you reporting Accessibility issue?

None

### Reproduction

not really a reduction

### Bug Description

Progress bar has an optional 'bar' slot & state. This makes using the custom style hooks a little tricker. I have to wrap it in a contitional:

```
export const useProgressBarStyles_unstable = (state: unknown) => {
  const progressStyles = useProgressBarStyles();
  const componentState = state as ProgressBarState;
  // todo file a bug on fluent component, bar in state should be required
  if (componentState.bar) {
    componentState.bar.className = mergeClasses(componentState.bar.className, progressStyles.bar);
  }
};
```

Ideally, I shouldn't have to check for null before styling.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Previous Behavior

ProgressBarState.bar slot was optional causing callers to have to null/undefined check it before use.
useProgressBar ensured it was never null or undefined.

## New Behavior

ProgressBarState slots are required.

## Related Issue(s)

- Fixes #27482 

## Testing
- ad-hoc tested creating a custom style hook for progress bar
- ad-doc tested with and without specifying the bar slot

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d310692a742e1140ce314219fbe9cbf07c366480'>d310692a742e1140ce314219fbe9cbf07c366480</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount_base.html">11</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount.html">13</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Avatar-mount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Avatar-mount.html">648</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Button-mount_base.html">314</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Button-mount.html">316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Field-mount_base.html">1116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Field-mount.html">1119</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProvider-mount_base.html">709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProvider-mount.html">697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-mount_base.html">88</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-mount.html">87</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">70</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">66</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">85</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">78</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount_base.html">11</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount.html">13</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/MakeStyles-mount_base.html">871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/MakeStyles-mount.html">848</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Persona-mount_base.html">1736</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/Persona-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/SpinButton-mount_base.html">1365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29366/perf-test-react-components/SpinButton-mount.html">1414</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by tomi-msft — APPROVED** [review]
thanks for updating the typing!

**Pull request merged**
