### PR TITLE
BREAKING: Removing deprecated `<componentName>ClassName` exports from v9 packages

### LINKED ISSUE #22132: Remove deprecated `<componentName>ClassName` exports
## Problem

Per #21847 static class names have been added to all Fluent UI v9 components. All components now export an object called `<componentName>ClassNames` where the keys are slot names and the values are the corresponding class name for that slot per #21206.

Previously all components applied a static class name to their root slots and exported this string as `<componentName>ClassName`. Adding the exported object makes this string export redundant and it has been marked as `@deprecated` in all components. Because of this deprecation we must disable eslint rules in several places which frustrates the development process.

## Proposal

Prior to moving from RC to Stable v9 we should remove all deprecated `<componentName>ClassName` exports.

## Packages with static class names

- [x] Unstable
  - [x] react-input
  - [x] react-card
- [x] Stable
  - [x] react-provider
  - [x] react-radio
  - [x] react-accordion
  - [x] react-avatar
  - [x] react-badge
  - [x] react-button
  - [x] react-checkbox
  - [x] react-divider
  - [x] react-image
  - [x] react-label
  - [x] react-link
  - [x] react-menu
  - [x] react-popover
  - [x] react-text
  - [x] react-tooltip

### PR DESCRIPTION
**Pull request by sopranopillow**
BREAKING

## Current behavior

Most packages export a static class name, which is now deprecated behavior. Currently all packages export a class name object as described in #21206. 

## New behavior

Deprecated `<componentName>ClassName` exports have been removed.

## Related PRs

#22130

Fixes #22132

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                             |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                  Change |
| :-------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr> | `43.039 kB`<br />`14.819 kB` | `43.025 kB`<br />`14.817 kB` | `-14 B` <br />`-2 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `73.907 kB`<br />`22.555 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `45.314 kB`<br />`13.175 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |     `21.1 kB`<br />`6.671 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `22.015 kB`<br />`6.976 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |    `22.15 kB`<br />`6.642 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `32.591 kB`<br />`9.056 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `38.836 kB`<br />`10.221 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `34.381 kB`<br />`9.645 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `41.662 kB`<br />`10.95 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `43.518 kB`<br />`9.984 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `59.102 kB`<br />`16.957 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `54.387 kB`<br />`15.706 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.891 kB`<br />`3.363 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `9.463 kB`<br />`3.881 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.863 kB`<br />`3.391 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `179.813 kB`<br />`50.19 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.178 kB`<br />`11.138 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |    `15.65 kB`<br />`5.636 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |    `10.314 kB`<br />`4.06 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `22.274 kB`<br />`7.336 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.644 kB`<br />`3.614 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |     `11.52 kB`<br />`4.69 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `110.335 kB`<br />`33.584 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             |  `113.51 kB`<br />`34.053 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `101.258 kB`<br />`30.847 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `14.227 kB`<br />`5.336 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `29.568 kB`<br />`10.122 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `13.751 kB`<br />`5.515 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `25.657 kB`<br />`8.302 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `41.985 kB`<br />`11.908 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `17.895 kB`<br />`5.988 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `25.539 kB`<br />`8.286 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `11.002 kB`<br />`4.336 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.324 kB`<br />`4.749 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/73f592de5bace4132289e64b1df78e9cc4b31a25'>73f592de5bace4132289e64b1df78e9cc4b31a25</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/Avatar-mount_base.html">1106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/Avatar-mount.html">1070</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/Button-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/Button-mount.html">681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProvider-mount_base.html">2233</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProvider-mount.html">2224</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-mount_base.html">332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-mount.html">342</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">271</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">357</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/MakeStyles-mount_base.html">1929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23026/perf-test-react-components/MakeStyles-mount.html">1934</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by ling1726 — APPROVED** [review]

**Review by spmonahan — CHANGES_REQUESTED** [review]
Just blocking this so it isn't merged ahead of schedule

**Review by andrefcdias — APPROVED** [review]
LGTM for Card and Image. Please revert Text changes as I already address these in https://github.com/microsoft/fluentui/pull/22934 as asked by @spmonahan.
Also, let's split up these migrations next time and leverage nx generators to simplify PR reviews, please.

**Review by behowell — APPROVED** [review]

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
