### PR TITLE
fix: react-charting horizontal-bar-chart-axis on hover render correct data

### PR DESCRIPTION
**Pull request by harsh9975**
https://github.com/microsoft/fluentui/assets/33349461/3492e116-d569-4ad3-bfdd-7ba6538d1610

## Previous Behavior
while hovering or selecting legend, data is displaying same for all the bar charts

## New Behavior
data is displaying properly

## Related Issue(s)

#29906 
- Fixes #
#29906

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/499eb8b3c02e05e817ff907b740af703c4a19bf1'>499eb8b3c02e05e817ff907b740af703c4a19bf1</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by AtishayMsft** [comment]
The expected behavior for this issue is that the callout should disappear if the control moves out of the chart canvas onto the legends.
Similar to line chart or area chart.

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
