### PR TITLE
Update northstar v2 colors

### PR DESCRIPTION
**Pull request by jurokapsiar**
Update Teams v2 color scheme with the new colors

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7a6fc1de0f33e7d593990df21a043939493fef49'>7a6fc1de0f33e7d593990df21a043939493fef49</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
DropdownManyItemsPerf.default | [553](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DropdownManyItemsPerf.default.html) | [494](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.12:1
ChatMinimalPerf.default | [622](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatMinimalPerf.default.html) | [565](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.1:1
RefMinimalPerf.default | [208](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RefMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.07:1
FlexMinimalPerf.default | [240](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/FlexMinimalPerf.default.html) | [227](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.06:1
AvatarMinimalPerf.default | [164](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AvatarMinimalPerf.default.html) | [156](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.05:1
HeaderMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/HeaderMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.05:1
SegmentMinimalPerf.default | [288](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SegmentMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.05:1
SkeletonMinimalPerf.default | [290](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SkeletonMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.05:1
GridMinimalPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/GridMinimalPerf.default.html) | [274](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LayoutMinimalPerf.default.html) | [290](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
TextMinimalPerf.default | [291](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TextMinimalPerf.default.html) | [280](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.04:1
ButtonMinimalPerf.default | [141](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonMinimalPerf.default.html) | [137](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.03:1
CardMinimalPerf.default | [468](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CardMinimalPerf.default.html) | [455](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.03:1
RadioGroupMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ReactionMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [788](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ToolbarMinimalPerf.default.html) | [766](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [281](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/BoxMinimalPerf.default.html) | [276](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [464](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonSlotsPerf.default.html) | [456](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [389](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CarouselMinimalPerf.default.html) | [383](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [637](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/HeaderSlotsPerf.default.html) | [623](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [320](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ImageMinimalPerf.default.html) | [313](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [571](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LoaderMinimalPerf.default.html) | [560](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
ProviderMinimalPerf.default | [335](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ProviderMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.02:1
StatusMinimalPerf.default | [564](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/StatusMinimalPerf.default.html) | [551](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.02:1
ChatWithPopoverPerf.default | [318](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatWithPopoverPerf.default.html) | [316](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [638](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DialogMinimalPerf.default.html) | [632](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [294](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DividerMinimalPerf.default.html) | [290](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1410](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SliderMinimalPerf.default.html) | [1398](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1614](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TableManyItemsPerf.default.html) | [1602](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [449](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AnimationMinimalPerf.default.html) | [450](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1:1
AttachmentSlotsPerf.default | [900](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AttachmentSlotsPerf.default.html) | [904](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2255](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2256](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [4740](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4733](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3429](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/EmbedMinimalPerf.default.html) | [3434](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [981](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [982](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [313](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LabelMinimalPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [538](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListWith60ListItems.default.html) | [536](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuMinimalPerf.default | [701](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/MenuMinimalPerf.default.html) | [699](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
RosterPerf.default | [940](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RosterPerf.default.html) | [939](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/RosterPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [521](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/PopupMinimalPerf.default.html) | [523](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1055](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1050](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3650](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3657](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [2270](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CustomToolbarPrototype.default.html) | [2260](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TreeMinimalPerf.default | [672](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TreeMinimalPerf.default.html) | [669](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
AttachmentMinimalPerf.default | [124](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AttachmentMinimalPerf.default.html) | [125](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.99:1
ButtonOverridesMissPerf.default | [1237](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1249](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [2528](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DropdownMinimalPerf.default.html) | [2561](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1066](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/InputMinimalPerf.default.html) | [1080](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [530](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListCommonPerf.default.html) | [538](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [419](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListMinimalPerf.default.html) | [425](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [450](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListNestedPerf.default.html) | [456](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
MenuButtonMinimalPerf.default | [1395](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1408](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TableMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TextAreaMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.99:1
TooltipMinimalPerf.default | [842](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TooltipMinimalPerf.default.html) | [852](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.99:1
TreeWith60ListItems.default | [140](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TreeWith60ListItems.default.html) | [141](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.99:1
FormMinimalPerf.default | [326](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/FormMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [492](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/IconMinimalPerf.default.html) | [507](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
ChatDuplicateMessagesPerf.default | [235](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [246](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.96:1
PortalMinimalPerf.default | [136](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/PortalMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.96:1
VideoMinimalPerf.default | [509](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/VideoMinimalPerf.default.html) | [534](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.95:1
AccordionMinimalPerf.default | [118](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AccordionMinimalPerf.default.html) | [126](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.94:1
AlertMinimalPerf.default | [217](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AlertMinimalPerf.default.html) | [230](https://fluentuipr.z22.web.core.windows.net/pull/22328/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9424"/>

**Review by ling1726 — APPROVED** [review]

**Comment by ling1726** [comment]
Some color contrasts before were already not 4.5:1 but now they are worse

image


Is that expected ?

**Comment by ling1726** [comment]
> > Some color contrasts before were already not 4.5:1 but now they are worse
> > image
> > Is that expected ?
> 
> good catch. Primary menu is probably not that much used so not sure if it is even part of spec. I will change the color to black: image

It's not the only one, I think I approved a few before on auto pilot

**Pull request merged**
