### PR TITLE
fix(react-datepicker-compat, Calendar): Add hover styles for gototoday button

### LINKED ISSUE #27948: [Bug]: High Contrast Bugs in Calendar
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 90.81 GB / 127.86 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Danavishnu_kb/pen/vYVaaQa

### Bug Description

Date picker's following components are missing their High Contrast style counterparts -

a. Hover/focus styles for Go To Today
image

b. Same for when in date view. Hover on December 2022 for example won't indicate hover with style change

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

|v8|v9|
|---|---|
|image|image|

## New Behavior

|v8|v9|
|---|---|
|image|image|

## Related Issue(s)

- Fixes #27948

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/01816611f845012bc10b54abdbab8fb2d1a0376f'>01816611f845012bc10b54abdbab8fb2d1a0376f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/BaseButton-mount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/BaseButton-mount.html">627</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Breadcrumb-mount_base.html">1679</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Breadcrumb-mount.html">1667</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Checkbox-mount_base.html">1684</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Checkbox-mount.html">1704</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/CheckboxBase-mount_base.html">1479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/CheckboxBase-mount.html">1473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ChoiceGroup-mount_base.html">2983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ChoiceGroup-mount.html">2919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ComboBox-mount_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ComboBox-mount.html">664</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/CommandBar-mount_base.html">6206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/CommandBar-mount.html">6246</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ContextualMenu-mount_base.html">12611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ContextualMenu-mount.html">12651</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DefaultButton-mount_base.html">746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DefaultButton-mount.html">756</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRow-mount_base.html">2188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRow-mount.html">2185</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRowFast-mount_base.html">2194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRowFast-mount.html">2165</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRowNoStyles-mount_base.html">1969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DetailsRowNoStyles-mount.html">2002</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Dialog-mount_base.html">2612</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Dialog-mount.html">2632</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DocumentCardTitle-mount_base.html">213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/DocumentCardTitle-mount.html">220</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Dropdown-mount_base.html">1949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Dropdown-mount.html">1995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/FocusTrapZone-mount_base.html">1104</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/FocusTrapZone-mount.html">1091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/FocusZone-mount_base.html">1063</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/FocusZone-mount.html">1075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-mount_base.html">41089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-mount.html">41178</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-virtual-rerender_base.html">19708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-virtual-rerender.html">19767</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50293</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedList-virtual-rerender-with-unmount.html">50120</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-mount_base.html">216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-mount.html">238</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-virtual-rerender_base.html">205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-virtual-rerender.html">207</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">225</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/IconButton-mount_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/IconButton-mount.html">1056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Label-mount_base.html">341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Label-mount.html">330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Layer-mount_base.html">2702</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Layer-mount.html">2746</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Link-mount_base.html">386</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Link-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/MenuButton-mount_base.html">923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/MenuButton-mount.html">925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/MessageBar-mount_base.html">21194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/MessageBar-mount.html">21261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Nav-mount_base.html">1943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Nav-mount.html">1927</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/OverflowSet-mount_base.html">773</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/OverflowSet-mount.html">774</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Panel-mount_base.html">1748</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Panel-mount.html">1728</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Persona-mount_base.html">714</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Persona-mount.html">735</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Pivot-mount_base.html">857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Pivot-mount.html">860</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/PrimaryButton-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/PrimaryButton-mount.html">840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Rating-mount_base.html">4587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Rating-mount.html">4643</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SearchBox-mount_base.html">889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SearchBox-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Shimmer-mount_base.html">1876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Shimmer-mount.html">1907</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Slider-mount_base.html">1350</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Slider-mount.html">1327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SpinButton-mount_base.html">2841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SpinButton-mount.html">2885</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Spinner-mount_base.html">386</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Spinner-mount.html">381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SplitButton-mount_base.html">1839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SplitButton-mount.html">1815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Stack-mount_base.html">409</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Stack-mount.html">403</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/StackWithIntrinsicChildren-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/StackWithIntrinsicChildren-mount.html">856</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/StackWithTextChildren-mount_base.html">2653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/StackWithTextChildren-mount.html">2592</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SwatchColorPicker-mount_base.html">6022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/SwatchColorPicker-mount.html">6147</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/TagPicker-mount_base.html">1405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/TagPicker-mount.html">1427</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Text-mount_base.html">365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Text-mount.html">368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/TextField-mount_base.html">899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/TextField-mount.html">958</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-mount_base.html">831</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-mount.html">834</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-virtual-rerender_base.html">589</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-virtual-rerender.html">583</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Toggle-mount_base.html">596</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/Toggle-mount.html">619</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/buttonNative-mount_base.html">200</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28458/perf-test/buttonNative-mount.html">189</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by smhigley — APPROVED** [review]

**Pull request merged**
