### PR TITLE
MenuItem : fixed hover styles for icon in disabled state

### LINKED ISSUE #26802: [Bug]: Disabled <MenuItem> still highlights its icon when hovered
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Using CodeSandbox
    "@fluentui/react-components": "9.15.0",
    "@fluentui/react-icons": "latest",
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-disable-menu-item-4epm1g?file=/package.json

## Expected Behavior
The "Edit" icon should keep gray even if it's being hovered on.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by kkakroo**
## Previous Behavior
Disabled `MenuItem` highlights icon when hovered

## New Behavior
Disabled `MenuItem` does not highlight icon when hovered.

#### Assuming below behaviour on icon hover while disabled is correct 
- Regular will stay regular on hover with disabled color.
- Filled will stay filled on hover with disabled color.
- Bundled will stay regular on hover with disabled color.

## Related Issue(s)

- Fixes #26802

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Avatar-mount_base.html">1543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Avatar-mount.html">1628</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Button-mount_base.html">1070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Button-mount.html">1117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Field-mount_base.html">2524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Field-mount.html">2466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProvider-mount_base.html">1880</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProvider-mount.html">1971</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-mount_base.html">701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-mount.html">725</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">634</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">668</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/InfoButton-mount_base.html">595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/InfoButton-mount.html">620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/MakeStyles-mount_base.html">2240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/MakeStyles-mount.html">2197</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Persona-mount_base.html">3810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/Persona-mount.html">3762</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/SpinButton-mount_base.html">2982</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27028/perf-test-react-components/SpinButton-mount.html">3030</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `202.311 kB`<br />`56.366 kB` | `202.553 kB`<br />`56.417 kB` | `242 B` <br />`51 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `126.86 kB`<br />`38.831 kB` | `127.102 kB`<br />`38.881 kB` | `242 B` <br />`50 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `129.929 kB`<br />`39.345 kB` | `130.171 kB`<br />`39.399 kB` | `242 B` <br />`54 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                |         Size (minified/GZIP) |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> |  `64.09 kB`<br />`17.544 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>               | `35.049 kB`<br />`11.533 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                            |   `6.324 kB`<br />`2.129 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/cb0acaa586d84b70a9d2c3a9f4a14d5cdd3022cb'>cb0acaa586d84b70a9d2c3a9f4a14d5cdd3022cb</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by layershifter — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
