### PR TITLE
Makes Label web component focusable when not disabled

### PR DESCRIPTION
**Pull request by brianchristopherbrady**
Adds a conditional tabindex to the Label template.

### CODE REVIEW

**Review by chrisdholt — CHANGES_REQUESTED** [review]
Labels are not focusable - where is this requirement coming from? We need to ensure that we’re validating assumptions. Label by itself is a text node.

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/cd72afce74e9c6f5eed240bd83abe338a7f75c18'>cd72afce74e9c6f5eed240bd83abe338a7f75c18</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by brianchristopherbrady** [comment]
Labels are not focusable

**Pull request closed without merging**
