### PR TITLE
add codeowners to theme designer v9

### PR DESCRIPTION
**Pull request by micahgodbolt**
new devs are going to be driving the theme designer effort with target of making it ready for build

### CODE REVIEW

**Comment by JustSlone** [comment]
@JinCodesAgain and @tibell_microsoft don't appear to be github accounts?
@ms-acalzaretto can you join the Microsoft organization? via the internal portal so we can add you to the team we use to manage permissions

**Review by ling1726 — APPROVED** [review]

**Comment by JustSlone** [comment]
> > @JinCodesAgain and @tibell_microsoft don't appear to be github accounts? @ms-acalzaretto can you join the Microsoft organization? via the internal portal so we can add you to the team we use to manage permissions
> 
> Joined -- I also updated Jin/Tim on joining as well. Waiting on them

Thanks, let us know when they join and if their GitHub user names are still accurate, they don't' seem to be resolving in the GitHub UI

**Comment by JustSlone** [comment]
@ms-acalzaretto any news on our other friends accounts? 
We could merge this with just you as owner for now, we can always add more folks later if needed.

**Comment by ms-acalzaretto** [comment]
It's fine to just merge me as owner!

**Review by JustSlone — APPROVED** [review]

**Pull request merged**
