### PR TITLE
fix: Portals should render correctly in react 18 strict mode

### LINKED ISSUE #25232: [Bug]: Portal Component Not Rendering in Strict Mode
### Library

React Components / v9 (@fluentui/react-components)

### System Info

I created a sandbox with side by side menu component, one has inline=true, the other set inline=false; 
The one with inline=false, the pop over will not shown after click on the menu.

Here's the code sandbox example https://codesandbox.io/s/great-thompson-gkfe8o?file=/src/index.js

Note: I've also tried other portal components, e.g., combobox, dropdown, etc, it's the same behavior the portal component doesn't render correctly

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/great-thompson-gkfe8o?file=/src/index.js

## Actual Behavior
only the menu that has inline=false, the flyout/pop over renders correctly.

## Expected Behavior
both menu should be able to open successfully

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### LINKED ISSUE #26031: [Bug]: Menu not working with in v9 with React 18
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.74 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/cocky-dan-qfkgkn?file=/src/App.tsx

## Actual Behavior
took an example from official samples and it doesn't work for react 18

code:
```
import "./styles.css";
import {
  Button,
  Menu,
  MenuItem,
  MenuList,
  MenuPopover,
  MenuTrigger
} from "@fluentui/react-components";

export default function App() {
  const NestedSubmenusControlled = () => {
    return (
      <Menu>
        <MenuTrigger disableButtonEnhancement>
          <Button>menu</Button>
        </MenuTrigger>

        <MenuPopover>
          <MenuList>
            <MenuItem>New </MenuItem>
            <MenuItem>New Window</MenuItem>
            <MenuItem disabled>Open File</MenuItem>
            <MenuItem>Open Folder</MenuItem>
          </MenuList>
        </MenuPopover>
      </Menu>
    );
  };

  return <NestedSubmenusControlled />;
}
```

## Expected Behavior
menu opens

### Logs

_No response_

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
## Previous Behavior

Portals do not render in React 18 strict mode

## New Behavior

Take a dependency on [use-disposable](https://www.npmjs.com/package/use-disposable) so that portals will render in strict mode

## Related Issue(s)

Fixes #25232
Fixes #26031

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `78.546 kB`<br />`25.167 kB` |  `79.191 kB`<br />`25.461 kB` | `645 B` <br />`294 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `77.775 kB`<br />`25.069 kB` |   `78.42 kB`<br />`25.367 kB` | `645 B` <br />`298 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `186.264 kB`<br />`52.303 kB` | `186.915 kB`<br />`52.645 kB` | `651 B` <br />`342 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `117.922 kB`<br />`35.391 kB` | `118.567 kB`<br />`35.721 kB` | `645 B` <br />`330 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `117.418 kB`<br />`36.256 kB` |  `118.063 kB`<br />`36.58 kB` | `645 B` <br />`324 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `120.487 kB`<br />`36.785 kB` | `121.132 kB`<br />`37.109 kB` | `645 B` <br />`324 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `103.666 kB`<br />`31.858 kB` | `104.311 kB`<br />`32.162 kB` | `645 B` <br />`304 B`  |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |   `10.495 kB`<br />`3.851 kB` |   `11.121 kB`<br />`4.157 kB` | `626 B` <br />`306 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `42.032 kB`<br />`14.739 kB` |  `42.677 kB`<br />`15.043 kB` | `645 B` <br />`304 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                |         Size (minified/GZIP) |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                                                       |         `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr>                                       |         `554 B`<br />`348 B` |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>                                         |   `3.153 kB`<br />`1.299 kB` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                              | `79.294 kB`<br />`24.443 kB` |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                          | `82.967 kB`<br />`21.022 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                       | `51.076 kB`<br />`14.285 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                             |  `15.006 kB`<br />`6.009 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                     | `67.306 kB`<br />`18.581 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                          |  `23.357 kB`<br />`7.361 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                            |  `24.247 kB`<br />`7.643 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                          |  `24.001 kB`<br />`7.049 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                       |   `32.923 kB`<br />`8.61 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                       |  `39.953 kB`<br />`9.933 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                               |  `37.611 kB`<br />`9.942 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                             | `45.057 kB`<br />`11.323 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                           | `48.753 kB`<br />`10.715 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                   | `77.541 kB`<br />`22.325 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                             | `72.485 kB`<br />`20.913 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                 |    `8.617 kB`<br />`3.62 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                 |  `10.382 kB`<br />`4.258 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                               |    `9.424 kB`<br />`3.97 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `59.288 kB`<br />`16.435 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>               |  `33.75 kB`<br />`11.101 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                       | `83.036 kB`<br />`24.754 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                    |  `16.515 kB`<br />`5.921 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                          |  `10.836 kB`<br />`4.283 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                          |   `24.194 kB`<br />`7.89 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                          |    `9.394 kB`<br />`3.88 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                            |  `11.862 kB`<br />`4.885 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                  |  `11.004 kB`<br />`4.188 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                    |  `57.113 kB`<br />`15.94 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                            |   `5.857 kB`<br />`1.978 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                                                       |  `19.826 kB`<br />`7.417 kB` |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/Progress.fixture.js'>Progress</abbr>                                                                 |  `13.536 kB`<br />`5.107 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                     |  `15.817 kB`<br />`5.905 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                          |  `36.42 kB`<br />`12.126 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                |   `14.304 kB`<br />`5.72 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                       |  `23.474 kB`<br />`8.017 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                       | `32.091 kB`<br />`10.183 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                           | `44.502 kB`<br />`12.812 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                    |  `20.013 kB`<br />`6.446 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                       | `33.427 kB`<br />`10.581 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                           |  `11.838 kB`<br />`4.625 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                         |   `15.148 kB`<br />`5.06 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                 |  `25.733 kB`<br />`8.328 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                           |           `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                     |  `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                   |  `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                          |         `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2ae8cc79c87d510b6ad5afd01b77c6a89f5debd9'>2ae8cc79c87d510b6ad5afd01b77c6a89f5debd9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 59 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25956&commitId=85dcfcd83512c3e35203de6d4d2690c20f8b5657&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1700 screenshots unchanged, 0 screenshots with different dimensions and 59 screenshots with visible difference.


  <details><summary><b>unknown</b> 59 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Menu Converged - basic.default - RTL.chromium.png|894| Changed|
|Menu Converged - basic.default - RTL.hover menuitem.chromium.png|888| Changed|
|Menu Converged - basic.default.chromium.png|908| Changed|
|Menu Converged - basic.default.hover menuitem.chromium.png|902| Changed|
|Menu Converged - groups.default - Dark Mode.chromium.png|11152| Changed|
|Menu Converged - groups.default - High Contrast.chromium.png|13872| Changed|
|Menu Converged - groups.default - RTL.chromium.png|2266| Changed|
|Menu Converged - groups.default.chromium.png|2329| Changed|
|Menu Converged - icon slotted content.default - RTL.chromium.png|1235| Changed|
|Menu Converged - icon slotted content.default - RTL.hover menuitem.chromium.png|1234| Changed|
|Menu Converged - icon slotted content.default.chromium.png|1258| Changed|
|Menu Converged - icon slotted content.default.hover menuitem.chromium.png|1249| Changed|
|Menu Converged - nested submenus.default - RTL.all open.chromium.png|2516| Changed|
|Menu Converged - nested submenus.default - RTL.chromium.png|1401| Changed|
|Menu Converged - nested submenus.default.all open.chromium.png|2539| Changed|
|Menu Converged - nested submenus.default.chromium.png|1424| Changed|
|Menu Converged - secondary content.default - RTL.chromium.png|1151| Changed|
|Menu Converged - secondary content.default - RTL.hover menuitem.chromium.png|1157| Changed|
|Menu Converged - secondary content.default.chromium.png|1158| Changed|
|Menu Converged - secondary content.default.hover menuitem.chromium.png|1160| Changed|
|Menu Converged - selection groups.default - RTL.chromium.png|2347| Changed|
|Menu Converged - selection groups.default - RTL.selected.chromium.png|2359| Changed|
|Menu Converged - selection groups.default.chromium.png|2357| Changed|
|Menu Converged - selection groups.default.selected.chromium.png|2369| Changed|
|Menu Converged - selection.checkbox - Dark Mode.chromium.png|7982| Changed|
|Menu Converged - selection.checkbox - Dark Mode.selected.chromium.png|8032| Changed|
|Menu Converged - selection.checkbox - High Contrast.chromium.png|9459| Changed|
|Menu Converged - selection.checkbox - High Contrast.selected.chromium.png|9748| Changed|
|Menu Converged - selection.checkbox - RTL.chromium.png|880| Changed|
|Menu Converged - selection.checkbox - RTL.selected.chromium.png|916| Changed|
|Menu Converged - selection.checkbox.chromium.png|912| Changed|
|Menu Converged - selection.checkbox.selected.chromium.png|948| Changed|
|Menu Converged - split item.default - RTL.chromium.png|1272| Changed|
|Menu Converged - split item.default - RTL.submenu open.chromium.png|2445| Changed|
|Menu Converged - split item.default.chromium.png|1305| Changed|
|Menu Converged - split item.default.submenu open.chromium.png|2478| Changed|
|Menu Converged - submenuIndicator slotted content.default - RTL.chromium.png|490| Changed|
|Menu Converged - submenuIndicator slotted content.default - RTL.submenus open.chromium.png|2316| Changed|
|Menu Converged - submenuIndicator slotted content.default.chromium.png|497| Changed|
|Menu Converged - submenuIndicator slotted content.default.submenus open.chromium.png|2277| Changed|
|Menu nested within a MenuTrigger.default.chromium.png|1529| Changed|
|Menu nested within a MenuTrigger.default.submenu open.chromium.png|3112| Changed|
|Popover Converged.positioning - High Contrast.positioned popovers.chromium.png|6314| Changed|
|Popover Converged.positioning - RTL.positioned popovers.chromium.png|3685| Changed|
|Popover Converged.positioning.positioned popovers.chromium.png|3687| Changed|
|Tooltip Converged.basic - Dark Mode.chromium.png|2656| Changed|
|Tooltip Converged.basic - High Contrast.chromium.png|3127| Changed|
|Tooltip Converged.basic.chromium.png|527| Changed|
|Tooltip Converged.inverted - Dark Mode.chromium.png|2640| Changed|
|Tooltip Converged.inverted withArrow - Dark Mode.chromium.png|4537| Changed|
|Tooltip Converged.inverted withArrow.chromium.png|7607| Changed|
|Tooltip Converged.inverted.chromium.png|4417| Changed|
|Tooltip Converged.positioning - High Contrast.positioned tooltips.chromium.png|8932| Changed|
|Tooltip Converged.positioning - RTL.positioned tooltips.chromium.png|2589| Changed|
|Tooltip Converged.positioning.positioned tooltips.chromium.png|2588| Changed|
|Tooltip Converged.text-wrapping.chromium.png|1635| Changed|
|Tooltip Converged.withArrow - Dark Mode.chromium.png|3427| Changed|
|Tooltip Converged.withArrow - High Contrast.chromium.png|4020| Changed|
|Tooltip Converged.withArrow.chromium.png|717| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [🕵 FluentUI-v0 Open the Visual Regressions report to inspect the 7 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25956&commitId=85dcfcd83512c3e35203de6d4d2690c20f8b5657&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1254 screenshots unchanged, 0 screenshots with different dimensions and 7 screenshots with visible difference.


  <details><summary><b>unknown</b> 7 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Chat.Chat Playground.chromium.png|1720| Changed|
|Label.Label Example Content Customization Shorthand.chromium.png|484| Changed|
|List.Selectable List Controlled Example.chromium.png|485| Changed|
|Menu.Menu With Submenu Controlled Example.chromium.png|486| Changed|
|Toolbar.Toolbar Example Overflow Positioning Shorthand Rtl.RTL- Overflow item is properly positioned.chromium.png|1564| Changed|
|Toolbar.Toolbar Example Overflow Positioning Shorthand.Overflow item is properly positioned.chromium.png|1564| Changed|
|Video.Video Example.chromium.png|33| Changed|

</details>


<div id="vrtCommentFluentUI-v0"/>

**Review by layershifter — APPROVED** [review]

**Review by TristanWatanabe — APPROVED** [review]

**Comment by TristanWatanabe** [comment]
Just took a look at the VR test results and the menu popover is now rendering away from the trigger button, is that expected?

**Comment by ling1726** [comment]
> Just took a look at the VR test results and the menu popover is now positioned further away from the trigger button, is that expected?

oh I'll dig into that, nothing seems incorrectly positioned in the demo doc site

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Avatar-mount_base.html">1297</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Avatar-mount.html">1322</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Button-mount_base.html">939</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Button-mount.html">942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProvider-mount_base.html">1579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProvider-mount.html">1567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-mount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-mount.html">631</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">585</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">585</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">633</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/MakeStyles-mount_base.html">1912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/MakeStyles-mount.html">1918</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Persona-mount_base.html">3014</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/Persona-mount.html">2923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/SpinButton-mount_base.html">2486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25956/perf-test-react-components/SpinButton-mount.html">2508</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
