### PR TITLE
Spinner: added delay prop

### LINKED ISSUE #27826: [Feature]: Add delay prop to Spinner
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Fluent UI v0 has a `delay` prop on Loader. It would be useful if v9 Spinner had the same - to make the component easier to use for common scenarios in Teams and easier to migrate to.

Proposing adding it to base component. If not, we can add it as a Teams specific feature.

### Have you discussed this feature with our team

Kay

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kkakroo**
## Previous Behavior
There was no `delay` prop in spinner.

## New Behavior
Added `delay` prop in spinner.

## Related Issue(s)

- Fixes #27826

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/fb5071ac25ed576b554332afc9305e4fc5ddaa14'>fb5071ac25ed576b554332afc9305e4fc5ddaa14</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">103</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Avatar-mount_base.html">721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Avatar-mount.html">696</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Button-mount_base.html">401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Button-mount.html">403</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Field-mount_base.html">1248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Field-mount.html">1240</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProvider-mount_base.html">786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProvider-mount.html">782</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-mount_base.html">104</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-mount.html">107</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">99</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">96</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">103</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/InfoButton-mount_base.html">12</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/InfoButton-mount.html">19</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/MakeStyles-mount_base.html">1193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/MakeStyles-mount.html">1215</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Persona-mount_base.html">1922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/Persona-mount.html">1887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/SpinButton-mount_base.html">1454</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27852/perf-test-react-components/SpinButton-mount.html">1490</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by tomi-msft** [comment]
Looks like you need to update the api. Run `yarn build` and push the updated `api.md` file. I also think it would be helpful to add some tests

**Comment by tomi-msft** [comment]
So, I think this is because of the way `shouldRenderSpinner` is introduced. By default it is set to the value of `isVisible`, which is false, so `onRenderSpinner` would not render it initially. The tests take this initial value and performs the check, which fails.

**Comment by tomi-msft** [comment]
So, I think this is because of the way `shouldRenderSpinner` is introduced. By default it is set to the value of `isVisible`, which is false, so `onRenderSpinner` would not render it initially. The tests take this initial value and performs the check, which fails.

**Comment by kkakroo** [comment]
thanks @tomi-msft , made changes to address the issue mentioned.

**Comment by tomi-msft** [comment]
Great @kkakroo, once the build is green I can merge it. Thanks for your contribution!

**Review by tomi-msft — APPROVED** [review]

**Comment by tomi-msft** [comment]
One thing, the web-components api.md file should not have been updated, can you revert it?

**Comment by kkakroo** [comment]
@tomi-msft , thanks for pointing it out. Done

**Pull request merged**
