### PR TITLE
fix: proper color for primary button in HC theme

### PR DESCRIPTION
**Pull request by chpalac**
# Overview 

N* `Button` uses `Loader` to show loading indicator in the button which only has purple or white SVG, so when having primary variation in HC theme the loader was invisible:

Not Working

Now we are overriding the background and it will be the purple version, but for that I have to declare it as proper button variables to be able to override the Loader background. 

PYDwP7RJai

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5a7e1cd7fdd851388e91834a868dab8405abf324'>5a7e1cd7fdd851388e91834a868dab8405abf324</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 7 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
ButtonMinimalPerf.default | [204](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonMinimalPerf.default.html) | [178](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.15:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonMinimalPerf.default.regression.txt)
PortalMinimalPerf.default | [172](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/PortalMinimalPerf.default.html) | [159](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.08:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/PortalMinimalPerf.default.regression.txt)
AccordionMinimalPerf.default | [174](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AccordionMinimalPerf.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.03:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AccordionMinimalPerf.default.regression.txt)
AttachmentMinimalPerf.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AttachmentMinimalPerf.default.html) | [170](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AttachmentMinimalPerf.default.regression.txt)
AvatarMinimalPerf.default | [214](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AvatarMinimalPerf.default.html) | [209](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.02:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AvatarMinimalPerf.default.regression.txt)
RefMinimalPerf.default | [232](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RefMinimalPerf.default.html) | [239](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.97:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RefMinimalPerf.default.regression.txt)
TreeWith60ListItems.default | [175](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TreeWith60ListItems.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.96:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TreeWith60ListItems.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
FlexMinimalPerf.default | [318](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/FlexMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.12:1
ReactionMinimalPerf.default | [421](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ReactionMinimalPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.08:1
SegmentMinimalPerf.default | [389](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SegmentMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.08:1
MenuMinimalPerf.default | [956](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/MenuMinimalPerf.default.html) | [895](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.07:1
ToolbarMinimalPerf.default | [1117](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1058](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1213](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1153](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
CheckboxMinimalPerf.default | [2970](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2838](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.05:1
HeaderMinimalPerf.default | [385](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/HeaderMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.05:1
ListNestedPerf.default | [635](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListNestedPerf.default.html) | [605](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListNestedPerf.default_base.html) | 1.05:1
BoxMinimalPerf.default | [399](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/BoxMinimalPerf.default.html) | [382](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.04:1
CarouselMinimalPerf.default | [533](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CarouselMinimalPerf.default.html) | [512](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [392](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LayoutMinimalPerf.default.html) | [376](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [544](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListMinimalPerf.default.html) | [524](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
ListWith60ListItems.default | [669](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListWith60ListItems.default.html) | [643](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.04:1
ChatMinimalPerf.default | [816](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatMinimalPerf.default.html) | [796](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
DropdownManyItemsPerf.default | [776](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DropdownManyItemsPerf.default.html) | [752](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.03:1
DropdownMinimalPerf.default | [3376](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DropdownMinimalPerf.default.html) | [3285](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.03:1
HeaderSlotsPerf.default | [843](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/HeaderSlotsPerf.default.html) | [818](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1310](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1272](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
PopupMinimalPerf.default | [648](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/PopupMinimalPerf.default.html) | [627](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [383](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TextMinimalPerf.default.html) | [373](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [874](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DialogMinimalPerf.default.html) | [857](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
EmbedMinimalPerf.default | [4472](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/EmbedMinimalPerf.default.html) | [4393](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [386](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ImageMinimalPerf.default.html) | [377](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1354](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/InputMinimalPerf.default.html) | [1331](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
ListCommonPerf.default | [690](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListCommonPerf.default.html) | [675](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ListCommonPerf.default_base.html) | 1.02:1
IconMinimalPerf.default | [708](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/IconMinimalPerf.default.html) | [693](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.02:1
AnimationMinimalPerf.default | [603](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AnimationMinimalPerf.default.html) | [596](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [636](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CardMinimalPerf.default.html) | [629](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [468](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [4847](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4778](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2169](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TableManyItemsPerf.default.html) | [2144](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TableMinimalPerf.default.html) | [440](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1663](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1660](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ChatWithPopoverPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatWithPopoverPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [396](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DividerMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [360](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/GridMinimalPerf.default.html) | [360](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
RosterPerf.default | [1253](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RosterPerf.default.html) | [1256](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/RosterPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1267](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1261](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [761](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/StatusMinimalPerf.default.html) | [759](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
VideoMinimalPerf.default | [728](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/VideoMinimalPerf.default.html) | [727](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [404](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ProviderMinimalPerf.default.html) | [408](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TextAreaMinimalPerf.default.html) | [563](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [2896](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CustomToolbarPrototype.default.html) | [2931](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
TreeMinimalPerf.default | [921](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TreeMinimalPerf.default.html) | [930](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
ButtonSlotsPerf.default | [587](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonSlotsPerf.default.html) | [598](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.98:1
TooltipMinimalPerf.default | [1259](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TooltipMinimalPerf.default.html) | [1290](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.98:1
ChatDuplicateMessagesPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.97:1
FormMinimalPerf.default | [462](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/FormMinimalPerf.default.html) | [474](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.97:1
LabelMinimalPerf.default | [399](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LabelMinimalPerf.default.html) | [412](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.97:1
SkeletonMinimalPerf.default | [364](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SkeletonMinimalPerf.default.html) | [377](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.97:1
SliderMinimalPerf.default | [1750](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SliderMinimalPerf.default.html) | [1806](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.97:1
AlertMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AlertMinimalPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.95:1
MenuButtonMinimalPerf.default | [1802](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1906](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.95:1
LoaderMinimalPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LoaderMinimalPerf.default.html) | [739](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.94:1
DatepickerMinimalPerf.default | [6073](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DatepickerMinimalPerf.default.html) | [6542](https://fluentuipr.z22.web.core.windows.net/pull/24171/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by layershifter** [comment]
@chpalac it's way forward with N* implementation that makes me sad, but it's what we have...

- As I see we have already sprites for white/purple in `Loader` component. Are these somehow different? Can we reuse existing?
- Can we try to have a single SVG and use local CSS variables as @jurokapsiar suggested? I.e. do `fill="var(--fuin-loader-color1)"`.

**Comment by chpalac** [comment]
> @chpalac it's way forward with N* implementation that makes me sad, but it's what we have...
> 
> * As I see we have already sprites for white/purple in `Loader` component. Are these somehow different? Can we reuse existing?

@layershifter 
I am "kind of" reusing them since I just copied them to the button folder so I could use it as variables there which would allow me to rewrite them in the HC, basically the ones I am introducing here in the Button folder is a copy of the ones in the Loader folder

**Comment by jurokapsiar** [comment]
I would recommend using Fluent UI v9 Button and/or Spinner for correct styling. v0 loader is too hardcoded and not so flexible.

**Pull request closed without merging**
