### PR TITLE
fix: v9 Combobox option focus on open updates

### PR DESCRIPTION
**Pull request by smhigley**
## Previous Behavior

- Multiselect Combobox & Dropdown began option focus at last selected option when opened (similar to single-select combobox)
- When opened from the combobox chevron, the option keyboard focus outline still showed up

## New Behavior

- Multiselect combo & dropdown always begin from the first option when opened (unlike single-select) -- discussed with design
- Focus visibility is reset when using the mouse to open a combobox from the chevron icon

## Related Issue(s)

Addresses poitns 1 & 2 in #26069

* Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                             |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `79.944 kB`<br />`25.571 kB` |  `79.945 kB`<br />`25.57 kB` |  `1 B` <br />`-1 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                    |  `77.14 kB`<br />`25.536 kB` | `77.141 kB`<br />`25.532 kB` |  `1 B` <br />`-4 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `79.184 kB`<br />`25.502 kB` | `79.179 kB`<br />`25.499 kB` | `-5 B` <br />`-3 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `59.888 kB`<br />`16.652 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.87 kB`<br />`53.066 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `34.379 kB`<br />`11.322 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.069 kB`<br />`2.053 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6daf6e3e4d5f888e77181ecf4f7dd63763d2752d'>6daf6e3e4d5f888e77181ecf4f7dd63763d2752d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Avatar-mount_base.html">1590</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Avatar-mount.html">1539</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Button-mount_base.html">1118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Button-mount.html">1104</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProvider-mount_base.html">1879</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProvider-mount.html">1884</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-mount_base.html">737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-mount.html">746</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">681</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">743</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">735</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/MakeStyles-mount_base.html">2246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/MakeStyles-mount.html">2254</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Persona-mount_base.html">3470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/Persona-mount.html">3496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/SpinButton-mount_base.html">2947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26173/perf-test-react-components/SpinButton-mount.html">2944</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by micahgodbolt — APPROVED** [review]

**Comment by micahgodbolt** [comment]
confirmed old and new behavior.

**Pull request merged**
