### PR TITLE
Special Folder Icons

### PR DESCRIPTION
**Pull request by taenri**
#### Pull request checklist

- [X] Addresses an existing issue: internal bug
- [X] Include a change request file using `$ yarn change`

#### Description of changes

Add special folder icon support for file-type-icons and signals.
i.e. Desktop, Documents, and Pictures

#### Focus areas to test

N/A

### CODE REVIEW

**Comment by dmichon-msft** [comment]
@ecraig12345 , that's correct, yes. The build now outputs to a unique folder per production build. Unfortunately how to ensure that code points to a valid build was left as an exercise to the developer.

**Comment by ecraig12345** [comment]
Here's the complete update to `initializeFileTypeIcons.tsx` including a new valid URL and removing the refresh query param since it's no longer needed:
```tsx
import * as React from 'react';
import { registerIcons, IIconOptions } from '@uifabric/styling';
import { FileTypeIconMap } from './FileTypeIconMap';

const PNG_SUFFIX = '_png';
const SVG_SUFFIX = '_svg';

const DEFAULT_BASE_URL = 'https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/';
const ICON_SIZES: number[] = [16, 20, 24, 32, 40, 48, 64, 96];

export function initializeFileTypeIcons(baseUrl: string = DEFAULT_BASE_URL, options?: Partial<IIconOptions>): void {
  ICON_SIZES.forEach((size: number) => {
    _initializeIcons(baseUrl, size, options);
  });
}

function _initializeIcons(baseUrl: string, size: number, options?: Partial<IIconOptions>): void {
  const iconTypes: string[] = Object.keys(FileTypeIconMap);
  const fileTypeIcons: { [key: string]: JSX.Element } = {};

  iconTypes.forEach((type: string) => {
    fileTypeIcons[type + size + PNG_SUFFIX] = <img src={baseUrl + size + '/' + type + '.png'} />;
    fileTypeIcons[type + size + SVG_SUFFIX] = <img src={baseUrl + size + '/' + type + '.svg'} />;

    // For high resolution screens, register additional versions
    // Apply height=100% and width=100% to force image to fit into containing element

    // SVGs scale well, so you can generally use the default image.
    // 1.5x is a special case where both SVGs and PNGs need a different image.
    // Remove if statements when missing image files for 20_1.5x are provided.
    if (size !== 20) {
      fileTypeIcons[type + size + '_1.5x' + PNG_SUFFIX] = (
        <img src={baseUrl + size + '_1.5x/' + type + '.png'} height="100%" width="100%" />
      );
      fileTypeIcons[type + size + '_1.5x' + SVG_SUFFIX] = (
        <img src={baseUrl + size + '_1.5x/' + type + '.svg'} height="100%" width="100%" />
      );
    }

    fileTypeIcons[type + size + '_2x' + PNG_SUFFIX] = (
      <img src={baseUrl + size + '_2x/' + type + '.png'} height="100%" width="100%" />
    );
    fileTypeIcons[type + size + '_3x' + PNG_SUFFIX] = (
      <img src={baseUrl + size + '_3x/' + type + '.png'} height="100%" width="100%" />
    );
    fileTypeIcons[type + size + '_4x' + PNG_SUFFIX] = (
      <img src={baseUrl + size + '_4x/' + type + '.png'} height="100%" width="100%" />
    );
  });

  registerIcons(
    {
      fontFace: {},
      style: {
        width: size,
        height: size,
        overflow: 'hidden',
      },
      icons: fileTypeIcons,
    },
    options,
  );
}
```

**Comment by ecraig12345** [comment]
I got a valid URL and pushed an update, also removing the refresh query param since it's no longer needed.

**Comment by taenri** [comment]
> I got a valid URL and pushed an update, also removing the refresh query param since it's no longer needed.

Thanks for pushing that update for me! ^_^

**Comment by bigbadcapers** [comment]
@Jahnp do you see any issues worth addressing before clicking the big green btn?

**Comment by Jahnp** [comment]
@bigbadcapers nope, looks great to me!

**Comment by taenri** [comment]
Thanks for the reviews everyone!

**Pull request merged**
