### PR TITLE
(chore) Move react-combobox to react-components subfolder 

### PR DESCRIPTION
**Pull request by TristanWatanabe**
## Changes

- Moves `@fluentui/react-combobox` to react-components common folder using `move-packages` nx generator.

## Related Issue(s)

Part of #22427

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/Avatar-mount_base.html">909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/Avatar-mount.html">923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/Button-mount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/Button-mount.html">553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProvider-mount_base.html">1820</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProvider-mount.html">1830</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-mount_base.html">281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-mount.html">278</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">243</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">233</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">314</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/MakeStyles-mount_base.html">1569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test-react-components/MakeStyles-mount.html">1596</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                   |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `73.754 kB`<br />`22.494 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                             |  `20.965 kB`<br />`6.605 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                               |  `21.918 kB`<br />`6.919 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                             |  `22.005 kB`<br />`6.582 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                       |   `15.455 kB`<br />`5.57 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                             | `29.382 kB`<br />`10.047 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                   |   `13.61 kB`<br />`5.462 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                          |  `25.312 kB`<br />`8.202 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                    |   `20.672 kB`<br />`7.07 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8437eb3b6023bdac5b234538e1116b1c7d24f53f'>8437eb3b6023bdac5b234538e1116b1c7d24f53f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/BaseButton-mount_base.html">786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/BaseButton-mount.html">779</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Breadcrumb-mount_base.html">2280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Breadcrumb-mount.html">2292</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Checkbox-mount_base.html">1290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Checkbox-mount.html">1259</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/CheckboxBase-mount_base.html">1072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/CheckboxBase-mount.html">1067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ChoiceGroup-mount_base.html">3943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ChoiceGroup-mount.html">3943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ComboBox-mount_base.html">768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ComboBox-mount.html">799</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/CommandBar-mount_base.html">8749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/CommandBar-mount.html">8810</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ContextualMenu-mount_base.html">9203</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ContextualMenu-mount.html">9184</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DefaultButton-mount_base.html">961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DefaultButton-mount.html">965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRow-mount_base.html">3071</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRow-mount.html">3039</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRowFast-mount_base.html">3109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRowFast-mount.html">3117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRowNoStyles-mount_base.html">2901</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DetailsRowNoStyles-mount.html">2877</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Dialog-mount_base.html">1897</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Dialog-mount.html">1902</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DocumentCardTitle-mount_base.html">147</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/DocumentCardTitle-mount.html">162</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Dropdown-mount_base.html">2792</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Dropdown-mount.html">2761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/FocusTrapZone-mount_base.html">1518</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/FocusTrapZone-mount.html">1527</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/FocusZone-mount_base.html">1512</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/FocusZone-mount.html">1529</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/IconButton-mount_base.html">1382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/IconButton-mount.html">1399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Label-mount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Label-mount.html">313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Layer-mount_base.html">2558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Layer-mount.html">2553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Link-mount_base.html">439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Link-mount.html">438</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/MenuButton-mount_base.html">1221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/MenuButton-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/MessageBar-mount_base.html">1864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/MessageBar-mount.html">1887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Nav-mount_base.html">2663</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Nav-mount.html">2617</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/OverflowSet-mount_base.html">991</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/OverflowSet-mount.html">981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Panel-mount_base.html">1795</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Panel-mount.html">1827</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Persona-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Persona-mount.html">867</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Pivot-mount_base.html">1138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Pivot-mount.html">1134</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/PrimaryButton-mount_base.html">1082</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/PrimaryButton-mount.html">1089</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Rating-mount_base.html">6648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Rating-mount.html">6723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SearchBox-mount_base.html">1114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SearchBox-mount.html">1120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Shimmer-mount_base.html">2222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Shimmer-mount.html">2263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Slider-mount_base.html">1696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Slider-mount.html">1683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SpinButton-mount_base.html">3952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SpinButton-mount.html">3992</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Spinner-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Spinner-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SplitButton-mount_base.html">2466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SplitButton-mount.html">2461</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Stack-mount_base.html">491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Stack-mount.html">484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/StackWithIntrinsicChildren-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/StackWithIntrinsicChildren-mount.html">1853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/StackWithTextChildren-mount_base.html">4615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/StackWithTextChildren-mount.html">4624</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SwatchColorPicker-mount_base.html">9100</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/SwatchColorPicker-mount.html">9087</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TagPicker-mount_base.html">2089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TagPicker-mount.html">2074</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TeachingBubble-mount_base.html">71838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TeachingBubble-mount.html">74141</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Text-mount_base.html">395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Text-mount.html">400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TextField-mount_base.html">1185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/TextField-mount.html">1156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-mount_base.html">946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-mount.html">954</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-virtual-rerender_base.html">601</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-virtual-rerender.html">610</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1423</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1471</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Toggle-mount_base.html">729</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/Toggle-mount.html">723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/buttonNative-mount_base.html">106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22830/perf-test/buttonNative-mount.html">103</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by JustSlone — APPROVED** [review]

**Comment by JustSlone** [comment]
@TristanWatanabe I added the `Do Not Merge` label for you, remove it when this is ready to merge

**Review by Hotell — APPROVED** [review]

**Pull request merged**
