### PR TITLE
feat(react-file-type-icons): Add getFileTypeIconAsUrl utility

### LINKED ISSUE #26975: [Feature]: Expand @fluentui/react-file-type-icons for use in React without Fluent UI v8
### Library

React / v8 (@fluentui/react)

#### Overview

Our product (enterprise search in SharePoint, Office.com and Bing) uses `@fluentui/react-file-type-icons` package for showing file type icons. Currently we are refactoring our code to 1) remove dependencies on global icons set on window and 2) allow to use our own CDN for serving icons.

The issue that we hit is that the package does not export the default CDN URL and does not support constructing pure icon URL (only JSX or raw HTML) from file extension and/or type.

#### Proposal
1. Export `DEFAULT_BASE_URL` from package's index as a part of export from [initializeFileTypeIcons.tsx](https://github.com/microsoft/fluentui/blob/master/packages/react-file-type-icons/src/initializeFileTypeIcons.tsx). This is to allow clients to switch between default and custom CDN URLs via e.g. flighting.
2. Create a new exported function that would return file type icon URL based on `IFileTypeIconOptions` data and base URL. This will be similar to existing [getFileTypeIconAsHTMLString.ts](https://github.com/microsoft/fluentui/blob/master/packages/react-file-type-icons/src/getFileTypeIconAsHTMLString.ts), but will simply return `src` URL instead of building HTML string. The function will then be available for use from React without having to use `Icon` component from Fluent UI v8.

#### Implementation
Draft PR: #27336 

### Have you discussed this feature with our team

_No response_

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by alina-zaieva**
## Previous Behavior
Not applicable, this is a new functionality.

## New Behavior

`getFileTypeIconAsUrl` utility is added to `@fluentui/react-file-type-icons` package. It uses the same implementation as existing `getFileTypeIconAsHTMLString`, but instead of returning a string with `img` DOM element it returns a raw URL that can be passed to an `img` element in `src` attribute.

## Related Issue(s)

- Fixes #26975

### CODE REVIEW

**Comment by alina-zaieva** [comment]
> @alina-zaieva please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4fad4cbbcbdb48847857c388135a3abda472add7'>4fad4cbbcbdb48847857c388135a3abda472add7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by bigbadcapers** [comment]
This looks distinctly useful in terms of adding more flexiblity to the invocation methods to ensure every app always gets the right filetype icon. It seems actually pretty necessary to support a more broad set of platforms. From that standpoint it's got approval from me. 

I can't speak as to the way the method is being published, eg TypeScript or Fluent conventions as I'm not the expert there.

**Review by bigbadcapers — APPROVED** [review]
Approved from a functionality / needs standpoint. Very useful new method. Please check with other TypeScript/RN/Fluent experts on as to whether it's been exposed with the proper naming conventions, etc.

**Comment by alina-zaieva** [comment]
@tomi-msft can you help with getting necessary approvals to complete this PR? 🙂

**Review by tomi-msft — APPROVED** [review]

**Pull request merged**
