### PR TITLE
Clean up Attachment examples

### PR DESCRIPTION
**Pull request by Hirse**
* Switch all examples to FunctionComponents
* Focus examples on one thing each

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4db219d06e9450976364a3f8af4109ae48320237'>4db219d06e9450976364a3f8af4109ae48320237</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by ling1726** [comment]
Is hover expected to be changed ? 

image

**Comment by Hirse** [comment]
> Is hover expected to be changed ?
> 
> image

Yes, only Attachments marked as `actionable` should have a hover effect.

**Comment by Hirse** [comment]
@ling1726 Could you take another look please?

**Comment by ling1726** [comment]
I'm still confused why some examples with only one attachment now have two. It makes it hard to review the screenshot:
image

**Comment by Hirse** [comment]
> I'm still confused why some examples with only one attachment now have two. It makes it hard to review the screenshot: image
> 
> In this case we should increase the number of screenshot tests

This test now has two to see the distinction between `actionable` and `actionable and action`.

**Comment by Hirse** [comment]
> I'm still confused why some examples with only one attachment now have two. It makes it hard to review the screenshot: image
> 
> In this case we should increase the number of screenshot tests

This test now has two to see the distinction between `actionable` and `actionable and action`.

**Pull request closed without merging**
