### PR TITLE
Introduce exportman and initial config

### PR DESCRIPTION
**Pull request by webpro**
## Current Behavior

Looking at the size of this project, it's in a pretty good shape when it comes to unused files and exports.

## New Behavior

However, nothing is perfect 💯 

## Related Issue(s)

N/A

## Introduction

Please allow me to introduce a new tool called "exportman" that may help in this repository. It helps with maintenance and refactorings by reporting unused files and exports. Let me give a quick example:

```
❯ yarn exportman --config exportman.json --cwd packages/fluentui/react-northstar --onlyFiles
src/themes/teams-high-contrast/components/Menu/menuItemIndicatorVariables.ts
src/themes/teams/components/List/listItemEndMediaVariables.ts
src/themes/teams/components/Menu/menuItemIndicatorVariables.ts
src/themes/teams/components/Skeleton/skeletonAvatarVariables.ts
```

When looking into it, these results seem pretty accurate to me. Let's take another example:

```
❯ yarn exportman --config exportman.json --cwd packages/fluentui/react-northstar --onlyExports
includes                     src/components/Debug/utils.ts
PillContext                  src/components/Pill/pillContext.ts
easyEase                     src/themes/teams/animations/timingFunctions.ts
maxEasyEase                  src/themes/teams/animations/timingFunctions.ts
decelerateMin                src/themes/teams/animations/timingFunctions.ts
decelerateMid                src/themes/teams/animations/timingFunctions.ts
accelerateMin                src/themes/teams/animations/timingFunctions.ts
accelerateMid                src/themes/teams/animations/timingFunctions.ts
isValidColor                 src/themes/teams/colors.ts
availableColors              src/themes/teams/colors.ts
labelColorAreas              src/themes/teams/components/Avatar/avatarVariables.ts
menuColorAreas               src/themes/teams/components/Carousel/carouselNavigationVariables.ts
formFieldColorAreas          src/themes/teams/components/Form/formFieldVariables.ts
formMessageColorAreas        src/themes/teams/components/Form/formMessageVariables.ts
headerDescriptionColorAreas  src/themes/teams/components/Header/headerDescriptionVariables.ts
headerColorAreas             src/themes/teams/components/Header/headerVariables.ts
underlinedItem               src/themes/teams/components/Menu/menuItemStyles.ts
segmentColorAreas            src/themes/teams/components/Segment/segmentVariables.ts
getSizeStyles                src/themes/teams/components/Status/statusStyles.ts
iconColorAreas               src/themes/teams/components/SvgIcon/svgIconVariables.ts
textColorAreas               src/themes/teams/components/Text/textVariables.ts
repoURL                      src/utils/constants.ts
docSiteUrl                   src/utils/constants.ts
round                        src/utils/fontSizeUtility.ts
getDocumentRemSize           src/utils/fontSizeUtility.ts
mergeBooleanValues           src/utils/mergeProviderContexts.ts
mergePerformanceOptions      src/utils/mergeProviderContexts.ts
getRenderer                  src/utils/mergeProviderContexts.ts
getParentNode                src/utils/positioner/getScrollParent.ts
```

OK, one more to also see how to target individual packages using the `--cwd` argument:

```
❯ yarn exportman --config exportman.json --cwd packages/web-components/
--- UNUSED FILES (0)
N/A
--- UNUSED EXPORTS (7)
Calendar                  src/calendar/index.ts
numberFieldFilledStyles   src/number-field/number-field.styles.ts
searchFilledStyles        src/search/search.styles.ts
selectStealthStyles       src/select/select.styles.ts
textAreaFilledStyles      src/text-area/text-area.styles.ts
textFieldFilledStyles     src/text-field/text-field.styles.ts
expandCollapseButtonSize  src/tree-item/tree-item.styles.ts
--- UNUSED TYPES (1)
PaletteRGBOptions  interface  src/color/palette.ts
--- UNUSED NAMESPACE MEMBERS (210)
accordionItemStyles              src/accordion/accordion-item/index.ts
accordionStyles                  src/accordion/index.ts
anchorStyles                     src/anchor/index.ts
Anchor                           src/anchor/index.ts
AnchorAppearance                 src/anchor/index.ts
...
```

Note that this project uses namespace imports and exports quite extensively, so this category may or may not always be helpful when using exportman. There are flags to report only specific categories of issues, though.

Such results as shown hopefully help when refactoring and cleaning up the various packages in this repo. Just scratching the surface here, there are more ways to start using this and I'm eager to continue its development.

I've included some basic configuration in this PR for an impression and to get started:

```json
{
  "packages/fluentui/react-northstar": {
    "entryFiles": ["src/index.ts"],
    "filePatterns": ["src/**/*.ts"]
  },
  "packages/*": {
    "entryFiles": ["src/index.ts", "src/**/*.spec.ts"],
    "filePatterns": [
      "src/**/*.ts",
      "!**/*.stories.ts",
      "!**/__test__",
      "!**/*.d.ts",
      "!src/_docs",
      "!src/index-rollup.ts"
    ]
  }
}
```

Also see https://github.com/webpro/exportman for more details. I'm happy to hear whether you'd like to discuss this going forward, or in case you may have any questions or feedback! Have a great day.

### CODE REVIEW

**Comment by webpro** [comment]
Upgraded to the latest version. One of the updates is a non-zero exit code for unused files, so exportman could be used in CI. And then some, feel free to read the docs at https://github.com/webpro/exportman

**Review by Hotell — CHANGES_REQUESTED** [review]
Hey, 

thanks for your initiative! unfortunately ATM we don't have capacity to accommodate such tooling. We might re-evaluate in the future. 

cheers

**Comment by webpro** [comment]
Coincidentally, I was just migrating this from "exportman" to "knip" (the former didn't cover that it also supports unused and unlisted dependencies).

For instance, when running this command we will now find that `@babel/runtime` is indeed not a used production dependency, as it should be moved to the `devDependencies`.

```
❯ yarn knip --cwd packages/fluentui/react-northstar --include files,dependencies
--- UNUSED FILES (4)
src/themes/teams-high-contrast/components/Menu/menuItemIndicatorVariables.ts
src/themes/teams/components/List/listItemEndMediaVariables.ts
src/themes/teams/components/Menu/menuItemIndicatorVariables.ts
src/themes/teams/components/Skeleton/skeletonAvatarVariables.ts
--- UNUSED DEPENDENCIES (1)
@babel/runtime
```

Feel free to close this PR. I am grateful for using this project as a nice workload for this new tool. Cheers!

**Comment by layershifter** [comment]
Closing for housekeeping as there is no agreement to introduce new tooling 🏡

**Pull request closed without merging**
