### PR TITLE
Add fluent2-theme to v8

### LINKED ISSUE #25981: Update Fluent v8 with Fluent 2 theme
A partner team has provided a custom theme for v8 that makes components follow the Fluent 2 design.
We need to integrate this code into Fluent v8 to allow customers to make v8 look like v9. This will help those migrating to v9 as well as those that want the latest design without migrating yet.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Changes
- New fluent2-theme package provide Fluent2WebLight and Fluent2WebDark themes
- New package follows conventions from azure-themes and theme-samples packages
- New package is NOT reexported from fluentui/react and will need to be added by callers to their projects
- Updated the theme dropdown in the public-docsite to include the new themes
- Updated the theme dropdown to have a wider width to accomodate the longer theme names.
- Updated the Themes documentation to explain the addition of the new themes.

## Related Issue(s)

* Fixes #25981

## Screenshots

image

image

image

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/baf93e56255ce8136a965a7304d7d5bcc0042384'>baf93e56255ce8136a965a7304d7d5bcc0042384</a></sub>
<div id="bundleSizeComment9423"/>

**Review by JustSlone — APPROVED** [review]
Looks good, I like the approach of shipping it as an independent theme

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Avatar-mount_base.html">1550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Avatar-mount.html">1618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Button-mount_base.html">1114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Button-mount.html">1166</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProvider-mount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProvider-mount.html">1935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-mount_base.html">774</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-mount.html">770</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">735</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">759</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">782</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/MakeStyles-mount_base.html">2340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/MakeStyles-mount.html">2303</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Persona-mount_base.html">3662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/Persona-mount.html">3590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/SpinButton-mount_base.html">3019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test-react-components/SpinButton-mount.html">3089</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount_base.html">90241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount.html">49888</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/BaseButton-mount_base.html">1066</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/BaseButton-mount.html">1112</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Breadcrumb-mount_base.html">2642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Breadcrumb-mount.html">2695</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Checkbox-mount_base.html">2404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Checkbox-mount.html">2499</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/CheckboxBase-mount_base.html">2127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/CheckboxBase-mount.html">2123</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ChoiceGroup-mount_base.html">4098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ChoiceGroup-mount.html">4376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ComboBox-mount_base.html">1135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ComboBox-mount.html">1181</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/CommandBar-mount_base.html">8768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/CommandBar-mount.html">8590</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ContextualMenu-mount_base.html">10489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ContextualMenu-mount.html">11104</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DefaultButton-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DefaultButton-mount.html">1258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRow-mount_base.html">3332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRow-mount.html">3328</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRowFast-mount_base.html">3481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRowFast-mount.html">3541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRowNoStyles-mount_base.html">3392</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DetailsRowNoStyles-mount.html">3096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Dialog-mount_base.html">3013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Dialog-mount.html">2738</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DocumentCardTitle-mount_base.html">543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/DocumentCardTitle-mount.html">542</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Dropdown-mount_base.html">2894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Dropdown-mount.html">3083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/FocusTrapZone-mount_base.html">1788</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/FocusTrapZone-mount.html">1841</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/FocusZone-mount_base.html">1720</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/FocusZone-mount.html">1801</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-mount_base.html">1677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-mount.html">2056</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-virtual-rerender_base.html">1069</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-virtual-rerender.html">987</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedList-virtual-rerender-with-unmount.html">1522</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-mount_base.html">527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-mount.html">504</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-virtual-rerender_base.html">490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-virtual-rerender.html">476</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">497</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/IconButton-mount_base.html">1692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/IconButton-mount.html">1728</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Label-mount_base.html">650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Label-mount.html">680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Layer-mount_base.html">4013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Layer-mount.html">3838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Link-mount_base.html">760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Link-mount.html">744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/MenuButton-mount_base.html">1659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/MenuButton-mount.html">1492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/MessageBar-mount_base.html">2180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/MessageBar-mount.html">2150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Nav-mount_base.html">2876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Nav-mount.html">2957</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/OverflowSet-mount_base.html">1283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/OverflowSet-mount.html">1219</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Panel-mount_base.html">2345</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Panel-mount.html">2266</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Persona-mount_base.html">1250</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Persona-mount.html">1179</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Pivot-mount_base.html">1626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Pivot-mount.html">1551</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/PrimaryButton-mount_base.html">1538</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/PrimaryButton-mount.html">1395</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Rating-mount_base.html">6174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Rating-mount.html">6217</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SearchBox-mount_base.html">1387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SearchBox-mount.html">1356</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Shimmer-mount_base.html">2661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Shimmer-mount.html">2563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Slider-mount_base.html">1911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Slider-mount.html">1955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SpinButton-mount_base.html">4241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SpinButton-mount.html">4364</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Spinner-mount_base.html">777</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Spinner-mount.html">708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SplitButton-mount_base.html">2902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SplitButton-mount.html">2860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Stack-mount_base.html">763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Stack-mount.html">740</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/StackWithIntrinsicChildren-mount_base.html">2094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/StackWithIntrinsicChildren-mount.html">2080</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/StackWithTextChildren-mount_base.html">4396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/StackWithTextChildren-mount.html">4339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SwatchColorPicker-mount_base.html">9586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/SwatchColorPicker-mount.html">9479</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TagPicker-mount_base.html">2430</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TagPicker-mount.html">2527</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount_base.html">90241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount.html">49888</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TeachingBubble-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Text-mount_base.html">724</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Text-mount.html">706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TextField-mount_base.html">1495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/TextField-mount.html">1472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-mount_base.html">1472</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-mount.html">1405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-virtual-rerender_base.html">1067</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-virtual-rerender.html">952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Toggle-mount_base.html">1038</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/Toggle-mount.html">1040</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/buttonNative-mount_base.html">493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25982/perf-test/buttonNative-mount.html">525</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 FluentUI-v0 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25982&commitId=aa97250e24acfff2ca687868a5ceb9ee01bace3d&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1259 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Chat.Chat Playground.chromium.png|1798| Changed|
|Video.Video Example.chromium.png|14| Changed|

</details>


<div id="vrtCommentFluentUI-v0"/>

**Review by micahgodbolt — APPROVED** [review]

**Pull request merged**
