### PR TITLE
Sankey Diagram: Improving generated aria-label

### PR DESCRIPTION
**Pull request by StarTether**
## Previous Behavior

When the `aria-label` is generated for nodes, it generates text like:
 - `link from192.168.42.72toinboxwith weight80`
 - `link frominboxtoClickedwith weight30`
 - `node192.168.42.72with weight80`
Those are unintelligible and are likely to be garbled by a screen reader.

## New Behavior

Those same kinds of strings are now generated as:
- `link from 192.168.42.72 to inbox with weight 80`
- `link from inbox to Clicked with weight 30`
- `node 192.168.42.72 with weight 80`

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/27ca189bc2fde6aade956712c1f87845296981bd'>27ca189bc2fde6aade956712c1f87845296981bd</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by AtishayMsft** [comment]
Some snapshots seem to be not updated. Can you check.
image

image

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
