### PR TITLE
Add explicit children prop to Window Provider

### PR DESCRIPTION
**Pull request by micahgodbolt**
We bumped window provider to support React 18, but it seems it wasn't used in any of the components we tested, so we didn't notice the typing error here.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4804edca42166453926aed4bc0fcda0f06dbdac7'>4804edca42166453926aed4bc0fcda0f06dbdac7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/BaseButton-mount_base.html">1205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/BaseButton-mount.html">1213</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Breadcrumb-mount_base.html">2841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Breadcrumb-mount.html">2840</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Checkbox-mount_base.html">2630</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Checkbox-mount.html">2712</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/CheckboxBase-mount_base.html">2391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/CheckboxBase-mount.html">2353</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ChoiceGroup-mount_base.html">4338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ChoiceGroup-mount.html">4472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ComboBox-mount_base.html">1184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ComboBox-mount.html">1216</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/CommandBar-mount_base.html">9437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/CommandBar-mount.html">9369</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ContextualMenu-mount_base.html">13268</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ContextualMenu-mount.html">13126</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DefaultButton-mount_base.html">1394</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DefaultButton-mount.html">1364</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRow-mount_base.html">3252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRow-mount.html">3259</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRowFast-mount_base.html">3220</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRowFast-mount.html">3385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRowNoStyles-mount_base.html">3068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DetailsRowNoStyles-mount.html">3080</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Dialog-mount_base.html">2920</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Dialog-mount.html">3039</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DocumentCardTitle-mount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/DocumentCardTitle-mount.html">588</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Dropdown-mount_base.html">3133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Dropdown-mount.html">3193</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/FocusTrapZone-mount_base.html">1963</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/FocusTrapZone-mount.html">1923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/FocusZone-mount_base.html">1935</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/FocusZone-mount.html">2050</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-mount_base.html">47659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-mount.html">52592</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-virtual-rerender_base.html">22256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-virtual-rerender.html">22435</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">81176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedList-virtual-rerender-with-unmount.html">82057</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-mount_base.html">556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-mount.html">563</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-virtual-rerender_base.html">540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-virtual-rerender.html">541</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">572</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/IconButton-mount_base.html">1868</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/IconButton-mount.html">1822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Label-mount_base.html">759</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Label-mount.html">786</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Layer-mount_base.html">4222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Layer-mount.html">4194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Link-mount_base.html">868</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Link-mount.html">865</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/MenuButton-mount_base.html">1624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/MenuButton-mount.html">1600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/MessageBar-mount_base.html">2411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/MessageBar-mount.html">2351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Nav-mount_base.html">3078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Nav-mount.html">3081</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/OverflowSet-mount_base.html">1400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/OverflowSet-mount.html">1402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Panel-mount_base.html">2549</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Panel-mount.html">2509</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Persona-mount_base.html">1299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Persona-mount.html">1277</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Pivot-mount_base.html">1517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Pivot-mount.html">1533</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/PrimaryButton-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/PrimaryButton-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Rating-mount_base.html">6971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Rating-mount.html">7079</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SearchBox-mount_base.html">1490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SearchBox-mount.html">1513</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Shimmer-mount_base.html">2961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Shimmer-mount.html">3039</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Slider-mount_base.html">2124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Slider-mount.html">2130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SpinButton-mount_base.html">4645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SpinButton-mount.html">4270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Spinner-mount_base.html">829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Spinner-mount.html">855</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SplitButton-mount_base.html">2834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SplitButton-mount.html">2889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Stack-mount_base.html">870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Stack-mount.html">884</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/StackWithIntrinsicChildren-mount_base.html">2414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/StackWithIntrinsicChildren-mount.html">2278</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/StackWithTextChildren-mount_base.html">4949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/StackWithTextChildren-mount.html">4984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SwatchColorPicker-mount_base.html">9559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/SwatchColorPicker-mount.html">9566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TagPicker-mount_base.html">2364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TagPicker-mount.html">2311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TeachingBubble-mount_base.html">75056</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TeachingBubble-mount.html">74744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Text-mount_base.html">818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Text-mount.html">844</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TextField-mount_base.html">1568</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/TextField-mount.html">1655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-mount_base.html">1444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-mount.html">1458</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-virtual-rerender_base.html">1140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-virtual-rerender.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2003</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Toggle-mount_base.html">1129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/Toggle-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/buttonNative-mount_base.html">539</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27117/perf-test/buttonNative-mount.html">551</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by TristanWatanabe — APPROVED** [review]

**Review by sopranopillow — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

**Review by Hotell — APPROVED** [review]
can we add team to owners of this pacakge so fluent admin approval wont be needed in future ? ty

**Pull request merged**
