### PR TITLE
fix: DataGridSelection cell should focus on input, not cell

### PR DESCRIPTION
**Pull request by ling1726**
Due to bugs in screenreaders such as https://github.com/FreedomScientific/VFO-standards-support/issues/615 the better experience is to focus on the `input` itself so that selection status is accounced.

Bumps tabster to get a fix for https://github.com/microsoft/tabster/issues/211

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                          |        Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------- | --------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                 |        `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr> |        `554 B`<br />`348 B` |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>   |  `3.153 kB`<br />`1.299 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                    | `23.357 kB`<br />`7.361 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                      | `24.247 kB`<br />`7.643 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                    | `24.001 kB`<br />`7.049 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                              | `16.515 kB`<br />`5.921 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                    | `10.836 kB`<br />`4.283 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                    |   `9.394 kB`<br />`3.88 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                      | `11.862 kB`<br />`4.885 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                            | `11.004 kB`<br />`4.188 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                 | `10.697 kB`<br />`3.938 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                 | `19.868 kB`<br />`7.432 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                              | `20.013 kB`<br />`6.446 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                     | `11.838 kB`<br />`4.625 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                   |  `15.148 kB`<br />`5.06 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>     |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>               | `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>             | `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                    |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7cfaf78c93f1408c633c612939bf1a1305d7fc76'>7cfaf78c93f1408c633c612939bf1a1305d7fc76</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Avatar-mount_base.html">1224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Avatar-mount.html">1332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Button-mount_base.html">867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Button-mount.html">925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProvider-mount_base.html">1526</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProvider-mount.html">1531</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-mount_base.html">628</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-mount.html">611</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">600</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">634</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/MakeStyles-mount_base.html">1869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/MakeStyles-mount.html">1933</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Persona-mount_base.html">3022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/Persona-mount.html">2997</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/SpinButton-mount_base.html">2541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test-react-components/SpinButton-mount.html">2458</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount_base.html">1954</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount.html">1975</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/BaseButton-mount_base.html">1185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/BaseButton-mount.html">1167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Breadcrumb-mount_base.html">2933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Breadcrumb-mount.html">2973</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Checkbox-mount_base.html">2607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Checkbox-mount.html">2635</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/CheckboxBase-mount_base.html">2357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/CheckboxBase-mount.html">2360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ChoiceGroup-mount_base.html">4332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ChoiceGroup-mount.html">4405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ComboBox-mount_base.html">1239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ComboBox-mount.html">1248</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/CommandBar-mount_base.html">9643</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/CommandBar-mount.html">9604</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ContextualMenu-mount_base.html">11221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ContextualMenu-mount.html">11247</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DefaultButton-mount_base.html">1376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DefaultButton-mount.html">1363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRow-mount_base.html">3569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRow-mount.html">3528</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRowFast-mount_base.html">3609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRowFast-mount.html">3551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRowNoStyles-mount_base.html">3463</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DetailsRowNoStyles-mount.html">3431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Dialog-mount_base.html">3075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Dialog-mount.html">3080</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DocumentCardTitle-mount_base.html">572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/DocumentCardTitle-mount.html">581</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Dropdown-mount_base.html">3217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Dropdown-mount.html">3210</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusTrapZone-mount_base.html">1983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusTrapZone-mount.html">2013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount_base.html">1954</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount.html">1975</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/FocusZone-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-mount_base.html">1862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-mount.html">2174</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-virtual-rerender_base.html">1127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-virtual-rerender.html">1140</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedList-virtual-rerender-with-unmount.html">1657</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-mount_base.html">569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-mount.html">566</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-virtual-rerender_base.html">530</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-virtual-rerender.html">548</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">566</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">564</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/IconButton-mount_base.html">1874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/IconButton-mount.html">1906</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Label-mount_base.html">728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Label-mount.html">734</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Layer-mount_base.html">4338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Layer-mount.html">4303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Link-mount_base.html">826</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Link-mount.html">828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/MenuButton-mount_base.html">1667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/MenuButton-mount.html">1646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/MessageBar-mount_base.html">2327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/MessageBar-mount.html">2332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Nav-mount_base.html">3255</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Nav-mount.html">3266</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/OverflowSet-mount_base.html">1370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/OverflowSet-mount.html">1373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Panel-mount_base.html">2578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Panel-mount.html">2552</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Persona-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Persona-mount.html">1320</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Pivot-mount_base.html">1646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Pivot-mount.html">1610</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/PrimaryButton-mount_base.html">1507</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/PrimaryButton-mount.html">1537</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Rating-mount_base.html">6957</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Rating-mount.html">6906</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SearchBox-mount_base.html">1511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SearchBox-mount.html">1507</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Shimmer-mount_base.html">2893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Shimmer-mount.html">2851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Slider-mount_base.html">2056</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Slider-mount.html">2122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SpinButton-mount_base.html">4785</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SpinButton-mount.html">4678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Spinner-mount_base.html">794</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Spinner-mount.html">795</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SplitButton-mount_base.html">3102</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SplitButton-mount.html">3098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Stack-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Stack-mount.html">830</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/StackWithIntrinsicChildren-mount_base.html">2362</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/StackWithIntrinsicChildren-mount.html">2344</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/StackWithTextChildren-mount_base.html">4813</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/StackWithTextChildren-mount.html">4819</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SwatchColorPicker-mount_base.html">10374</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/SwatchColorPicker-mount.html">10488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TagPicker-mount_base.html">2622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TagPicker-mount.html">2636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TeachingBubble-mount_base.html">89669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TeachingBubble-mount.html">90211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Text-mount_base.html">800</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Text-mount.html">799</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TextField-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/TextField-mount.html">1582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-mount_base.html">1515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-mount.html">1515</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-virtual-rerender_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-virtual-rerender.html">1068</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2139</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2164</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Toggle-mount_base.html">1099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/Toggle-mount.html">1088</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/buttonNative-mount_base.html">534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26076/perf-test/buttonNative-mount.html">550</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Review by micahgodbolt — APPROVED** [review]

**Review by layershifter — APPROVED** [review]

**Pull request merged**
