### PR TITLE
fix: Pad in slider so the thumb does not render outside the bounds of the root element

### LINKED ISSUE #25313: [Bug]: Slider's thumb extends past the edges of the control
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-field-sliderfield--default

## Actual Behavior
The thumb of Slider extends beyond the bounds of its root, which causes it to appear misaligned with a label or other form controls:
image

## Expected Behavior
The slider should be aligned with the edge of its root. Perhaps the track needs to be padded in, so the thumb doesn't extend past the end when it is at 0?

Note: This bug is logged based on a comment in a Field VR test PR: https://github.com/microsoft/fluentui/pull/25263#issuecomment-1282865440

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by behowell**
## Current Behavior

The thumb of Slider extends beyond the bounds of its root, which causes it to appear misaligned with a label or other form controls:
image

## New Behavior

Add padding to the edges of slider, so the track is now inset by half of the thumb width. The edges of the thumb will never extend past the bounds of the root element.

image

Preview: https://fluentuipr.z22.web.core.windows.net/pull/25378/public-docsite-v9/storybook/index.html?path=/docs/components-slider--default

## Related Issue(s)

* Fixes #25313

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/Avatar-mount_base.html">1330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/Avatar-mount.html">1303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/Button-mount_base.html">942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/Button-mount.html">928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProvider-mount_base.html">1606</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProvider-mount.html">1569</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-mount_base.html">633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-mount.html">643</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">600</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">617</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/MakeStyles-mount_base.html">1871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/MakeStyles-mount.html">1901</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/SpinButton-mount_base.html">2506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25378/perf-test-react-components/SpinButton-mount.html">2502</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                   Change |
| :----------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr> | `31.805 kB`<br />`10.085 kB` | `32.729 kB`<br />`10.253 kB` | `924 B` <br />`168 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |   `62.94 kB`<br />`17.663 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.603 kB`<br />`52.909 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.446 kB`<br />`11.033 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7733f95a5a23ec57c4be1e2353a21fc391d8374d'>7733f95a5a23ec57c4be1e2353a21fc391d8374d</a></sub>
<div id="bundleSizeComment9423"/>

**Review by micahgodbolt — APPROVED** [review]

**Comment by spmonahan** [comment]
I see two small issues with Screener.

1. The vertical RTL story is cut off. This was case before this PR so I don't think it's a blocker, though it should be fixed.
slider_vertical_rtl
2. None of the VR tests actually verify the change. This issue is only apparent when the slider thumb is at the left-most values (in LTR; right-most in RTL) but all of the VR tests have a value toward the middle. I think we should add a test where the slider value is such that the thumb would show this issue were it not fixed.

**Comment by behowell** [comment]
@spmonahan I fixed the VR tests, and added some 0% and 100% ones as well, to test this particular change. The fixes to the VR tests resulted in some extra test-only padding changes.

**Review by khmakoto — APPROVED** [review]

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
