### PR TITLE
RFC: Docs Component Anatomy & Audit

### PR DESCRIPTION
**Pull request by levithomason**
# Introduction

This PR introduces an automatic anatomy highlighter for stories. It is a prototype to demonstrate the usefulness only.

Features:
1. Automatically highlight components and slots, similar to Fluent 2 design specs
2. Highlight anatomy in the story on hover of the items in the named list
3. Handle moving anatomy and state updates

Usefulness:
1. Quickly show user what components and slots are in use
2. Show the placement and nesting of components and slots instantly
3. Help contributors maintain consistent patterns by revealing anatomy

Authors: @levithomason @miroslavstastny 

# 💬 Discussions 

#### Integration

What is the best way to integrate this capability?
- [ ] In our development flow?
- [ ] In our public docs?

#### Consistency

The audit revealed mostly inconsistencies in:
- [ ] DOM Structure
- [ ] Component naming conventions
- [ ] Class name conventions
- [ ] Composition patterns

We should answer:
1. Do we care about consistency?
2. Is inconsistency a problem worth solving?
3. Should we we automate conformance?

We propose yes to all of the above as it is necessary to enable 2nd layer tooling and assistance, such as the anatomy viewer. Consistency is also required for any future design tools, token explorers, etc. which would sit on top of our patterns.

**Composition Patterns**

We should reach a conclusion on how to properly compose custom components.
1. What is the pattern for using hooks?
6. What is the pattern for reusing component A in component B?

# 📖 Collection Component Docs 

There are several inconsistencies and unresolved patterns with collection components.

**RadioGroup, Radio** has separate top level documentation pages when Radio is meant to be used inside of a RadioGroup. This conflicts with other components like Combobox, Dropdown, TabList, MenuList, etc. which do not have documentation pages for their subcomponents (Option, MenuItem, etc).

**Card** is an example of a component which uses folders to nest separate documentation for subcomponents, even though those subcomponents are not usable outside of a Card.

The **Breadcrumb** collection has a similar issue to Card in that it documents subcomponents that are unusable outside the Breadcrumb. However, it also does so using a separate top level story for each sub component vs a folder.

**Virtualizer** has 3 separate top level components, which are functional on their own, and are documented as 3 separate top level stories. However, this conflicts (in part) with Tree which uses a folder to group similar top level stories.

**Tree** itself combines several of the above issues as it uses a folder to organize its group of stories but also includes a top level story for `TreeItem` which is not usable on its own.

# 📸 Anatomy Screenshots  

We've included only one screenshot for each component, however, the prototype on this branch applied the highlighting to all stories. We also included any extra stories for a given component if it had issues with the anatomy.

### Accordion

image

When you click the Accordion Header, it opens and the anatomy selectors automatically update. They are currently prototyped on a RAF. Notice `4` the AccordionPanel is now highlighted.

image

### Avatar

Badge story shown. Notice the selection boxes only grab the first instance in a list.

image

On hover of the list of anatomy, all instances are highlighted. Here we highlight **`b` badge** and all Avatar badges get the same highlight as the anatomy list being hovered:

image

### AvatarGroup

Notice since the AvatarGroup is a component itself, the `Avatar` anatomy is not listed, only the `AvatarGroup` anatomy. This is by design so each story focuses only on the anatomy relevant to the story itself, not every component used inside the story.

image

### Badge

image

image

### Counter Badge

**💬 Discuss** `CounterBadge` composes `Badge` and the current prototype only shows components which explicitly match the component page being shown. So, `Badge` is excluded since this is the `CounterBadge` page.

```html
<div class="fui-Badge r1l7mb74 fui-CounterBadge ___g1d9dq0_1moluvk ffp7eso f1phragk">5</div>
```

image

### PresenceBadge

The final implementation may want to consider drawing lines from the indicator dot to the anatomy box to prevent obscuring the component like this example does.

image

### Button

image

### CompoundButton

image

### MenuButton

image

### SplitButton

image

### ToggleButton

image

### Card

image

### CardFooter

image

### CardHeader

This is a dense story with many examples of a single component implemented in various ways. The usefulness of the highlighting feature is shown in the video.

https://github.com/microsoft/fluentui/assets/5067638/669ffa8d-a02d-46af-964f-18436466ad01

### CardPreview
image

### Checkbox
image

### Combobox

**👁️  See** Collection Component Docs.

**💬 Discuss** This raises the topic of collection components (Combobox, Dropdown, RadioGroup, TabList). Our conventions for these vary in terms of structure, naming, and composition.

Combox does not follow Fluent UI React v9 naming patterns for its anatomy. It consists of:

```
Combobox
  Listbox
    OptionGroup
      OptionGroup__label
      Option
      Option
        Option__checkIcon
      ...
```

The anatomy view does not capture many configurable slots due to the naming and structure differences of this component.

image

> The prototype does follow portals, such as the listbox.

If the naming were to follow the `ComboBox*` pattern for components and `ComboBox*__*` pattern for slots, we might see something like this where each component/slot is a type of "Combobox":

image

### DataGrid

This is a dense view that is difficult to read on first glance, however, it is indicative of the component anatomy which is truly complex.

image

When hovering on various parts the anatomy is much more useful for understanding the structure than clicking through `tsx` files or looking at the source code.

https://github.com/microsoft/fluentui/assets/5067638/303abab0-6869-4f12-8316-f1f8e9d9f943

The anatomy tool does not highlight anything in the "Virtualization" story, however, upon inspecting this example is just using an iframe. So, the tool in this case is again useful as it is catching an issue in our docs. We likely should not be shipping stories that are iframe'd to other repos:

image

### Dialog

Note, the prototype doesn't provide and good experience for hovering over anatomy pieces when there is a backdrop.

image

### Divider

image

### Dropdown

**👁️  See** Collection Component Docs.

image

### Field

image

In this example it is immediately clear that the cat icon and input are custom elements as they have no anatomy annotation. The icon would be an easy element to assume to come from Fluent UI or at least have a slot for input icons. Without this tool, it is unclear what is custom and what is provided by Fluent UI.

image

### FluentProvider

image

### Image

image

### Input

image

### Label

image

### Link

image

### Menu

**👁️  See** Collection Component Docs.

image

>The `Menu` is not visible as it is only in the React Tree, not the DOM. The prototype requires the component or one of its slots to render a class to the DOM (`.fui-Component` or `.fui-Component__slot`) in order to show the anatomy on the left. This could be resolved by using the React Tree instead of the DOM as a source of truth for traversals.

image

### MenuList

**👁️  See** Collection Component Docs.

image

If we captured all `Menu*` named components, not just `MenuList*`, then the anatomy would look like this:

image

### Overflow

Overflow is a utility with no DOM, so anatomy annotations do not apply here.

image

### Persona

image

### Popover

image

### Portal

Nothing to see here, utility component only, no DOM.

image

### ProgressBar

image

### Radio

image

### RadioGroup

**👁️  See** Collection Component Docs.

image

### Select

**👁️  See** Collection Component Docs.

image

image

### Skeleton

image

### Slider

image

### SpinButton

image

### Spinner

image

### Switch

image

### Table

**👁️  See** DataGrid comments which also apply to Table.

image

### TabList

**👁️  See** Collection Component Docs.

image

### Text

image

### Textarea

image

### Toast

Even though it is useful, `Toaster` is included in the anatomy by a bug in the component name matcher. **Toast**er starts with `Toast`. This should technically be fixed in a final version as component anatomies that start with the currently viewed component name should not be included in the view, only actual subcomponents and slots.

image

### Toolbar

**👁️  See** Collection Component Docs.

The `Toolbar` story uses `Toolbar`, `ToolbarButton` and `ToolbarDivider` but only shows `Toolbar` in the anatomy as the other components do not follow the class name convention for composing components. They are missing `fui-Toolbar*` classes.

image

### Tooltip

image

## Compat Components

These components are v8 made to work with v9 styling and tokens, but do not follow v9 architecture.

### DatePicker

All v9 components are properly shown.

image

### Alert

image

image

### Breadcrumb

**👁️  See** `BreadcrumbButton` comment.

image

### BreadcrumbButton

**💬 Discuss** This should probably be combined into the `Breadcrumb` stories page. `BreadcrumbButton` is not usable on its own. There is one story, which shows the use of `Breadcrumb`, `BreadcrumbItem`, and `BreadcrumbButton` together.

As a separate issue, the story should be simplified to not include boilerplate for the "playground" type code around the story. There is no need to show the appearance and size in a single story, but it should be separate concise stories for each capability of the `BreadcrumbButton`.

Note, this type of finding and review is not a direct result of anatomy work, but it is due to the audit work that is required by the anatomy work. We should have a process for doing this type of audit regularly. At the least, it should be a step required for promoting preview components to proper components.

image

### BreadcrumbDivider

**👁️  See** `BreadcrumbButton` comment.

image

### BreadcrumbItem

**👁️  See** `BreadcrumbButton` comment.

image

### BreadcrumbLink

**👁️  See** `BreadcrumbButton` comment.

image

### Drawer

image

The prototype does not handle anatomy annotation labels well when a component is full-bleed (to the edge of the iframe area). This could be fixed by a smarter label placement algorithm which we did not do.

image

### InfoButton

image

### InfoLabel

image

### SearchBox

**💬 Discuss** The `contentBefore` slot is "missing" from the anatomy view. Why?

The SearchBox internally uses the `Input` component as its root. The `contentBefore` slot is passed through the SearchBox state on to `Input`'s props. However, since SearchBox does no special handling of the `contentBefore`, there is no SearchBox className added to this slot. Notice `contentAfter` which does appear in the anatomy, because SearchBox has special handling of this Input prop and adds a `SearchBox__contentAfter` className here.

Summary of findings:
- SearchBox uses Input as its root component
- SearchBox allows passing Input props through
- SearchBox state does not include all Input state keys
- SearchBox props do include all input props
- This means SearchBox render anatomy only has classes for its own slots and "customized" slots of Input, not all Input slots.

This raises a few questions about composition:
1. Do we allow root components to be extended vs. composing individual hooks together (useSearchBoxStyles composing useInputStyles)?
7. Should all slots carry the component's class name? Example, SearchBox contentBefore does not have `fui-SearchBox__contentBefore` because it is using this slot from Input and does not make any modifications to it.

Original PR comment: https://github.com/microsoft/fluentui/pull/28090#discussion_r1213448088

image

### Tree/flatTree

image

### Tree/Layouts

image

### Tree/Tree

**👁️  See** Collection Component Docs.

image

### Tree/TreeItem

**💬 Discuss** `TreeItem` has a duplicate className of `fui-TreeItemLayout__expandIcon fui-TreeItemLayout__expandIcon` on the expandIcon slot. We could not find why. This is relatively low consequence but still probably a bug we should fix.
1. Do we have other components with this issue?
2. Do we have a way of catching this?

image

### Virtualizer

On first glance, the anatomy view is not useful. On reconsideration, it does reveal how the virtualizer works.

image

You can see how the `before`, `after`, and `afterContainer` are used to generate the list on scroll. This would be useful for debugging and for developing features such as loading indicators or placeholders:

<div float="left">
  image

  image
</div>

You can also see that the `Virtualizer` does not render anything to the DOM, as indicated by the grayed out `(?) Virtualizer` label in the list of anatomy.

image

### VirtualizerScrollView

**💬 Discuss** Nothing shows in the view for multiple reasons:
1. The className for VirtualizerScrollView breaks our pattern of `fui-VirtualizerScrollView` and uses `fui-Virtualizer-Scroll-View`.
2. When composing `Virtualizer` we don't currently follow a predictable pattern or convention, so the anatomy viewer fails to show all the composed components/slots.

image

#### 1 - Class Name

```tsx
// useVirtualizerScrollViewStyles.styles.ts line 7
const virtualizerScrollViewClassName = 'fui-Virtualizer-Scroll-View';
```

Fixing the className to use `fui-VirtualizerScrollView`, we get a `container` slot visible. However, `VirtualizerScrollView` also composes `Virtualizer` but we don't see any of those components or slots.

image

#### 2 - Composition

Hacking the story and anatomy view to show all, we see this:

image

### VirtualizerScrollViewDynamic

**👁️  See** Preview Components `VirtualizerScrollView` discussion. This `VirtualizerScrollViewDynamic` component has identical patterns and issues.

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount.html">78</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount_base.html">14</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount.html">10</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Avatar-mount_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Avatar-mount.html">600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Button-mount_base.html">301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Button-mount.html">291</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Field-mount_base.html">1069</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Field-mount.html">1038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProvider-mount_base.html">637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProvider-mount.html">647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount.html">78</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">61</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">63</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">64</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">69</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount_base.html">14</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount.html">10</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/MakeStyles-mount_base.html">839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/MakeStyles-mount.html">854</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Persona-mount_base.html">1649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/Persona-mount.html">1580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/SpinButton-mount_base.html">1236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28326/perf-test-react-components/SpinButton-mount.html">1307</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `89.11 kB`<br />`25.236 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `83.764 kB`<br />`23.685 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |      `9.229 kB`<br />`3.9 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `11.402 kB`<br />`4.683 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |   `10.034 kB`<br />`4.248 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `65.162 kB`<br />`17.952 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `210.395 kB`<br />`58.717 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `36.395 kB`<br />`11.996 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.473 kB`<br />`2.196 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f1f4a835fe3fa20b7c80d2d049efdfcd62a61d8e'>f1f4a835fe3fa20b7c80d2d049efdfcd62a61d8e</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by spmonahan** [comment]
> 1. Do we care about consistency?
> 2. Is inconsistency a problem worth solving?
> 3. Should we we automate conformance?

We have conformance tests for [component class names](https://github.com/microsoft/fluentui/blob/master/packages/react-conformance/src/defaultTests.tsx#L266-L353) which align with component anatomy so I think we do care about consistency and we can automate it, though this analysis shows we have room to improve on this front 🙂

**Comment by layershifter** [comment]
Closing for housekeeping 🏡  Feel free to re-open 👍

**Pull request closed without merging**
