### PR TITLE
Switch from `node-sass` to `sass`

### PR DESCRIPTION
**Pull request by ecraig12345**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by ecraig12345** [comment]
Realized `just-scripts` is hardcoded to look for `node-sass`, so this doesn't work. 
https://github.com/microsoft/just/blob/master/packages/just-scripts/src/tasks/sassTask.ts#L31
https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=243285&view=logs&j=fd74590e-6928-5e99-f1e9-db18703a506f&t=9cad5233-5818-5d38-1a56-70f7b454b419&l=701

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>                                                      |    `2.836 kB`<br />`1.209 kB` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `74.792 kB`<br />`22.516 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `45.142 kB`<br />`13.111 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `20.895 kB`<br />`6.567 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.848 kB`<br />`6.883 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `21.951 kB`<br />`6.565 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `28.013 kB`<br />`8.059 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `33.508 kB`<br />`9.092 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `29.796 kB`<br />`8.665 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `36.268 kB`<br />`9.863 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |    `37.395 kB`<br />`8.68 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `53.619 kB`<br />`15.372 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `48.904 kB`<br />`14.089 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.686 kB`<br />`3.264 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |     `9.251 kB`<br />`3.78 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.658 kB`<br />`3.291 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox</abbr>                                                                              |    `6.817 kB`<br />`2.901 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `176.089 kB`<br />`49.113 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.601 kB`<br />`10.668 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.385 kB`<br />`5.539 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.109 kB`<br />`3.958 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |    `21.661 kB`<br />`7.18 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.371 kB`<br />`3.504 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.106 kB`<br />`4.507 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `105.852 kB`<br />`32.433 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `109.031 kB`<br />`32.897 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `96.787 kB`<br />`29.559 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |     `6.272 kB`<br />`2.17 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |    `23.21 kB`<br />`8.084 kB` |
| <samp>react-priority-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                      |   `10.606 kB`<br />`4.087 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |    `14.009 kB`<br />`5.25 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |   `16.562 kB`<br />`6.264 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |    `25.549 kB`<br />`8.25 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `16.459 kB`<br />`5.549 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `24.279 kB`<br />`8.001 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `10.797 kB`<br />`4.233 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.113 kB`<br />`4.576 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                              |   `20.602 kB`<br />`7.033 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                                        |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `29.676 kB`<br />`6.604 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |   `18.492 kB`<br />`5.296 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `42.837 kB`<br />`14.727 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/df80d6f3552e939c7eee343876251a873313139a'>df80d6f3552e939c7eee343876251a873313139a</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/Avatar-mount_base.html">1042</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/Avatar-mount.html">1061</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/Button-mount_base.html">642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/Button-mount.html">609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProvider-mount_base.html">2103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProvider-mount.html">2134</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-mount_base.html">317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-mount.html">316</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">273</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">330</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/MakeStyles-mount_base.html">1796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-react-components/MakeStyles-mount.html">1848</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
ChatDuplicateMessagesPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [279](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.08:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatDuplicateMessagesPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AccordionMinimalPerf.default | [157](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AccordionMinimalPerf.default.html) | [133](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.18:1
FormMinimalPerf.default | [419](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/FormMinimalPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.09:1
ListNestedPerf.default | [583](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListNestedPerf.default.html) | [537](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListNestedPerf.default_base.html) | 1.09:1
SkeletonMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SkeletonMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.07:1
BoxMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/BoxMinimalPerf.default.html) | [325](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.06:1
ImageMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ImageMinimalPerf.default.html) | [357](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [167](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TreeWith60ListItems.default.html) | [158](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
AnimationMinimalPerf.default | [544](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AnimationMinimalPerf.default.html) | [518](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.05:1
LayoutMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LayoutMinimalPerf.default.html) | [337](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [599](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/IconMinimalPerf.default.html) | [571](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
AttachmentMinimalPerf.default | [152](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AttachmentMinimalPerf.default.html) | [146](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.04:1
CardMinimalPerf.default | [549](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CardMinimalPerf.default.html) | [529](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.04:1
ListCommonPerf.default | [650](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListCommonPerf.default.html) | [623](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListCommonPerf.default_base.html) | 1.04:1
RadioGroupMinimalPerf.default | [448](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [432](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [239](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RefMinimalPerf.default.html) | [230](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [502](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TextAreaMinimalPerf.default.html) | [484](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [549](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonSlotsPerf.default.html) | [531](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ProviderMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SegmentMinimalPerf.default.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TextMinimalPerf.default.html) | [330](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
TooltipMinimalPerf.default | [1042](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TooltipMinimalPerf.default.html) | [1010](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.03:1
DividerMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DividerMinimalPerf.default.html) | [341](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [510](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListMinimalPerf.default.html) | [501](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [668](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LoaderMinimalPerf.default.html) | [658](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [2766](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CustomToolbarPrototype.default.html) | [2712](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [1089](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1081](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
CarouselMinimalPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CarouselMinimalPerf.default.html) | [468](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [299](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/FlexMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [852](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/MenuMinimalPerf.default.html) | [841](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1676](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1667](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [4409](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4357](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1948](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TableManyItemsPerf.default.html) | [1932](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [391](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TableMinimalPerf.default.html) | [386](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5708](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5689](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [751](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DialogMinimalPerf.default.html) | [749](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DropdownManyItemsPerf.default.html) | [693](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3018](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DropdownMinimalPerf.default.html) | [3025](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [625](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/PopupMinimalPerf.default.html) | [622](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ButtonMinimalPerf.default | [167](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonMinimalPerf.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [737](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatMinimalPerf.default.html) | [747](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
ChatWithPopoverPerf.default | [370](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatWithPopoverPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2693](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2716](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4161](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/EmbedMinimalPerf.default.html) | [4183](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
HeaderSlotsPerf.default | [729](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/HeaderSlotsPerf.default.html) | [739](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1281](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/InputMinimalPerf.default.html) | [1295](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [658](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/StatusMinimalPerf.default.html) | [665](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
ButtonOverridesMissPerf.default | [1487](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1518](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.98:1
HeaderMinimalPerf.default | [361](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/HeaderMinimalPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.98:1
ItemLayoutMinimalPerf.default | [1228](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1251](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.98:1
LabelMinimalPerf.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LabelMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.98:1
AlertMinimalPerf.default | [262](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AlertMinimalPerf.default.html) | [271](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.97:1
GridMinimalPerf.default | [315](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/GridMinimalPerf.default.html) | [324](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.97:1
PortalMinimalPerf.default | [172](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/PortalMinimalPerf.default.html) | [177](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.97:1
ProviderMergeThemesPerf.default | [1272](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1316](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.97:1
SliderMinimalPerf.default | [1677](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SliderMinimalPerf.default.html) | [1737](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.97:1
VideoMinimalPerf.default | [622](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/VideoMinimalPerf.default.html) | [640](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.97:1
ListWith60ListItems.default | [645](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListWith60ListItems.default.html) | [674](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.96:1
ReactionMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ReactionMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.96:1
TreeMinimalPerf.default | [794](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TreeMinimalPerf.default.html) | [827](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.96:1
AvatarMinimalPerf.default | [186](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AvatarMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.95:1
RosterPerf.default | [1096](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RosterPerf.default.html) | [1155](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/RosterPerf.default_base.html) | 0.95:1
ToolbarMinimalPerf.default | [933](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ToolbarMinimalPerf.default.html) | [978](https://fluentuipr.z22.web.core.windows.net/pull/22323/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9424"/>

**Pull request closed without merging**
