### PR TITLE
Cherry pick: Fix resizing of justified columns for constrained viewport widths

### LINKED ISSUE #15971: ​DetailsList: Resize columns behavior changed after strict mode fixes
### Environment Information

- **Package version(s)**: 7.149.4
- **Browser and OS versions**: Windows 10 + Edge

### Describe the issue:

The behavior of the header column of DetailsList changed when it was updated from v7.140.0 to v7.141.0.

7.141.0 or later
- Double-clicking on a column to AutoResize only allocates space in the display area and does not produce a horizontal scroll bar.
- Cannot view the contents that don't fit in the column.

7.140.0 or earlier
- Double-clicking on a column to AutoResize widens it out of the display area and produces a horizontal scroll bar.
- Can view the contents that doesn't fit in the column.

I want to keep the behavior as it was before 7.140.0, how should I set up the DetailsList?

### PR DESCRIPTION
**Pull request by sysofwan**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15971
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Cherrypick of PR #17374

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/BaseButton-mount_base.html">1018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/BaseButton-mount.html">1002</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Breadcrumb-mount_base.html">44405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Breadcrumb-mount.html">43789</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Checkbox-mount_base.html">1732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Checkbox-mount.html">1736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/CheckboxBase-mount_base.html">1463</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/CheckboxBase-mount.html">1425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ChoiceGroup-mount_base.html">5677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ChoiceGroup-mount.html">5587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ComboBox-mount_base.html">1003</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ComboBox-mount.html">1023</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/CommandBar-mount_base.html">8434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/CommandBar-mount.html">8358</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ContextualMenu-mount_base.html">15237</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/ContextualMenu-mount.html">15156</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DefaultButton-mount_base.html">1292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DefaultButton-mount.html">1289</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRow-mount_base.html">4176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRow-mount.html">4261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRowFast-mount_base.html">4305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRowFast-mount.html">4225</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRowNoStyles-mount_base.html">3976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DetailsRowNoStyles-mount.html">3927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Dialog-mount_base.html">1910</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Dialog-mount.html">1930</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DocumentCardTitle-mount_base.html">2025</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/DocumentCardTitle-mount.html">2003</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Dropdown-mount_base.html">2915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Dropdown-mount.html">2936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/FocusTrapZone-mount_base.html">1898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/FocusTrapZone-mount.html">1929</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/FocusZone-mount_base.html">2001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/FocusZone-mount.html">1918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/IconButton-mount_base.html">2012</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/IconButton-mount.html">2029</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Label-mount_base.html">374</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Label-mount.html">381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Layer-mount_base.html">2169</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Layer-mount.html">2164</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Link-mount_base.html">511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Link-mount.html">500</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/MenuButton-mount_base.html">1682</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/MenuButton-mount.html">1674</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/MessageBar-mount_base.html">2235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/MessageBar-mount.html">2215</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Nav-mount_base.html">3665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Nav-mount.html">3619</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/OverflowSet-mount_base.html">1560</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/OverflowSet-mount.html">1554</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Panel-mount_base.html">1624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Panel-mount.html">1597</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Persona-mount_base.html">946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Persona-mount.html">931</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Pivot-mount_base.html">1744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Pivot-mount.html">1712</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/PrimaryButton-mount_base.html">1592</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/PrimaryButton-mount.html">1582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Rating-mount_base.html">8614</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Rating-mount.html">9409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SearchBox-mount_base.html">1434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SearchBox-mount.html">1439</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Shimmer-mount_base.html">2930</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Shimmer-mount.html">2870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Slider-mount_base.html">1661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Slider-mount.html">1665</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SpinButton-mount_base.html">5514</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SpinButton-mount.html">5521</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Spinner-mount_base.html">432</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Spinner-mount.html">456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SplitButton-mount_base.html">3545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SplitButton-mount.html">3512</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Stack-mount_base.html">544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Stack-mount.html">544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/StackWithIntrinsicChildren-mount_base.html">1770</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/StackWithIntrinsicChildren-mount.html">1756</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/StackWithTextChildren-mount_base.html">5306</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/StackWithTextChildren-mount.html">5303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SwatchColorPicker-mount_base.html">11383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/SwatchColorPicker-mount.html">11420</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TagPicker-mount_base.html">3035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TagPicker-mount.html">3052</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TeachingBubble-mount_base.html">54555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TeachingBubble-mount.html">53952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Text-mount_base.html">462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Text-mount.html">472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TextField-mount_base.html">1532</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/TextField-mount.html">1527</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Toggle-mount_base.html">926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/Toggle-mount.html">917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/button-mount_base.html">121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18612/perf-test/button-mount.html">120</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by sysofwan** [comment]
@ThomasMichon Can you help review this? Simple cherry pick of PR #17374 to resolve #15971

**Comment by makislev** [comment]
@ThomasMichon Can we please get some attention on this PR? this is blocking us from opening a new feature to customers

**Review by ThomasMichon — APPROVED** [review]

**Comment by makislev** [comment]
@ThomasMichon thank you!!

**Comment by sysofwan** [comment]
@ecraig12345 can you help review the PR for cxe-red?

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
