### PR TITLE
Fix V9 Button focus inset box shadow for FireFox scaling

### LINKED ISSUE #29417: [Bug]: Button focus ring looks incorrect in Firefox
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-button-button--default#shape

## Actual Behavior
When tabbing buttons the focus ring is rendered incorrectly in Firefox.

button_firefox_focus_ring

## Expected Behavior
The focus ring should render correctly.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by Mitch-At-Work**
## Previous Behavior
Previously, in some instances of scaling on FireFox (including at 100%) - button border would not be uniform on focus (inset border box shadow)
image
image
image

## New Behavior
All button styles should now retain the 1px border + inset 2px box shadow on all browsers
image
image
image

## Related Issue(s)
- Fixes #29417

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Avatar-mount_base.html">673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Avatar-mount.html">648</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Button-mount_base.html">319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Button-mount.html">321</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Field-mount_base.html">1103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Field-mount.html">1149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProvider-mount_base.html">730</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProvider-mount.html">742</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-mount_base.html">90</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-mount.html">96</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">81</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">89</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/InfoButton-mount_base.html">16</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/InfoButton-mount.html">15</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/MakeStyles-mount_base.html">882</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/MakeStyles-mount.html">866</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Persona-mount_base.html">1795</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/Persona-mount.html">1723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/SpinButton-mount_base.html">1371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29441/perf-test-react-components/SpinButton-mount.html">1414</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `83.172 kB`<br />`23.078 kB` |  `83.236 kB`<br />`23.087 kB` |  `64 B` <br />`9 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |  `38.892 kB`<br />`10.882 kB` |  `38.956 kB`<br />`10.895 kB` | `64 B` <br />`13 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `46.247 kB`<br />`12.375 kB` |  `46.311 kB`<br />`12.389 kB` | `64 B` <br />`14 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `43.666 kB`<br />`12.26 kB` |   `43.73 kB`<br />`12.272 kB` | `64 B` <br />`12 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `51.68 kB`<br />`13.845 kB` |  `51.744 kB`<br />`13.857 kB` | `64 B` <br />`12 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `55.938 kB`<br />`12.783 kB` |  `56.002 kB`<br />`12.797 kB` | `64 B` <br />`14 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `68.748 kB`<br />`19.742 kB` |  `68.812 kB`<br />`19.756 kB` | `64 B` <br />`14 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `206.455 kB`<br />`59.319 kB` | `206.519 kB`<br />`59.333 kB` | `64 B` <br />`14 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `91.484 kB`<br />`26.485 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               |  `86.31 kB`<br />`24.946 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |  `12.074 kB`<br />`5.034 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |    `14.323 kB`<br />`5.8 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |  `13.031 kB`<br />`5.404 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `40.866 kB`<br />`13.546 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                              |    `6.503 kB`<br />`2.22 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6080e5644c19b7d3b5df0ca5316f6b73935ae5ba'>6080e5644c19b7d3b5df0ca5316f6b73935ae5ba</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by spmonahan** [comment]
Looks like there is another problem with offset in the Primary Button in Firefox.

Primary Button in Firefox

Windows 11, Firefox 118.0.1

**Comment by spmonahan** [comment]
Firefox and Safari on Mac are a little off

### Firefox
https://github.com/microsoft/fluentui/assets/93940821/f483fd2b-6840-4327-af74-e346601fab36

### Safari

https://github.com/microsoft/fluentui/assets/93940821/b23504f6-2fc2-4d75-8385-a53d2800bbb9

**Comment by Mitch-At-Work** [comment]
> Firefox and Safari on Mac are a little off
> 
> ### Firefox
>  firefox_mac.mov 
> ### Safari
>  safari_mac.mov

Where these same styles present on Safari prior to changes? If so I might move this to be Firefox specific to reduce impact.

Given this may be an issue with scaling on FF, it may require a bugfix to achieve this same style without adding or modifying divs.

**Comment by spmonahan** [comment]
> Were these same styles present on Safari prior to changes? If so I might move this to be Firefox specific to reduce impact.

Safari looks good prior to this change.

**Comment by Mitch-At-Work** [comment]
Firefox bug opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1857642

Moving this code to Firefox specific CSS

**Comment by Mitch-At-Work** [comment]
- Reduced FF CSS to be more specific so that we don't override other button rulesets.
- Used (-moz-appearance:button) for specificity, the rule for none exists in the same early FF browser version, but this is more specific to the components type.

**Review by spmonahan — APPROVED** [review]
Looks good in Firefox on Windows 11

**Pull request merged**
