### PR TITLE
Update GetStartedDevelopSimple.md

### PR DESCRIPTION
**Pull request by dhatGuy**
Fix typo

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Corrected a sentence

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/BaseButton-mount_base.html">976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/BaseButton-mount.html">995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Breadcrumb-mount_base.html">44591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Breadcrumb-mount.html">44684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Checkbox-mount_base.html">1730</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Checkbox-mount.html">1718</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/CheckboxBase-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/CheckboxBase-mount.html">1441</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ChoiceGroup-mount_base.html">5465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ChoiceGroup-mount.html">5473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ComboBox-mount_base.html">1003</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ComboBox-mount.html">1014</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/CommandBar-mount_base.html">8125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/CommandBar-mount.html">8196</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ContextualMenu-mount_base.html">15767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/ContextualMenu-mount.html">16152</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DefaultButton-mount_base.html">1264</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DefaultButton-mount.html">1257</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRow-mount_base.html">3846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRow-mount.html">3955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRowFast-mount_base.html">3983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRowFast-mount.html">3938</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRowNoStyles-mount_base.html">3643</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DetailsRowNoStyles-mount.html">3698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Dialog-mount_base.html">1622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Dialog-mount.html">1622</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DocumentCardTitle-mount_base.html">1931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/DocumentCardTitle-mount.html">1902</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Dropdown-mount_base.html">2816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Dropdown-mount.html">2839</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/FocusTrapZone-mount_base.html">1866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/FocusTrapZone-mount.html">1795</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/FocusZone-mount_base.html">1866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/FocusZone-mount.html">1911</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/IconButton-mount_base.html">1918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/IconButton-mount.html">1948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Label-mount_base.html">369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Label-mount.html">338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Layer-mount_base.html">2093</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Layer-mount.html">2106</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Link-mount_base.html">466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Link-mount.html">485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/MenuButton-mount_base.html">1623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/MenuButton-mount.html">1609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/MessageBar-mount_base.html">2170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/MessageBar-mount.html">2170</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Nav-mount_base.html">3479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Nav-mount.html">3558</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/OverflowSet-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/OverflowSet-mount.html">1567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Panel-mount_base.html">1560</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Panel-mount.html">1576</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Persona-mount_base.html">889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Persona-mount.html">875</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Pivot-mount_base.html">1525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Pivot-mount.html">1521</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/PrimaryButton-mount_base.html">1379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/PrimaryButton-mount.html">1397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Rating-mount_base.html">8391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Rating-mount.html">8404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SearchBox-mount_base.html">1393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SearchBox-mount.html">1421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Shimmer-mount_base.html">2837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Shimmer-mount.html">2840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Slider-mount_base.html">1640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Slider-mount.html">1572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SpinButton-mount_base.html">5370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SpinButton-mount.html">5428</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Spinner-mount_base.html">436</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Spinner-mount.html">446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SplitButton-mount_base.html">3457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SplitButton-mount.html">3485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Stack-mount_base.html">537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Stack-mount.html">532</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/StackWithIntrinsicChildren-mount.html">1684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/StackWithTextChildren-mount_base.html">5229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/StackWithTextChildren-mount.html">5237</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SwatchColorPicker-mount_base.html">10989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/SwatchColorPicker-mount.html">11036</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TagPicker-mount_base.html">2993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TagPicker-mount.html">3055</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TeachingBubble-mount_base.html">53896</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TeachingBubble-mount.html">53996</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Text-mount_base.html">474</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Text-mount.html">474</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TextField-mount_base.html">1509</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/TextField-mount.html">1534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Toggle-mount_base.html">914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/Toggle-mount.html">890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/button-mount_base.html">119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16366/merge/perf-test/button-mount.html">107</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by layershifter** [comment]
@dhatGuy thanks for contributing! Could you please generate a change file via `yarn change`?

**Comment by dhatGuy** [comment]
> @dhatGuy thanks for contributing! Could you please generate a change file via `yarn change`?

```
Please describe the changes for: @uifabric/fabric-website
? Change type › - Use arrow-keys. Return to submit.
❯   Patch      - bug fixes; no backwards incompatible changes.
    Minor      - small feature; backwards compatible changes.
    None       - this change does not affect the published package in any way.
```

I have no idea which option to choose.

**Comment by layershifter** [comment]
@dhatGuy IMO, it should be "None" as it's just a typo ;)

**Review by ecraig12345 — APPROVED** [review]

**Pull request merged**
