### PR TITLE
fix: Portal compat should apply `focus-visible` ponyfill

### LINKED ISSUE #24411: [Bug]: Focus ring broken with portal compat
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1018.01 MB / 15.42 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 101.0.4951.54
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/hungry-easley-4k6ovf?file=/example.tsx >= 9.2.0
https://codesandbox.io/s/throbbing-rgb-tqu2ey?file=/package.json < 9.2.0

### Bug Description

The portal compat registration forwards all CSS variables but does not forward `data-keyboard-nav` in < 9.2.0

For > 9.2.0 portal compat was overlooked (😔🙇‍♂️🙇‍♂️)

## Actual Behavior
Focus ring does not appear for v9 components in v0 portal

## Expected Behavior
Focus ring appears for v9 components in v0 portal

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
`@fluentui/react-portal-compat` now takes a dependency on `@fluentui/react-tabster` to apply the `focus-vislble` ponyfill. Also setup e2e tests for the portal compat package to test that the ponyfill is correctly applied.

## Current Behavior

Portal compat will not apply v9 focus outline styles

## New Behavior

Portal compat will apply v9 focus outline styles

## Related Issue(s)

Fixes #24411

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e4d50f2c501c4a8be23b24373242f650a601fdaf'>e4d50f2c501c4a8be23b24373242f650a601fdaf</a></sub>
<div id="bundleSizeComment9423"/>

**Review by bsunderhus — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/Avatar-mount_base.html">1279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/Avatar-mount.html">1288</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/Button-mount_base.html">953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/Button-mount.html">933</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProvider-mount_base.html">1629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProvider-mount.html">1584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-mount_base.html">626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-mount.html">622</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">585</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">597</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">638</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/MakeStyles-mount_base.html">1899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/MakeStyles-mount.html">1905</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/SpinButton-mount_base.html">2574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24712/perf-test-react-components/SpinButton-mount.html">2485</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by layershifter** [comment]
@ling1726 Can you please add a bundle size fixture to see how it affects bundle size?

**Comment by ling1726** [comment]
> @ling1726 Can you please add a bundle size fixture to see how it affects bundle size?

Added in https://github.com/microsoft/fluentui/pull/24712/commits/263e12ac1e04c2e60168fe48233395834b8f6a32

The minified size is ~5kb. I looked into the output and the extra code is keyborg + the ponyfill itself.

It should be fine since if users are using the `FluentProvider` then they have already paid the cost of keyborg

**Review by layershifter — APPROVED** [review]

**Pull request merged**
