### PR TITLE
fix nav in high contrast according the changes in master branch

### PR DESCRIPTION
**Pull request by Leolewin**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Port [13850](https://github.com/microsoft/fluentui/pull/13850) to update Nav to latest redlines in office-ui-fabric-react/5.79.1

#### Focus areas to test

(optional)

### CODE REVIEW

**Review by khmakoto — DISMISSED** [review]
Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

**Comment by Leolewin** [comment]
> Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

Hi, @khmakoto , how about the feedback of  version 8 beta release? We have a accessibility bug in SharePoint 2019 caused by it and this PR is sent to settle the issue. I have sent a email to fabric team before and didn't  get any response. So is there any one who can review my changes, reopen this PR and merge it into branch microsoft:office-ui-fabric-react_v5.79.1? Thanks

**Comment by khmakoto** [comment]
Hi @Leolewin, didn't meant for the PR to close, I've reopened it for now after seeing that another branch is being targeted. Sorry for that.

@ecraig12345 are you the one that should review this change?

**Comment by Leolewin** [comment]
> Hi @Leolewin, didn't meant for the PR to close, I've reopened it for now after seeing that another branch is being targeted. Sorry for that.
> 
> @ecraig12345 are you the one that should review this change?

@khmakoto Thanks for your great help.

**Review by Phoebe-0319 — APPROVED** [review]

**Pull request merged**
