### PR TITLE
Fix Slider issues with keyboard control

### LINKED ISSUE #16918: Slider with Keyboard control
### Environment Information

- **Package version(s)**: 7.158.3
- **Browser and OS versions**: MS Edge (88.0.705.63) / Windows 10 Enterprise 2004

### Describe the issue:
Two scenarios but I believe they come from the same root cause:
   
-  When the slider is controlled via keyboard, setting the value via `value` prop doesn't update the UI.
   To reproduce:
   1. Tab to slider and change the value using arrow key
   2. Click on Reset button
  [_Expected_] Slider handle moves to reset position
  [_Actual_] Slider handle doesn't move

- When the slider is controlled via mouse, and value is reset, then keyboard interaction starts from last position.
   To reproduce:
      
   1. Change the value of slider using mouse (eg value: 5)
   2. Click on Reset button => Value becomes 0, and slider handle moves to reset position
   3. Tab to slider and use arrow key to change the value
   [_Expected_] Value moves from Reset value
   [_Actual_] Value moves from previous value (eg value 5)

### Please provide a reproduction of the issue in a codepen:
Please use this codepen to follow the steps above: [link](https://codepen.io/KludgeMaker/pen/rNWMGwP)

### PR DESCRIPTION
**Pull request by Shriram-Balaji**
* Reset the renderedValue after updateValue is called.
* Override Slider's state value with props when available

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16918 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

- Fixes `props.value` not being respected in Slider Component, when using keyboard controls.
- Fixes slider handler position, by resetting the `renderedValue` after updating state (similar to mouseOut and touchEnd events)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/BaseButton-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/BaseButton-mount.html">861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Breadcrumb-mount_base.html">39829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Breadcrumb-mount.html">39563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Checkbox-mount_base.html">1452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Checkbox-mount.html">1462</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/CheckboxBase-mount_base.html">1219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/CheckboxBase-mount.html">1212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ChoiceGroup-mount_base.html">4626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ChoiceGroup-mount.html">4636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ComboBox-mount_base.html">892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ComboBox-mount.html">857</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/CommandBar-mount_base.html">7270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/CommandBar-mount.html">7273</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ContextualMenu-mount_base.html">12544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/ContextualMenu-mount.html">12644</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DefaultButton-mount_base.html">1063</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DefaultButton-mount.html">1044</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRow-mount_base.html">3379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRow-mount.html">3364</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRowFast-mount_base.html">3369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRowFast-mount.html">3369</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRowNoStyles-mount_base.html">3218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DetailsRowNoStyles-mount.html">3250</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Dialog-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Dialog-mount.html">1620</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DocumentCardTitle-mount_base.html">1765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/DocumentCardTitle-mount.html">1721</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Dropdown-mount_base.html">2347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Dropdown-mount.html">2395</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/FocusTrapZone-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/FocusTrapZone-mount.html">1639</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/FocusZone-mount_base.html">1710</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/FocusZone-mount.html">1737</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/IconButton-mount_base.html">1672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/IconButton-mount.html">1656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Label-mount_base.html">317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Label-mount.html">310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Layer-mount_base.html">1816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Layer-mount.html">1833</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Link-mount_base.html">412</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Link-mount.html">422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/MenuButton-mount_base.html">1378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/MenuButton-mount.html">1362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/MessageBar-mount_base.html">1912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/MessageBar-mount.html">1984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Nav-mount_base.html">3048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Nav-mount.html">3023</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/OverflowSet-mount_base.html">1323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/OverflowSet-mount.html">1362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Panel-mount_base.html">1368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Panel-mount.html">1379</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Persona-mount_base.html">754</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Persona-mount.html">729</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Pivot-mount_base.html">1361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Pivot-mount.html">1341</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/PrimaryButton-mount_base.html">1204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/PrimaryButton-mount.html">1181</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Rating-mount_base.html">7156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Rating-mount.html">6969</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SearchBox-mount_base.html">1191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SearchBox-mount.html">1174</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Shimmer-mount_base.html">2393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Shimmer-mount.html">2432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Slider-mount_base.html">1391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Slider-mount.html">1393</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SpinButton-mount_base.html">4757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SpinButton-mount.html">4618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Spinner-mount_base.html">396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Spinner-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SplitButton-mount_base.html">3001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SplitButton-mount.html">2992</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Stack-mount_base.html">478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Stack-mount.html">471</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/StackWithIntrinsicChildren-mount.html">1415</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/StackWithTextChildren-mount_base.html">4356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/StackWithTextChildren-mount.html">4330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SwatchColorPicker-mount_base.html">9647</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/SwatchColorPicker-mount.html">9652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TagPicker-mount_base.html">2589</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TagPicker-mount.html">2607</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TeachingBubble-mount_base.html">48101</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TeachingBubble-mount.html">48163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Text-mount_base.html">404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Text-mount.html">411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TextField-mount_base.html">1277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/TextField-mount.html">1279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Toggle-mount_base.html">774</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/Toggle-mount.html">798</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/button-mount_base.html">102</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/17251/merge/perf-test/button-mount.html">103</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ecraig12345 — DISMISSED** [review]
Now that version 8 has released, changes should go to the `master` branch first and be cherry-picked to `7.0` only if immediately needed. Please make another version of this PR targeting `master`, then let me know once that's created and I'll remove the "request changes" status.

**Review by joschect — COMMENTED** [review]
Thanks for submitting this change! I think that this looks good.

**Comment by joschect** [comment]
@ecraig12345 I think that this problem is only with the v7 slider since the new slider has been moved to being purely function but I might be wrong. @Shriram-Balaji Do you know if this still reproduces?

**Comment by Shriram-Balaji** [comment]
@ecraig12345 @joschect I believe it works as expected on 8.0, and is only an issue with 7.0.

For reference: The same repro mentioned in #16918 works on codesandbox with 8.0 
https://codesandbox.io/s/slider-with-keyboard-handler-on-fluentuireact-80-kwfct?file=/src/App.js

Also tried to switch out the versions of "@fluent/react" on the dependency list on the left sidebar on CSB, and the issue is visible for 7.x

**Comment by ecraig12345** [comment]
> I believe it works as expected on 8.0 and is only an issue with 7.0.
> 
> For reference: The same repro mentioned in #16918 works on codesandbox with 8.0
> https://codesandbox.io/s/slider-with-keyboard-handler-on-fluentuireact-80-kwfct?file=/src/App.js
> 
> Also tried to switch out the versions of "@fluent/react" on the dependency list on the left of codesandbox and the issue is visible for 7.x only
> 
> Do I need to still point me PR to master, as I think Slider on master works alright?

@Shriram-Balaji Thanks for verifying that! Just doing the change in 7 should be fine.

**Review by joschect — APPROVED** [review]

**Pull request merged**
