### PR TITLE
Creates Divider Web Component

### PR DESCRIPTION
**Pull request by halerankin**
Creates Divider Web Component

Had to update fork and apply changes to a new branch to be sure that I captured all the latest added to web-components-v3.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/1322f3f962e8a850fe104cc2ba9b12b2bc2f2842'>1322f3f962e8a850fe104cc2ba9b12b2bc2f2842</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by chrisdholt** [comment]
@halerankin looks like a lot of files are being re-added here?

**Comment by procload** [comment]
I believe there was an initial git error and there was an attempt to address it. This doesn't look correct, however. Let me work with @halerankin this afternoon to clean this up.

**Comment by halerankin** [comment]
Closing this PR.

**Pull request closed without merging**
