### PR TITLE
fix(react-infobutton): Apply aria-owns only when the popover is open and cleanup infobutton stories

### LINKED ISSUE #28158: InfoLabel: Only add aria-owns when the popover is open.
`aria-owns` is currently applied when providing info. While this is correct, aria-owns should only be applied when the popover is open instead of always as this is an a11y violation.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

`aria-owns` was added always, which is wrong since when the popover is closed it doesn't exist in the dom.

## New Behavior

`aria-owns` is now applied only when the popover is open.

InfoButton stories are now simpler and easy to follow.

## Related Issue(s)

- Fixes #28158

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Avatar-mount_base.html">573</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Avatar-mount.html">596</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Button-mount_base.html">291</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Button-mount.html">301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Field-mount_base.html">1039</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Field-mount.html">1051</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProvider-mount_base.html">676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProvider-mount.html">656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-mount_base.html">80</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-mount.html">83</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">66</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">64</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">67</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">66</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/InfoButton-mount_base.html">17</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/InfoButton-mount.html">7</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/MakeStyles-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/MakeStyles-mount.html">882</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Persona-mount_base.html">1625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/Persona-mount.html">1586</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/SpinButton-mount_base.html">1277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28463/perf-test-react-components/SpinButton-mount.html">1274</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                    |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :--------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoLabel.fixture.js'>InfoLabel</abbr> | `134.776 kB`<br />`41.369 kB` | `134.917 kB`<br />`41.437 kB` | `141 B` <br />`68 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `65.175 kB`<br />`17.915 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `210.657 kB`<br />`58.768 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `36.409 kB`<br />`12.003 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `131.312 kB`<br />`40.301 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.473 kB`<br />`2.196 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4bc71e1e82a2b0044ffdde84f84d8c47271bbdac'>4bc71e1e82a2b0044ffdde84f84d8c47271bbdac</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by smhigley — APPROVED** [review]

**Pull request merged**
