### PR TITLE
Yushsingla/event annotation bug fix

### PR DESCRIPTION
**Pull request by yush-singla**
## Previous Behavior
WorkItem https://uifabric.visualstudio.com/iss/_workitems/edit/7478

The event annotation line and text being changed to white color if the OS level dark mode is enabled, thus making the lines invisible to eye, due to white background. The issue is the use of OS level dark mode, instead of library's inbuilt method to get theme based on fluentUI theme provider.

## New Behavior

The bug has been patched by removing the hardcoded colors by default and instead using theme palette colors to get the desired color in both light and dark themes. Hence now the lines appear black in light theme and white in dark theme, maintaining the contrast witht the background.

## Related Issue(s)

- Fixes https://uifabric.visualstudio.com/iss/_workitems/edit/7478

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/88f01346113e912c48078427326ec425da9d4ff0'>88f01346113e912c48078427326ec425da9d4ff0</a></sub>
<div id="bundleSizeComment9423"/>

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
