### PR TITLE
[cherrypick] Fix onRenderDetailsGroupHeader props for custom group.onRenderHeader

### LINKED ISSUE #18099: Incorrect groupHeaderProps passed to groupProps.onRenderHeader in DetailsList
### Environment Information

- **Package version(s)**: 8 (and earlier versions as well)
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

The behavior of `checkboxVisibility` for Group Header is inconsistent when a `groupProps.onRenderHeader` is provided, as incorrect props are passed to `groupProps.onRenderHeader`.

#### Actual behavior:

Custom group header [which calls the defaultRender] with `checkboxVisibility` as hidden - [codepen example](https://codepen.io/shagra-ms/pen/MWpYpvL)
image

Notice the checkbox on group header.

#### Expected behavior:

image

The above can be tried on [this codepen](https://codepen.io/shagra-ms/pen/bGqNqov), which is similar to the above.

#### Root cause:

The `selectionMode` prop is updated while rendering `GroupedList`, based on `checkboxVisibility` - [[link](https://github.com/microsoft/fluentui/blob/244770a98640cae0813270522a242a7c4a23dcb7/packages/react/src/components/DetailsList/DetailsList.base.tsx#L570)]

image

But, if a `groupProps.onRenderHeader` is available, the `selectionMode` prop is not upaded based on `checkboxVisibility` - [[link](https://github.com/microsoft/fluentui/blob/244770a98640cae0813270522a242a7c4a23dcb7/packages/react/src/components/DetailsList/DetailsList.base.tsx#L361)]

image

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes #18101

Requested priority: Normal

Products/sites affected: Microsoft Lists

### PR DESCRIPTION
**Pull request by shagra-ms**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #18099 in Fluent 7
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Cherry-pick #18101

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/BaseButton-mount_base.html">913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/BaseButton-mount.html">905</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Breadcrumb-mount_base.html">42536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Breadcrumb-mount.html">42771</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Checkbox-mount_base.html">1572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Checkbox-mount.html">1634</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/CheckboxBase-mount_base.html">1331</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/CheckboxBase-mount.html">1360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ChoiceGroup-mount_base.html">5062</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ChoiceGroup-mount.html">5070</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ComboBox-mount_base.html">909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ComboBox-mount.html">895</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/CommandBar-mount_base.html">7796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/CommandBar-mount.html">7818</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ContextualMenu-mount_base.html">14304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/ContextualMenu-mount.html">13996</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DefaultButton-mount_base.html">1158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DefaultButton-mount.html">1177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRow-mount_base.html">3812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRow-mount.html">3876</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRowFast-mount_base.html">4195</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRowFast-mount.html">3768</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRowNoStyles-mount_base.html">3573</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DetailsRowNoStyles-mount.html">4018</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Dialog-mount_base.html">1726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Dialog-mount.html">1802</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DocumentCardTitle-mount_base.html">1850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/DocumentCardTitle-mount.html">1850</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Dropdown-mount_base.html">2498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Dropdown-mount.html">2468</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/FocusTrapZone-mount_base.html">1801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/FocusTrapZone-mount.html">1741</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/FocusZone-mount_base.html">1821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/FocusZone-mount.html">1804</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/IconButton-mount_base.html">1799</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/IconButton-mount.html">1740</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Label-mount_base.html">323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Label-mount.html">339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Layer-mount_base.html">2060</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Layer-mount.html">1979</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Link-mount_base.html">462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Link-mount.html">433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/MenuButton-mount_base.html">1475</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/MenuButton-mount.html">1475</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/MessageBar-mount_base.html">2037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/MessageBar-mount.html">2067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Nav-mount_base.html">3445</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Nav-mount.html">3374</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/OverflowSet-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/OverflowSet-mount.html">1455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Panel-mount_base.html">1485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Panel-mount.html">1466</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Persona-mount_base.html">802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Persona-mount.html">811</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Pivot-mount_base.html">1622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Pivot-mount.html">1499</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/PrimaryButton-mount_base.html">1299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/PrimaryButton-mount.html">1307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Rating-mount_base.html">8005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Rating-mount.html">8009</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SearchBox-mount_base.html">1298</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SearchBox-mount.html">1310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Shimmer-mount_base.html">2625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Shimmer-mount.html">2501</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Slider-mount_base.html">1509</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Slider-mount.html">1498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SpinButton-mount_base.html">5110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SpinButton-mount.html">5124</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Spinner-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Spinner-mount.html">407</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SplitButton-mount_base.html">3189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SplitButton-mount.html">3194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Stack-mount_base.html">493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Stack-mount.html">514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/StackWithIntrinsicChildren-mount_base.html">1637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/StackWithIntrinsicChildren-mount.html">1701</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/StackWithTextChildren-mount_base.html">4856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/StackWithTextChildren-mount.html">4917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SwatchColorPicker-mount_base.html">10649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/SwatchColorPicker-mount.html">10825</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TagPicker-mount_base.html">2846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TagPicker-mount.html">2887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TeachingBubble-mount_base.html">51602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TeachingBubble-mount.html">52096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Text-mount_base.html">443</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Text-mount.html">410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TextField-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/TextField-mount.html">1425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Toggle-mount_base.html">808</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/Toggle-mount.html">852</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/button-mount_base.html">116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21148/perf-test/button-mount.html">115</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by shagra-ms** [comment]
@ecraig12345 Requesting help with this.

**Comment by shagra-ms** [comment]
@micahgodbolt requesting help with this.

**Comment by shagra-ms** [comment]
@ThomasMichon Can you please help here?

**Review by micahgodbolt — APPROVED** [review]
Might need to re-run CI to get screener to pass

**Comment by shagra-ms** [comment]
@micahgodbolt Thanks for approving this. This looks ready to merge now. Can you please help ?

**Pull request merged**
