### PR TITLE
Update Spinner component UI to maintain consistency with WinUI `ProgressRing`

### LINKED ISSUE #16088: [FEATURE] New ProgressRing (Spinner) consistent with WinUI
#### Describe the feature that you would like added
  
`ProgressRing` (read: `Spinner`) control __consistent__ with [WinUI](https://github.com/microsoft/microsoft-ui-xaml).  
  
#### What component or utility would this be added to
  
`Spinner` (will be called `ProgressRing` for consistency with WinUI).  
  
#### Have you discussed this feature with our team, and if so, who
  
Kind of. To @paulgildea in [this comment](https://github.com/microsoft/fluentui/issues/15745#issuecomment-720160747) in #15745.  
  
#### Additional context/screenshots

[*Live REPL*](https://create-react-app.sfm61319.repl.co)  
  
Screenshot GIF

### PR DESCRIPTION
**Pull request by SFM61319**
## Current Behavior

[Old `Spinner`](https://github.com/microsoft/fluentui/tree/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/Spinner) component UI inconsistent with WinUI [`ProgressRing`](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.progressring?view=winui-3.0 "WinUI ProgressRing")

https://user-images.githubusercontent.com/45308169/156897915-89d2cf0d-3e06-4d5d-aba8-de0d1fff3292.mp4

## New Behavior

New `Spinner` component UI consistent with WinUI `ProgressRing`

https://user-images.githubusercontent.com/45308169/156898209-03c3ea1d-b023-4c03-9502-53b1d2ae9c1f.mp4

## Related Issue(s)

Fixes #16088

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/966ed6ca242079a1865d0011972205afba1ab85d'>966ed6ca242079a1865d0011972205afba1ab85d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount_base.html">787</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount.html">773</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount_base.html">693</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount.html">647</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Avatar-mount_base.html">1168</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Avatar-mount.html">1153</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/BaseButton-mount_base.html">1167</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/BaseButton-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Breadcrumb-mount_base.html">2985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Breadcrumb-mount.html">3018</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ButtonNext-mount_base.html">736</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ButtonNext-mount.html">737</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Checkbox-mount_base.html">1830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Checkbox-mount.html">1765</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/CheckboxBase-mount_base.html">1541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/CheckboxBase-mount.html">1491</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ChoiceGroup-mount_base.html">5116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ChoiceGroup-mount.html">5154</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ComboBox-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ComboBox-mount.html">1194</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/CommandBar-mount_base.html">10828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/CommandBar-mount.html">10807</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ContextualMenu-mount_base.html">17357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ContextualMenu-mount.html">17906</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DefaultButton-mount_base.html">1403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DefaultButton-mount.html">1389</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRow-mount_base.html">4212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRow-mount.html">4278</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRowFast-mount_base.html">4126</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRowFast-mount.html">4254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRowNoStyles-mount_base.html">4035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DetailsRowNoStyles-mount.html">4014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Dialog-mount_base.html">2538</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Dialog-mount.html">2561</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DocumentCardTitle-mount_base.html">382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/DocumentCardTitle-mount.html">386</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Dropdown-mount_base.html">3723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Dropdown-mount.html">3681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderNext-mount_base.html">2191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderNext-mount.html">2242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-mount_base.html">376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-mount.html">379</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-virtual-rerender.html">319</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">416</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FocusTrapZone-mount_base.html">2109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FocusTrapZone-mount.html">2119</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FocusZone-mount_base.html">2110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/FocusZone-mount.html">2133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/IconButton-mount_base.html">2039</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/IconButton-mount.html">2050</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Label-mount_base.html">578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Label-mount.html">603</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Layer-mount_base.html">3328</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Layer-mount.html">3292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Link-mount_base.html">691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Link-mount.html">715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MakeStyles-mount_base.html">1973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MakeStyles-mount.html">1936</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MenuButton-mount_base.html">1739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MenuButton-mount.html">1816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MessageBar-mount_base.html">2311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/MessageBar-mount.html">2263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Nav-mount_base.html">3619</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Nav-mount.html">3644</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/OverflowSet-mount_base.html">1353</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/OverflowSet-mount.html">1386</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Panel-mount_base.html">2417</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Panel-mount.html">2409</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Persona-mount_base.html">1115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Persona-mount.html">1106</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Pivot-mount_base.html">1695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Pivot-mount.html">1802</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/PrimaryButton-mount_base.html">1550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/PrimaryButton-mount.html">1578</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Rating-mount_base.html">8125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Rating-mount.html">8321</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SearchBox-mount_base.html">1616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SearchBox-mount.html">1621</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Shimmer-mount_base.html">2817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Shimmer-mount.html">2778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Slider-mount_base.html">2189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Slider-mount.html">2241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SpinButton-mount_base.html">5529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SpinButton-mount.html">5559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Spinner-mount_base.html">650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Spinner-mount.html">872</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SplitButton-mount_base.html">3587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SplitButton-mount.html">3455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount_base.html">787</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount.html">773</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Stack-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/StackWithIntrinsicChildren-mount_base.html">2522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/StackWithIntrinsicChildren-mount.html">2705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/StackWithTextChildren-mount_base.html">5673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/StackWithTextChildren-mount.html">5684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SwatchColorPicker-mount_base.html">12232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/SwatchColorPicker-mount.html">12374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TagPicker-mount_base.html">2957</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TagPicker-mount.html">2922</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TeachingBubble-mount_base.html">13678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TeachingBubble-mount.html">13916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount_base.html">693</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount.html">647</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Text-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TextField-mount_base.html">1696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/TextField-mount.html">1711</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-mount.html">1474</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-virtual-rerender_base.html">888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-virtual-rerender.html">840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2148</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2166</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Toggle-mount_base.html">1047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/Toggle-mount.html">1075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/buttonNative-mount_base.html">353</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21973/perf-test/buttonNative-mount.html">342</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
@SFM61319 is there an issue tracking why this change is happening? Is there a new design source that we're aligning to? Its hard to take in a random change to the look of one of our controls.

**Comment by SFM61319** [comment]
> @SFM61319 is there an issue tracking why this change is happening? Is there a new design source that we're aligning to? Its hard to take in a random change to the look of one of our controls.

@micahgodbolt Yes sir, #16088. Some devs said that while it was not in the project's current roadmap/plans, consistency across platforms was indeed one of the main goals. And that I was more than welcome to submit a PR for the same. I waited for an year for it to be implemented by the team of professionals, but since there were too many tasks (on the roadmap) for the devs, I've decided to implement it myself (so that the updated control is released on/before v9).

**Comment by SFM61319** [comment]
Also do note that the GIFs on the issue are old. The control in the submitted PR is WinUI 2.6 `ProgressRing` based (newer). I was unable to comment on that issue because of the lock.

**Comment by micahgodbolt** [comment]
@SFM61319 while we appreciate the work done in this PR, we don't have any intention to update the v8 version of the spinner due to our focus being on the v9 version of the library, and the potential for an update to the v8 version causing regression for those that relied on the existing implementation. 

We're sorry that we didn't state this sooner in the original issue. Major changes to DOM structure of controls are considered breaking changes and can only be done in major version bumps.

**Comment by SFM61319** [comment]
@micahgodbolt Ah, no problem, please take further actions. The code in this PR is always available for reference if the team plans on updating the control UI in the future anyway!  
  
Thanks for the reply!

**Pull request closed without merging**
