### PR TITLE
feat(test-bundles): make the bundle-size flow generic to simplify local DX but most importantly CI

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

- size-auditor ci is non trivial/not generic/takes unnecessary long time on CI to process

## New Behavior

- simplified and more performant builds on CI for size-auditor processing for v8,v0 libraries
- as a follow-up this should be collocated per package to be able to easily enable `affected` approach on CI ( run only if PR changes are affecting particular package )

## Related Issue(s)

- Follows https://github.com/microsoft/fluentui/pull/28208

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Avatar-mount_base.html">611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Avatar-mount.html">586</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Button-mount_base.html">308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Button-mount.html">301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Field-mount_base.html">1013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Field-mount.html">1030</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProvider-mount_base.html">651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProvider-mount.html">651</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-mount_base.html">76</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-mount.html">77</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">64</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">69</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">73</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">68</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/InfoButton-mount_base.html">10</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/InfoButton-mount.html">16</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/MakeStyles-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/MakeStyles-mount.html">859</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Persona-mount_base.html">1572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/Persona-mount.html">1556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/SpinButton-mount_base.html">1252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test-react-components/SpinButton-mount.html">1251</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/BaseButton-mount_base.html">635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/BaseButton-mount.html">623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Breadcrumb-mount_base.html">1681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Breadcrumb-mount.html">1668</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Checkbox-mount_base.html">1695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Checkbox-mount.html">1711</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/CheckboxBase-mount_base.html">1479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/CheckboxBase-mount.html">1489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ChoiceGroup-mount_base.html">2959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ChoiceGroup-mount.html">2868</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ComboBox-mount_base.html">654</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ComboBox-mount.html">643</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/CommandBar-mount_base.html">6177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/CommandBar-mount.html">6141</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ContextualMenu-mount_base.html">12376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ContextualMenu-mount.html">12516</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DefaultButton-mount_base.html">726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DefaultButton-mount.html">745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRow-mount_base.html">2170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRow-mount.html">2211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRowFast-mount_base.html">2184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRowFast-mount.html">2178</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRowNoStyles-mount_base.html">1996</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DetailsRowNoStyles-mount.html">1979</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Dialog-mount_base.html">2571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Dialog-mount.html">2638</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DocumentCardTitle-mount_base.html">227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/DocumentCardTitle-mount.html">227</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Dropdown-mount_base.html">1991</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Dropdown-mount.html">1979</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/FocusTrapZone-mount_base.html">1102</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/FocusTrapZone-mount.html">1143</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/FocusZone-mount_base.html">1056</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/FocusZone-mount.html">1050</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-mount_base.html">41244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-mount.html">41251</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-virtual-rerender_base.html">19610</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-virtual-rerender.html">19766</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50345</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedList-virtual-rerender-with-unmount.html">50261</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-mount_base.html">215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-mount.html">224</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-virtual-rerender_base.html">215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-virtual-rerender.html">198</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">227</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/IconButton-mount_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/IconButton-mount.html">1083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Label-mount_base.html">341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Label-mount.html">338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Layer-mount_base.html">2658</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Layer-mount.html">2659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Link-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Link-mount.html">380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/MenuButton-mount_base.html">921</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/MenuButton-mount.html">919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/MessageBar-mount_base.html">21404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/MessageBar-mount.html">21305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Nav-mount_base.html">1929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Nav-mount.html">1902</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/OverflowSet-mount_base.html">793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/OverflowSet-mount.html">777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Panel-mount_base.html">1764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Panel-mount.html">1749</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Persona-mount_base.html">730</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Persona-mount.html">742</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Pivot-mount_base.html">870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Pivot-mount.html">870</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/PrimaryButton-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/PrimaryButton-mount.html">837</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Rating-mount_base.html">4597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Rating-mount.html">4607</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SearchBox-mount_base.html">884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SearchBox-mount.html">878</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Shimmer-mount_base.html">1819</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Shimmer-mount.html">1793</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Slider-mount_base.html">1289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Slider-mount.html">1265</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SpinButton-mount_base.html">2737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SpinButton-mount.html">2741</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Spinner-mount_base.html">365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Spinner-mount.html">372</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SplitButton-mount_base.html">1786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SplitButton-mount.html">1784</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Stack-mount_base.html">401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Stack-mount.html">390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/StackWithIntrinsicChildren-mount_base.html">812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/StackWithIntrinsicChildren-mount.html">818</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/StackWithTextChildren-mount_base.html">2546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/StackWithTextChildren-mount.html">2553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SwatchColorPicker-mount_base.html">5961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/SwatchColorPicker-mount.html">5925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/TagPicker-mount_base.html">1397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/TagPicker-mount.html">1373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Text-mount_base.html">359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Text-mount.html">365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/TextField-mount_base.html">895</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/TextField-mount.html">897</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-mount_base.html">832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-mount.html">811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-virtual-rerender_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-virtual-rerender.html">567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1267</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Toggle-mount_base.html">595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/Toggle-mount.html">593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/buttonNative-mount_base.html">181</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28210/perf-test/buttonNative-mount.html">185</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/517b807cd97ee89a470ac5e9dec48a6f42b69532'>517b807cd97ee89a470ac5e9dec48a6f42b69532</a></sub>
<div id="bundleSizeComment9423"/>

**Review by sopranopillow — APPROVED** [review]

**Review by TristanWatanabe — APPROVED** [review]

**Pull request merged**
