### PR TITLE
Persona: Remove empty divs when there is no secondaryText, tertiaryText, or optionalText

### PR DESCRIPTION
**Pull request by behowell**
## Current Behavior

The Persona control wraps the `secondaryText`, `tertiaryText`, and `optionalText` with a div for layout. However, it still renders the  empty divs even when there is no text. This adds unnecessary DOM nodes to a component that already has a large number of DOM nodes.

## New Behavior

Persona no longer renders empty `<div>` for secondary, tertiary, and optional text if those are not present

## Related Issue(s)

* #23386

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5f06f19e57ffdc265f10ef26db086bf48dc8f610'>5f06f19e57ffdc265f10ef26db086bf48dc8f610</a></sub>
<div id="bundleSizeComment9423"/>

**Review by khmakoto — COMMENTED** [review]
Would this be considered breaking since we are removing elements from the DOM tree?

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/BaseButton-mount_base.html">926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/BaseButton-mount.html">913</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Breadcrumb-mount_base.html">2777</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Breadcrumb-mount.html">2861</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Checkbox-mount_base.html">1583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Checkbox-mount.html">1514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/CheckboxBase-mount_base.html">1300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/CheckboxBase-mount.html">1281</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ChoiceGroup-mount_base.html">4864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ChoiceGroup-mount.html">4861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ComboBox-mount_base.html">1025</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ComboBox-mount.html">1011</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/CommandBar-mount_base.html">10907</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/CommandBar-mount.html">10843</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ContextualMenu-mount_base.html">11902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ContextualMenu-mount.html">11648</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DefaultButton-mount_base.html">1204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DefaultButton-mount.html">1200</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRow-mount_base.html">3967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRow-mount.html">3883</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRowFast-mount_base.html">3870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRowFast-mount.html">3997</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRowNoStyles-mount_base.html">3702</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DetailsRowNoStyles-mount.html">3833</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Dialog-mount_base.html">2333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Dialog-mount.html">2305</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DocumentCardTitle-mount_base.html">164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/DocumentCardTitle-mount.html">169</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Dropdown-mount_base.html">3431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Dropdown-mount.html">3381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/FocusTrapZone-mount_base.html">1826</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/FocusTrapZone-mount.html">1923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/FocusZone-mount_base.html">1871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/FocusZone-mount.html">1926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/IconButton-mount_base.html">1827</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/IconButton-mount.html">1848</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Label-mount_base.html">361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Label-mount.html">347</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Layer-mount_base.html">3039</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Layer-mount.html">3129</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Link-mount_base.html">488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Link-mount.html">492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/MenuButton-mount_base.html">1556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/MenuButton-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/MessageBar-mount_base.html">2196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/MessageBar-mount.html">2318</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Nav-mount_base.html">3445</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Nav-mount.html">3405</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/OverflowSet-mount_base.html">1102</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/OverflowSet-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Panel-mount_base.html">2196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Panel-mount.html">2250</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Persona-mount_base.html">987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Persona-mount.html">1003</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Pivot-mount_base.html">1503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Pivot-mount.html">1515</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/PrimaryButton-mount_base.html">1368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/PrimaryButton-mount.html">1341</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Rating-mount_base.html">7942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Rating-mount.html">7952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SearchBox-mount_base.html">1332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SearchBox-mount.html">1347</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Shimmer-mount_base.html">2597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Shimmer-mount.html">2581</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Slider-mount_base.html">2023</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Slider-mount.html">2036</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SpinButton-mount_base.html">5206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SpinButton-mount.html">5163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Spinner-mount_base.html">447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Spinner-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SplitButton-mount_base.html">3288</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SplitButton-mount.html">3357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Stack-mount_base.html">517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Stack-mount.html">548</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/StackWithIntrinsicChildren-mount_base.html">2367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/StackWithIntrinsicChildren-mount.html">2346</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/StackWithTextChildren-mount_base.html">5448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/StackWithTextChildren-mount.html">5448</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SwatchColorPicker-mount_base.html">11748</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/SwatchColorPicker-mount.html">11996</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TagPicker-mount_base.html">2867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TagPicker-mount.html">2853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TeachingBubble-mount_base.html">94400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TeachingBubble-mount.html">94151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Text-mount_base.html">448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Text-mount.html">423</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TextField-mount_base.html">1476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/TextField-mount.html">1451</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-mount_base.html">1225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-mount.html">1242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-virtual-rerender_base.html">655</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-virtual-rerender.html">653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2008</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Toggle-mount_base.html">799</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/Toggle-mount.html">829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/buttonNative-mount_base.html">138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23401/perf-test/buttonNative-mount.html">140</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by spmonahan** [comment]
> Would this be considered breaking since we are removing elements from the DOM tree?

In the case of conditionally rendering the empty nodes I think it should be a non-breaking change to hide those when there is no content. We'll still render them if they are relevant.

The `span` change _might_ be a breaking change. I supposed it depends on what we consider our public API surface. In this case the span doesn't have any classes or other props applied to it so in that sense it cannot be directly targeted via our API. If someone is targeting the element via styling there is probably a rule like `.persona > span` which would have to be changed to `.persona > *` after this change. We're making this change at a partner's request to improve performance by reducing the amount of rendered DOM but if a CSS rule with a universal selector is required the perf change is probably a wash in which case I'd be in favor of keeping the span.

My 2 cents is that we should not consider this a breaking change as the DOM being entirely removed is not accessible via the public API and conditionally rendering elements _should_ have no impact on applications. Of course I may turn out to be completely wrong on both counts so I think we should run these changes by our partners before merging them.

**Comment by behowell** [comment]
I've pulled the PersonaCoin change out of this PR. We can consider handling that in a future PR. It might be best to do that change behind a new prop or setting since it is more likely to be a breaking change. That would allow us to make even more significant (and potentially breaking) DOM changes, like removing some layers of divs that wrap the content.

**Review by khmakoto — APPROVED** [review]

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
