### PR TITLE
Add choiceGroup subtext as optional prop

### PR DESCRIPTION
**Pull request by MicrosoftMitch**
## Current Behavior

Currently we do not have a standardized method of adding subtext below choice groups, this was a request from our MADS team to add and use in admin 365 components via fluent.

## New Behavior
image

## Spec'd Behavior (MADS)
image

## Related Issue(s)

Internal m365 admin ticket 4102:

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2b8643c7bc1644ec5c5930f18e28440eeb8c8bd6'>2b8643c7bc1644ec5c5930f18e28440eeb8c8bd6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Avatar-mount_base.html">934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Avatar-mount.html">929</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/BaseButton-mount_base.html">972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/BaseButton-mount.html">955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Breadcrumb-mount_base.html">2804</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Breadcrumb-mount.html">2784</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ButtonNext-mount_base.html">491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ButtonNext-mount.html">493</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Checkbox-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Checkbox-mount.html">1560</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/CheckboxBase-mount_base.html">1340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/CheckboxBase-mount.html">1313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ChoiceGroup-mount_base.html">4981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ChoiceGroup-mount.html">4896</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ComboBox-mount_base.html">1037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ComboBox-mount.html">1018</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/CommandBar-mount_base.html">10604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/CommandBar-mount.html">10682</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ContextualMenu-mount_base.html">8676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ContextualMenu-mount.html">8724</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DefaultButton-mount_base.html">1179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DefaultButton-mount.html">1207</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRow-mount_base.html">3797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRow-mount.html">3902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRowFast-mount_base.html">3841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRowFast-mount.html">3778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRowNoStyles-mount_base.html">3648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DetailsRowNoStyles-mount.html">3692</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Dialog-mount_base.html">2315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Dialog-mount.html">2320</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DocumentCardTitle-mount_base.html">212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/DocumentCardTitle-mount.html">187</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Dropdown-mount_base.html">3387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Dropdown-mount.html">3341</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderNext-mount_base.html">1959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderNext-mount.html">1965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-mount_base.html">182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-mount.html">171</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-virtual-rerender.html">127</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">218</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FocusTrapZone-mount_base.html">1940</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FocusTrapZone-mount.html">1923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FocusZone-mount_base.html">1932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/FocusZone-mount.html">1904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/IconButton-mount_base.html">1787</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/IconButton-mount.html">1826</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Label-mount_base.html">396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Label-mount.html">375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Layer-mount_base.html">3075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Layer-mount.html">3156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Link-mount_base.html">515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Link-mount.html">511</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MakeStyles-mount_base.html">1764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MakeStyles-mount.html">1782</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MenuButton-mount_base.html">1504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MenuButton-mount.html">1543</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MessageBar-mount_base.html">2098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/MessageBar-mount.html">2127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Nav-mount_base.html">3332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Nav-mount.html">3487</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/OverflowSet-mount_base.html">1196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/OverflowSet-mount.html">1161</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Panel-mount_base.html">2265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Panel-mount.html">2189</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Persona-mount_base.html">903</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Persona-mount.html">902</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Pivot-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Pivot-mount.html">1483</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/PrimaryButton-mount_base.html">1329</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/PrimaryButton-mount.html">1311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Rating-mount_base.html">7803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Rating-mount.html">7758</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SearchBox-mount_base.html">1387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SearchBox-mount.html">1397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Shimmer-mount_base.html">2600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Shimmer-mount.html">2567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Slider-mount_base.html">1997</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Slider-mount.html">2017</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SpinButton-mount_base.html">5224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SpinButton-mount.html">5337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Spinner-mount_base.html">501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Spinner-mount.html">474</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SplitButton-mount_base.html">3260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SplitButton-mount.html">3258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Stack-mount_base.html">541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Stack-mount.html">565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/StackWithIntrinsicChildren-mount_base.html">2497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/StackWithIntrinsicChildren-mount.html">2452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/StackWithTextChildren-mount_base.html">5453</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/StackWithTextChildren-mount.html">5454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SwatchColorPicker-mount_base.html">11783</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/SwatchColorPicker-mount.html">11635</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TagPicker-mount_base.html">2715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TagPicker-mount.html">2713</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TeachingBubble-mount_base.html">13515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TeachingBubble-mount.html">13678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Text-mount_base.html">475</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Text-mount.html">495</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TextField-mount_base.html">1505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/TextField-mount.html">1482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-mount_base.html">1211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-virtual-rerender_base.html">644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-virtual-rerender.html">641</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Toggle-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/Toggle-mount.html">880</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/buttonNative-mount_base.html">166</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21874/perf-test/buttonNative-mount.html">163</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by MicrosoftMitch** [comment]
Getting a screener failure here due to new ChoiceGroup option I believe.

**Comment by ecraig12345** [comment]
Thanks for the PR but a couple things:
- Please don't include internal links in public PRs
- Please remove the react-radio changes for now and make an issue to discuss whether this is something we want to include in the converged component (cc @behowell)

**Comment by ecraig12345** [comment]
It also would have been good to make an issue to discuss this proposed change overall before doing it. It's actually already possible to add subtext using `IChoiceGroupOption.onRenderLabel`, so I'm not sure if we need to support this in the main library.
https://codesandbox.io/s/choicegroup-subtext-tvusev?file=/src/index.tsx

```tsx
interface IChoiceGroupOptionExtended extends IChoiceGroupOption {
  subtext?: string;
}

const onRenderLabel: IChoiceGroupOptionExtended['onRenderLabel'] = (props, defaultRender) => {
  const { labelId, text, subtext } = props as IChoiceGroupOptionExtended;
  return (
    <span id={labelId} className="ms-ChoiceFieldLabel">
      {text}
      {subtext && <span style={{ paddingTop: '4px', display: 'block' }}>{subtext}</span>}
    </span>
  );
};
```

**Comment by MicrosoftMitch** [comment]
Thank you @ecraig12345 - my mistake, that would be our preferred case; I'll close this PR out and create an issue next time to discuss beforehand.

**Comment by ecraig12345** [comment]
@MicrosoftMitch Sounds good. And regardless, thanks for your willingness to contribute to the library! :)

**Pull request closed without merging**
