### PR TITLE
fix(ProgressBar): rename rectangular shape to square

### PR DESCRIPTION
**Pull request by miroslavstastny**
## Previous Behavior

```jsx
<ProgressBar shape="rectangular" />
```

The `rectangular` shape is inconsistent with all other components which use `'rounded' | 'circular' | 'square'`

## New Behavior

```jsx
<ProgressBar shape="square" />
```

The `shape` prop now accepts `'rounded' | 'square'`

### CODE REVIEW

**Comment by miroslavstastny** [comment]
We agreed on the rename in tech sync on Jan 18.

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Avatar-mount_base.html">1260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Avatar-mount.html">1272</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Button-mount_base.html">923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Button-mount.html">918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProvider-mount_base.html">1495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProvider-mount.html">1513</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-mount_base.html">576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-mount.html">587</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">538</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">574</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/InfoButton-mount_base.html">531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/InfoButton-mount.html">506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/MakeStyles-mount_base.html">1945</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/MakeStyles-mount.html">1962</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Persona-mount_base.html">2819</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/Persona-mount.html">2810</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/SpinButton-mount_base.html">2312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26419/perf-test-react-components/SpinButton-mount.html">2332</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                          |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                 Change |
| :--------------------------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>     | `13.578 kB`<br />`5.235 kB` | `13.573 kB`<br />`5.232 kB` | `-5 B` <br />`-3 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressField.fixture.js'>ProgressField</abbr> | `23.404 kB`<br />`8.201 kB` | `23.399 kB`<br />`8.201 kB` |                                                                                                 `-5 B` <br /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `59.888 kB`<br />`16.652 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `187.539 kB`<br />`52.638 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.379 kB`<br />`11.322 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.069 kB`<br />`2.053 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d2818f204f2bd95093960b3ce69e926556ffb6df'>d2818f204f2bd95093960b3ce69e926556ffb6df</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by tomi-msft — APPROVED** [review]
lgtm

**Pull request merged**
