### PR TITLE
(web components) Standardize focus treatment

### PR DESCRIPTION
**Pull request by bheston**
## Current Behavior

In the web component styles, the focus treatment is a mix of reusing existing display borders or supplementing borders with inset box-shadows. This is difficult to style and creates inconsistencies between components, states, and is blocking the update to support color opacity for use over mica.

## New Behavior

Since `outline` is fully support _and_ now follows `border-radius`, it's a much better option for a treatment that can overlay and ignore any potential border treatments. By separating the focus treatment from any visible borders, we can more easily and consistently apply the opacity color update.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/83b033de0fe819bc30cc437ec7c4a83dd4c6997e'>83b033de0fe819bc30cc437ec7c4a83dd4c6997e</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by EisenbergEffect** [comment]
I'm not sure how we should treat this PR. Can you provide a couple of before and after screenshots? I'm trying to understand if this actually constitutes a significant visual change to the component focus styles or if it's more subtle (and a flexibility improvement). The reason is that if it's not a minor visual change that isn't going to mess folks up, then we need to bump the major version. And I don't think we should bump a major version while we're currently in progress on the next major version.

In general, I don't think we should be spending any time on this version of Fluent unless it's to fix a critical bugs because we need to get the new Fluent implementation up and running pretty soon so we don't cause major blocks for other teams.

**Comment by bheston** [comment]
> I'm not sure how we should treat this PR. Can you provide a couple of before and after screenshots? I'm trying to understand if this actually constitutes a significant visual change to the component focus styles or if it's more subtle (and a flexibility improvement).

This was not intended to be a visual change in any way. I've gone back through and created before and after screenshots, which illustrate only one minor difference on the offset of the treatment on the breadcrumb, which is desirable, and I don't believe breaking.

I fixed a few unintended visual changes, so hopefully there are no concerns merging this.

Before

Update

**Comment by EisenbergEffect** [comment]
Awesome! Just wanted to make sure. From reading the CSS it didn't look like it was a real visual change. The screenshots help a lot though.

**Review by EisenbergEffect — APPROVED** [review]

**Pull request merged**
