### PR TITLE
chore(react-popover): migrate to new package structure

### PR DESCRIPTION
**Pull request by TristanWatanabe**
## Changes:
- Runs `migrate-converged-pkg` which reflects updates made in #24458.
	- Moves stories to `stories/` folder in the root of the package.
	- Collocates any e2e tests with the component implementation and jest tests.
	- removes `common/` folder and moves contents to new `testing/` folder 
	- adds `docs/` folder to package root.

## Issue:
- Part of #24129

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `86.891 kB`<br />`21.708 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `51.076 kB`<br />`14.285 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |   `15.006 kB`<br />`6.009 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |  `65.654 kB`<br />`18.382 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.975 kB`<br />`17.687 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `190.427 kB`<br />`53.087 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `33.48 kB`<br />`11.037 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `117.938 kB`<br />`35.399 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `57.131 kB`<br />`15.951 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `103.682 kB`<br />`31.867 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3ca7917d818ccde26b1dc172241f88a6e8f322b3'>3ca7917d818ccde26b1dc172241f88a6e8f322b3</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/Avatar-mount_base.html">1340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/Avatar-mount.html">1325</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/Button-mount_base.html">942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/Button-mount.html">948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProvider-mount_base.html">1595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProvider-mount.html">1584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-mount_base.html">625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-mount.html">633</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">589</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">619</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/MakeStyles-mount_base.html">1936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/MakeStyles-mount.html">1929</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/SpinButton-mount_base.html">2569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25735/perf-test-react-components/SpinButton-mount.html">2581</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25735&commitId=8b7d1d20b08e1c4f37c489d2cfdb26367e6c1c21&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1749 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+active+badge.normal.chromium.png|9| Changed|
|Avatar Converged.size+active+ring-shadow.normal.chromium.png|4| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
