### PR TITLE
v9 Breaking Changes for Final Release Candidate

### LINKED ISSUE #22130: Coordinate Breaking RC Changes
## Problem

During Fluent UI React v9 RC we have discovered some deprecations and breaking changes we want to give serious consideration. There is a high bar for making any breaking changes as we move from RC to Stable v9 and any breaks we do make must be done in a coordinated fashion that eases any upgrade pain for consumers and is simple to communicate. Ideally this will make upgrading simpler for the core development team as well.

We need to collect all potential breaking changes to be made as part of RC and have a plan for evaluating and implementing them.

## Appetite

6 weeks.

## Solution

All proposed breaking changes will be linked to this issue so we can easily see the scope of proposed change. As part of moving from RC to Stable we will assemble a "ship room" to consider each proposal and either move forward with it or discard it.

The workflow for all proposed changes is:

1. Review the change and decide whether or not to move forward with it.
    1. Some considerations in no particular order
        1. What is Partner appetite/need for this upgrade?
        2. Can it be automated via something like codemods or is it a relatively simple find-n-replace?
        3. Can the break be worked around?
        4. What are the benefits of making the break vs the costs of not making it? For example, are we using an OSS library that is no longer supported?
        5. Is there a dramatic performance benefit of making the change?
        6. ...please add other considerations, keeping in mind this isn't an exhaustive list...
2. If we **will not** make the change
    1. Note the decision and discard the proposal
3. If we **will** make the change
    1. Write up docs explaining how to migrate from the old API to the new one. Write any tooling like codemods to assist in the upgrade.
    2. Communicate the change with Partners
    3. Make the change in a backwards compatible manner and ship this version so Partners can piecemeal upgrade their applications.
    4. Remove the old API and ship this version once all Partners have upgraded.
    5. Ensure you have availability to help Partners through the upgrade process

## Risks (Rabbit holes)

1. Discussing proposed changes exhaustively. We should aim to quickly make yes or no decisions about which changes to make.
2. Spending lots of time writing codemods

## Out of scope (No-gos)

1. Significant reworking/refactoring of APIs. This is not an opportunity to fundamentally rethink features but clean up little inconsistencies and set Partners and the development team up for success in the long term.

### PR DESCRIPTION
**Pull request by spmonahan**
⚠️ BREAKING CHANGES ⚠️

⚠️ DO NOT MERGE THIS WITHOUT SPEAKING WITH @spmonahan FIRST ⚠️

This PR introduces breaking changes into Fluent UI v9 and should only be merged _after_ we cut our final non-breaking RC release.

This pull request rolls several changes into a single "breaking change" branch. This approach allows us to merge all breaking changes and resolve all merge conflicts off the `master` branch.

For all the changes contained in this PR see: #22130

Fixes #22130

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |     Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                    Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: | ----------------------------: | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `33.02 kB`<br />`9.066 kB` |   `32.887 kB`<br />`9.008 kB` | `-133 B` <br />`-58 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `39.83 kB`<br />`10.293 kB` |  `39.697 kB`<br />`10.207 kB` | `-133 B` <br />`-86 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `34.814 kB`<br />`9.655 kB` |   `34.681 kB`<br />`9.593 kB` | `-133 B` <br />`-62 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          | `42.095 kB`<br />`10.964 kB` |   `41.867 kB`<br />`10.88 kB` | `-228 B` <br />`-84 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `43.951 kB`<br />`9.988 kB` |   `43.818 kB`<br />`9.928 kB` | `-133 B` <br />`-60 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `180.2 kB`<br />`50.239 kB` | `180.067 kB`<br />`50.197 kB` | `-133 B` <br />`-42 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |  `14.224 kB`<br />`4.719 kB` |   `14.226 kB`<br />`4.714 kB` |     `2 B` <br />`-5 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 | `42.939 kB`<br />`14.782 kB` |  `42.925 kB`<br />`14.779 kB` |   `-14 B` <br />`-3 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |          Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                |  `73.734 kB`<br />`22.498 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                         |  `45.608 kB`<br />`13.312 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                            |   `21.002 kB`<br />`6.628 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                              |   `21.915 kB`<br />`6.933 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                            |   `22.246 kB`<br />`6.672 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     |  `59.002 kB`<br />`16.923 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               |  `54.287 kB`<br />`15.672 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |    `7.793 kB`<br />`3.327 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |    `9.363 kB`<br />`3.841 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |     `7.765 kB`<br />`3.35 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> |  `34.078 kB`<br />`11.098 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                      |    `15.55 kB`<br />`5.595 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                            |   `10.235 kB`<br />`4.036 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                            |   `22.174 kB`<br />`7.304 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                            |    `8.546 kB`<br />`3.574 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                              |   `11.422 kB`<br />`4.648 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                               | `110.243 kB`<br />`33.543 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                  | `113.418 kB`<br />`34.011 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                      | `101.158 kB`<br />`30.817 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                       |   `14.127 kB`<br />`5.299 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                            |  `29.468 kB`<br />`10.091 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                  |   `13.651 kB`<br />`5.484 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                         |   `17.132 kB`<br />`6.365 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                         |   `25.557 kB`<br />`8.266 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                             |  `41.865 kB`<br />`11.861 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                      |   `17.795 kB`<br />`5.951 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                         |   `25.439 kB`<br />`8.247 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                             |   `10.904 kB`<br />`4.298 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6cb084a7afe7d662dc2d9d65b91474f132566390'>6cb084a7afe7d662dc2d9d65b91474f132566390</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/Avatar-mount_base.html">1236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/Avatar-mount.html">1263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/Button-mount_base.html">763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/Button-mount.html">761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProvider-mount_base.html">2352</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProvider-mount.html">2358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-mount_base.html">390</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-mount.html">397</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">324</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">448</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/MakeStyles-mount_base.html">1980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23092/perf-test-react-components/MakeStyles-mount.html">2002</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by khmakoto — CHANGES_REQUESTED** [review]
Adding a block so this isn't unintentionally merged before time.

**Review by andrefcdias — APPROVED** [review]
👍🏻 for Card, Text and Image

**Review by ling1726 — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
