### PR TITLE
fix(Calendar): focus indicator styles moved to correct element

### PR DESCRIPTION
**Pull request by smhigley**
This issue was surfaced on our docs site, since it adds `outline: 0` styles that are not present on storybook.

Our Calendar/Datepicker has been using default browser focus styles for the date grid since we moved the focus target from the button to the `<td>` element. This PR fixes that by moving the focus styles to the `<td>` element.

I also had to adjust the selected date style, since both it and our focus styles used the `::after` pseudo element. Now the selected date uses `::before`.

Updated cell focus outline (this was previously what was implemented before the regression):
screenshot of month calendar with a grid of dates, and a think black line around one date

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b01ac1a166a8dc67a6c53409d9fe86977517bae6'>b01ac1a166a8dc67a6c53409d9fe86977517bae6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/BaseButton-mount_base.html">790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/BaseButton-mount.html">779</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Breadcrumb-mount_base.html">2332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Breadcrumb-mount.html">2370</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Checkbox-mount_base.html">1290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Checkbox-mount.html">1298</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/CheckboxBase-mount_base.html">1119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/CheckboxBase-mount.html">1095</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ChoiceGroup-mount_base.html">4078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ChoiceGroup-mount.html">4088</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ComboBox-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ComboBox-mount.html">829</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/CommandBar-mount_base.html">9196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/CommandBar-mount.html">9187</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ContextualMenu-mount_base.html">10173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ContextualMenu-mount.html">10175</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DefaultButton-mount_base.html">1000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DefaultButton-mount.html">996</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRow-mount_base.html">3315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRow-mount.html">3294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRowFast-mount_base.html">3325</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRowFast-mount.html">3337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRowNoStyles-mount_base.html">3172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DetailsRowNoStyles-mount.html">3158</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Dialog-mount_base.html">1962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Dialog-mount.html">1998</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DocumentCardTitle-mount_base.html">155</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/DocumentCardTitle-mount.html">157</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Dropdown-mount_base.html">2862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Dropdown-mount.html">2811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/FocusTrapZone-mount_base.html">1626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/FocusTrapZone-mount.html">1589</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/FocusZone-mount_base.html">1565</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/FocusZone-mount.html">1580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/IconButton-mount_base.html">1551</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/IconButton-mount.html">1533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Label-mount_base.html">299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Label-mount.html">319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Layer-mount_base.html">2546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Layer-mount.html">2544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Link-mount_base.html">402</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Link-mount.html">408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/MenuButton-mount_base.html">1262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/MenuButton-mount.html">1280</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/MessageBar-mount_base.html">1830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/MessageBar-mount.html">1829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Nav-mount_base.html">2884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Nav-mount.html">2841</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/OverflowSet-mount_base.html">942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/OverflowSet-mount.html">960</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Panel-mount_base.html">1857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Panel-mount.html">1859</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Persona-mount_base.html">879</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Persona-mount.html">879</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Pivot-mount_base.html">1251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Pivot-mount.html">1259</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/PrimaryButton-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/PrimaryButton-mount.html">1117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Rating-mount_base.html">6717</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Rating-mount.html">6745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SearchBox-mount_base.html">1129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SearchBox-mount.html">1151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Shimmer-mount_base.html">2132</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Shimmer-mount.html">2149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Slider-mount_base.html">1681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Slider-mount.html">1698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SpinButton-mount_base.html">4364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SpinButton-mount.html">4340</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Spinner-mount_base.html">364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Spinner-mount.html">370</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SplitButton-mount_base.html">2778</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SplitButton-mount.html">2751</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Stack-mount_base.html">451</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Stack-mount.html">442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/StackWithIntrinsicChildren-mount_base.html">2016</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/StackWithIntrinsicChildren-mount.html">2013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/StackWithTextChildren-mount_base.html">4519</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/StackWithTextChildren-mount.html">4506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SwatchColorPicker-mount_base.html">10096</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/SwatchColorPicker-mount.html">10143</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TagPicker-mount_base.html">2365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TagPicker-mount.html">2354</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TeachingBubble-mount_base.html">87434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TeachingBubble-mount.html">85990</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Text-mount_base.html">368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Text-mount.html">383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TextField-mount_base.html">1215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/TextField-mount.html">1249</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-mount_base.html">1021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-mount.html">1036</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-virtual-rerender_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-virtual-rerender.html">573</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1650</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Toggle-mount_base.html">699</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/Toggle-mount.html">691</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/buttonNative-mount_base.html">118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23311/perf-test/buttonNative-mount.html">104</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
is there a reason we have to move the 'selected date style'? Is selected date AND focus style supposed to show up at the same time? Moving the styles from one pseudo to another could easily break someone that did custom styles to this control.

**Comment by smhigley** [comment]
> is there a reason we have to move the 'selected date style'? Is selected date AND focus style supposed to show up at the same time? Moving the styles from one pseudo to another could easily break someone that did custom styles to this control.

The issue is the existing focus style already uses `::after`, and the selected date style is much newer (within the last few months, I think, since it was changed following an issue about contrast). I don't want to change the focus style since it's been around for so long, and I don't think there's anything we can do about the selected date style that would have less impact. The selection + focus does need to be able to show up at the same time IMO, since otherwise it's not possible to tell if the focused date is also selected.

**Review by jhellesen — APPROVED** [review]

**Comment by smhigley** [comment]
@conniec218 yup! If you click the Details link for "Pull request demo site" in the list of checks, you can see the docs site build for this PR

**Pull request merged**
