### PR TITLE
Azure Theme: Updating control outlines, pivot indentation and label weight

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Part of #15285
- [x] Include a change request file using `$ yarn change`

#### Description of changes

_Cherry-pick of #15395._

_Original PR description:_

### Dropdowns 
- Removed control outline via callout, updated separator line for each theme
- Per Figma designs: dropdown input 24px and dropdown items 32px 

### Callout
- implementation vs figma 
<div style="display:flex">

</div>

### Label 
- removed semibold from label per label redesign 

### Pivots
- Removed left/right padding from individual pivot
- Fixed indentation of Pivot on rest state, aligned with rest of content on the page.

### CODE REVIEW

**Comment by Jacqueline-ms** [comment]
I'm noticing that compound buttons are breaking in this branch, trying to see why. 

image

**Comment by Jacqueline-ms** [comment]
Cannot replicate this compound button error in master branch.

**Comment by khmakoto** [comment]
@Jacqueline-ms how are you testing the `CompoundButtons` with this branch if you don't mind me asking so that I can see what's happening there.

**Comment by Jacqueline-ms** [comment]
@khmakoto Not a problem, yarn start at the root and then select "@fluentUI/azure-themes".

**Comment by Jacqueline-ms** [comment]
Looks great! Thanks for doing this.

**Review by Jacqueline-ms — APPROVED** [review]

**Review by ecraig12345 — APPROVED** [review]

**Pull request merged**
