### PR TITLE
Adds Tests For Fluent Button Web Component

### PR DESCRIPTION
**Pull request by halerankin**
Adds Playwright tests for Fluent Button web component.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b03b40647507909a151f966be6cd67b65cfcf3f9'>b03b40647507909a151f966be6cd67b65cfcf3f9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by halerankin** [comment]
Note: I'm getting flaky tests. I'll review and make adjustments,

**Comment by levithomason** [comment]
The build appears to have passed, but it seems 3 tests failed? They are marked as "flaky" in the logs:
https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=315660&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5&l=1501

**Tests**

image

image

image

**Flaky Tests**

Side note, I would highly encourage that we consider only 0 flaky tests to be a pass. Otherwise, we'll end up with many flaky tests and low confidence.

**Comment by JustSlone** [comment]
@halerankin closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
