### PR TITLE
Dark theme: Fixes to persona, peoplePicker, and dateTime

### LINKED ISSUE #11827: Datepicker calendar content illegible in dark mode
### Environment Information

- **Package version(s)**: none
- **Browser and OS versions**: Version 79.0.3945.117

#### Actual behavior:

Calendar days are illegible on components demo site in dark mode.
Not sure if it the bug is reproducing in npm packages since I've never used the library.
https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker 
Screenshot 2020-01-29 at 11 15 52

#### Expected behavior:
Calendar works in dark mode on the demo website.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

### PR DESCRIPTION
**Pull request by marygans**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #11827
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Dark Mode Updates to: 
- Persona
- PeoplePicker
- DateTime Picker

### **Before:** 
Persona: 
Screen Shot 2020-03-25 at 12 05 27 PM
Screen Shot 2020-03-25 at 12 05 14 PM

PeoplePicker:
Screen Shot 2020-03-25 at 12 05 48 PM
Screen Shot 2020-03-25 at 12 05 43 PM
Screen Shot 2020-03-25 at 12 05 57 PM

Calendar: 
Screen Shot 2020-03-25 at 12 06 12 PM

### **After:**
Persona:
Screen Shot 2020-03-25 at 11 57 20 AM
Screen Shot 2020-03-25 at 11 58 10 AM

PeoplePicker: 
Screen Shot 2020-03-25 at 11 57 40 AM
Screen Shot 2020-03-25 at 11 57 49 AM

Calendar: 
Screen Shot 2020-03-25 at 11 58 30 AM

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12423)

### CODE REVIEW

**Comment by marygans** [comment]
> Run `yarn change` build's failing on the check change step: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=61003&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=e32f6c0c-095d-5644-3d3c-8457b0141736

I posted in teams but I'm getting something weird when I do a yarn change and Im no sure why. I didn't make changes to all of these packages. 

Here is a screenshot:

 

yarn-change-image

**Comment by tavikukko** [comment]
any changes getting this forward?

**Comment by bhushan2511** [comment]
Please fix this issue, customer experience is terrible:

Dark-Mode-disaster

**Comment by marygans** [comment]
> Run `yarn change` build's failing on the check change step: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=61003&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=e32f6c0c-095d-5644-3d3c-8457b0141736

Done! Sorry for the ghosting on this

**Comment by Debml** [comment]
@marygans correct me if I'm wrong, but this won't add native theme-ing support to the component for people using a theme customizer, right?

**Comment by bhushan2511** [comment]
Could you please let me know when this changes might get merged? Its critical for our team, its been almost a month since this PR is open, please let me know if its going to take another month, if so our team will work on creating custom style for this component.

**Comment by tavikukko** [comment]
Updated to the latest office-ui-fabric-react (7.110.0) but seems like the Calendar component dark mode did not get fixed? I thought it was part of this PR. Am I missing something @marygans ? Thanks.

**Comment by bhushan2511** [comment]
@marygans This PR did not fix the dark mode issue, could you please take a look?

**Comment by tavikukko** [comment]
ok got it working,
You need to import the fixed themes from theme-samples package. When applying the DarkCustomizations theme to the app, then the DatePicked component works correctly.

image

```typescript
import { DarkCustomizations, DefaultCustomizations } from '@uifabric/theme-samples'
/* our other code */
return (
 <Fabric>
  <Customizer {...DarkCustomizations}>
  </Customizer>
 </Fabric>
)
```
So the fix was made in the theme, not the component it self.

**Pull request merged**
