### PR TITLE
chore(react-input, react-textarea): Deprecating filled with shadow appearance variants

### PR DESCRIPTION
**Pull request by sopranopillow**
This PR removes the filled with shadow appearance variants. This is due to the shadow appearances not being visible when used on a background that meets our contrast ratio guidelines. 

This is how our current docs show the variants:
image

To be able to see the shadow, a lighter background is required like this one:
image

This contradicts our guidelines on using a background with enough contrast ratio for accessibility requirements.

### CODE REVIEW

**Comment by spmonahan** [comment]
> This PR removes the filled with shadow appearance variants due to encouraging the use of a background that doesn't meet an accessible contrast ratio.

Can you expand on the issue a bit more please?

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                               Change |
| :----------------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>          | `23.757 kB`<br />`7.704 kB` | `23.762 kB`<br />`7.706 kB` | `5 B` <br />`2 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr> | `25.013 kB`<br />`8.133 kB` | `25.018 kB`<br />`8.133 kB` |                                                                                                `5 B` <br /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.672 kB`<br />`52.359 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.394 kB`<br />`11.007 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.851 kB`<br />`1.964 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `44.102 kB`<br />`12.425 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/483f160617f1037e672fe74b8e52abfee9378517'>483f160617f1037e672fe74b8e52abfee9378517</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by sopranopillow** [comment]
> > This PR removes the filled with shadow appearance variants due to encouraging the use of a background that doesn't meet an accessible contrast ratio.
> 
> Can you expand on the issue a bit more please?

I just updated it :)

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/Avatar-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/Avatar-mount.html">1312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/Button-mount_base.html">933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/Button-mount.html">949</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProvider-mount_base.html">1604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProvider-mount.html">1571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-mount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-mount.html">633</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">585</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">630</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">625</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/MakeStyles-mount_base.html">1886</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/MakeStyles-mount.html">1887</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/SpinButton-mount_base.html">2529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24900/perf-test-react-components/SpinButton-mount.html">2537</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by spmonahan — APPROVED** [review]

**Pull request merged**
