### PR TITLE
fix(BasePicker): suggestion list is opened event if the inputvalue is…

### PR DESCRIPTION
**Pull request by tdetugny**
#### Pull request checklist

- [x] Include a change request file using `$ yarn change`

#### Description of changes
currently:
When user enter value then remove it, the suggestion is closed
Expected:
When user enter value then remove it, the suggestion **should always be open**

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by joschect** [comment]
@tdetugny Thanks for submitting this pr! Was there a bug/regression that was recently introduced? There were some changes made within the past weeks. I think that it closing when there are no options might be expected behavior but  I'd like to know more about your use case!

**Comment by tdetugny** [comment]
@joschect I think it's an old issue. Here's an example: I enter the letter "A" and then I delete it. The suggestion list disappears.
https://www.loom.com/share/ea51ea249b49428aba98ec3ecfec3eaf
after my patch, it doesn't disappear anymore:
https://www.loom.com/share/74d643c46dc04691bddce6b2f04cd3fe

**Comment by joschect** [comment]
@tdetugny I believe that this is actually intended behavior. The issue could be that we don't re-display the MRU if that kind of function is provided. You can retrigger it as a user by pressing enter or clicking on the input again.

**Review by khmakoto — CHANGES_REQUESTED** [review]
Thanks for submitting this fix, but due to work we're currently doing to prepare `master` for our version 8 beta release, we're asking contributors to either wait a couple weeks to submit fixes (if it's not urgent) or submit to the new `7.0` branch (if it's urgent). See #15222 for more details.

**Pull request closed without merging**
