### PR TITLE
chore(checkbox): update spec

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Update checkbox spec in favor of having 

`<Checkbox checked={true|false|'mixed'} />` 

other than

`<Checkbox checked={Boolean} indeterminate={Boolean} />`

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by JustSlone** [comment]
Should we add the motivation for the `<Checkbox checked={true|false|'mixed'} />` pattern in the spec? Are we planning on accepting the array of values as well?

**Comment by xugao** [comment]
I am good with this change. Only thing is I am not sure about the value 'mixed'. I wonder if calling it 'indeterminate' is better

**Comment by ecraig12345** [comment]
> I am good with this change. Only thing is I am not sure about the value 'mixed'. I wonder if calling it 'indeterminate' is better.

`indeterminate` would be more consistent with the HTML attribute name. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate

**Comment by layershifter** [comment]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html

`mixed` is proposed because it matches ARIA value for `aria-checked`.

**Comment by layershifter** [comment]
> > I am good with this change. Only thing is I am not sure about the value 'mixed'. I wonder if calling it 'indeterminate' is better.
> 
> `indeterminate` would be more consistent with the HTML attribute name. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate

In the same time:

> Note: No browser currently supports indeterminate as an attribute. It must be set via JavaScript. See Indeterminate state checkboxes for details.

And this is actually extremely confusing, at least for me.

**Comment by layershifter** [comment]
The idea is inspired by [this Tweet](https://twitter.com/markdalgleish/status/1331497695807107072?s=20), for me there are two things:
- `Checkbox` has three states, while `checked={false}` + indeterminate={false}` are adding forth without any effect
- `indeterminate` is a HTML attribute, but can be set only via DOM 😱

**Comment by levithomason** [comment]
I just met with @assuncaocharles and @layershifter and I also support `checked='mixed'` as a replacement to the `indeterminate`. This API is inline with current ARIA specs and also will be compatible with future potential browser platform updates. We should always think of API changes as if they were browser platform updates and use that as a litmus test.

We should take this point to Open UI as well and suggest that the platform support a `mixed` value.  I wouldn't be surprised if others have already suggested it.

**Review by layershifter — APPROVED** [review]

**Review by xugao — APPROVED** [review]
LGTM. Thanks for everyone's inputs!

**Pull request merged**
