### PR TITLE
fix(scripts): make lint errors reporting propagate to STDOUT during pre-commit (lint-staged exec)

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

- if linting fails on pre-commit any eslint error stdout is consumed by subprocess and nothing is printed to user besides `FAILURE`
- if you touched/created `cypress.config.ts` within your package/pr pre-commit linting will fail on `import/no-extraneous-dependencies` rule violation.

## New Behavior

- linting failures during pre-commit are propagated to STDOUT thus reported by eslint 
- if you touched/created `cypress.config.ts` within your package/pr pre-commit linting will pass (cypress.config.ts is now part of devdependecy globs for import rule configuration)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3f806f907d1e5389101750b21a751bdb8c45a736'>3f806f907d1e5389101750b21a751bdb8c45a736</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Avatar-mount_base.html">1708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Avatar-mount.html">1728</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Button-mount_base.html">1173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Button-mount.html">1144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProvider-mount_base.html">2031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProvider-mount.html">2003</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-mount_base.html">733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-mount.html">733</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">690</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">734</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/MakeStyles-mount_base.html">2380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/MakeStyles-mount.html">2350</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Persona-mount_base.html">4016</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/Persona-mount.html">4084</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/SpinButton-mount_base.html">3305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test-react-components/SpinButton-mount.html">3358</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 4 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26212&commitId=60f213902bd1a7056a80a59ec22ec9476a0c93a2&env=prod)

✅ There was 4 screenshots added, 0 screenshots removed, 1041 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/BaseButton-mount_base.html">1210</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/BaseButton-mount.html">1170</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Breadcrumb-mount_base.html">2798</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Breadcrumb-mount.html">2856</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Checkbox-mount_base.html">2624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Checkbox-mount.html">2672</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/CheckboxBase-mount_base.html">2364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/CheckboxBase-mount.html">2368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ChoiceGroup-mount_base.html">4285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ChoiceGroup-mount.html">4299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ComboBox-mount_base.html">1167</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ComboBox-mount.html">1144</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/CommandBar-mount_base.html">9261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/CommandBar-mount.html">9252</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ContextualMenu-mount_base.html">10195</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ContextualMenu-mount.html">10097</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DefaultButton-mount_base.html">1375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DefaultButton-mount.html">1338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRow-mount_base.html">3408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRow-mount.html">3361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRowFast-mount_base.html">3380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRowFast-mount.html">3378</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRowNoStyles-mount_base.html">3213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DetailsRowNoStyles-mount.html">3253</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Dialog-mount_base.html">2924</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Dialog-mount.html">2937</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DocumentCardTitle-mount_base.html">568</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/DocumentCardTitle-mount.html">587</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Dropdown-mount_base.html">3122</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Dropdown-mount.html">3150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/FocusTrapZone-mount_base.html">1961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/FocusTrapZone-mount.html">1927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/FocusZone-mount_base.html">1962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/FocusZone-mount.html">1984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-mount_base.html">1822</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-mount.html">2053</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-virtual-rerender_base.html">1088</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-virtual-rerender.html">1108</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedList-virtual-rerender-with-unmount.html">1596</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-mount_base.html">565</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-mount.html">571</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-virtual-rerender_base.html">544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-virtual-rerender.html">549</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">567</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/IconButton-mount_base.html">1801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/IconButton-mount.html">1797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Label-mount_base.html">744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Label-mount.html">750</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Layer-mount_base.html">4180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Layer-mount.html">4178</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Link-mount_base.html">863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Link-mount.html">843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/MenuButton-mount_base.html">1609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/MenuButton-mount.html">1636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/MessageBar-mount_base.html">2336</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/MessageBar-mount.html">2344</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Nav-mount_base.html">3086</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Nav-mount.html">3075</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/OverflowSet-mount_base.html">1396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/OverflowSet-mount.html">1421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Panel-mount_base.html">2490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Panel-mount.html">2484</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Persona-mount_base.html">1297</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Persona-mount.html">1284</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Pivot-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Pivot-mount.html">1528</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/PrimaryButton-mount_base.html">1493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/PrimaryButton-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Rating-mount_base.html">6994</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Rating-mount.html">6940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SearchBox-mount_base.html">1505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SearchBox-mount.html">1498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Shimmer-mount_base.html">2894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Shimmer-mount.html">2927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Slider-mount_base.html">2107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Slider-mount.html">2097</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SpinButton-mount_base.html">4258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SpinButton-mount.html">4271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Spinner-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Spinner-mount.html">835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SplitButton-mount_base.html">2839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SplitButton-mount.html">2842</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Stack-mount_base.html">863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Stack-mount.html">863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/StackWithIntrinsicChildren-mount_base.html">2209</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/StackWithIntrinsicChildren-mount.html">2260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/StackWithTextChildren-mount_base.html">4912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/StackWithTextChildren-mount.html">4913</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SwatchColorPicker-mount_base.html">9406</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/SwatchColorPicker-mount.html">9398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TagPicker-mount_base.html">2331</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TagPicker-mount.html">2307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TeachingBubble-mount_base.html">74626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TeachingBubble-mount.html">76518</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Text-mount_base.html">814</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Text-mount.html">822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TextField-mount_base.html">1581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/TextField-mount.html">1549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-mount_base.html">1426</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-mount.html">1442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-virtual-rerender_base.html">1132</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-virtual-rerender.html">1150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Toggle-mount_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/Toggle-mount.html">1139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/buttonNative-mount_base.html">525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26212/perf-test/buttonNative-mount.html">526</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [🕵 FluentUI-v0 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26212&commitId=60f213902bd1a7056a80a59ec22ec9476a0c93a2&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1258 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Checkbox.Checkbox Example Checked Mixed.chromium.png|72| Changed|
|Checkbox.Checkbox Example.chromium.png|51| Changed|

</details>


<div id="vrtCommentFluentUI-v0"/>

**Review by spmonahan — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
