### PR TITLE
chore: Force bump all v9 packages to release correct source maps

### LINKED ISSUE #21686: create-react-app logs warnings for source maps with react-components
simply install create-react-app and react-components and we get lots of this error

image

Code used in create-react-app, pulled from the [card example in the docsite](https://6002298f95a00c00213f4d55-tarzihbtdc.chromatic.com/?path=/docs/preview-components-card--default#action-card)

```tsx
import * as React from "react";

import { Body, Caption } from "@fluentui/react-text";

import { Button } from "@fluentui/react-button";
import { OpenRegular, MoreVerticalRegular } from "@fluentui/react-icons";
import {
  Card,
  CardFooter,
  CardHeader,
  CardPreview,
} from "@fluentui/react-components/unstable"; // codesandbox-dependency: @fluentui/react-card ^9.0.0-beta

const ASSET_URL =
  "https://raw.githubusercontent.com/microsoft/fluentui/master/packages/react-card";

const avatarMauricioURL = ASSET_URL + "/assets/avatar_mauricio.svg";
const powerpointLogoURL = ASSET_URL + "/assets/powerpoint_logo.svg";
const aiDeckTemplateURL = ASSET_URL + "/assets/ai_deck_template.png";

export const Default = () => {
  return (
    <>
      <Card tabIndex={0} onClick={() => console.log("Test action")}>
        <CardHeader
          image={<img src={avatarMauricioURL} alt="Face of a person" />}
          header={
            <Body>
              <b>Mauricio August</b> + 7 others edited
            </Body>
          }
          description={<Caption>Artificial Intelligence Deck</Caption>}
          action={
            <Button
              appearance="transparent"
              icon={<MoreVerticalRegular fontSize={20} />}
            />
          }
        />

        <CardPreview
          logo={<img src={powerpointLogoURL} alt="Microsoft PowerPoint logo" />}
        >
          <img
            src={aiDeckTemplateURL}
            alt="Preview of an artificial intelligence slide deck"
          />
        </CardPreview>

        <CardFooter>
          <Button icon={<OpenRegular fontSize={16} />}>View changes</Button>
        </CardFooter>
      </Card>
    </>
  );
};
```

### PR DESCRIPTION
**Pull request by ling1726**
## Current Behavior

Source maps do not have correct source code

## New Behavior

Source maps have correct source code

## Related Issue(s)

Fixes #21686

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `54.905 kB`<br />`17.567 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `44.339 kB`<br />`12.767 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `20.831 kB`<br />`6.533 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.699 kB`<br />`6.827 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `21.785 kB`<br />`6.507 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `27.932 kB`<br />`8.025 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `33.196 kB`<br />`8.987 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `29.584 kB`<br />`8.598 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `35.729 kB`<br />`9.676 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `37.209 kB`<br />`8.627 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `48.512 kB`<br />`14.352 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `43.987 kB`<br />`13.188 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |     `7.615 kB`<br />`3.23 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `8.893 kB`<br />`3.675 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.806 kB`<br />`3.357 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `165.744 kB`<br />`46.848 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.479 kB`<br />`10.625 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.256 kB`<br />`5.511 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.067 kB`<br />`3.934 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |     `21.5 kB`<br />`7.116 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.303 kB`<br />`3.472 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.064 kB`<br />`4.487 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `102.914 kB`<br />`31.69 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `105.269 kB`<br />`32.056 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `95.841 kB`<br />`29.229 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `6.249 kB`<br />`2.163 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |   `22.828 kB`<br />`7.951 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `13.962 kB`<br />`5.231 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `22.928 kB`<br />`7.747 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |    `6.773 kB`<br />`2.879 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `25.387 kB`<br />`8.204 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `10.755 kB`<br />`4.212 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.067 kB`<br />`4.558 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                                        |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `29.426 kB`<br />`6.551 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |     `18.42 kB`<br />`5.27 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `42.479 kB`<br />`14.593 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b3abd0f59ff90fd36e13e57b655840658c95326c'>b3abd0f59ff90fd36e13e57b655840658c95326c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Avatar-mount_base.html">780</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Avatar-mount.html">793</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/BaseButton-mount_base.html">915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/BaseButton-mount.html">900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Breadcrumb-mount_base.html">2620</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Breadcrumb-mount.html">2619</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ButtonNext-mount_base.html">462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ButtonNext-mount.html">457</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Checkbox-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Checkbox-mount.html">1510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/CheckboxBase-mount_base.html">1271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/CheckboxBase-mount.html">1274</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ChoiceGroup-mount_base.html">4756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ChoiceGroup-mount.html">4593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ComboBox-mount_base.html">989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ComboBox-mount.html">962</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/CommandBar-mount_base.html">9850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/CommandBar-mount.html">9940</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ContextualMenu-mount_base.html">16174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ContextualMenu-mount.html">15687</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DefaultButton-mount_base.html">1156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DefaultButton-mount.html">1131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRow-mount_base.html">3675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRow-mount.html">3661</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRowFast-mount_base.html">3665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRowFast-mount.html">3637</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRowNoStyles-mount_base.html">3457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DetailsRowNoStyles-mount.html">3535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Dialog-mount_base.html">2852</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Dialog-mount.html">2909</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DocumentCardTitle-mount_base.html">167</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/DocumentCardTitle-mount.html">191</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Dropdown-mount_base.html">3144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Dropdown-mount.html">3172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderNext-mount_base.html">1820</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderNext-mount.html">1826</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-mount_base.html">158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-mount.html">151</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-virtual-rerender.html">115</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">203</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">194</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FocusTrapZone-mount_base.html">1803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FocusTrapZone-mount.html">1771</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FocusZone-mount_base.html">1760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/FocusZone-mount.html">1811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/IconButton-mount_base.html">1721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/IconButton-mount.html">1706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Label-mount_base.html">355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Label-mount.html">366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Layer-mount_base.html">2884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Layer-mount.html">2901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Link-mount_base.html">479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Link-mount.html">488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MakeStyles-mount_base.html">1698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MakeStyles-mount.html">1655</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MenuButton-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MenuButton-mount.html">1430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MessageBar-mount_base.html">1976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/MessageBar-mount.html">1940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Nav-mount_base.html">3216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Nav-mount.html">3235</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/OverflowSet-mount_base.html">1108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/OverflowSet-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Panel-mount_base.html">2505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Panel-mount.html">2490</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Persona-mount_base.html">868</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Persona-mount.html">869</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Pivot-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Pivot-mount.html">1397</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/PrimaryButton-mount_base.html">1283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/PrimaryButton-mount.html">1290</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Rating-mount_base.html">7366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Rating-mount.html">7520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SearchBox-mount_base.html">1294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SearchBox-mount.html">1297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Shimmer-mount_base.html">2421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Shimmer-mount.html">2472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Slider-mount_base.html">1877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Slider-mount.html">1900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SpinButton-mount_base.html">4839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SpinButton-mount.html">4845</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Spinner-mount_base.html">442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Spinner-mount.html">453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SplitButton-mount_base.html">3061</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SplitButton-mount.html">3059</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Stack-mount_base.html">523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Stack-mount.html">506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/StackWithIntrinsicChildren-mount_base.html">2232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/StackWithIntrinsicChildren-mount.html">2264</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/StackWithTextChildren-mount_base.html">5123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/StackWithTextChildren-mount.html">5082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SwatchColorPicker-mount_base.html">11219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/SwatchColorPicker-mount.html">11160</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TagPicker-mount_base.html">2546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TagPicker-mount.html">2544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TeachingBubble-mount_base.html">12706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TeachingBubble-mount.html">12751</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Text-mount_base.html">441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Text-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TextField-mount_base.html">1361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/TextField-mount.html">1387</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-mount_base.html">1172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-mount.html">1169</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-virtual-rerender_base.html">616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-virtual-rerender.html">624</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1864</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Toggle-mount_base.html">815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/Toggle-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/buttonNative-mount_base.html">150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21690/perf-test/buttonNative-mount.html">149</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Review by Hotell — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

**Comment by JustSlone** [comment]
@ling1726 will this issue fully resolve #21686 for partners? Teams are hitting the source map issue when using v9 in their applications and it is causing much pain for devs.

**Comment by ling1726** [comment]
> @ling1726 will this issue fully resolve #21686 for partners? Teams are hitting the source map issue when using v9 in their applications and it is causing much pain for devs.

The issue is already fixed (but not in this PR). This PR just force bumps every package to make sure beachball publishes all of the packages to get that fix

**Pull request merged**
