### PR TITLE
fix: InfoLabel popover dismisses if the InfoButton is clicked when it is already open

### LINKED ISSUE #30725: [Bug]: InfoLabel doesn't close when clicking on the icon again
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 144.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.3.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-infolabel--default

## Actual Behavior
In **Chrome/Edge/Firefox**, when InfoLabel's popover is open, the popover doesn't close when the user clicks on the icon again.  This issue doesn't occur in Safari.

## Expected Behavior
Behavior should be as described in the documentation:
> To close the Popover, the user may click the button again

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by behowell**
## Previous Behavior

The InfoLabel popover doesn't dismiss if the InfoButton is clicked when the popover is already open. Or more accurately, it dismisses and immediately shows again. This happens because the popover gets dismissed when focus moves outside, which  happens on mouseDown on the button. Subsequently, the button's click event shows the popover again.

## New Behavior

* Don't dismiss the popover if focus moves to the InfoButton that launched it. Instead, the popover is only dismissed when focus moves outside of _both_ the popover _and_ the button.
* Use React's onBlurCapture instead of a native focusout event, to avoid an event listener leak. (The focusout listener was never removed when the ref changed.)

## Related Issue(s)

- Fixes #30725

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Avatar-mount_base.html">671</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Avatar-mount.html">653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Button-mount_base.html">323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Button-mount.html">320</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Field-mount_base.html">1156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Field-mount.html">1216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProvider-mount_base.html">740</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProvider-mount.html">716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-mount_base.html">94</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-mount.html">102</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">82</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">78</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">94</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">94</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/MakeStyles-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/MakeStyles-mount.html">855</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Persona-mount_base.html">1789</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/Persona-mount.html">1787</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/SpinButton-mount_base.html">1465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30731/perf-test-react-components/SpinButton-mount.html">1428</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `71.098 kB`<br />`20.515 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `217.205 kB`<br />`61.941 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `43.585 kB`<br />`14.352 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `7.944 kB`<br />`2.588 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/77527ac13d9b9ffc627342ef70f2a417a8f18971'>77527ac13d9b9ffc627342ef70f2a417a8f18971</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by sopranopillow — COMMENTED** [review]
Looks great, thanks for the update! Only one comment, would you mind updating the cypress tests to account for this new behavior? https://github.com/microsoft/fluentui/blob/a234ae04a43739ecc040d700f9f5d6434b64a9b6/packages/react-components/react-infolabel/src/components/InfoLabel/InfoLabel.cy.tsx#L29

**Review by Hotell — APPROVED** [review]
approving for v-build / generator added cypress component tests setup

**Review by sopranopillow — APPROVED** [review]

**Pull request merged**
