### PR TITLE
chore(react-dialog): adds RTL story example for Dialog

### PR DESCRIPTION
**Pull request by bsunderhus**
Adds RTL story to `Dialog` documentation

### CODE REVIEW

**Comment by layershifter** [comment]
What is a purpose of it? We don't have RTL examples in general (`FluentProvider` is an exception as it has `dir` prop).

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                    Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ---------------------------: | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.925 kB`<br />`51.884 kB` | `189.01 kB`<br />`51.922 kB` |    `85 B` <br />`38 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |   `85.19 kB`<br />`25.322 kB` | `84.804 kB`<br />`25.244 kB` | `-386 B` <br />`-78 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `32.876 kB`<br />`10.773 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0fa48e25fd9b173a8574c3ad3421979e627a145d'>0fa48e25fd9b173a8574c3ad3421979e627a145d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/Avatar-mount_base.html">1258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/Avatar-mount.html">1193</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/Button-mount_base.html">884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/Button-mount.html">855</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProvider-mount_base.html">1505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProvider-mount.html">1559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-mount_base.html">619</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-mount.html">633</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">592</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">623</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/MakeStyles-mount_base.html">1925</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/MakeStyles-mount.html">1931</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/SpinButton-mount_base.html">2294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24352/perf-test-react-components/SpinButton-mount.html">2279</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by bsunderhus** [comment]
> What is a purpose of it? We don't have RTL examples in general (`FluentProvider` is an exception as it has `dir` prop).

That's a good point in fact! I'd assume it would be nice to have for examples purposes

**Pull request closed without merging**
