### PR TITLE
Jieleiwang/supportwbtxextension

### PR DESCRIPTION
**Pull request by jieleiwang**
## Current Behavior

There is no icon support for wbtx file

## New Behavior

wbtx file will show whiteboard icon

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e255da7cf629534ebaaac05af3b5bb9a2f7def71'>e255da7cf629534ebaaac05af3b5bb9a2f7def71</a></sub>
<div id="bundleSizeComment9423"/>

**Review by bigbadcapers — APPROVED** [review]

**Review by Jahnp — APPROVED** [review]

**Comment by jieleiwang** [comment]
I accept terms described in the CLA document

**Comment by jieleiwang** [comment]
accept CLA

**Comment by jieleiwang** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by jieleiwang** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by smhigley — APPROVED** [review]
Just adding as a note: the .wbtx extension is a newly created file type from the Whiteboard team

**Pull request merged**
