### PR TITLE
Scrollable Pane: Fix pointer events

### LINKED ISSUE #7673: Sticky- scroll behavior
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 If the cursor is placed on[ sticky header](https://microsoft.sharepoint.com/teams/cyrusplayground/yiminlib/Forms/AllItems.aspx?enableFeatures=1207
), on scrolling down, the [scroll stops](https://microsoft-my.sharepoint.com/:v:/p/hatrived/ETlMSXTP5a1DmWMAWnrUJTsBMafNwggO15VXdU2IcNIkCw?e=CufVyC
) when component becomes sticky & scrolling (up & down) doesn’t work after a certain scroll

 
#### Expected behavior:
 Not known

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7673
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Change `pointer-events` from `none` to `auto` for ScrollablePane's sticky above/below region

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by JustSlone** [comment]
@ecraig12345 or @dzearing can you take a look at this PR? Looks like we don't have a code owner for this file setup, if there is a clear owner let me know and I'll update the codeowners.

**Comment by dzearing** [comment]
This needs a passing build so that we can actually playtest with deploy links. Rerunning the failed build.

**Comment by ecraig12345** [comment]
@dzearing The build passed. http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/13744/merge/

@leddie24 Can you please also make this change in the react-next version of ScrollablePane?

**Comment by xugao** [comment]
@ecraig12345 - ScrollablePane has not been dup'ed in `react-next` yet

**Pull request merged**
