### PR TITLE
BREAKING: `useTable` renamed to `useTableFeatures`

### PR DESCRIPTION
**Pull request by ling1726**
## ⚠️ Breaking change

In order to avoid future naming conflicts hooks have been renamed to be more specific to the `Table` component

- `useSelection` -> `useTableSelection`
- `useSort` -> `useTableSort`
- `useTable` -> `useTableFeatures` (to avoid conflict with `useTable_unstable`)

## Previous Behavior

```ts
  import { useTable, useSort, useSelection } from '@fluentui/react-components/unstable';
  const {
    getRows,
    selection: { allRowsSelected, someRowsSelected, toggleAllRows, toggleRow, isRowSelected },
    sort: { getSortDirection, toggleColumnSort, sort },
  } = useTable(
    {
      columns,
      items,
    },
    [
      useSelection({
        selectionMode: 'multiselect',
        defaultSelectedItems: new Set([0, 1]),
      }),
      useSort({ defaultSortState: { sortColumn: 'file', sortDirection: 'ascending' } }),
    ],
  );
```

## New Behavior

```ts
  import { useTableFeatures, useTableSort, useTableSelection } from '@fluentui/react-components/unstable';
  const {
    getRows,
    selection: { allRowsSelected, someRowsSelected, toggleAllRows, toggleRow, isRowSelected },
    sort: { getSortDirection, toggleColumnSort, sort },
  } = useTableFeatures(
    {
      columns,
      items,
    },
    [
      useTableSelection ({
        selectionMode: 'multiselect',
        defaultSelectedItems: new Set([0, 1]),
      }),
      useTableSort({ defaultSortState: { sortColumn: 'file', sortDirection: 'ascending' } }),
    ],
  );
```

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/Avatar-mount_base.html">1303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/Avatar-mount.html">1306</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/Button-mount_base.html">950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/Button-mount.html">946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProvider-mount_base.html">1563</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProvider-mount.html">1580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-mount_base.html">635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-mount.html">636</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">590</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">631</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/MakeStyles-mount_base.html">1893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/MakeStyles-mount.html">1914</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/SpinButton-mount_base.html">2572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25797/perf-test-react-components/SpinButton-mount.html">2570</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.975 kB`<br />`17.687 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `190.411 kB`<br />`53.077 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `33.48 kB`<br />`11.037 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f7d7f82f6b3117ce163c6fee84b03c8774bed95f'>f7d7f82f6b3117ce163c6fee84b03c8774bed95f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25797&commitId=371ea72299ba2a6dab64014a65c6b716ca9a7532&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1749 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+active+badge.normal.chromium.png|10| Changed|
|Avatar Converged.size+active+ring-shadow.normal.chromium.png|12| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Comment by layershifter** [comment]
Is there sense to also rename `useSelection` & `useSort`? `import { useSort } from '@fluentui/react-components'` might be confusing as it does not have a connection to the component.

**Review by layershifter — APPROVED** [review]

**Comment by ling1726** [comment]
> Is there sense to also rename `useSelection` & `useSort`? `import { useSort } from '@fluentui/react-components'` might be confusing as it does not have a connection to the component.


Perhaps, there's less urgency there since there's no naming conflict there

**Comment by ling1726** [comment]
In any case I've renmaed `useSelection` and `useSort`  to `useTableSelection` and `useTableSort` respectively @layershifter

**Pull request merged**
