### PR TITLE
fix(public-docsite-v9): Fix storybook NoMetaError issues

### PR DESCRIPTION
**Pull request by dmytrokirpa**
## Previous Behavior

Many stories in the Storybook configuration are missing a default export, resulting in a `NoMetaError: CSF: missing default export` and causing Storybook to skip these stories. While this does not currently break the build, it will become a breaking issue starting with Storybook version 7 and beyond.

Screenshot 2024-07-08 at 23 21 52

## New Behavior

Only stories matching the `**/*.index.stories.tsx` pattern are included in the Storybook configuration, which resolves all errors shown in the previous screenshot and clears the way for upgrading Storybook to the newer version.

## Related Issue(s)

- Part of #30858

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

**Comment by Hotell** [comment]
hmm pipeline didn't run weird - triggered manually.

can you please double-check that the new pattern catches all application stories so the output is same as before the change ?

**Comment by dmytrokirpa** [comment]
> hmm pipeline didn't run weird - triggered manually.
> 
> can you please double-check that the new pattern catches all application stories so the output is same as before the change ?

Upon double-checking, it's confirmed that all `**/*.stories.tsx` files with a default export are named `index.stories.tsx`. The sole exception is `ReactIconGrid`, which is actually a React component and should not be used by Storybook.

Screenshot 2024-07-09 at 15 07 24

**Review by Hotell — APPROVED** [review]
LGTM

**Pull request merged**
