### PR TITLE
bugfix: `Dialog`, `MenuPopover` and `PopoverTrigger` stops propagation on Escape keydown 

### PR DESCRIPTION
**Pull request by bsunderhus**
## Current Behavior

Multiple components might listen to `Escape`.

Those components might have their own `Escape` key dismiss behaviour. At the moment `Escape` key pressing will dismiss `Menu`, `Popover` and `Dialog`.

### Problem

When interacting with multiple layout components that have behaviours associated with `Escape` pressing, conflicts might happen.

E,g: a `Menu` or a `Popover` inside a `Dialog`
```tsx
const MenuInsideDialogExample = () => {
  return (
    <Dialog>
      <DialogTrigger>
        <Button>Open dialog</Button>
      </DialogTrigger>
      <DialogSurface>
        <Menu>
          <MenuTrigger>
            <Button>Toggle menu</Button>
          </MenuTrigger>

          <MenuPopover>
            <MenuList>
              <MenuItem>Item</MenuItem>
            </MenuList>
          </MenuPopover>
        </Menu>
        <DialogActions>
          <DialogTrigger>
            <Button>
              Close
            </Button>
          </DialogTrigger>
        </DialogActions>
      </DialogSurface>
    </Dialog>,
  );
}
```

In this scenario, when `Escape` is pressed inside an open `Menu` it should only dismiss `Menu`, at the moment it's currently dismissing both `Menu` and `Dialog`

## New Behavior

By stopping propagation on `Escape` keydown, this conflict is avoided since no other component will listen to this event

### CODE REVIEW

**Comment by bsunderhus** [comment]
This will not work for `inline` `Menu`, since they'll be render inside the `Dialog`. @ling1726, would you have any solutions for that case?

I was thinking maybe stopping event propagation of the event on `Menu` itself might solve it? 🤔

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `187.656 kB`<br />`51.96 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `33.359 kB`<br />`11.004 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    | `80.608 kB`<br />`24.053 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `5.851 kB`<br />`1.964 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7f8bad094dadcdb671d5746848e96b5bd4b5791a'>7f8bad094dadcdb671d5746848e96b5bd4b5791a</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/Avatar-mount_base.html">1347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/Avatar-mount.html">1296</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/Button-mount_base.html">961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/Button-mount.html">975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProvider-mount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProvider-mount.html">1623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-mount_base.html">632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-mount.html">622</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">601</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">639</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/MakeStyles-mount_base.html">1917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/MakeStyles-mount.html">1956</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/SpinButton-mount_base.html">2555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24750/perf-test-react-components/SpinButton-mount.html">2524</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by ling1726 — APPROVED** [review]

**Comment by micahgodbolt** [comment]
How about tooltip? Will this change the behavior of tooltip propagation? I've opened an issue for a customer to track it here: https://github.com/microsoft/fluentui/issues/24800

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
