### PR TITLE
feat: adding Avatar component

### PR DESCRIPTION
**Pull request by khamudom**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Added Avatar component and styles. 
Created examples in stories with the ability to change shape and toggle the badge on and off.

image

keyboard focus visual
image

### CODE REVIEW

**Comment by brookdozer** [comment]
`./fixtures/avatar.html` isn't needed, though it doesn't hurt to leave it.

**Comment by litteredwitherrors** [comment]
Getting weird rendering on the Avatar story page.

image

**Comment by bheston** [comment]
> @chrisdholt What's the plan for this? It's 5 months old.

Sorry, this is probably holding on me. I was hoping to pull together a sample of Avatars from around the web, but my main concern was around the last comment Chris tagged me in. I don't understand why `Avatar` has its own `link` attribute. I understand this would be a foundation change (deprecation), and it _is_ optional, but it seems that Avatar itself should just be the picture, or paired with the presence badge or any other combination someone can imagine, but if it needs to link somewhere it should just be inside an `Anchor` which already has the correct styling. There are so many variations even across GitHub, Discord, Teams, Edge, Office, etc. that combining the visual and the functional is more complex. This component seems stronger with less functionality.

My proposal is to deprecate `link` and not implement it in Fluent UI. This aligns with what I've seen in the Fluent UI design as well, where the only hover treatment documented is a tooltip or flyout. Our existing components already support this functionality without visual styling interactions.

**Comment by chrisdholt** [comment]
> > @chrisdholt What's the plan for this? It's 5 months old.
> 
> Sorry, this is probably holding on me. I was hoping to pull together a sample of Avatars from around the web, but my main concern was around the last comment Chris tagged me in. I don't understand why `Avatar` has its own `link` attribute. I understand this would be a foundation change (deprecation), and it _is_ optional, but it seems that Avatar itself should just be the picture, or paired with the presence badge or any other combination someone can imagine, but if it needs to link somewhere it should just be inside an `Anchor` which already has the correct styling. There are so many variations even across GitHub, Discord, Teams, Edge, Office, etc. that combining the visual and the functional is more complex. This component seems stronger with less functionality.
> 
> My proposal is to deprecate `link` and not implement it in Fluent UI. This aligns with what I've seen in the Fluent UI design as well, where the only hover treatment documented is a tooltip or flyout. Our existing components already support this functionality without visual styling interactions.

Thanks @bheston - on deprecation of link, that's fine and helpful considering where we are in the process. For tooltips, I think that's fine, though I'm curious how we would attach behavior for something like a flyout, where invoking via keyboard will need to move a user there somehow. Flyouts have a lot of interactive content in them so would we have an avatar that would primarily be a button? If we can grab what works for *most* flyouts and pri that in FAST we can do what's necessary in Fluent as divergent, not too worried about that. My primary concern is making sure that we represent *most* flyouts here.

**Comment by bheston** [comment]
> > > @chrisdholt What's the plan for this? It's 5 months old.
> > 
> > 
> > Sorry, this is probably holding on me. I was hoping to pull together a sample of Avatars from around the web, but my main concern was around the last comment Chris tagged me in. I don't understand why `Avatar` has its own `link` attribute. I understand this would be a foundation change (deprecation), and it _is_ optional, but it seems that Avatar itself should just be the picture, or paired with the presence badge or any other combination someone can imagine, but if it needs to link somewhere it should just be inside an `Anchor` which already has the correct styling. There are so many variations even across GitHub, Discord, Teams, Edge, Office, etc. that combining the visual and the functional is more complex. This component seems stronger with less functionality.
> > My proposal is to deprecate `link` and not implement it in Fluent UI. This aligns with what I've seen in the Fluent UI design as well, where the only hover treatment documented is a tooltip or flyout. Our existing components already support this functionality without visual styling interactions.
> 
> Thanks @bheston - on deprecation of link, that's fine and helpful considering where we are in the process. For tooltips, I think that's fine, though I'm curious how we would attach behavior for something like a flyout, where invoking via keyboard will need to move a user there somehow. Flyouts have a lot of interactive content in them so would we have an avatar that would primarily be a button? If we can grab what works for _most_ flyouts and pri that in FAST we can do what's necessary in Fluent as divergent, not too worried about that. My primary concern is making sure that we represent _most_ flyouts here.

Good catch. Fluent describes it as a "popover", which looks like some combination of a tooltip, flyout, and teaching tip. If there is no interactive content I suspect it would function like a tooltip, but if there is something interactive, you're right it would need to get focus. In that case from an accessibility perspective the avatar would probably be wrapped in a button instead, which we can support. Either way, I don't think _that_ would be the responsibility of the `Avatar` either, but instead a composition within `Button`.

**Review by EisenbergEffect — CHANGES_REQUESTED** [review]
See comments.

**Pull request closed without merging**
