### PR TITLE
SearchBox: disable pointer events when is focused (backport to v7)

### LINKED ISSUE #20938: SearchBox component: a cursor can't be placed after the first letter
To reproduce:
https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox
Type anything in the search box component.
Try to place cursor after the 1st letter 

#### Actual behavior:

The cursor is placed before the 1st letter. All other letters work properly.

#### Expected behavior:

Should be possible to place cursor at any position

### Priorities and help requested:

Requested priority: High

Products/sites affected: all products

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20938
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Backport of #20951. See for details https://github.com/microsoft/fluentui/issues/20938#issuecomment-987909119.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/BaseButton-mount_base.html">796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/BaseButton-mount.html">683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Breadcrumb-mount_base.html">36768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Breadcrumb-mount.html">35867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Checkbox-mount_base.html">1306</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Checkbox-mount.html">1316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/CheckboxBase-mount_base.html">1090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/CheckboxBase-mount.html">1093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ChoiceGroup-mount_base.html">4020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ChoiceGroup-mount.html">4232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ComboBox-mount_base.html">764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ComboBox-mount.html">756</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/CommandBar-mount_base.html">6593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/CommandBar-mount.html">6527</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ContextualMenu-mount_base.html">12449</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/ContextualMenu-mount.html">11837</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DefaultButton-mount_base.html">950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DefaultButton-mount.html">935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRow-mount_base.html">3258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRow-mount.html">3179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRowFast-mount_base.html">3250</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRowFast-mount.html">3251</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRowNoStyles-mount_base.html">3006</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DetailsRowNoStyles-mount.html">3083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Dialog-mount_base.html">1448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Dialog-mount.html">1441</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DocumentCardTitle-mount_base.html">1598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/DocumentCardTitle-mount.html">1592</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Dropdown-mount_base.html">2047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Dropdown-mount.html">2081</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/FocusTrapZone-mount_base.html">1471</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/FocusTrapZone-mount.html">1418</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/FocusZone-mount_base.html">1469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/FocusZone-mount.html">1516</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/IconButton-mount_base.html">1382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/IconButton-mount.html">1492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Label-mount_base.html">286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Label-mount.html">282</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Layer-mount_base.html">1647</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Layer-mount.html">1582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Link-mount_base.html">371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Link-mount.html">362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/MenuButton-mount_base.html">1235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/MenuButton-mount.html">1249</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/MessageBar-mount_base.html">1778</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/MessageBar-mount.html">1604</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Nav-mount_base.html">2793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Nav-mount.html">2766</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/OverflowSet-mount_base.html">1205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/OverflowSet-mount.html">1186</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Panel-mount_base.html">1179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Panel-mount.html">1248</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Persona-mount_base.html">669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Persona-mount.html">612</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Pivot-mount_base.html">1268</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Pivot-mount.html">1131</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/PrimaryButton-mount_base.html">1037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/PrimaryButton-mount.html">1063</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Rating-mount_base.html">6483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Rating-mount.html">6572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SearchBox-mount_base.html">1087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SearchBox-mount.html">1073</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Shimmer-mount_base.html">2165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Shimmer-mount.html">2026</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Slider-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Slider-mount.html">1273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SpinButton-mount_base.html">4282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SpinButton-mount.html">4204</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Spinner-mount_base.html">312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Spinner-mount.html">353</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SplitButton-mount_base.html">2685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SplitButton-mount.html">2685</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Stack-mount_base.html">419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Stack-mount.html">424</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/StackWithIntrinsicChildren-mount_base.html">1404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/StackWithIntrinsicChildren-mount.html">1426</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/StackWithTextChildren-mount_base.html">3992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/StackWithTextChildren-mount.html">4001</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SwatchColorPicker-mount_base.html">8721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/SwatchColorPicker-mount.html">8546</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TagPicker-mount_base.html">2442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TagPicker-mount.html">2360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TeachingBubble-mount_base.html">43788</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TeachingBubble-mount.html">44647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Text-mount_base.html">363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Text-mount.html">357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TextField-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/TextField-mount.html">1119</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Toggle-mount_base.html">656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/Toggle-mount.html">708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/button-mount_base.html">89</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20971/perf-test/button-mount.html">86</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ecraig12345 — APPROVED** [review]

**Pull request merged**
