### PR TITLE
docs(public-docsite-v9): fix document link to theme colors page

### PR DESCRIPTION
**Pull request by raylax**
## New Behavior

Fix colors page link

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/763202a8995b7ca3e9e552828e07f015ffbdc6d7'>763202a8995b7ca3e9e552828e07f015ffbdc6d7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by raylax** [comment]
So sorry, I am not familiar with the submission process

Nothing happens after running `yarn change`

Is this okay now?

**Comment by spmonahan** [comment]
> So sorry, I am not familiar with the submission process
> 
> Nothing happens after running `yarn change`
> 
> Is this okay now?

Yeah, I'll kick off the workflow now. Most documentation changes don't create a change file (this is what `yarn change` does) but I wasn't sure if the docsite would need one or not.

**Review by tudorpopams — APPROVED** [review]

**Pull request merged**
