### PR TITLE
Adds Tests For Fluent Compound Button Web Component

### PR DESCRIPTION
**Pull request by halerankin**
Adds Playwright tests for Fluent Compound Button web component.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7dc3db675004976f0ebe835c83b5982bd14caeeb'>7dc3db675004976f0ebe835c83b5982bd14caeeb</a></sub>
<div id="bundleSizeComment9423"/>

**Review by miroslavstastny — COMMENTED** [review]
Reports flaky/failed test:
```
  1 failed
    [webkit] › src/compound-button/compound-button.spec.ts:25:3 › Compound Button › should set the `disabled` attribute on the internal control 
  2 flaky
    [chromium] › src/compound-button/compound-button.spec.ts:25:3 › Compound Button › should set the `disabled` attribute on the internal control 
    [firefox] › src/compound-button/compound-button.spec.ts:25:3 › Compound Button › should set the `disabled` attribute on the internal control 
```

and lint warnings
```
packages/web-components/src/compound-button/compound-button.spec.ts
  196:5   warning  'control' is assigned a value but never used  @typescript-eslint/no-unused-vars
  378:29  warning  Avoid having conditionals in tests            playwright/no-conditional-in-test
  378:29  warning  Avoid having conditionals in tests            playwright/no-conditional-in-test
```

**Comment by halerankin** [comment]
> 

Fixed. Passes linter.

**Comment by JustSlone** [comment]
@halerankin closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
