### PR TITLE
ContextualMenu: add aria-selected to checked menu items

### PR DESCRIPTION
**Pull request by FrancisMengx**
#### Pull request checklist
- [x] Include a change request file using `$ yarn change`

#### Description of changes
In contextmenubutton drop down, aria-checked is not a valid aria property for announciator to announce the checked state. Change aria-checked to aria-selected

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12952)

### CODE REVIEW

**Comment by dzearing** [comment]
@joschect and @jurokapsiar 

Here's a codepen to illustrate a checked item in a menu:

https://codepen.io/dzearing/pen/QWjqOQp

* The role is `menuitemcheckbox`
* The `aria-checked` value is set to `true`
* There is no `aria-selected`

In reading this spec:

https://www.w3.org/TR/wai-aria-1.1/#menuitemcheckbox

This looks correct. The spec does not specify setting `aria-selected` at all.

**Comment by FrancisMengx** [comment]
I think the issue is that some times the role can be ```menuitem``` .
Just made a change when role is ```menuitemcheckbox``` then use ```aria-checked``` and when role is ```menuitem``` use ```aria-selected```.

**Comment by dzearing** [comment]
Seems like you may not have merged the change you're mentioning.

**Comment by FrancisMengx** [comment]
@dzearing  Here it is.

**Comment by FrancisMengx** [comment]
@joschect Gentle ping. Do you have any concerns on this PR?

**Comment by ecraig12345** [comment]
@joschect Can you review this?

**Pull request merged**
