### PR TITLE
refactor(scripts): introduce barrel api within `/jest`

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

- `/scripts/jest` contains both v8 and v0 that is used via deep imports across packages

## New Behavior

- `/scripts/jest` contains encapsulate v8 and v0 that is used via barrel API
- api surface has been also reduced and configs simplified

## Related Issue(s)

* Fixes partially https://github.com/microsoft/fluentui/issues/24349

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                          |        Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------- | --------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                 |        `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr> |        `554 B`<br />`348 B` |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>   |  `3.153 kB`<br />`1.299 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                    | `23.357 kB`<br />`7.361 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                      | `24.247 kB`<br />`7.643 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                    | `24.001 kB`<br />`7.049 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                              | `16.515 kB`<br />`5.921 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                    | `10.836 kB`<br />`4.283 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                    |   `9.394 kB`<br />`3.88 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                            | `11.004 kB`<br />`4.188 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                 | `10.697 kB`<br />`3.938 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                 | `19.883 kB`<br />`7.439 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                              | `20.013 kB`<br />`6.446 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                     | `11.838 kB`<br />`4.625 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                   |  `15.148 kB`<br />`5.06 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>     |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>               | `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>             | `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                    |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/51764c31f529dfc0bfde204cbd90db32da4af35b'>51764c31f529dfc0bfde204cbd90db32da4af35b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Avatar-mount_base.html">1265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Avatar-mount.html">1277</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Button-mount_base.html">918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Button-mount.html">911</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProvider-mount_base.html">1497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProvider-mount.html">1518</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-mount_base.html">584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-mount.html">587</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">540</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">573</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/MakeStyles-mount_base.html">1993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/MakeStyles-mount.html">1970</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Persona-mount_base.html">2794</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/Persona-mount.html">2777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/SpinButton-mount_base.html">2313</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test-react-components/SpinButton-mount.html">2348</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 1 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26100&commitId=bb62abe31dea5aadcc1acbf358c57edb62375f26&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1044 screenshots unchanged, 0 screenshots with different dimensions and 1 screenshots with visible difference.


  <details><summary><b>unknown</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Coachmark.Collapsed.default.chromium.png|159| Changed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/BaseButton-mount_base.html">1179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/BaseButton-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Breadcrumb-mount_base.html">2827</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Breadcrumb-mount.html">2816</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Checkbox-mount_base.html">2633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Checkbox-mount.html">2634</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/CheckboxBase-mount_base.html">2347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/CheckboxBase-mount.html">2358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ChoiceGroup-mount_base.html">4311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ChoiceGroup-mount.html">4264</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ComboBox-mount_base.html">1170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ComboBox-mount.html">1180</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/CommandBar-mount_base.html">9266</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/CommandBar-mount.html">9295</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ContextualMenu-mount_base.html">10127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ContextualMenu-mount.html">10038</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DefaultButton-mount_base.html">1355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DefaultButton-mount.html">1359</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRow-mount_base.html">3362</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRow-mount.html">3365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRowFast-mount_base.html">3327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRowFast-mount.html">3346</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRowNoStyles-mount_base.html">3194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DetailsRowNoStyles-mount.html">3212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Dialog-mount_base.html">2999</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Dialog-mount.html">2946</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DocumentCardTitle-mount_base.html">586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/DocumentCardTitle-mount.html">587</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Dropdown-mount_base.html">3161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Dropdown-mount.html">3159</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/FocusTrapZone-mount_base.html">1960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/FocusTrapZone-mount.html">1935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/FocusZone-mount_base.html">1909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/FocusZone-mount.html">1919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-mount_base.html">1802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-mount.html">2069</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-virtual-rerender_base.html">1098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-virtual-rerender.html">1101</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedList-virtual-rerender-with-unmount.html">1618</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-mount_base.html">559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-mount.html">567</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-virtual-rerender_base.html">543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-virtual-rerender.html">552</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">559</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/IconButton-mount_base.html">1766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/IconButton-mount.html">1802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Label-mount_base.html">742</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Label-mount.html">745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Layer-mount_base.html">4194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Layer-mount.html">4167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Link-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Link-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/MenuButton-mount_base.html">1590</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/MenuButton-mount.html">1582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/MessageBar-mount_base.html">2316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/MessageBar-mount.html">2324</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Nav-mount_base.html">3021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Nav-mount.html">3045</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/OverflowSet-mount_base.html">1397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/OverflowSet-mount.html">1418</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Panel-mount_base.html">2473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Panel-mount.html">2516</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Persona-mount_base.html">1284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Persona-mount.html">1297</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Pivot-mount_base.html">1503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Pivot-mount.html">1520</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/PrimaryButton-mount_base.html">1491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/PrimaryButton-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Rating-mount_base.html">6952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Rating-mount.html">6902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SearchBox-mount_base.html">1493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SearchBox-mount.html">1507</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Shimmer-mount_base.html">2951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Shimmer-mount.html">2887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Slider-mount_base.html">2138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Slider-mount.html">2102</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SpinButton-mount_base.html">4259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SpinButton-mount.html">4234</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Spinner-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Spinner-mount.html">831</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SplitButton-mount_base.html">2846</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SplitButton-mount.html">2809</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Stack-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Stack-mount.html">859</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/StackWithIntrinsicChildren-mount_base.html">2283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/StackWithIntrinsicChildren-mount.html">2246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/StackWithTextChildren-mount_base.html">4902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/StackWithTextChildren-mount.html">4948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SwatchColorPicker-mount_base.html">9403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/SwatchColorPicker-mount.html">9411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TagPicker-mount_base.html">2338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TagPicker-mount.html">2298</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TeachingBubble-mount_base.html">74059</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TeachingBubble-mount.html">74189</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Text-mount_base.html">836</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Text-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TextField-mount_base.html">1540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/TextField-mount.html">1524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-mount.html">1445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-virtual-rerender_base.html">1144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-virtual-rerender.html">1143</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2009</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1986</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Toggle-mount_base.html">1135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/Toggle-mount.html">1138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/buttonNative-mount_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26100/perf-test/buttonNative-mount.html">530</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 4 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26100&commitId=bb62abe31dea5aadcc1acbf358c57edb62375f26&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1756 screenshots unchanged, 0 screenshots with different dimensions and 4 screenshots with visible difference.


  <details><summary><b>unknown</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.basic - Dark Mode.normal.chromium.png|395| Changed|
|Avatar Converged.basic - High Contrast.normal.chromium.png|597| Changed|
|Avatar Converged.basic - RTL.normal.chromium.png|602| Changed|
|Avatar Converged.basic.normal.chromium.png|615| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Review by AtishayMsft — APPROVED** [review]
Approved on behalf of Charting team

**Review by ling1726 — APPROVED** [review]

**Review by TristanWatanabe — APPROVED** [review]

**Pull request merged**
