### PR TITLE
Update icons to v3.70

### LINKED ISSUE #11371: Please update the project log to the new version
#### Describe the feature that you would like added

With project for the web, in nov. 2019 a new project icon was introduced, please change the project icon of Office UI fabric to this new version.

#### What component or utility would this be added to

Office Icons

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

project2019_96x1

### LINKED ISSUE #11478: Missing shape icons
### Environment Information

- **Package version(s)**: Current version (https://developer.microsoft.com/en-us/fabric#/styles/web/icons#available-icons) How to see which version is used?
- **Browser and OS versions**: any

#### Actual behavior:

There are a few shape icons missing:
image

#### Expected behavior:

Following counterparts are missing:
- ShapeSolid
- CubeShapeSolid
- CircleShape
- SquareShape
- DropShape

### PR DESCRIPTION
**Pull request by Jahnp**
#### Pull request checklist

- [x] Addresses an existing issue: fixes #11478, fixes #11371, part of #11886
- [x] Include a change request file using `$ yarn change`

#### Description of changes
Updating @uifabric/icon's icon set to the latest version from the [Fabric icons tool](https://aka.ms/uifabric-icons), v3.70. This PR adds new icons from that version to the "chunked" subsets that get automatically loaded on usage. There may also be visual updates to some icons.

Apologies - I know this has a lot of changed files, but it can't really be batched. The core code/asset changes are under `packages/icons`.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12088)

### CODE REVIEW

**Comment by ecraig12345** [comment]
Size auditor is failing -- @KevinTCoughlin do the icon additions actually have any impact on bundle size for you, or do you use custom subsets?

**Comment by KevinTCoughlin** [comment]
> Size auditor is failing -- @KevinTCoughlin do the icon additions actually have any impact on bundle size for you, or do you use custom subsets?

Apologies for the delay @ecraig12345. First-party SharePoint code utilizes https://www.npmjs.com/package/@microsoft/office-ui-fabric-react-bundle which does the following:

```ts
export * from 'office-ui-fabric-react/lib/Icon';
```

The majority of third-party developers currently bundle `office-ui-fabric-react` themselves.

I anticipate the `2.918 kB` size increase here to impact first-party SharePoint. That said, I don't have a great solution to mitigate the icon bloat soonest. It is unfortunate that this icon mapping continues to grow over time.

Regarding run-time cost, at least it is a "simple" structure to parse. Unbounded increase in memory is a greater concern. See the below memory dump from SPO containing all Fabric Icon strings.

image

To address, SharePoint would have to export and utilize an icon sub-set as you mention. @Jahnp perhaps you can consider the above if you anticipate additional revisions to this package.

cc: @patmill @johnguy0 @antonlabunets

**Comment by dzearing** [comment]
@Jahnp Is this still needed? It seems there are conflicts, looks like the url may have changed?

**Comment by Jahnp** [comment]
Sorry for letting this linger. This PR is very stale at this point and many new icons have been made available since this was opened. I'm going to go ahead and abandon this for now.

Additionally, @KevinTCoughlin brings up some excellent points about the downstream impact of the constantly-growing icons package's bundle size on users of SPFx and similar solutions. I agree with the concerns and think it's probably best to avoid continued revisions like this that simply add new icons. Within SPFx, it would likely be best to investigate a custom icon subset.

Further, I'm inclined to **stop updating the default icon set** in this manner and instead recommend that users looking for new icons should consider custom icon subsets with the [the Fabric icons tool](https://aka.ms/uifabric-icons) instead.

**Pull request closed without merging**
