### PR TITLE
docs(react-infobutton): Update spec to match implementation

### LINKED ISSUE #26355: InfoButton: Update docs and spec
Issue to track the sync of the InfoButton's docs with its implementation.

### PR DESCRIPTION
**Pull request by sopranopillow**
This PR adds some minor changes to the Spec to match the actual implementation. The changes are mainly accessibility related.

## Related Issue(s)

- Fixes #26355

### CODE REVIEW

**Review by tomi-msft — APPROVED** [review]
lgtm

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |   `64.09 kB`<br />`17.544 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `201.738 kB`<br />`56.207 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `35.049 kB`<br />`11.533 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `126.948 kB`<br />`38.682 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.324 kB`<br />`2.129 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d1a7eb2d7768ccb46293ab261055fc61634ee70b'>d1a7eb2d7768ccb46293ab261055fc61634ee70b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Avatar-mount_base.html">1324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Avatar-mount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Button-mount_base.html">947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Button-mount.html">930</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Field-mount_base.html">2057</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Field-mount.html">1969</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProvider-mount_base.html">1555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProvider-mount.html">1502</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-mount_base.html">563</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-mount.html">557</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">532</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">590</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">550</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/InfoButton-mount_base.html">562</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/InfoButton-mount.html">505</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/MakeStyles-mount_base.html">1756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/MakeStyles-mount.html">1802</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Persona-mount_base.html">2900</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/Persona-mount.html">3007</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/SpinButton-mount_base.html">2384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26846/perf-test-react-components/SpinButton-mount.html">2530</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Pull request merged**
