### PR TITLE
Rename website packages

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Addresses an existing issue: Part of #13384
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Rename `@uifabric/fabric-website-resources` to `@fluentui/public-docsite-resources` and `@uifabric/fabric-website` to `@fluentui/public-docsite`.

Stop publishing the website and example packages since the only previous known consuming site is no longer under active development. (We can always change this later.)

Note that there are still a bunch of references to `fabric-website` in CDN URLs, build artifact names, and manifest names. I'm leaving these for now because a lot more work in various places would be required to update them properly.

### CODE REVIEW

**Comment by xugao** [comment]
Something went wrong with [PR deploy site](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/15439/merge/public-docsite/dist/index.html
)

**Comment by ecraig12345** [comment]
> Something went wrong with [PR deploy site](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/15439/merge/public-docsite/dist/index.html)

Not surprising, I'll take a look.

**Comment by ecraig12345** [comment]
pr-deploy-site was set to upload stuff for only `@uifabric` packages under a `dist` folder, so when the scope changed that broke. I removed the exception and updated the paths referenced in `pr-deploy-site.js`.

**Review by xugao — APPROVED** [review]
For the packages we are making as `private`. we can remove the change logs

**Pull request merged**
