### PR TITLE
SelectedPersona: Fix hover/active states in normal and high contrast modes

### PR DESCRIPTION
**Pull request by salaman**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Fixed and cleaned up SelectedPersona styles to have more consistent hover/active states in normal and HC themes.

##### Screenshots

Left: before, right: after

Normal:
image image

Hover:
image image

Selected:
image image

Selected + hover:
image image

Invalid:
image image

Invalid + hover:
image image

Invalid + selected:
image image

Normal + high contrast:
image image

Hover + high contrast:
image image

Selected + high contrast:
image image

Selected + hover + high contrast:
image image

Invalid + high contrast:
image image

Invalid + hover + high contrast:
image image

Invalid + selected + high contrast:
image image

### CODE REVIEW

**Comment by elisabethcvs** [comment]
Thanks for putting all the screenshots, definitely helps. I think for the invalid hover+selected we probably want to keep the red text. Not sure if it meets contrast ratios but I think the info is important. Maybe there's a lighter/darker version?

**Review by elisabethcvs — CHANGES_REQUESTED** [review]
Comment

**Comment by salaman** [comment]
@elisabethcvs the current OWA style doesn't preserve the red in selected state (presumably because it looks hideous against the blue) and I'm not sure it's worth the added complexity to have a different colour. There's also no `redLight`, only `red` and `redDark`. If you feel strongly for it I can add it back but it doesn't visually look good and I expect fails the contrast ratio check.

**Comment by elisabethcvs** [comment]
Nope if that's the existing default behavior then that sounds good

**Review by elisabethcvs — APPROVED** [review]

**Pull request merged**
