### PR TITLE
Fix issue where focus outline was not showing for Toggle in IE11

### LINKED ISSUE #16938: IE11: Toggle has no focus state
### Environment Information

- **Package version(s)**: 7.156.0
- **Browser and OS versions**: Internet Explorer, Win10

### Please provide a reproduction of the bug in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/7.159.0/#/examples/toggle

#### Actual behavior:
Tabbing to toggle shows no outline

#### Expected behavior:
Tabbing to toggle shows outline (can be seen in other browsers)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Any products using toggle

### PR DESCRIPTION
**Pull request by taurheim**
## Current Behavior

See bug for repro details - focus does not show for Toggle in IE11

## New Behavior

Focusing toggle in IE11 shows outline

## Related Issue(s)

Fixes #16938

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/240b1c16b5493d3d2497af761f9c179be992378f'>240b1c16b5493d3d2497af761f9c179be992378f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Avatar-mount_base.html">889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Avatar-mount.html">917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/BaseButton-mount_base.html">996</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/BaseButton-mount.html">977</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Breadcrumb-mount_base.html">2775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Breadcrumb-mount.html">2661</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ButtonNext-mount_base.html">542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ButtonNext-mount.html">540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Checkbox-mount_base.html">1587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Checkbox-mount.html">1622</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/CheckboxBase-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/CheckboxBase-mount.html">1370</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ChoiceGroup-mount_base.html">4993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ChoiceGroup-mount.html">4954</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ComboBox-mount_base.html">999</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ComboBox-mount.html">1081</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/CommandBar-mount_base.html">10446</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/CommandBar-mount.html">10631</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ContextualMenu-mount_base.html">17511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ContextualMenu-mount.html">17400</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DefaultButton-mount_base.html">1234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DefaultButton-mount.html">1205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRow-mount_base.html">3885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRow-mount.html">3941</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRowFast-mount_base.html">3929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRowFast-mount.html">3887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRowNoStyles-mount_base.html">3637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DetailsRowNoStyles-mount.html">3604</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Dialog-mount_base.html">2646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Dialog-mount.html">2726</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DocumentCardTitle-mount_base.html">187</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/DocumentCardTitle-mount.html">205</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Dropdown-mount_base.html">3310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Dropdown-mount.html">3397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderNext-mount_base.html">1925</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderNext-mount.html">1963</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-mount_base.html">183</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-mount.html">170</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-virtual-rerender.html">117</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">202</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FocusTrapZone-mount_base.html">1946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FocusTrapZone-mount.html">1901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FocusZone-mount_base.html">1884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/FocusZone-mount.html">1886</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/IconButton-mount_base.html">1837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/IconButton-mount.html">1994</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Label-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Label-mount.html">375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Layer-mount_base.html">3133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Layer-mount.html">3099</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Link-mount_base.html">501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Link-mount.html">519</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MakeStyles-mount_base.html">1775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MakeStyles-mount.html">1816</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MenuButton-mount_base.html">1571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MenuButton-mount.html">1572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MessageBar-mount_base.html">2145</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/MessageBar-mount.html">2050</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Nav-mount_base.html">3469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Nav-mount.html">3505</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/OverflowSet-mount_base.html">1169</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/OverflowSet-mount.html">1167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Panel-mount_base.html">2583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Panel-mount.html">2528</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Persona-mount_base.html">898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Persona-mount.html">885</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Pivot-mount_base.html">1525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Pivot-mount.html">1512</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/PrimaryButton-mount_base.html">1383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/PrimaryButton-mount.html">1357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Rating-mount_base.html">7988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Rating-mount.html">7863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SearchBox-mount_base.html">1457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SearchBox-mount.html">1419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Shimmer-mount_base.html">2655</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Shimmer-mount.html">2642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Slider-mount_base.html">1991</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Slider-mount.html">1991</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SpinButton-mount_base.html">5175</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SpinButton-mount.html">5206</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Spinner-mount_base.html">473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Spinner-mount.html">453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SplitButton-mount_base.html">3319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SplitButton-mount.html">3303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Stack-mount_base.html">545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Stack-mount.html">554</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/StackWithIntrinsicChildren-mount_base.html">2382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/StackWithIntrinsicChildren-mount.html">2394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/StackWithTextChildren-mount_base.html">5418</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/StackWithTextChildren-mount.html">5482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SwatchColorPicker-mount_base.html">11642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/SwatchColorPicker-mount.html">12845</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TagPicker-mount_base.html">2719</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TagPicker-mount.html">2766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TeachingBubble-mount_base.html">13634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TeachingBubble-mount.html">13698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Text-mount_base.html">444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Text-mount.html">482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TextField-mount_base.html">1471</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/TextField-mount.html">1459</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-mount_base.html">1300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-mount.html">1263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-virtual-rerender_base.html">660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-virtual-rerender.html">667</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Toggle-mount_base.html">883</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/Toggle-mount.html">858</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/buttonNative-mount_base.html">143</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21618/perf-test/buttonNative-mount.html">156</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

**Comment by spmonahan** [comment]
Hey @taurheim ! I know it doesn't immediately look like your change caused the build failure but it did. Our `react-examples` package depends on `@fluentui/react` so changes in the latter package often cause snapshot failure in the former as is the case here: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=235649&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=8250ef03-1890-59ab-a6a8-5d0b4c2baa1b&l=6813

We recently [merged a PR to address this](https://github.com/microsoft/fluentui/pull/21605). If you haven't already, you should pull from upstream and push those changes into your PR branch, then the build should pass.

**Comment by ecraig12345** [comment]
In this case the snapshot failure is in the actual Toggle tests, so you'll still need to update snapshots for that. Assuming you've configured things per our [setup guide](https://github.com/microsoft/fluentui/wiki/Setup) where the remote for your fork is called `origin` and the remote for the main repo is called `upstream`, you can run these commands to update your local copy and update snapshots:
```
git pull upstream master
yarn
yarn build --to @fluentui/react
yarn workspace @fluentui/react update-snapshots
```
Then commit and push the changes.

**Review by khmakoto — APPROVED** [review]

**Pull request merged**
