### PR TITLE
fix: potential memory leaks when using nullish coalescing

### PR DESCRIPTION
**Pull request by marcosmoura**
For more context:
- https://github.com/microsoft/fluentui/pull/29193
- https://github.com/microsoft/fluentui/issues/29192
- https://github.com/swc-project/swc/issues/7977

This applies the same fixes introduced by #29193 to other parts of our code.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Avatar-mount_base.html">634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Avatar-mount.html">609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Button-mount_base.html">321</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Button-mount.html">316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Field-mount_base.html">1117</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Field-mount.html">1093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProvider-mount_base.html">687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProvider-mount.html">685</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-mount_base.html">76</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-mount.html">82</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">65</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">57</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">78</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/InfoButton-mount_base.html">12</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/InfoButton-mount.html">11</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/MakeStyles-mount_base.html">854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/MakeStyles-mount.html">856</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Persona-mount_base.html">1755</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/Persona-mount.html">1723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/SpinButton-mount_base.html">1392</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29195/perf-test-react-components/SpinButton-mount.html">1348</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `91.584 kB`<br />`27.965 kB` |  `91.577 kB`<br />`27.953 kB` |  `-7 B` <br />`-12 B`  |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `83.657 kB`<br />`22.895 kB` |  `83.647 kB`<br />`22.892 kB` |  `-10 B` <br />`-3 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `49.035 kB`<br />`15.434 kB` |  `49.028 kB`<br />`15.436 kB` |    `-7 B` <br />`2 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |  `63.687 kB`<br />`19.786 kB` |  `63.684 kB`<br />`19.782 kB` |   `-3 B` <br />`-4 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |  `39.667 kB`<br />`10.794 kB` |  `39.657 kB`<br />`10.779 kB` | `-10 B` <br />`-15 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `47.023 kB`<br />`12.295 kB` |  `47.012 kB`<br />`12.291 kB` |  `-11 B` <br />`-4 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `44.094 kB`<br />`12.056 kB` |  `44.082 kB`<br />`12.049 kB` |  `-12 B` <br />`-7 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `52.12 kB`<br />`13.632 kB` |  `52.119 kB`<br />`13.627 kB` |   `-1 B` <br />`-5 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `56.756 kB`<br />`12.702 kB` |  `56.745 kB`<br />`12.699 kB` |  `-11 B` <br />`-3 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `91.443 kB`<br />`26.437 kB` |  `91.442 kB`<br />`26.427 kB` |  `-1 B` <br />`-10 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `86.232 kB`<br />`24.895 kB` |  `86.226 kB`<br />`24.894 kB` |   `-6 B` <br />`-1 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `14.431 kB`<br />`5.832 kB` |   `14.431 kB`<br />`5.833 kB` |                                                                                                    <br />`1 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |   `13.097 kB`<br />`5.434 kB` |   `13.097 kB`<br />`5.433 kB` |                                                                                                   <br />`-1 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `69.572 kB`<br />`19.658 kB` |  `69.547 kB`<br />`19.658 kB` |                                                                                                  `-25 B` <br /> |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `208.393 kB`<br />`59.395 kB` |  `208.345 kB`<br />`59.36 kB` | `-48 B` <br />`-35 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `90.125 kB`<br />`27.485 kB` |  `90.126 kB`<br />`27.479 kB` |    `1 B` <br />`-6 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `139.823 kB`<br />`43.055 kB` |   `139.8 kB`<br />`43.044 kB` | `-23 B` <br />`-11 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `142.559 kB`<br />`43.576 kB` | `142.536 kB`<br />`43.569 kB` |  `-23 B` <br />`-7 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `55.926 kB`<br />`17.314 kB` |  `55.919 kB`<br />`17.314 kB` |                                                                                                   `-7 B` <br /> |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `22.481 kB`<br />`8.146 kB` |   `22.478 kB`<br />`8.142 kB` |   `-3 B` <br />`-4 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 | `156.606 kB`<br />`43.603 kB` | `156.603 kB`<br />`43.553 kB` |  `-3 B` <br />`-50 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                                                            |   `42.651 kB`<br />`13.28 kB` |  `42.646 kB`<br />`13.268 kB` |  `-5 B` <br />`-12 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `129.472 kB`<br />`34.761 kB` | `129.465 kB`<br />`34.749 kB` |  `-7 B` <br />`-12 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |  `74.748 kB`<br />`20.076 kB` |  `74.743 kB`<br />`20.061 kB` |  `-5 B` <br />`-15 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |  `73.379 kB`<br />`19.672 kB` |  `73.374 kB`<br />`19.655 kB` |  `-5 B` <br />`-17 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/InteractionTag.fixture.js'>InteractionTag</abbr>                                                              |   `14.038 kB`<br />`5.658 kB` |   `14.032 kB`<br />`5.652 kB` |   `-6 B` <br />`-6 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/tag.fixture.js'>Tag</abbr>                                                                                    |   `29.806 kB`<br />`9.597 kB` |   `29.804 kB`<br />`9.595 kB` |   `-2 B` <br />`-2 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/TagGroup.fixture.js'>TagGroup</abbr>                                                                          |  `72.687 kB`<br />`21.648 kB` |  `72.681 kB`<br />`21.647 kB` |   `-6 B` <br />`-1 B`  |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr>                                                                   |  `91.789 kB`<br />`27.423 kB` |  `91.764 kB`<br />`27.422 kB` |  `-25 B` <br />`-1 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                               |   `18.782 kB`<br />`7.48 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `12.14 kB`<br />`5.061 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `40.966 kB`<br />`13.569 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                              |   `6.541 kB`<br />`2.227 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/48153fef6aa6ba63abfdfad25fb76dea13395b94'>48153fef6aa6ba63abfdfad25fb76dea13395b94</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by bsunderhus — COMMENTED** [review]
Should we later on create an Issue to have an ESLint rule to enforce this?! I'm not sure how easy would it be to solve this on SWC side....

**Comment by Hotell** [comment]
> Should we later on create an Issue to have an ESLint rule to enforce this?! I'm not sure how easy would it be to solve this on SWC side....

swc already merged  a fix, waiting for new release.  

if you follow internal teams chanel you can get answers to your questions as well

**Review by behowell — APPROVED** [review]

**Comment by marcosmoura** [comment]
Closed as this issue was covered by SWC library

**Pull request closed without merging**
