### PR TITLE
add fabricbot config to repo

### PR DESCRIPTION
**Pull request by micahgodbolt**
fabricbot is moving to code base configuration, as they have removed the ability to edit rules inside of their UI.

This PR only introduces the config as it is today. Future changes will be made in subsequent PRs.

### CODE REVIEW

**Comment by JustSlone** [comment]
Is there anything we need to do to disable the config that is stored in the service before we merge this in?

Also, if we think there is risk of this not working, it would be safer to bring in the config as, then follow up with a PR to change the config.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3c3291c008824d45e18580d51b6eb1526ea3792d'>3c3291c008824d45e18580d51b6eb1526ea3792d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by micahgodbolt** [comment]
i'm ok with the idea of splitting this up. If something goes wrong it'll be easier to discect

**Comment by JustSlone** [comment]
> Is there anything we need to do to disable the config that is stored in the service before we merge this in?

Do we know the answer to this? Are we going to get duplicate rules running if we merge this in?

**Comment by micahgodbolt** [comment]
> > Is there anything we need to do to disable the config that is stored in the service before we merge this in?
> 
> Do we know the answer to this? Are we going to get duplicate rules running if we merge this in?

From reading the instructions I'm confident that this is the approach we have to take in order to modify our rules in the future. There is no other way to modify, change, remove, add rules to the existing ruleset other than this file.

**Comment by DragosDanielBoia** [comment]
hi @micahgodbolt can we get this merge into master, I'm from the FabricBot team, we took over the system and in order to move forward you will need to have this into the default branch,

**Comment by Hotell** [comment]
this bot started to block all our PRs caused by `auto-merge.config.enforce` - we removed that check from master protection rules. Is this somehow related  ( the migration of the bot config etc )?

This config is quite gigantic without any docs etc, how are we gonna maintain this ?

> Future changes will be made in subsequent PRs

can you elaborate more about what "future changes" are you referring ?

**Review by DragosDanielBoia — APPROVED** [review]

**Comment by sopranopillow** [comment]
This config was added in the new yml format per #28981

**Pull request closed without merging**
