### PR TITLE
fix(Button): Revert margin fix for Safari to fix Stack regression

### LINKED ISSUE #25701: [Bug]: Regression - `childrenGap` on Stack with `wrap` breaks layout
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.13 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 100.0.2
    Safari: 16.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/laughing-architecture-f92pyg?file=/src/ActionBar.tsx

### Bug Description

As far as I can tell since v8.97 using wrap on a Stack with childrenGap breaks the layout and does not apply the correct gap. Sometimes it works on the first page load but if you press reload (in the code sandbox use the one of the integrated preview not your browser reload) it breaks.

## Actual Behavior
image

## Expected Behavior
A stack with wrap and childrenGap should render correctly:
image

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

`DefaultButton` has a margin set to 0 by default.

## New Behavior

`DefaultButton` doesn't have a margin set to 0 by default.

For more detail on why the `margin: 0` was added, see #25052. While it seems to be the correct fix, this caused a regression to `Stack` since the root style rule has the same specificity as the selector rule that stack uses for its `childrenGap`. This boils down to the following [example](https://codepen.io/sopranopillow/pen/PoaQvML?editors=1100).

## Related Issue(s)

* Fixes #25701
* Related #25052

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/77b8194cfeefddf753b473be572233fc5defe186'>77b8194cfeefddf753b473be572233fc5defe186</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 3 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25759&commitId=de1a67ef8c3b1f3c82ef68b53b6ae595bf1b1dd5&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1036 screenshots unchanged, 0 screenshots with different dimensions and 3 screenshots with visible difference.


  <details><summary><b>unknown</b> 3 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|TagPicker.Root.chromium.png|141| Changed|
|TagPicker.Selected - RTL.chromium.png|141| Changed|
|TagPicker.Selected.chromium.png|141| Changed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/BaseButton-mount_base.html">1412</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/BaseButton-mount.html">1434</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Breadcrumb-mount_base.html">3521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Breadcrumb-mount.html">3468</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Checkbox-mount_base.html">3188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Checkbox-mount.html">3126</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/CheckboxBase-mount_base.html">2776</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/CheckboxBase-mount.html">2767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ChoiceGroup-mount_base.html">5190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ChoiceGroup-mount.html">5329</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ComboBox-mount_base.html">1504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ComboBox-mount.html">1554</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/CommandBar-mount_base.html">11375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/CommandBar-mount.html">11408</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ContextualMenu-mount_base.html">13254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ContextualMenu-mount.html">13337</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DefaultButton-mount_base.html">1657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DefaultButton-mount.html">1650</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRow-mount_base.html">4417</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRow-mount.html">4292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRowFast-mount_base.html">4300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRowFast-mount.html">4254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRowNoStyles-mount_base.html">4074</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DetailsRowNoStyles-mount.html">4206</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Dialog-mount_base.html">3669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Dialog-mount.html">3695</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DocumentCardTitle-mount_base.html">680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/DocumentCardTitle-mount.html">678</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Dropdown-mount_base.html">3923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Dropdown-mount.html">3782</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/FocusTrapZone-mount_base.html">2507</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/FocusTrapZone-mount.html">2422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/FocusZone-mount_base.html">2319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/FocusZone-mount.html">2317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-mount_base.html">2256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-mount.html">2638</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-virtual-rerender_base.html">1355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-virtual-rerender.html">1379</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedList-virtual-rerender-with-unmount.html">1976</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-mount_base.html">675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-mount.html">666</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-virtual-rerender_base.html">648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-virtual-rerender.html">654</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">681</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/IconButton-mount_base.html">2281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/IconButton-mount.html">2242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Label-mount_base.html">880</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Label-mount.html">869</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Layer-mount_base.html">5201</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Layer-mount.html">5192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Link-mount_base.html">1028</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Link-mount.html">1041</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/MenuButton-mount_base.html">2017</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/MenuButton-mount.html">1988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/MessageBar-mount_base.html">2773</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/MessageBar-mount.html">2738</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Nav-mount_base.html">3962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Nav-mount.html">3921</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/OverflowSet-mount_base.html">1584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/OverflowSet-mount.html">1652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Panel-mount_base.html">3008</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Panel-mount.html">3039</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Persona-mount_base.html">1489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Persona-mount.html">1496</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Pivot-mount_base.html">1962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Pivot-mount.html">1960</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/PrimaryButton-mount_base.html">1823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/PrimaryButton-mount.html">1811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Rating-mount_base.html">8225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Rating-mount.html">8349</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SearchBox-mount_base.html">1775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SearchBox-mount.html">1816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Shimmer-mount_base.html">3400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Shimmer-mount.html">3429</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Slider-mount_base.html">2517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Slider-mount.html">2452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SpinButton-mount_base.html">5584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SpinButton-mount.html">5567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Spinner-mount_base.html">974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Spinner-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SplitButton-mount_base.html">3640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SplitButton-mount.html">3650</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Stack-mount_base.html">1025</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Stack-mount.html">966</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/StackWithIntrinsicChildren-mount_base.html">2865</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/StackWithIntrinsicChildren-mount.html">2965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/StackWithTextChildren-mount_base.html">5852</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/StackWithTextChildren-mount.html">5877</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SwatchColorPicker-mount_base.html">12360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/SwatchColorPicker-mount.html">12397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TagPicker-mount_base.html">3113</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TagPicker-mount.html">3059</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TeachingBubble-mount_base.html">101971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TeachingBubble-mount.html">101122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Text-mount_base.html">1035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Text-mount.html">996</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TextField-mount_base.html">1960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/TextField-mount.html">1968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-mount_base.html">1807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-mount.html">1842</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-virtual-rerender_base.html">1284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-virtual-rerender.html">1246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Toggle-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/Toggle-mount.html">1352</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/buttonNative-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25759/perf-test/buttonNative-mount.html">653</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Comment by idigra** [comment]
This change reverted the fix for the original bug, leaving it unfixed (I actually discovered it the accidentally on our product). Are there any plans to re-fix the original bug?

**Pull request merged**
