### PR TITLE
fix: replace internal useKeyborg() with useKeyborgRef()

### LINKED ISSUE #30961: [Bug]: Keyborg error on Popover close when Dropdown is used inside Popover
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Latest version of @fluentui/react-components: 9.47.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-fgyuuu?file=src%2FApp.tsx

## Actual Behavior
Opening and closing a Popover containing a Dropdown produces console errors from the library's Keyborg dependency

image

## Expected Behavior
No errors should be produced

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### LINKED ISSUE #31294: [Bug]: Dropdown does not have focus indicators in Strict Mode
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/hqj6td?file=src%2Fexample.tsx

## Actual Behavior
- Navigate to Dropdown
- Press <kbd>Enter</kbd>
- Try to navigate using <kbd>ArrowDown</kbd> or <kbd>ArrowUp</kbd>
- No focus indicators 💥 

## Expected Behavior
- Focus indicators are present

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by layershifter**
## Previous Behavior

- No focus indicators as `focusVisibleRef` in `useActiveDescendant()` was always `false`
  https://github.com/microsoft/fluentui/blob/2f4006afba4bdb5a9ff136a5ee8079bfd1533268/packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts#L94
- Errors `Keyborg instance is being disposed incorrectly.`
  image

### What was happening?

*React 18, no StrictMode*

```
- render, create `Keyborg` in `useMemo()` #1
- unmount
- dispose `Keyborg` in `useEffect()` #1
```

*React 18, StrictMode*

```
- render, create `Keyborg` in `useMemo()` #1
- render, create `Keyborg` in `useMemo()` #2
- dispose `Keyborg` in `useEffect()` #2
- unmount
- dispose `Keyborg` in `useEffect()` #2
```

> Note: The problem is described in detail in https://github.com/microsoft/use-disposable.

## New Behavior

`Keyborg` instances are created in `useEffect` now and are disposed properly.

## Related Issue(s)

- Fixes #31294.
- Fixes #30961.
- Fixes https://github.com/microsoft/keyborg/issues/77

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Avatar-mount_base.html">668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Avatar-mount.html">630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Button-mount_base.html">308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Button-mount.html">302</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Field-mount_base.html">1129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Field-mount.html">1151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProvider-mount_base.html">706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProvider-mount.html">706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-mount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-mount.html">84</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">32</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">33</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">73</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">83</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/MakeStyles-mount_base.html">847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/MakeStyles-mount.html">894</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Persona-mount_base.html">1758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/Persona-mount.html">1727</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/SpinButton-mount_base.html">1423</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/SpinButton-mount.html">1433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/SwatchPicker-mount_base.html">1522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31295/perf-test-react-components/SwatchPicker-mount.html">1557</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `105.464 kB`<br />`33.885 kB` | `105.556 kB`<br />`33.9 kB` | `92 B` <br />`15 B` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `106.936 kB`<br />`33.86 kB` | `107.028 kB`<br />`33.875 kB` | `92 B` <br />`15 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.101 MB`<br />`267.249 kB` | `1.101 MB`<br />`267.271 kB` | `92 B` <br />`22 B` |
| <samp>react-tag-picker-preview</samp> <br /> <abbr title='bundle-size/Package.fixture.js'>@fluentui/react-tag-picker-preview - package</abbr> | `188.87 kB`<br />`55.778 kB` | `188.962 kB`<br />`55.803 kB` | `92 B` <br />`25 B` |
| <samp>react-timepicker-compat</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `107.482 kB`<br />`35.234 kB` | `107.574 kB`<br />`35.25 kB` | `92 B` <br />`16 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `101.386 kB`<br />`30.643 kB` |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr> | `83.737 kB`<br />`23.475 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr> | `50.175 kB`<br />`15.944 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr> | `19.702 kB`<br />`7.794 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr> | `64.829 kB`<br />`20.272 kB` |
| <samp>react-breadcrumb</samp> <br /> <abbr title='bundle-size/index.fixture.js'>@fluentui/react-breadcrumb - package</abbr> | `117.263 kB`<br />`32.241 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr> | `39.513 kB`<br />`11.17 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr> | `46.874 kB`<br />`12.662 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr> | `44.292 kB`<br />`12.544 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr> | `52.306 kB`<br />`14.135 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr> | `56.558 kB`<br />`13.068 kB` |
| <samp>react-calendar-compat</samp> <br /> <abbr title='bundle-size/Calendar.fixture.js'>Calendar Compat</abbr> | `153.874 kB`<br />`40.203 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr> | `104.438 kB`<br />`29.41 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr> | `97.449 kB`<br />`27.681 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr> | `13.971 kB`<br />`5.626 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr> | `16.214 kB`<br />`6.386 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr> | `14.015 kB`<br />`5.752 kB` |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr> | `36.102 kB`<br />`12.131 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `71.55 kB`<br />`20.584 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `221.825 kB`<br />`62.568 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `44.037 kB`<br />`14.418 kB` |
| <samp>react-datepicker-compat</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker Compat</abbr> | `227.989 kB`<br />`63.592 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr> | `117.345 kB`<br />`36.161 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr> | `17.082 kB`<br />`6.911 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr> | `154.383 kB`<br />`46.161 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu  (including selectable components)</abbr> | `157.069 kB`<br />`46.71 kB` |
| <samp>react-message-bar</samp> <br /> <abbr title='bundle-size/Default.fixture.js'>MessageBar (all components)</abbr> | `24.204 kB`<br />`8.983 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr> | `57.066 kB`<br />`17.821 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr> | `128.669 kB`<br />`40.26 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr> | `14.163 kB`<br />`4.948 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `8.39 kB`<br />`2.64 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr> | `24.211 kB`<br />`8.721 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr> | `33.396 kB`<br />`10.316 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr> | `15.354 kB`<br />`6.265 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr> | `40.395 kB`<br />`13.024 kB` |
| <samp>react-swatch-picker-preview</samp> <br /> <abbr title='bundle-size/index.fixture.js'>@fluentui/react-swatch-picker-preview - package</abbr> | `108.862 kB`<br />`30.32 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr> | `36.04 kB`<br />`11.305 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr> | `169.274 kB`<br />`46.907 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr> | `45.77 kB`<br />`14.174 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr> | `138.358 kB`<br />`37.213 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr> | `76.774 kB`<br />`20.602 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr> | `75.417 kB`<br />`20.205 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/InteractionTag.fixture.js'>InteractionTag</abbr> | `15.299 kB`<br />`6.08 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/tag.fixture.js'>Tag</abbr> | `29.092 kB`<br />`9.418 kB` |
| <samp>react-tags</samp> <br /> <abbr title='bundle-size/TagGroup.fixture.js'>TagGroup</abbr> | `82.49 kB`<br />`24.46 kB` |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr> | `99.113 kB`<br />`29.844 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr> | `55.201 kB`<br />`19.285 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2f4006afba4bdb5a9ff136a5ee8079bfd1533268'>2f4006afba4bdb5a9ff136a5ee8079bfd1533268</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by bsunderhus — APPROVED** [review]
LGTM, I don't get it how simply moving the creation of keyborg instance from `useMemo` to `useEffect` solved this though.... is there a reason?

**Review by YuanboXue-Amber — APPROVED** [review]

**Comment by layershifter** [comment]
> LGTM, I don't get it how simply moving the creation of keyborg instance from `useMemo` to `useEffect` solved this though.... is there a reason?

@bsunderhus I tried to explain it in PR description, but it seems that I failed. Let me try explain it better with code 🐱 

Here is an example: https://stackblitz.com/edit/vitejs-vite-dae6we. We subscribed to notifications about keyboard nav state on a destroyed instance.

**Pull request merged**
