### PR TITLE
Axe-core integration into react-charting #3

### LINKED ISSUE #29980: Integrate with axe-core in charting controls to automate accessibility testing
The charting library is accessibility compliant.
The task is to integrate with axe-core tool that powers the [Fastpass](https://accessibilityinsights.io/docs/web/getstarted/fastpass/) web tool.  https://www.npmjs.com/package/axe-core

### PR DESCRIPTION
**Pull request by Shubhabrata08**
## Previous Behavior

axe-core was added to certain charts in react charting through the following PRs-

1. https://github.com/microsoft/fluentui/pull/30059
2. https://github.com/microsoft/fluentui/pull/30139

## New Behavior

axe-core has been integrated with the remaining of react-charting library.
This PR includes:

1. GaugeChart
2. HeatMapChart
3. PieChart
4. SankeyChart
5. SparklineChart
6. TreeChart

## Related Issue(s)

- Fixes #29980

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e959d219195a11c77cb78f4faf26effea63d3db7'>e959d219195a11c77cb78f4faf26effea63d3db7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by AtishayMsft** [comment]
@Shubhabrata08 Could you pull latest changes for this PR.

**Comment by Shubhabrata08** [comment]
Sure, @AtishayMsft

**Review by AtishayMsft — APPROVED** [review]

**Pull request merged**
