### PR TITLE
feat: automatically add v9 package stories to public docsite and correctly create codesandbox demo source code

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

If we wanna add v9 package that is not part of react-components suite to our public-docsite there are manual steps needed to update runtime code.

## New Behavior

Any v9 package that is part of `@fluentui/react-component` or `public-docsite-v9` dependencies is automatically added/rendered to public-docsite-v9.

## Related Issue(s)

- Fixes https://github.com/microsoft/fluentui/issues/26691
- Partially fixes https://github.com/microsoft/fluentui/issues/28471
- complements https://github.com/microsoft/fluentui/pull/28505

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/820b2c5b432f0f72df241c197b8cc0f5112657b3'>820b2c5b432f0f72df241c197b8cc0f5112657b3</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by tudorpopams — APPROVED** [review]

**Pull request merged**
