### PR TITLE
Fix BasePicker focus

### LINKED ISSUE #12967: BasePicker aggressively steals focus
### Environment Information

- **Package version(s)**: 7.84.1
- **Browser and OS versions**: all

#### Actual behavior:

On every render, BasePicker's componentWillReceiveProps makes a call to resetFocus, which calls .focus() on either the input or one of the selected items. 

#### Expected behavior:

.focus() should only be called when necessary, if ever.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Blocking)

Products/sites affected: Planner feature development

### PR DESCRIPTION
**Pull request by daweffe**
Update fork from original

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #12967   
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Bail out of resetFocus unless focus has been lost or is on the suggestions

#### Focus areas to test

Test code using BasePicker. Focus on keyboard usage and make sure focus is always where you expect it to be.
[office-ui-fabric-react-2020-05-01-13-47-25-patch-fixBasePickerFocus.json.txt](https://github.com/microsoft/fluentui/files/4566314/office-ui-fabric-react-2020-05-01-13-47-25-patch-fixBasePickerFocus.json.txt)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12968)

### CODE REVIEW

**Comment by ecraig12345** [comment]
@joschect Can you review this?

**Comment by joschect** [comment]
@ecraig12345 I've talked with @daweffe offline about this. I think there is another solution. Closing this for now.

**Comment by daweffe** [comment]
@joschect did this get fixed in the last year? I can still repro the issue. Is there some change I need to make in the consuming code?

**Comment by khmakoto** [comment]
@daweffe I don't think this has been fixed yet, the bot just closed the issue since it hadn't been updated for a long time, reopening it now.

**Pull request closed without merging**
