### PR TITLE
Add sanity check for addEventListener in useOnEvent

### PR DESCRIPTION
**Pull request by smikula**
## Previous Behavior

In rare cases (according to telemetry) the call to add an event listener to `actualElement` will fail because "addEventListener is not a function".  (Presumably it is `undefined`, that is it doesn't exist on the object.)

## New Behavior

`useOnEvent` should never throw.

### CODE REVIEW

**Review by spmonahan — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/BaseButton-mount_base.html">659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/BaseButton-mount.html">646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Breadcrumb-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Breadcrumb-mount.html">1723</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Checkbox-mount_base.html">1723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Checkbox-mount.html">1718</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/CheckboxBase-mount_base.html">1518</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/CheckboxBase-mount.html">1472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ChoiceGroup-mount_base.html">2986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ChoiceGroup-mount.html">2959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ComboBox-mount_base.html">659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ComboBox-mount.html">684</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/CommandBar-mount_base.html">6259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/CommandBar-mount.html">6273</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ContextualMenu-mount_base.html">14287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ContextualMenu-mount.html">14175</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DefaultButton-mount_base.html">779</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DefaultButton-mount.html">780</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRow-mount_base.html">2175</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRow-mount.html">2207</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRowFast-mount_base.html">2213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRowFast-mount.html">2214</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRowNoStyles-mount_base.html">2052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DetailsRowNoStyles-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Dialog-mount_base.html">2802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Dialog-mount.html">2713</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DocumentCardTitle-mount_base.html">230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/DocumentCardTitle-mount.html">233</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Dropdown-mount_base.html">1995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Dropdown-mount.html">2014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/FocusTrapZone-mount_base.html">1140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/FocusTrapZone-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/FocusZone-mount_base.html">1058</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/FocusZone-mount.html">1047</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-mount_base.html">41949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-mount.html">42328</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-virtual-rerender_base.html">20105</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-virtual-rerender.html">20219</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">55626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedList-virtual-rerender-with-unmount.html">51335</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-mount_base.html">233</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-mount.html">235</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-virtual-rerender_base.html">219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-virtual-rerender.html">224</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">231</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/IconButton-mount_base.html">1139</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/IconButton-mount.html">1107</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Label-mount_base.html">340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Label-mount.html">345</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Layer-mount_base.html">2790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Layer-mount.html">2761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Link-mount_base.html">394</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Link-mount.html">406</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/MenuButton-mount_base.html">972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/MenuButton-mount.html">945</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/MessageBar-mount_base.html">21521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/MessageBar-mount.html">21422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Nav-mount_base.html">1966</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Nav-mount.html">2047</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/OverflowSet-mount_base.html">802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/OverflowSet-mount.html">796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Panel-mount_base.html">2044</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Panel-mount.html">1792</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Persona-mount_base.html">764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Persona-mount.html">766</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Pivot-mount_base.html">900</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Pivot-mount.html">888</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/PrimaryButton-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/PrimaryButton-mount.html">857</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Rating-mount_base.html">4676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Rating-mount.html">4591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SearchBox-mount_base.html">935</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SearchBox-mount.html">946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Shimmer-mount_base.html">1839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Shimmer-mount.html">1955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Slider-mount_base.html">1304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Slider-mount.html">1309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SpinButton-mount_base.html">2893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SpinButton-mount.html">2902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Spinner-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Spinner-mount.html">391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SplitButton-mount_base.html">1841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SplitButton-mount.html">1838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Stack-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Stack-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/StackWithIntrinsicChildren-mount_base.html">853</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/StackWithIntrinsicChildren-mount.html">878</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/StackWithTextChildren-mount_base.html">2615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/StackWithTextChildren-mount.html">2632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SwatchColorPicker-mount_base.html">6212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/SwatchColorPicker-mount.html">6297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/TagPicker-mount_base.html">1423</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/TagPicker-mount.html">1480</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Text-mount_base.html">377</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Text-mount.html">384</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/TextField-mount_base.html">953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/TextField-mount.html">946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-mount_base.html">864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-mount.html">843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-virtual-rerender.html">601</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1267</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Toggle-mount_base.html">602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/Toggle-mount.html">635</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/buttonNative-mount_base.html">193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29699/perf-test/buttonNative-mount.html">192</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c4307342eaed393fa1ae146061536d4420ebcd19'>c4307342eaed393fa1ae146061536d4420ebcd19</a></sub>
<div id="bundleSizeComment9423"/>

**Pull request merged**
