### PR TITLE
Remove ecraig12345 from v7 codeowners

### PR DESCRIPTION
**Pull request by ecraig12345**
Remove myself from v7 codeowners (this was already done in master).

For website stuff I changed the codeowner to the website team instead. For components I just removed myself, so now cxe-red is the owner.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/BaseButton-mount_base.html">702</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/BaseButton-mount.html">731</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Breadcrumb-mount_base.html">32528</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Breadcrumb-mount.html">36704</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Checkbox-mount_base.html">1282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Checkbox-mount.html">1262</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/CheckboxBase-mount_base.html">1061</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/CheckboxBase-mount.html">964</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ChoiceGroup-mount_base.html">4113</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ChoiceGroup-mount.html">4187</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ComboBox-mount_base.html">750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ComboBox-mount.html">758</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/CommandBar-mount_base.html">6752</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/CommandBar-mount.html">6750</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ContextualMenu-mount_base.html">13143</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/ContextualMenu-mount.html">12881</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DefaultButton-mount_base.html">957</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DefaultButton-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRow-mount_base.html">3270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRow-mount.html">3246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRowFast-mount_base.html">3188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRowFast-mount.html">3183</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRowNoStyles-mount_base.html">3078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DetailsRowNoStyles-mount.html">3066</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Dialog-mount_base.html">1515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Dialog-mount.html">1446</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DocumentCardTitle-mount_base.html">1546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/DocumentCardTitle-mount.html">1565</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Dropdown-mount_base.html">2160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Dropdown-mount.html">2057</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/FocusTrapZone-mount_base.html">1502</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/FocusTrapZone-mount.html">1454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/FocusZone-mount_base.html">1556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/FocusZone-mount.html">1572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/IconButton-mount_base.html">1403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/IconButton-mount.html">1488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Label-mount_base.html">280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Label-mount.html">254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Layer-mount_base.html">1651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Layer-mount.html">1653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Link-mount_base.html">374</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Link-mount.html">365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/MenuButton-mount_base.html">1225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/MenuButton-mount.html">1232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/MessageBar-mount_base.html">1663</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/MessageBar-mount.html">1802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Nav-mount_base.html">2767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Nav-mount.html">2724</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/OverflowSet-mount_base.html">1098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/OverflowSet-mount.html">1211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Panel-mount_base.html">1239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Panel-mount.html">1200</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Persona-mount_base.html">812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Persona-mount.html">819</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Pivot-mount_base.html">1222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Pivot-mount.html">1237</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/PrimaryButton-mount_base.html">1052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/PrimaryButton-mount.html">1038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Rating-mount_base.html">6757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Rating-mount.html">6695</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SearchBox-mount_base.html">1057</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SearchBox-mount.html">1085</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Shimmer-mount_base.html">2164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Shimmer-mount.html">2171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Slider-mount_base.html">1287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Slider-mount.html">1291</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SpinButton-mount_base.html">4185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SpinButton-mount.html">4261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Spinner-mount_base.html">345</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Spinner-mount.html">347</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SplitButton-mount_base.html">2664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SplitButton-mount.html">2611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Stack-mount_base.html">432</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Stack-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/StackWithIntrinsicChildren-mount_base.html">1348</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/StackWithIntrinsicChildren-mount.html">1453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/StackWithTextChildren-mount_base.html">4021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/StackWithTextChildren-mount.html">4000</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SwatchColorPicker-mount_base.html">13675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/SwatchColorPicker-mount.html">8912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TagPicker-mount_base.html">2428</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TagPicker-mount.html">2419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TeachingBubble-mount_base.html">43915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TeachingBubble-mount.html">43730</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Text-mount_base.html">354</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Text-mount.html">368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TextField-mount_base.html">3244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/TextField-mount.html">1153</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Toggle-mount_base.html">709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/Toggle-mount.html">706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/button-mount_base.html">92</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22909/perf-test/button-mount.html">91</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by ling1726 — APPROVED** [review]

**Review by andrefcdias — DISMISSED** [review]
Why are there changes to FocusTrapZone?
And please leave only the removal of your username in the CODEOWNERS file. Seems like it was mistakenly formatted as a Markdown file.

**Review by spmonahan — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Comment by ecraig12345** [comment]
@Hotell FYI, looks like saying `fixes <link to PR comment>` accidentally closed this PR

**Comment by ecraig12345** [comment]
@andrefcdias Can you please unblock this? The issues are fixed.

**Pull request merged**
