### PR TITLE
docs(react-avatar): Adding readme and migration guide for AvatarGroup

### PR DESCRIPTION
**Pull request by sopranopillow**
This PR adds a readme and migration guide for AvatarGroup.

## Related Issue(s)

#22240

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `46.757 kB`<br />`13.737 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          | `136.183 kB`<br />`40.662 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |  `66.472 kB`<br />`19.079 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.067 kB`<br />`52.144 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `31.883 kB`<br />`10.516 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2765b1f72c50c96e7f8e433d80762e9fa25d685f'>2765b1f72c50c96e7f8e433d80762e9fa25d685f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount_base.html">2458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount.html">2504</a></td>
            <td>50000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/Avatar-mount_base.html">1665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/Avatar-mount.html">1705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/Button-mount_base.html">1262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/Button-mount.html">1221</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProvider-mount_base.html">2299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProvider-mount.html">2314</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-mount_base.html">898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-mount.html">912</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">831</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">815</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">895</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount_base.html">2458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount.html">2504</a></td>
            <td>50000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23758/perf-test-react-components/MakeStyles-mount.regression.txt">Possible regression</a></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by khmakoto — APPROVED** [review]
I think this is ok for now, once we move the component to stable we should look at having a singular README for both `Avatar` and `AvatarGroup` in the `react-avatar` package root that points to the specs and migration guides of each (which by then should be probably moved to their respective component folders).

Can you make an issue tracking this follow-up work?

**Comment by sopranopillow** [comment]
> I think this is ok for now, once we move the component to stable we should look at having a singular README for both `Avatar` and `AvatarGroup` in the `react-avatar` package root that points to the specs and migration guides of each (which by then should be probably moved to their respective component folders).
> 
> Can you make an issue tracking this follow-up work?

Yes, that will be the next step once it's moved to stable. I'll add it to the epic to keep track of it.

**Pull request merged**
