### PR TITLE
Button: Stop applying active styles when mouse moves away while it is being held and improving styles in High Contrast mode

### LINKED ISSUE #21403: Button high contrast mode issues
The a11y review of the v9 `Button` component (#20917) identified a bunch of high contrast mode issues that need to be fixed:

- Border change after mouse click stays active even after mouse up.
- Transparent variant does not elicit a change after `:hover` nor `:active`.
- Icons in non-primary variants are not visible.

### LINKED ISSUE #21406: ToggleButton high contrast mode issues
The a11y review of the v9 `ToggleButton` component (#20917) identified a bunch of high contrast mode issues that need to be fixed besides the ones that are already pointed out in #21403 for the regular `Button` component:

- The selected state does not represent a visual difference from the non-selected one in all variants.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

There are 2 problems with buttons right now:

- `:active` styles apply even when the mouse moves away while being held from the `Buttons`.

Before

- A number of High Contrast styles in Button could be better:
  - Hovering over or clicking the buttons triggers a change in border color but not in color. Clicking on the buttons also leaves the focus border highlighted until clicking outside of the button and hovering over it again or focusing into and away from it via the keyboard.
Before
  - Disabled focusable buttons look like regular buttons.
image
  - Checked styles for all `ToggleButton` appearances are broken in High Contrast mode, as they remain exactly as if they were unchecked.
image

## New Behavior

This PR does 2 things:
- Changes all of the `:active` styles to be `:hover:active` to better reflect what we actually want to style for all `Button` components.

After

- Improves the High Contrast styles mentioned above:
  - Hovering over or clicking the buttons now triggers a border color and color change accordingly. The focus styling sticking is also no longer an issue now.
After
  - Disabled focusable buttons now look like disabled buttons.
image
  - Checked `ToggleButtons` styles are now distinct from unchecked styles.
image

## Related Issue

Fixes #21403, fixes #21406

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                      Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |    `28.083 kB`<br />`8.09 kB` |   `28.286 kB`<br />`8.091 kB` |      `203 B` <br />`1 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `33.578 kB`<br />`9.126 kB` |    `33.801 kB`<br />`9.12 kB` |     `223 B` <br />`-6 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |    `29.85 kB`<br />`8.684 kB` |    `30.053 kB`<br />`8.69 kB` |      `203 B` <br />`6 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `36.322 kB`<br />`9.878 kB` |   `36.559 kB`<br />`9.879 kB` |      `237 B` <br />`1 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `37.465 kB`<br />`8.717 kB` |   `38.619 kB`<br />`8.934 kB` | `1.154 kB` <br />`217 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `174.881 kB`<br />`49.118 kB` | `175.084 kB`<br />`49.117 kB` |     `203 B` <br />`-1 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `57.884 kB`<br />`16.524 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               | `53.169 kB`<br />`15.238 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `7.756 kB`<br />`3.299 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `9.321 kB`<br />`3.816 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |   `7.728 kB`<br />`3.323 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `32.671 kB`<br />`10.696 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/af7befccb9b4897cf99c8a4283ab2cbd80018f69'>af7befccb9b4897cf99c8a4283ab2cbd80018f69</a></sub>
<div id="bundleSizeComment9423"/>

**Review by tomi-msft — APPROVED** [review]
lgtm

**Review by sopranopillow — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/Avatar-mount_base.html">1103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/Avatar-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/Button-mount_base.html">701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/Button-mount.html">673</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProvider-mount_base.html">2200</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProvider-mount.html">2209</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-mount_base.html">349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-mount.html">353</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">287</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">372</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/MakeStyles-mount_base.html">1930</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22574/perf-test-react-components/MakeStyles-mount.html">1921</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by khmakoto** [comment]
@msft-fluent-ui-bot require approval from @smhigley

**Comment by khmakoto** [comment]
@msft-fluent-ui-bot merge after 1 minute

**Review by spmonahan — APPROVED** [review]
Does the icon color need to change for checked ToggleButtons?

toggle button high contrast icon

**Review by spmonahan — APPROVED** [review]

**Comment by khmakoto** [comment]
@msft-fluent-ui-bot require approval from @smhigley

**Review by smhigley — APPROVED** [review]
The fact that this somehow works in HCM despite not having `forced-color-adjust: none` worries me a bit, but it does actually work, so I'm approving ¯\_(ツ)_/¯

We can always come back to it if it turns out this is working b/c of some obscure bug or hack or something :D

**Pull request merged**
