### PR TITLE
chore(react-table): adopt custom JSX pragma

### PR DESCRIPTION
**Pull request by bsunderhus**
## New Behavior

1. Adopts `react-jsx-runtime` custom pragma on `react-table`
2. adds `resolveShorthand` to all slots (some `root` slots were missing it)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount_base.html">20</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount.html">24</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Avatar-mount_base.html">717</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Avatar-mount.html">705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Button-mount_base.html">397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Button-mount.html">408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Field-mount_base.html">1213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Field-mount.html">1209</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProvider-mount_base.html">773</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProvider-mount.html">813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-mount_base.html">111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-mount.html">110</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">96</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">96</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">95</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">100</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount_base.html">20</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount.html">24</a></td>
            <td>5000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/InfoButton-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/MakeStyles-mount_base.html">1205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/MakeStyles-mount.html">1201</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Persona-mount_base.html">1902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/Persona-mount.html">1850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/SpinButton-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27543/perf-test-react-components/SpinButton-mount.html">1477</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                     |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :-------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                         | `150.983 kB`<br />`41.093 kB` | `151.664 kB`<br />`41.334 kB` | `681 B` <br />`241 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>    |  `47.196 kB`<br />`12.732 kB` |  `47.268 kB`<br />`12.834 kB` |  `72 B` <br />`102 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>         | `139.125 kB`<br />`35.768 kB` | `139.799 kB`<br />`36.162 kB` | `674 B` <br />`394 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr> |  `86.954 kB`<br />`21.779 kB` |  `87.684 kB`<br />`22.169 kB` | `730 B` <br />`390 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>           |  `86.284 kB`<br />`21.589 kB` |  `87.014 kB`<br />`21.967 kB` | `730 B` <br />`378 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `68.075 kB`<br />`18.416 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `207.606 kB`<br />`57.581 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `38.778 kB`<br />`12.337 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.446 kB`<br />`2.185 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e5c39d1494652e5803b6e8822a2e3fb894aec811'>e5c39d1494652e5803b6e8822a2e3fb894aec811</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by bsunderhus** [comment]
I'll be waiting for https://github.com/microsoft/fluentui/pull/27571 before merging this PR

**Review by miroslavstastny — APPROVED** [review]

**Pull request merged**
