### PR TITLE
chore(react-menu): stop spreading props on state

### PR DESCRIPTION
**Pull request by bsunderhus**
As there's no easy way to force state in Typescript to be only the properties you've declared, it is possible to create a superset of `state` by spreading `props` on it. This creates unmapped properties on state being passed down the line, in the remote case state is spread on an element (hope this doesn't happen) this will generate undesired attributes on that element.

A better alternative is to simply not spread `...props` into `state`, instead redeclare properties required by state.

Effective changes:

1. stops spreading `props` on `state`
2. makes `MenuState` types stricter

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.818 kB`<br />`51.901 kB` | `188.931 kB`<br />`51.926 kB` | `113 B` <br />`25 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `115.697 kB`<br />`35.316 kB` |  `115.81 kB`<br />`35.329 kB` | `113 B` <br />`13 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `118.896 kB`<br />`35.806 kB` | `119.009 kB`<br />`35.822 kB` | `113 B` <br />`16 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |        Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `33.19 kB`<br />`10.921 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/a3081ce8cb9aef65dd64fe9328b84959d7b0e665'>a3081ce8cb9aef65dd64fe9328b84959d7b0e665</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/Avatar-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/Avatar-mount.html">1311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/Button-mount_base.html">961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/Button-mount.html">950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProvider-mount_base.html">1627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProvider-mount.html">1583</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-mount_base.html">635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-mount.html">632</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">584</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">624</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/MakeStyles-mount_base.html">1919</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/MakeStyles-mount.html">1916</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/SpinButton-mount_base.html">2615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24562/perf-test-react-components/SpinButton-mount.html">2537</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by layershifter** [comment]
@bsunderhus FYI CI is failing:
 
image

**Comment by bsunderhus** [comment]
> @bsunderhus FYI CI is failing:
> 
> image

I'm on it @layershifter , the fact that this doesn't pass this easily is one more argument to stop spreading `props` all over the place.

**Review by ling1726 — APPROVED** [review]
yeah stricter typings for this are 🚀

**Pull request merged**
