### PR TITLE
chore(ssr-tests-v9): use playwright

### PR DESCRIPTION
**Pull request by layershifter**
## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Avatar-mount_base.html">887</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Avatar-mount.html">904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Button-mount_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Button-mount.html">581</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Field-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Field-mount.html">1574</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProvider-mount_base.html">1115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProvider-mount.html">1101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-mount_base.html">293</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-mount.html">301</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">273</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">289</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/InfoButton-mount_base.html">198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/InfoButton-mount.html">216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/MakeStyles-mount_base.html">1407</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/MakeStyles-mount.html">1414</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Persona-mount_base.html">2130</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/Persona-mount.html">2076</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/SpinButton-mount_base.html">1863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test-react-components/SpinButton-mount.html">1847</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/BaseButton-mount_base.html">982</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/BaseButton-mount.html">983</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Breadcrumb-mount_base.html">2299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Breadcrumb-mount.html">2375</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Checkbox-mount_base.html">2252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Checkbox-mount.html">2227</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/CheckboxBase-mount_base.html">1984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/CheckboxBase-mount.html">1993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ChoiceGroup-mount_base.html">3876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ChoiceGroup-mount.html">3916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ComboBox-mount_base.html">1024</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ComboBox-mount.html">1037</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/CommandBar-mount_base.html">8278</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/CommandBar-mount.html">8207</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ContextualMenu-mount_base.html">17859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ContextualMenu-mount.html">16867</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DefaultButton-mount_base.html">1151</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DefaultButton-mount.html">1168</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRow-mount_base.html">3034</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRow-mount.html">3074</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRowFast-mount_base.html">3083</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRowFast-mount.html">3084</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRowNoStyles-mount_base.html">2847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DetailsRowNoStyles-mount.html">2842</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Dialog-mount_base.html">3415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Dialog-mount.html">3346</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DocumentCardTitle-mount_base.html">444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/DocumentCardTitle-mount.html">438</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Dropdown-mount_base.html">2750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Dropdown-mount.html">2737</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/FocusTrapZone-mount_base.html">1639</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/FocusTrapZone-mount.html">1630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/FocusZone-mount_base.html">1577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/FocusZone-mount.html">1591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-mount_base.html">50415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-mount.html">58503</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-virtual-rerender_base.html">24477</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-virtual-rerender.html">24507</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">76091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedList-virtual-rerender-with-unmount.html">77138</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-mount_base.html">454</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-mount.html">454</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-virtual-rerender_base.html">439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-virtual-rerender.html">415</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">456</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">444</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/IconButton-mount_base.html">1616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/IconButton-mount.html">1606</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Label-mount_base.html">592</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Label-mount.html">570</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Layer-mount_base.html">3737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Layer-mount.html">3700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Link-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Link-mount.html">665</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/MenuButton-mount_base.html">1392</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/MenuButton-mount.html">1405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/MessageBar-mount_base.html">27561</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/MessageBar-mount.html">27514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Nav-mount_base.html">2715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Nav-mount.html">2710</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/OverflowSet-mount_base.html">1142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/OverflowSet-mount.html">1147</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Panel-mount_base.html">2173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Panel-mount.html">2165</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Persona-mount_base.html">1097</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Persona-mount.html">1107</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Pivot-mount_base.html">1337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Pivot-mount.html">1339</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/PrimaryButton-mount_base.html">1272</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/PrimaryButton-mount.html">1269</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Rating-mount_base.html">5830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Rating-mount.html">5843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SearchBox-mount_base.html">1260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SearchBox-mount.html">1280</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Shimmer-mount_base.html">2447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Shimmer-mount.html">2429</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Slider-mount_base.html">1763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Slider-mount.html">1799</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SpinButton-mount_base.html">3914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SpinButton-mount.html">3935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Spinner-mount_base.html">626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Spinner-mount.html">636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SplitButton-mount_base.html">2676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SplitButton-mount.html">2655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Stack-mount_base.html">657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Stack-mount.html">667</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/StackWithIntrinsicChildren-mount_base.html">1249</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/StackWithIntrinsicChildren-mount.html">1261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/StackWithTextChildren-mount_base.html">3379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/StackWithTextChildren-mount.html">3375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SwatchColorPicker-mount_base.html">8288</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/SwatchColorPicker-mount.html">8365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/TagPicker-mount_base.html">2136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/TagPicker-mount.html">2159</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Text-mount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Text-mount.html">612</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/TextField-mount_base.html">1312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/TextField-mount.html">1348</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-mount_base.html">1232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-mount.html">1244</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-virtual-rerender_base.html">889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-virtual-rerender.html">903</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Toggle-mount_base.html">912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/Toggle-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/buttonNative-mount_base.html">415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27337/perf-test/buttonNative-mount.html">409</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by Hotell** [comment]
lets put this on hold. changing runners wont help avoiding timeout issues on our pipelines. 

improving multiple areas of our stack/pipelines will  https://github.com/microsoft/fluentui/pull/26928

**Pull request closed without merging**
