### PR TITLE
Fix: Remove Intermittent Gray Outline on Radio Components

### PR DESCRIPTION
**Pull request by brianchristopherbrady**
This update addresses a rendering issue causing an intermittent gray outline to appear around radio web components when using keyboard navigation. 

Before:
image

After:
image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f74d0d2869e5d1eb46ff78c3fb1198e1924997c9'>f74d0d2869e5d1eb46ff78c3fb1198e1924997c9</a></sub>
<div id="bundleSizeComment9423"/>

**Review by procload — APPROVED** [review]

**Comment by chrisdholt** [comment]
This looks to be missing a change file, can you add one?

**Comment by JustSlone** [comment]
@brianchristopherbrady closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
