### PR TITLE
fix: MenuList props should win over context props

### LINKED ISSUE #26253: MenuList props will lose to context props
https://codesandbox.io/s/little-sunset-7t5bhs?file=/example.tsx

`checkedValues` and `onCheckedValueChange` will lose to the menu context equivalents due to a regression in #25672.

### PR DESCRIPTION
**Pull request by ling1726**
Fixes the regression introduced in #25672 so that prop values win over context props with the same name.

Also removes deprecation notice on `defaultCheckedValues`  and `onCheckedValueChange` for `MenuList` which are completely reasonable to use in scenarios where `MenuList` is used standalone.

Also updates documentation so that `Menu` examples will use the selection props on the root `Menu` components. Adds selection examples for `MenuList` to be more clear about the differences between the two.

Fixes #26253

### CODE REVIEW

**Review by bsunderhus — APPROVED** [review]
nit: are those new stories related to the fix? Shouldn't those be introduced in another PR?!

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.928 kB`<br />`53.088 kB` |     `189 kB`<br />`53.116 kB` | `72 B` <br />`28 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `119.484 kB`<br />`36.932 kB` | `119.556 kB`<br />`36.965 kB` | `72 B` <br />`33 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `122.553 kB`<br />`37.452 kB` | `122.625 kB`<br />`37.483 kB` | `72 B` <br />`31 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                |         Size (minified/GZIP) |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `59.888 kB`<br />`16.652 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>               | `34.379 kB`<br />`11.322 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                            |   `6.069 kB`<br />`2.053 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/96c5a1cbb36d728bebfbf05203d372a82b1968d8'>96c5a1cbb36d728bebfbf05203d372a82b1968d8</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Avatar-mount_base.html">1282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Avatar-mount.html">1284</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Button-mount_base.html">922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Button-mount.html">925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProvider-mount_base.html">1495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProvider-mount.html">1492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-mount_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-mount.html">573</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">544</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">584</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/MakeStyles-mount_base.html">1953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/MakeStyles-mount.html">1936</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Persona-mount_base.html">2832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/Persona-mount.html">2766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/SpinButton-mount_base.html">2323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26252/perf-test-react-components/SpinButton-mount.html">2320</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Pull request merged**
