### PR TITLE
Adds Fluent Toolbar Web Component

### PR DESCRIPTION
**Pull request by halerankin**
> Please note: This new PR is a duplicate of [this closed PR](https://github.com/microsoft/fluentui/pull/27888). I needed to delete my fork and create a new one because the build was failing no matter what I tried.

# Fluent Toolbar Web Component
Addresses [task](https://powerbi.visualstudio.com/Trident/_workitems/edit/1078846) #1078846

## What Toolbar Does

This is a bucket for buttons, icon buttons, dropdown buttons, split buttons, input, search field, divider.

- `orientation`: `vertical` or `horizontal` (default)
- `size`: `small`, `medium` (default), `large`. This does not apply when vertical.
- RTL support -- Example shown in Storybook

## What Toolbar Does Not

Items present in the [Fluent UI Figma (MVP)](https://www.figma.com/file/QfHyx6ApwFEcw5q4pM9CSZ/Toolbar?type=design&node-id=2367-13918&t=NuPLsJ1NemOOP6dw-4) but not implemented:

- Overflow handling -- Responsive toolbar which implements a More menu and ellipses
- Multiple toolbar groups to serve as tab stops within the toolbar
- Tooltip. The FAST Tooltip should first be built as a web component.
- Invoke/Selected states

While reviewing the Figma, I saw no guidance on any change to button appearance based on toolbar size. The Figma shows appearance instances of primary, outline and subtle.

## Default vs Optional

- Toolbar Heights - icons stay the same size at S, M, L
- Default - rounded corners, no border
- Optional - square edges, border, box-shadow

Demonstrated default vs optional in the storybook.

## Storybook Screenshot

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/a00e814aa5a1641754d4b7fb6f05c0ac2aa4e060'>a00e814aa5a1641754d4b7fb6f05c0ac2aa4e060</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by halerankin** [comment]
Last merge and rebase pulled in and re-committed over 100 files.

**Comment by JustSlone** [comment]
@halerankin closing as that is the only way to stop notifying reviewers. Please update your PR to point to master following this guide: https://github.com/microsoft/fluentui/pull/31361 and reopen when it's updated. Thanks!

**Pull request closed without merging**
