### PR TITLE
fix(react-datepicker-compat): Error handling story now doesn't use Date.now to avoid SSR errors

### LINKED ISSUE #27957: [Bug]: labels in stories are not SSR safe
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior
SSR tests are failing

## Expected Behavior
SSR tests are passing

## Repro
- Open `scripts/test-ssr/src/commands/main.ts`
- Uncomment following
  ```diff
  const EXCLUDED_STORIES = [
  -  // TODO: re-enable ISSUE LINK
  - '**/react-datepicker-compat/**',
    // TODO: re-enable ISSUE LINK
    '**/react-toast/**',
    // Portals currently do not support hydration
    // https://github.com/facebook/react/issues/13097
    '**/react-portal/**',
    // https://github.com/microsoft/fluentui/issues/27338
    '**/react-table/stories/DataGrid/Virtualization.stories.tsx',
    '**/react-table/stories/Table/Virtualization.stories.tsx',
  ];
  ```
- Run tests `yarn workspace @fluentui/react-datepicker-compat test-ssr`
- Notice that tests are failing
- The problem is with a `Date` used in a story:
  https://github.com/microsoft/fluentui/blob/ab53a4c86a49a4d4268f3d87809bee263f818c5d/packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx#L23-L26
  

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

Fluent UI repo itself

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

Error handling story uses Date.now()

## New Behavior

Error handling story doesn't use Date.now() instead it uses a specific date.

## Related Issue(s)

- Fixes #27957

### CODE REVIEW

**Review by khmakoto — APPROVED** [review]

**Comment by sopranopillow** [comment]
@layershifter I was not able to repro the steps you gave in the original issue, in my local machine everything works. I am guessing that the error comes from Date.now() and therefore the server timezone/time messes up with that. Let me know if maybe I'm thinking of the wrong thing here, thanks!

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                    |          Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-datepicker-compat</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker Compat</abbr> | `221.446 kB`<br />`58.861 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0e26a2c598d52a6399af2b5e73deffad3649f4b9'>0e26a2c598d52a6399af2b5e73deffad3649f4b9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by layershifter — APPROVED** [review]
All good, thanks 👍

**Pull request merged**
