### PR TITLE
fix(Tooltip): invisible tooltip is taking up space

### LINKED ISSUE #13235: invisible Tooltip is taking up space
### Environment Information

- **Package version(s)**: 0.49.0
- **Browser and OS versions**: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

* Go to https://fluentsite.z22.web.core.windows.net/components/tooltip/definition
* Scroll all the way to the bottom
* Inspect element
* Search for ".ui-tooltip__content"
* Observe: the tooltip is taking up space below the body tag.

#### Actual behavior:

Body Height; Notice the extra space in the bottom: image

The extra space is coming from the invisible tooltip: 
image

#### Expected behavior:
Invisible Tooltip should not occupy any space on the page.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
teams.microsoft.com

### PR DESCRIPTION
**Pull request by fealkhou**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13235 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

tooltip currently has a position absolute without any top/right/bottom/left values. This is causing the invisible tooltip to occupy a space directly underneath the body's tag which could cause extra scrolling because of additional overall height.

This change hides the tooltip completely using display: none; instead of making it invisible with opacity: 
image

### CODE REVIEW

**Comment by fealkhou** [comment]
@ecraig12345 what's the best way to get this reviewed? Am I missing something is why it's not reviewed yet?

**Comment by ecraig12345** [comment]
@fealkhou Sorry about the delay, I'm not familiar with this code but asked some other people to review.

**Comment by ecraig12345** [comment]
@fealkhou Looks like you still need to sign the CLA before we can merge this.

> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/fluentui?pullRequest=13237) before we can accept your contribution.
> 
> ❌ fealkhou [sign now](https://cla.opensource.microsoft.com/microsoft/fluentui?pullRequest=13237)

**Comment by fealkhou** [comment]
Thanks @ecraig12345 & @layershifter ! CLA is signed now

**Pull request merged**
