### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by ling1726**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by andrefcdias — APPROVED** [review]
test

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/38c344976e3f3b0f005c6803a529b03f0df0f11c'>38c344976e3f3b0f005c6803a529b03f0df0f11c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AccordionMinimalPerf.default | [123](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AccordionMinimalPerf.default.html) | [110](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.12:1
TreeWith60ListItems.default | [160](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TreeWith60ListItems.default.html) | [145](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.1:1
AttachmentMinimalPerf.default | [127](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AttachmentMinimalPerf.default.html) | [116](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.09:1
FlexMinimalPerf.default | [247](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/FlexMinimalPerf.default.html) | [229](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.08:1
ListCommonPerf.default | [543](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListCommonPerf.default.html) | [503](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListCommonPerf.default_base.html) | 1.08:1
PortalMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/PortalMinimalPerf.default.html) | [139](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.08:1
BoxMinimalPerf.default | [284](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/BoxMinimalPerf.default.html) | [271](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
ButtonMinimalPerf.default | [139](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonMinimalPerf.default.html) | [133](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [306](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ImageMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
AvatarMinimalPerf.default | [164](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AvatarMinimalPerf.default.html) | [157](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.04:1
DividerMinimalPerf.default | [294](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DividerMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
GridMinimalPerf.default | [282](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/GridMinimalPerf.default.html) | [272](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [300](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LayoutMinimalPerf.default.html) | [288](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
IconMinimalPerf.default | [523](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/IconMinimalPerf.default.html) | [504](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [412](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TextAreaMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
TreeMinimalPerf.default | [691](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TreeMinimalPerf.default.html) | [664](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [638](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/HeaderSlotsPerf.default.html) | [622](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [335](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ProviderMinimalPerf.default.html) | [324](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
SkeletonMinimalPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SkeletonMinimalPerf.default.html) | [277](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [460](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AnimationMinimalPerf.default.html) | [452](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1263](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1241](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CarouselMinimalPerf.default.html) | [386](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [645](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DialogMinimalPerf.default.html) | [635](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [568](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DropdownManyItemsPerf.default.html) | [558](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [298](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/HeaderMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [433](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListMinimalPerf.default.html) | [425](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [578](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LoaderMinimalPerf.default.html) | [569](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
ChatDuplicateMessagesPerf.default | [239](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [236](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1095](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/InputMinimalPerf.default.html) | [1082](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [706](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/MenuMinimalPerf.default.html) | [696](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
RosterPerf.default | [948](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RosterPerf.default.html) | [939](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RosterPerf.default_base.html) | 1.01:1
RefMinimalPerf.default | [198](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RefMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1430](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SliderMinimalPerf.default.html) | [1411](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [282](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TextMinimalPerf.default.html) | [279](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [862](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TooltipMinimalPerf.default.html) | [852](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [457](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CardMinimalPerf.default.html) | [456](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CardMinimalPerf.default_base.html) | 1:1
ChatMinimalPerf.default | [622](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatMinimalPerf.default.html) | [622](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2261](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2264](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [4753](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4746](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
FormMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/FormMinimalPerf.default.html) | [335](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/FormMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [992](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [993](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [316](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LabelMinimalPerf.default.html) | [317](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ListNestedPerf.default | [456](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListNestedPerf.default.html) | [457](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListNestedPerf.default_base.html) | 1:1
ListWith60ListItems.default | [543](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListWith60ListItems.default.html) | [543](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1416](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1410](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [521](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/PopupMinimalPerf.default.html) | [520](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1059](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1062](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
RadioGroupMinimalPerf.default | [372](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [372](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3682](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3670](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1616](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TableManyItemsPerf.default.html) | [1611](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
TableMinimalPerf.default | [328](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TableMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
VideoMinimalPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/VideoMinimalPerf.default.html) | [546](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1:1
AlertMinimalPerf.default | [216](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AlertMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [916](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AttachmentSlotsPerf.default.html) | [928](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [2556](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DropdownMinimalPerf.default.html) | [2573](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [3455](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/EmbedMinimalPerf.default.html) | [3492](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
ReactionMinimalPerf.default | [305](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ReactionMinimalPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/StatusMinimalPerf.default.html) | [565](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [2266](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CustomToolbarPrototype.default.html) | [2286](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SegmentMinimalPerf.default.html) | [285](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.98:1
ToolbarMinimalPerf.default | [788](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ToolbarMinimalPerf.default.html) | [805](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.98:1
ButtonSlotsPerf.default | [432](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonSlotsPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.97:1
ChatWithPopoverPerf.default | [316](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatWithPopoverPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.96:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/Avatar-mount_base.html">879</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/Avatar-mount.html">910</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/Button-mount_base.html">535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/Button-mount.html">535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProvider-mount_base.html">1838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProvider-mount.html">1881</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-mount_base.html">305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-mount.html">286</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">210</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">232</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">267</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/MakeStyles-mount_base.html">1524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22306/perf-test-react-components/MakeStyles-mount.html">1527</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Pull request closed without merging**
