### PR TITLE
Support single point in area chart

### PR DESCRIPTION
**Pull request by AtishayMsft**
## Previous Behavior

Having single point in the area chart does not render the point

## New Behavior

Area chart now supports having a single point in the chart.

## Related Issue(s)

* Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/388133213c27c5b72276621b64c1eff46504d971'>388133213c27c5b72276621b64c1eff46504d971</a></sub>
<div id="bundleSizeComment9423"/>

**Review by ankityadav4 — APPROVED** [review]

**Comment by Gutentag0004** [comment]
I just saw your fix for the drawing single point in Area chart, but did you meet the issue that the callout box appears in wrong position?

**Comment by AtishayMsft** [comment]
@Gutentag0004 do you have a repro of your issue. Does it happen on latest version of charting library as well.

**Comment by Gutentag0004** [comment]
@AtishayMsft  I resolve it, I set the xAxis to Date it shows the problem that callout positioning is wrong. I change the xAxis to number, it works well. BTW, can we support the custom radius of single point. I saw it was hard coded as 6.

**Comment by AtishayMsft** [comment]
Got it. I have logged an issue #30118 to track this bug.
The radius of 6 px is as per design guidance. Could you tell your specific needs why you need a custom radius.

**Comment by Gutentag0004** [comment]
Because our char shows the radius as 2 and meet the issue that it can not render a single point. After apply your update it works to show the single point but found the radius is coded as 6. Our purpose is want to make the radius consistent, so it will be great if it supports custom radius.

**Comment by AtishayMsft** [comment]
Do you have a mock which shows your use case of needing a radius of 2px. And you are looking for consistency with what other control?

**Comment by Gutentag0004** [comment]
#1  The result when render multiple points
image


#2 The result when render silgle point with radius of 6
image

**Comment by AtishayMsft** [comment]
> #1 The result when render multiple points image
> 
> #2 The result when render silgle point with radius of 6 image

What does the circle in the first graph denote. Are you able to implement it using fluent area chart.

**Pull request merged**
