### PR TITLE
chore(react-dialog): adds unit test to ensure focus on first element

### PR DESCRIPTION
**Pull request by bsunderhus**
## New Behavior

1. adds unit test to ensure focus on first element.

### CODE REVIEW

**Comment by bsunderhus** [comment]
Blocked by https://github.com/microsoft/tabster/issues/250

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `67.994 kB`<br />`18.395 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `207.4 kB`<br />`57.516 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `38.819 kB`<br />`12.351 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    | `93.616 kB`<br />`27.452 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.446 kB`<br />`2.185 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/df9564ee42c12b0dfab646f9e4dd4038c636d3ee'>df9564ee42c12b0dfab646f9e4dd4038c636d3ee</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Avatar-mount_base.html">1028</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Avatar-mount.html">1042</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Button-mount_base.html">658</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Button-mount.html">653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Field-mount_base.html">1904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Field-mount.html">1898</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProvider-mount_base.html">1355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProvider-mount.html">1333</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-mount_base.html">347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-mount.html">347</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">320</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">335</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">325</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/InfoButton-mount_base.html">241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/InfoButton-mount.html">230</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/MakeStyles-mount_base.html">1503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/MakeStyles-mount.html">1504</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Persona-mount_base.html">2600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/Persona-mount.html">2581</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/SpinButton-mount_base.html">2267</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27322/perf-test-react-components/SpinButton-mount.html">2312</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by mshoho** [comment]
The problem with the unittest in this PR seems to be rooted in JSDOM. It doesn't propagate `offsetParent` and `body.getBoundingClientRect()` that is used to check if an element is inside a hidden iframe also doesn't work correctly. Which is understandable from the JSDOM perspective (otherwise it would be just the browser). Perhaps this kind of tests should go to the E2E tests and cannot be tested using current unittesting framework that uses JSDOM.

**Pull request closed without merging**
