### PR TITLE
Updated description for spin button

### LINKED ISSUE #26540: [Feature]: SpinButton - Update description on Storybook
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hey Sean! Can you please update the wording on the Storybook description to include that SpinButtons can also be used non-numerically. It should read as below:

"SpinButtons are used to allow numerical **and non-numerical** input bounded between minimum and maximum values with buttons to increment and decrement the input value."

### Have you discussed this feature with our team

Sean Monahan

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kkakroo**
## Previous Behavior

Storybook description for SpinButton did not include that it can also be used non-numerically

## New Behavior

Storybook description for SpinButton includes that it can also be used non-numerically

## Related Issue(s)

* Fixes #26540

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `63.787 kB`<br />`17.457 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `191.562 kB`<br />`53.554 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.751 kB`<br />`11.453 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.069 kB`<br />`2.053 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `45.161 kB`<br />`13.035 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButtonField.fixture.js'>SpinButtonField</abbr>                                                              |  `54.361 kB`<br />`15.594 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d75055c94921130a2433ea62f0002f560ef7e610'>d75055c94921130a2433ea62f0002f560ef7e610</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Avatar-mount_base.html">1283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Avatar-mount.html">1294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Button-mount_base.html">922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Button-mount.html">915</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProvider-mount_base.html">1558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProvider-mount.html">1524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-mount_base.html">586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-mount.html">586</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">531</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">579</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/InfoButton-mount_base.html">516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/InfoButton-mount.html">520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/MakeStyles-mount_base.html">1989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/MakeStyles-mount.html">1957</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Persona-mount_base.html">2811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/Persona-mount.html">2769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/SpinButton-mount_base.html">2358</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26659/perf-test-react-components/SpinButton-mount.html">2368</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by spmonahan — APPROVED** [review]

**Comment by spmonahan** [comment]
@kkakroo Thanks for making this change! I always appreciate folks helping out!

**Pull request merged**
