### PR TITLE
Support for negative values for VerticalBarChart

### LINKED ISSUE #28707: [Bug]: Giving Negative values (Y-axis) in  fluent-ui react charting (vertical bar chart) makes the bar disappears
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
react v18
fluent ui charting-5.16.56
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://fluentuipr.z22.web.core.windows.net/heads/master/react-charting/demo/index.html

## Actual Behavior
giving negative values to yaxis makes the fluent ui vertical chart bar disappear

## Expected Behavior
the negative value should appear in y-axis

### Logs

_No response_

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by Shubhabrata08**
## Previous Behavior
VerticalBarChart renders wrongly in case of negative y values.
image

## New Behavior
Negative value support added for VerticalBarChart
image
image

This PR brings the following logic changes:
1. In case of presence of both negative and positive y values, equidistant scaling on either sides is maintained as [-maxAbsoluteYVal,+maxAbsoluteVal]
2. In order to have y=0 line show up as anchor points, odd tick counts are auto incremented by 1.
3. The changes will show up only on using supportNegativeValues flag in VerticalBarChart props

## Related Issue(s)

- Fixes #28707

### CODE REVIEW

**Comment by AtishayMsft** [comment]
This representation is a bit confusing. We need to show the y=0 axis line here. 
And put all the changes behind a flag to ensure no regressions.

**Comment by krkshitij** [comment]
@srmukher Some ids do not match in the snapshots resulting in build failure, but this is not happening on the local machine. Could you please help resolve this issue?

**Comment by AtishayMsft** [comment]
Could you share a screenshot after the latest changes.

**Comment by Shubhabrata08** [comment]
Sure,
image

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2a42b52a62aa5bc6e2c0fb81e43d4edf0b0fc4e9'>2a42b52a62aa5bc6e2c0fb81e43d4edf0b0fc4e9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by layershifter** [comment]
Closing for housekeeping 🏡 Feel free to re-open

**Pull request closed without merging**
