### PR TITLE
fix: SSRProvider TypeScript definitions

### PR DESCRIPTION
**Pull request by desenmeng**
## Current Behavior
image

## New Behavior

* fix the issue
## Related Issue(s)

* children prop now needs to be listed explicitly when defining props in React 18
* [How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/023737b640281434710caecc55270838895b50bc'>023737b640281434710caecc55270838895b50bc</a></sub>
<div id="bundleSizeComment9423"/>

**Review by ling1726 — APPROVED** [review]

**Comment by ling1726** [comment]
Please build the package so that the api.md file is updated.

Also run `yarn change` to generate a changefile which will add an entry to the changelog during release

**Comment by layershifter** [comment]
@desenmeng I created a change file, can you please sign CLA?

**Review by ling1726 — APPROVED** [review]

**Comment by desenmeng** [comment]
@microsoft-github-policy-service agree

**Comment by ling1726** [comment]
@desenmeng Please build the package so that the api.md file is updated by running `yarn build`

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Avatar-mount_base.html">1552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Avatar-mount.html">1536</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Button-mount_base.html">1047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Button-mount.html">1037</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProvider-mount_base.html">1859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProvider-mount.html">1868</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-mount.html">656</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">625</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">642</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/InfoButton-mount_base.html">587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/InfoButton-mount.html">565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/MakeStyles-mount_base.html">2083</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/MakeStyles-mount.html">2105</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Persona-mount_base.html">3662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/Persona-mount.html">3586</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/SpinButton-mount_base.html">3171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25582/perf-test-react-components/SpinButton-mount.html">3130</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Pull request merged**
