### PR TITLE
fix(scripts-tasks): don't run swc:compile task twice

### PR DESCRIPTION
**Pull request by Hotell**
## Previous Behavior

- `swc:compile` is being run twice  for every `react-components:build` task 
- `api-extractor` task ends up with failure if no config is present
  - image

## New Behavior

- undo typo introduced https://github.com/microsoft/fluentui/pull/31008/files#diff-6b9fd8010d1649873a9056e36874ef5494545149935c80ed533ca7aed1f27837R154
- api-extractor ends with success if no configs are present
  - image
 

## Related Issue(s)

- Fixes #

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">43</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">37</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Avatar-mount_base.html">643</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Avatar-mount.html">645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Button-mount_base.html">312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Button-mount.html">299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Field-mount_base.html">1132</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Field-mount.html">1122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProvider-mount_base.html">701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProvider-mount.html">700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-mount_base.html">88</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-mount.html">80</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">43</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">37</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">73</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">73</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/MakeStyles-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/MakeStyles-mount.html">880</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Persona-mount_base.html">1748</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/Persona-mount.html">1698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/SpinButton-mount_base.html">1393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/SpinButton-mount.html">1371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/SwatchPicker-mount_base.html">1531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-react-components/SwatchPicker-mount.html">1509</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by TristanWatanabe — APPROVED** [review]

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AttachmentMinimalPerf.default | [93](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AttachmentMinimalPerf.default.html) | [80](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.16:1
PortalMinimalPerf.default | [93](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/PortalMinimalPerf.default.html) | [83](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.12:1
CardMinimalPerf.default | [322](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CardMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.09:1
GridMinimalPerf.default | [195](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/GridMinimalPerf.default.html) | [179](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.09:1
LayoutMinimalPerf.default | [206](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LayoutMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.07:1
ProviderMinimalPerf.default | [208](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ProviderMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.06:1
ChatMinimalPerf.default | [435](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatMinimalPerf.default.html) | [414](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
DividerMinimalPerf.default | [215](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DividerMinimalPerf.default.html) | [204](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.05:1
TextAreaMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TextAreaMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.05:1
AttachmentSlotsPerf.default | [654](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AttachmentSlotsPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [166](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.04:1
ChatWithPopoverPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatWithPopoverPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.04:1
FlexMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/FlexMinimalPerf.default.html) | [150](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.04:1
LoaderMinimalPerf.default | [202](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LoaderMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.04:1
MenuButtonMinimalPerf.default | [988](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [948](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.04:1
SkeletonMinimalPerf.default | [204](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SkeletonMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.04:1
TreeMinimalPerf.default | [492](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TreeMinimalPerf.default.html) | [475](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.04:1
BoxMinimalPerf.default | [204](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/BoxMinimalPerf.default.html) | [199](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.03:1
ButtonMinimalPerf.default | [90](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonMinimalPerf.default.html) | [87](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.03:1
CheckboxMinimalPerf.default | [1140](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CheckboxMinimalPerf.default.html) | [1110](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.03:1
LabelMinimalPerf.default | [219](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LabelMinimalPerf.default.html) | [213](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [232](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TableMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [551](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ToolbarMinimalPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
TreeWith60ListItems.default | [91](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TreeWith60ListItems.default.html) | [88](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.03:1
AccordionMinimalPerf.default | [87](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AccordionMinimalPerf.default.html) | [85](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [263](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CarouselMinimalPerf.default.html) | [259](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
DatepickerMinimalPerf.default | [3604](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DatepickerMinimalPerf.default.html) | [3526](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [437](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DialogMinimalPerf.default.html) | [429](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [310](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListMinimalPerf.default.html) | [305](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [2280](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [2230](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1115](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TableManyItemsPerf.default.html) | [1094](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [1420](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DropdownMinimalPerf.default.html) | [1404](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [1875](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/EmbedMinimalPerf.default.html) | [1856](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [215](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/HeaderMinimalPerf.default.html) | [212](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [451](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/HeaderSlotsPerf.default.html) | [448](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [699](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [692](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
RosterPerf.default | [1595](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RosterPerf.default.html) | [1572](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RosterPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [1274](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TooltipMinimalPerf.default.html) | [1264](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [656](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [655](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [391](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DropdownManyItemsPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
ListCommonPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListCommonPerf.default.html) | [389](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
ListNestedPerf.default | [328](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListNestedPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListNestedPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/PopupMinimalPerf.default.html) | [349](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
IconMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/IconMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/IconMinimalPerf.default_base.html) | 1:1
AnimationMinimalPerf.default | [298](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AnimationMinimalPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.99:1
MenuMinimalPerf.default | [501](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/MenuMinimalPerf.default.html) | [506](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [641](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [649](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
RefMinimalPerf.default | [112](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RefMinimalPerf.default.html) | [113](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [396](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/StatusMinimalPerf.default.html) | [401](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
TextMinimalPerf.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TextMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [220](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/FormMinimalPerf.default.html) | [225](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.98:1
ListWith60ListItems.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListWith60ListItems.default.html) | [377](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.98:1
RadioGroupMinimalPerf.default | [261](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [265](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.98:1
SegmentMinimalPerf.default | [189](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SegmentMinimalPerf.default.html) | [192](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.98:1
SliderMinimalPerf.default | [738](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SliderMinimalPerf.default.html) | [751](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.98:1
CustomToolbarPrototype.default | [1464](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CustomToolbarPrototype.default.html) | [1488](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.98:1
ButtonSlotsPerf.default | [305](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonSlotsPerf.default.html) | [313](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.97:1
InputMinimalPerf.default | [542](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/InputMinimalPerf.default.html) | [556](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.97:1
VideoMinimalPerf.default | [443](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/VideoMinimalPerf.default.html) | [456](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.97:1
AvatarMinimalPerf.default | [104](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AvatarMinimalPerf.default.html) | [108](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.96:1
ImageMinimalPerf.default | [222](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ImageMinimalPerf.default.html) | [231](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.96:1
ReactionMinimalPerf.default | [215](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ReactionMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.95:1
AlertMinimalPerf.default | [154](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AlertMinimalPerf.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/31100/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Pull request merged**
