### PR TITLE
DO NOT MERGE: validate unit test CI

### PR DESCRIPTION
**Pull request by miroslavstastny**
Random change to verify unit test CI

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/eee4a63c0af9e2c51b30477053c4d990cd331405'>eee4a63c0af9e2c51b30477053c4d990cd331405</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by chrisdholt** [comment]
@miroslavstastny we should likely add a change file so this gets to the tests - I think as of now it'll fail before the build gets that far.

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by miroslavstastny** [comment]
The CI now fails as expected:

image

image

**Pull request closed without merging**
