### PR TITLE
DetailsList: Remove drag and drop border animation causing style mutations via mergeStyles

### LINKED ISSUE #7116: Merge-Styles bloating document head
### Bug Report

- __Package version(s)__: 6.103.0
- __Browser and OS versions__: Chrome 70 rhel 7.5

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No, I do not understand this code well enough.

Requested priority: Normal

Products/sites affected: This is reproducible at https://developer.microsoft.com/en-us/fabric#/components/detailslist

#### Describe the issue:
DetailsList creates a new empty `<style data-merge-styles="true" type="text/css"></style>` on each render. Over time this bloats the dom and causes sluggishness.

#### Actual behavior:
DetailsList merge-styles creates a new empty `<style data-merge-styles="true" type="text/css"></style>` on each render. 

#### Expected behavior:
DetailsList merge-styles does not create new style tags on every render, or can clean up unused styles tags periodically.

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7116
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Removes the `border-color` animation from `DetailsColumn` which is not memoized due to the usage of key-frames. This is creating a new `<styles/>` tag per render (click, resize, etc.) causing performance issues.

The animation was originally added in #4857 and refactored to use mergeStyles as part of #5490.

#### Focus areas to test

**How to Test**

You can test this by examining the `<style data-merge-styles="true" type="text/css"></style>` which are added per interaction with `DetailsList` (anything that causes re-render). For example, clicking a row appends a node to `<head>` each time.

**Sample Test Output**

Below are the count of nodes in `<head>` _before_ and _after_ clicking **4** times on an alternating row which causes a re-render.

**Before**

- Initial count on load:

```shell
document.head.childElementCount
17:32:14.266 84
```

- Count after **4** clicks alternating rows

```shell
document.head.childElementCount
17:33:05.215 89
```

**After**

- Initial count on load:

```shell
document.head.childElementCount
17:30:23.126 84
```

- Count after **4** clicks alternating column header

```shell
document.head.childElementCount
17:33:50.589 85
```

The _one_ style-sheet added here are the styles for `DetailsList` including focus, check, etc. So the increase in node count by 1 on initial _click_ is expected behavior.

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@kenotron by chance, do you know how to trigger this animation? I'll try more in a bit. I'd like to repro it and see if we can fix using `transition`.

**Comment by KevinTCoughlin** [comment]
FWIW I grepped the rest of OUIFR and did not see other usages of `keyframes` that could cause a similar problem https://github.com/OfficeDev/office-ui-fabric-react/search?l=TypeScript&q=keyframes%28

🎉

**Comment by betrue-final-final** [comment]
Hey @dzearing and @KevinTCoughlin, what exactly did we remove here? I'd love to see what it was.

**Comment by dzearing** [comment]
@betrue-final-final still not sure how to reproduce this scenario completely but it seems like a border "pulse" from theme colored to transparent over a couple seconds.

We needed to remove it because it's causing a serious perf bug, but we will need to re-evaluate the right fix separately. @KevinTCoughlin will follow up with @yiminwu on this issue and see what needs to be done.

**Comment by betrue-final-final** [comment]
That doesn't seem intentional then. We didn't design a pulse for drag and drop.

**Comment by arkogupta** [comment]
@KevinTCoughlin @kenotron Can't we use `memoizeFunction` here to solve the problem? I guess there are more complications involved ? 
Will using `transition` to have the fade-out effect also cause the same perf issue ?

**Pull request merged**
