### PR TITLE
feat(DatePicker): Added date range selection

### LINKED ISSUE #21183: DatePicker: date range selection
#### Describe the feature that you would like added

Make it possible to select a date range in `DatePicker`.

#### What component or utility would this be added to

`DatePicker`

### PR DESCRIPTION
**Pull request by jasperwreed**
## Current Behavior

The DatePicker allows users to select one date at a time.

## New Behavior

The DatePicker acts more like the Calendar in that users are able to select date ranges as well as single dates.

## Related Issue(s)

Fixes #21183

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b01ac1a166a8dc67a6c53409d9fe86977517bae6'>b01ac1a166a8dc67a6c53409d9fe86977517bae6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/BaseButton-mount_base.html">936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/BaseButton-mount.html">923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Breadcrumb-mount_base.html">2811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Breadcrumb-mount.html">2789</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Checkbox-mount_base.html">1519</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Checkbox-mount.html">1513</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/CheckboxBase-mount_base.html">1302</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/CheckboxBase-mount.html">1367</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ChoiceGroup-mount_base.html">4762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ChoiceGroup-mount.html">4812</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ComboBox-mount_base.html">1048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ComboBox-mount.html">959</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/CommandBar-mount_base.html">10591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/CommandBar-mount.html">10502</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ContextualMenu-mount_base.html">11422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ContextualMenu-mount.html">11571</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DefaultButton-mount_base.html">1162</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DefaultButton-mount.html">1163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRow-mount_base.html">3801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRow-mount.html">3802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRowFast-mount_base.html">3914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRowFast-mount.html">3899</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRowNoStyles-mount_base.html">3677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DetailsRowNoStyles-mount.html">3741</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Dialog-mount_base.html">2314</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Dialog-mount.html">2292</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DocumentCardTitle-mount_base.html">175</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/DocumentCardTitle-mount.html">182</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Dropdown-mount_base.html">3383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Dropdown-mount.html">3314</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/FocusTrapZone-mount_base.html">1894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/FocusTrapZone-mount.html">1864</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/FocusZone-mount_base.html">1837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/FocusZone-mount.html">1847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/IconButton-mount_base.html">1849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/IconButton-mount.html">1759</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Label-mount_base.html">343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Label-mount.html">366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Layer-mount_base.html">2937</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Layer-mount.html">3104</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Link-mount_base.html">493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Link-mount.html">485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/MenuButton-mount_base.html">1494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/MenuButton-mount.html">1514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/MessageBar-mount_base.html">2103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/MessageBar-mount.html">2144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Nav-mount_base.html">3311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Nav-mount.html">3330</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/OverflowSet-mount_base.html">1091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/OverflowSet-mount.html">1082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Panel-mount_base.html">2160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Panel-mount.html">2199</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Persona-mount_base.html">1033</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Persona-mount.html">1005</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Pivot-mount_base.html">1508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Pivot-mount.html">1456</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/PrimaryButton-mount_base.html">1326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/PrimaryButton-mount.html">1359</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Rating-mount_base.html">7763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Rating-mount.html">7706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SearchBox-mount_base.html">1339</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SearchBox-mount.html">1317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Shimmer-mount_base.html">2520</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Shimmer-mount.html">2536</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Slider-mount_base.html">1922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Slider-mount.html">1941</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SpinButton-mount_base.html">5099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SpinButton-mount.html">5017</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Spinner-mount_base.html">422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Spinner-mount.html">429</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SplitButton-mount_base.html">3164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SplitButton-mount.html">3266</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Stack-mount_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Stack-mount.html">532</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/StackWithIntrinsicChildren-mount_base.html">2263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/StackWithIntrinsicChildren-mount.html">2316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/StackWithTextChildren-mount_base.html">5232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/StackWithTextChildren-mount.html">5383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SwatchColorPicker-mount_base.html">11567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/SwatchColorPicker-mount.html">11659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TagPicker-mount_base.html">2772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TagPicker-mount.html">2783</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TeachingBubble-mount_base.html">92311</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TeachingBubble-mount.html">92421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Text-mount_base.html">424</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Text-mount.html">437</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TextField-mount_base.html">1403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/TextField-mount.html">1431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-mount_base.html">1192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-mount.html">1163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-virtual-rerender_base.html">639</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-virtual-rerender.html">642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Toggle-mount_base.html">777</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/Toggle-mount.html">802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/buttonNative-mount_base.html">121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23313/perf-test/buttonNative-mount.html">123</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by nivb52** [comment]
Hi,
looks great.
What is the state of this PR ?

**Comment by JustSlone** [comment]
@jasperwreed thanks for the contribution, how's the PR going, is it ready to be reviewed? If so, go ahead and move it out of draft and follow up with @microsoft/fluent-date-time 

FYI: @microsoft/fluent-date-time

**Pull request closed without merging**
