### PR TITLE
fix: disable fluentui debug console messages for the server runtime

### PR DESCRIPTION
**Pull request by marwan38**
## Current Behavior

Fela renderer logs to the console about it's current debug state. This occurs within the server runtime as well which causes a lot of spam in the server logs.

## New Behavior

Will not log to console in the server runtime

## Related Issue(s)

N/A

Fixes #

N/A

### CODE REVIEW

**Comment by marwan38** [comment]
I ran `yarn change` after I made the commit. Is the command meant to be run before the staged files have been commited?

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/17b9063802b28bf7f4b1c4d439623819ad8940fa'>17b9063802b28bf7f4b1c4d439623819ad8940fa</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AvatarMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AvatarMinimalPerf.default.html) | [128](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.17:1
ChatDuplicateMessagesPerf.default | [238](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [204](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.17:1
AlertMinimalPerf.default | [222](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AlertMinimalPerf.default.html) | [192](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.16:1
AnimationMinimalPerf.default | [443](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AnimationMinimalPerf.default.html) | [381](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.16:1
DropdownManyItemsPerf.default | [550](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DropdownManyItemsPerf.default.html) | [476](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.16:1
BoxMinimalPerf.default | [279](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/BoxMinimalPerf.default.html) | [244](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.14:1
ButtonSlotsPerf.default | [460](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonSlotsPerf.default.html) | [407](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.13:1
CarouselMinimalPerf.default | [372](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CarouselMinimalPerf.default.html) | [330](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.13:1
ReactionMinimalPerf.default | [298](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ReactionMinimalPerf.default.html) | [264](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.13:1
TableManyItemsPerf.default | [1537](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TableManyItemsPerf.default.html) | [1376](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.12:1
TextMinimalPerf.default | [278](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TextMinimalPerf.default.html) | [248](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.12:1
LoaderMinimalPerf.default | [532](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LoaderMinimalPerf.default.html) | [484](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.1:1
StatusMinimalPerf.default | [535](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/StatusMinimalPerf.default.html) | [489](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.09:1
AttachmentSlotsPerf.default | [904](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AttachmentSlotsPerf.default.html) | [841](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.07:1
CheckboxMinimalPerf.default | [1647](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CheckboxMinimalPerf.default.html) | [1533](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.07:1
TreeWith60ListItems.default | [130](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TreeWith60ListItems.default.html) | [121](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.07:1
AccordionMinimalPerf.default | [109](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AccordionMinimalPerf.default.html) | [103](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.06:1
MenuButtonMinimalPerf.default | [1374](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1296](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.06:1
ProviderMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ProviderMinimalPerf.default.html) | [316](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.06:1
PortalMinimalPerf.default | [146](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/PortalMinimalPerf.default.html) | [139](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [544](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatMinimalPerf.default.html) | [524](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.04:1
DividerMinimalPerf.default | [260](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DividerMinimalPerf.default.html) | [249](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LayoutMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
MenuMinimalPerf.default | [648](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/MenuMinimalPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.04:1
VideoMinimalPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/VideoMinimalPerf.default.html) | [525](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.04:1
RadioGroupMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [342](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
TooltipMinimalPerf.default | [1872](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TooltipMinimalPerf.default.html) | [1810](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [656](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TreeMinimalPerf.default.html) | [638](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
ChatWithPopoverPerf.default | [269](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatWithPopoverPerf.default.html) | [263](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [2163](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DropdownMinimalPerf.default.html) | [2126](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
FormMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/FormMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.02:1
RosterPerf.default | [1722](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RosterPerf.default.html) | [1695](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
TextAreaMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TextAreaMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ImageMinimalPerf.default.html) | [277](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [858](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [850](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
LabelMinimalPerf.default | [275](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LabelMinimalPerf.default.html) | [273](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.01:1
ListNestedPerf.default | [458](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListNestedPerf.default.html) | [455](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListNestedPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [959](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [945](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [328](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TableMinimalPerf.default.html) | [326](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [260](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/HeaderMinimalPerf.default.html) | [261](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
InputMinimalPerf.default | [867](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/InputMinimalPerf.default.html) | [865](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/InputMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [518](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/PopupMinimalPerf.default.html) | [517](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ToolbarMinimalPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ToolbarMinimalPerf.default.html) | [692](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [965](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [976](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [4402](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4452](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.99:1
HeaderSlotsPerf.default | [619](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/HeaderSlotsPerf.default.html) | [625](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
ListWith60ListItems.default | [471](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListWith60ListItems.default.html) | [475](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.99:1
IconMinimalPerf.default | [468](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/IconMinimalPerf.default.html) | [474](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [2022](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CustomToolbarPrototype.default.html) | [2049](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
ButtonMinimalPerf.default | [122](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonMinimalPerf.default.html) | [127](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.96:1
SkeletonMinimalPerf.default | [242](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SkeletonMinimalPerf.default.html) | [252](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.96:1
AttachmentMinimalPerf.default | [114](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AttachmentMinimalPerf.default.html) | [120](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.95:1
SegmentMinimalPerf.default | [240](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SegmentMinimalPerf.default.html) | [255](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.94:1
SplitButtonMinimalPerf.default | [3361](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3589](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.94:1
ListCommonPerf.default | [454](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListCommonPerf.default.html) | [486](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/ListCommonPerf.default_base.html) | 0.93:1
RefMinimalPerf.default | [163](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RefMinimalPerf.default.html) | [176](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.93:1
SliderMinimalPerf.default | [1213](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SliderMinimalPerf.default.html) | [1307](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.93:1
CardMinimalPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CardMinimalPerf.default.html) | [426](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.92:1
DialogMinimalPerf.default | [569](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DialogMinimalPerf.default.html) | [617](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.92:1
FlexMinimalPerf.default | [212](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/FlexMinimalPerf.default.html) | [234](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.91:1
EmbedMinimalPerf.default | [2726](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/EmbedMinimalPerf.default.html) | [3014](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.9:1
GridMinimalPerf.default | [238](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/GridMinimalPerf.default.html) | [267](https://fluentuipr.z22.web.core.windows.net/pull/24803/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.89:1

</details><div id="perfComment9424"/>

**Comment by marwan38** [comment]
Bump

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Pull request merged**
