### PR TITLE
chore: Remove max-width style from Button components

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

`Button` components have a `maxWidth` defined, which is a constraint that constantly needs to be overridden by developers.

## New Behavior

`Button` components don't have a `maxWidth` defined anymore.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `83.788 kB`<br />`20.843 kB` |  `83.739 kB`<br />`20.823 kB` | `-49 B` <br />`-20 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `36.396 kB`<br />`9.579 kB` |   `36.347 kB`<br />`9.559 kB` | `-49 B` <br />`-20 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `43.469 kB`<br />`10.812 kB` |  `43.373 kB`<br />`10.775 kB` | `-96 B` <br />`-37 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `39.014 kB`<br />`10.456 kB` |  `38.965 kB`<br />`10.438 kB` | `-49 B` <br />`-18 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `46.544 kB`<br />`11.84 kB` |   `46.495 kB`<br />`11.82 kB` | `-49 B` <br />`-20 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `51.91 kB`<br />`11.003 kB` |  `51.861 kB`<br />`10.983 kB` | `-49 B` <br />`-20 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.816 kB`<br />`51.903 kB` | `188.767 kB`<br />`51.885 kB` | `-49 B` <br />`-18 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `67.458 kB`<br />`19.264 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               |  `63.14 kB`<br />`18.176 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `8.461 kB`<br />`3.555 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `9.504 kB`<br />`3.896 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |    `8.562 kB`<br />`3.61 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `33.259 kB`<br />`10.952 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7c2ccadde562224609e08d5bdd2c42b078f5bef2'>7c2ccadde562224609e08d5bdd2c42b078f5bef2</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/Avatar-mount_base.html">1299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/Avatar-mount.html">1374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/Button-mount_base.html">962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/Button-mount.html">986</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProvider-mount_base.html">1482</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProvider-mount.html">1530</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-mount_base.html">632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-mount.html">641</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">593</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">620</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/MakeStyles-mount_base.html">1872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/MakeStyles-mount.html">1877</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/SpinButton-mount_base.html">2437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24647/perf-test-react-components/SpinButton-mount.html">2531</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by bsunderhus — APPROVED** [review]
LGTM! Thx @khmakoto!

**Comment by micahgodbolt** [comment]
Okay, a good thing to note here is that buttons are by default inline-block with a min-width....so it's not like everyone's buttons are going to blow up and be super wide after this PR. This would be a good things to be able to communicate to partners though, as there are some scenarios where this could cause regressions.

**Review by sopranopillow — APPROVED** [review]

**Pull request merged**
