### PR TITLE
fix: Stopping autocomplete in Combobox from suggesting disabled options

### LINKED ISSUE #25739: [Bug]: v8 Combobox autocompletes to disabled option values
### Library

React / v8 (@fluentui/react)

### System Info

```shell
all browsers
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/smhigley/pen/ZERrbmo/fc1bc5e44b1844f5ef47e42dec3fe13c

### Bug Description

The linked example is the docs autocomplete/allowFreeform example, with the option text modified to be "Cat", just so it's different enough from other options to get autocomplete before the last letter.

## Actual Behavior
After typing "C", the combobox autocompletes "Cat", despite the option being disabled

## Expected Behavior
We probably should not autocomplete disabled option values 😅

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Previous Behavior

Enabling `autocomplete` on the `Combobox` component would suggest disabled options.

Before

## New Behavior

Enabling `autocomplete` on the `Combobox` component no longer suggests disabled options.

A couple of unit tests have been added so this behavior does not regress in the future.

After

## Related Issue(s)

* Fixes #25739

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3b98e91e026e9a458d792e767902e060eaba5a3c'>3b98e91e026e9a458d792e767902e060eaba5a3c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/BaseButton-mount_base.html">1196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/BaseButton-mount.html">1170</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Breadcrumb-mount_base.html">2805</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Breadcrumb-mount.html">2806</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Checkbox-mount_base.html">2649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Checkbox-mount.html">2646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/CheckboxBase-mount_base.html">2360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/CheckboxBase-mount.html">2380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ChoiceGroup-mount_base.html">4273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ChoiceGroup-mount.html">4271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ComboBox-mount_base.html">1197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ComboBox-mount.html">1190</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/CommandBar-mount_base.html">9244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/CommandBar-mount.html">9270</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ContextualMenu-mount_base.html">9996</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ContextualMenu-mount.html">10058</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DefaultButton-mount_base.html">1341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DefaultButton-mount.html">1380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRow-mount_base.html">3376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRow-mount.html">3339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRowFast-mount_base.html">3385</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRowFast-mount.html">3381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRowNoStyles-mount_base.html">3228</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DetailsRowNoStyles-mount.html">3246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Dialog-mount_base.html">2940</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Dialog-mount.html">2951</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DocumentCardTitle-mount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/DocumentCardTitle-mount.html">578</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Dropdown-mount_base.html">3155</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Dropdown-mount.html">3153</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/FocusTrapZone-mount_base.html">1962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/FocusTrapZone-mount.html">1957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/FocusZone-mount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/FocusZone-mount.html">1944</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-mount_base.html">1823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-mount.html">2027</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-virtual-rerender_base.html">1089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-virtual-rerender.html">1096</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedList-virtual-rerender-with-unmount.html">1608</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-mount_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-mount.html">564</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-virtual-rerender_base.html">548</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-virtual-rerender.html">548</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">558</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/IconButton-mount_base.html">1789</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/IconButton-mount.html">1782</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Label-mount_base.html">739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Label-mount.html">740</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Layer-mount_base.html">4180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Layer-mount.html">4171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Link-mount_base.html">856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Link-mount.html">861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/MenuButton-mount_base.html">1620</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/MenuButton-mount.html">1618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/MessageBar-mount_base.html">2354</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/MessageBar-mount.html">2335</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Nav-mount_base.html">3089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Nav-mount.html">3065</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/OverflowSet-mount_base.html">1415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/OverflowSet-mount.html">1401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Panel-mount_base.html">2489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Panel-mount.html">2499</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Persona-mount_base.html">1320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Persona-mount.html">1279</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Pivot-mount_base.html">1485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Pivot-mount.html">1515</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/PrimaryButton-mount_base.html">1487</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/PrimaryButton-mount.html">1480</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Rating-mount_base.html">7020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Rating-mount.html">6904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SearchBox-mount_base.html">1485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SearchBox-mount.html">1482</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Shimmer-mount_base.html">2930</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Shimmer-mount.html">2894</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Slider-mount_base.html">2073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Slider-mount.html">2122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SpinButton-mount_base.html">4250</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SpinButton-mount.html">4228</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Spinner-mount_base.html">825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Spinner-mount.html">826</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SplitButton-mount_base.html">2808</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SplitButton-mount.html">2818</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Stack-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Stack-mount.html">863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/StackWithIntrinsicChildren-mount_base.html">2271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/StackWithIntrinsicChildren-mount.html">2279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/StackWithTextChildren-mount_base.html">4971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/StackWithTextChildren-mount.html">4957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SwatchColorPicker-mount_base.html">9387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/SwatchColorPicker-mount.html">9425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TagPicker-mount_base.html">2328</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TagPicker-mount.html">2326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TeachingBubble-mount_base.html">73995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TeachingBubble-mount.html">72944</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Text-mount_base.html">823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Text-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TextField-mount_base.html">1550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/TextField-mount.html">1546</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-mount_base.html">1431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-mount.html">1434</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-virtual-rerender_base.html">1140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-virtual-rerender.html">1135</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Toggle-mount_base.html">1123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/Toggle-mount.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/buttonNative-mount_base.html">524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25909/perf-test/buttonNative-mount.html">532</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 7 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25909&commitId=e98ee9002b7418c0ef28bc92c9353d6be1522710&env=prod)

✅ There was 0 screenshots added, 4 screenshots removed, 1032 screenshots unchanged, 0 screenshots with different dimensions and 3 screenshots with visible difference.


  <details><summary><b>unknown</b> 7 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|TagPicker.Root.chromium.png|136| Changed|
|TagPicker.Selected - RTL.chromium.png|136| Changed|
|TagPicker.Selected.chromium.png|136| Changed|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Review by smhigley — COMMENTED** [review]
There's a couple more, one on line 813, because I guess we also allow people to match options with an empty string 😅. The other is line 852, which isn't technically autocomplete but we probably also shouldn't match freeform values to disabled options.

**Review by smhigley — APPROVED** [review]

**Pull request merged**
