### PR TITLE
ComboBox: borderColor should be applied properly in the case of error

### LINKED ISSUE #12122: ComboBox: borderColor applied by errorMessage is supplied to an incorrect element
Error border color is supplied to ComboBox(number)wrapper, but the one that is actually used is within ComboBox(number)wrapper's ::after.

### Environment Information

- **Package version(s)**: 7.98.1

### Please provide a reproduction of the bug in a codepen:

See the border color of ComboBoxes that are given an errorMessage:
https://fabricweb.z5.web.core.windows.net/oufr/7.98.1/#/examples/ComboBox
Compare it to the color of TextFields that are given the same prop:
https://fabricweb.z5.web.core.windows.net/oufr/7.98.1/#/examples/TextField

#### Actual behavior:

The border color stays as if the input had no error.

#### Expected behavior:

The border color changes to inform about the error.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

### PR DESCRIPTION
**Pull request by aneeshack4**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #12122 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

The error ComboBox doesn't have the right color applied to it right now - fixed it so that it's correct:
image
on hover, it still get the hover color:
image
Added a Screener test for the error case too.
#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12155)

### CODE REVIEW

**Comment by aneeshack4** [comment]
@xugao which screener test are you referring to? I don't see any failures...

**Comment by aneeshack4** [comment]
@joschect can you review these 3 new scenarios that were added: https://screener.io/v2/states/Skgr32fUL.microsoft-fluentui/checkbox_border and approve/merge this PR please?

**Comment by joschect** [comment]
@aneeshack4 I don't appear to have permissions to approve screener changes.

**Comment by aneeshack4** [comment]
@betrue-final-final can you approve these new screener scenarios?

**Comment by aneeshack4** [comment]
@joschect need codeowner approval

**Pull request merged**
