### PR TITLE
Table: enable unconstrained column width changes

### PR DESCRIPTION
**Pull request by george-cz**
A draft to explore if this is something we want to do.

This PR allows the devs to disable constrains when it comes to resizing columns. Subsequently its possible to change width of a column without ever impacting other column widths at the cost of introducing a scrollbar.

No changes to DataGrid yet, that would come after we validate the approach/behavior and after we decide if this is wanted/needed.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Avatar-mount_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Avatar-mount.html">620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Button-mount_base.html">328</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Button-mount.html">308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Field-mount_base.html">1084</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Field-mount.html">1096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProvider-mount_base.html">690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProvider-mount.html">679</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-mount_base.html">80</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-mount.html">79</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">63</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">72</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">69</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/InfoButton-mount_base.html">9</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/InfoButton-mount.html">10</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/MakeStyles-mount_base.html">848</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/MakeStyles-mount.html">855</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Persona-mount_base.html">1785</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/Persona-mount.html">1700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/SpinButton-mount_base.html">1357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28908/perf-test-react-components/SpinButton-mount.html">1369</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d7743e64df7a0b0bd607cf9df3667203eda49e34'>d7743e64df7a0b0bd607cf9df3667203eda49e34</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by layershifter** [comment]
Closing for housekeeping 🏡  Feel free to re-open 👍

**Pull request closed without merging**
