### PR TITLE
init: package for virtualized DataGrid components

### PR DESCRIPTION
**Pull request by ling1726**
automated bootstrappping only.

This package is intended to be the home for a variation of `DataGridBody` that is powered by `react-window` for virtualization

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `3.153 kB`<br />`1.299 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             | `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/ecf69c4add0ef27441205cfb721c61185ba2f64b'>ecf69c4add0ef27441205cfb721c61185ba2f64b</a></sub>
<div id="bundleSizeComment9423"/>

**Review by jurokapsiar — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Avatar-mount_base.html">1603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Avatar-mount.html">1621</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Button-mount_base.html">1110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Button-mount.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProvider-mount_base.html">1912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProvider-mount.html">1890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-mount_base.html">713</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-mount.html">699</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">662</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">703</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/MakeStyles-mount_base.html">2258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/MakeStyles-mount.html">2291</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Persona-mount_base.html">3903</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/Persona-mount.html">3867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/SpinButton-mount_base.html">3223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test-react-components/SpinButton-mount.html">3146</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 1 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26078&commitId=04acc9972e2a5ae8a30f7864977c8ed522abc80d&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1044 screenshots unchanged, 0 screenshots with different dimensions and 1 screenshots with visible difference.


  <details><summary><b>unknown</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Coachmark.Collapsed.default.chromium.png|159| Changed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/BaseButton-mount_base.html">1465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/BaseButton-mount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Breadcrumb-mount_base.html">3703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Breadcrumb-mount.html">3643</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Checkbox-mount_base.html">3306</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Checkbox-mount.html">3262</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/CheckboxBase-mount_base.html">2894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/CheckboxBase-mount.html">3007</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ChoiceGroup-mount_base.html">5513</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ChoiceGroup-mount.html">5568</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ComboBox-mount_base.html">1603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ComboBox-mount.html">1616</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/CommandBar-mount_base.html">11871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/CommandBar-mount.html">11929</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ContextualMenu-mount_base.html">13667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ContextualMenu-mount.html">13744</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DefaultButton-mount_base.html">1722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DefaultButton-mount.html">1778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRow-mount_base.html">4513</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRow-mount.html">4554</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRowFast-mount_base.html">4489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRowFast-mount.html">4504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRowNoStyles-mount_base.html">4279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DetailsRowNoStyles-mount.html">4336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Dialog-mount_base.html">3913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Dialog-mount.html">3864</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DocumentCardTitle-mount_base.html">728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/DocumentCardTitle-mount.html">705</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Dropdown-mount_base.html">4073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Dropdown-mount.html">3973</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/FocusTrapZone-mount_base.html">2550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/FocusTrapZone-mount.html">2566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/FocusZone-mount_base.html">2458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/FocusZone-mount.html">2501</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-mount_base.html">2453</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-mount.html">2682</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-virtual-rerender_base.html">1395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-virtual-rerender.html">1413</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">2071</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedList-virtual-rerender-with-unmount.html">2216</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-mount_base.html">715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-mount.html">733</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-virtual-rerender_base.html">685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-virtual-rerender.html">676</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">713</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">772</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/IconButton-mount_base.html">2397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/IconButton-mount.html">2461</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Label-mount_base.html">902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Label-mount.html">926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Layer-mount_base.html">5470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Layer-mount.html">5562</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Link-mount_base.html">1031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Link-mount.html">1041</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/MenuButton-mount_base.html">2107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/MenuButton-mount.html">2179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/MessageBar-mount_base.html">2829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/MessageBar-mount.html">2959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Nav-mount_base.html">4020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Nav-mount.html">4150</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/OverflowSet-mount_base.html">1705</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/OverflowSet-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Panel-mount_base.html">3240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Panel-mount.html">3205</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Persona-mount_base.html">1641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Persona-mount.html">1693</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Pivot-mount_base.html">2031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Pivot-mount.html">2054</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/PrimaryButton-mount_base.html">1898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/PrimaryButton-mount.html">1950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Rating-mount_base.html">8656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Rating-mount.html">8666</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SearchBox-mount_base.html">1913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SearchBox-mount.html">1937</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Shimmer-mount_base.html">3628</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Shimmer-mount.html">3625</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Slider-mount_base.html">2564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Slider-mount.html">2643</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SpinButton-mount_base.html">5811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SpinButton-mount.html">5714</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Spinner-mount_base.html">986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Spinner-mount.html">1013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SplitButton-mount_base.html">3888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SplitButton-mount.html">3903</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Stack-mount_base.html">1017</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Stack-mount.html">998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/StackWithIntrinsicChildren-mount_base.html">2945</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/StackWithIntrinsicChildren-mount.html">2916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/StackWithTextChildren-mount_base.html">5946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/StackWithTextChildren-mount.html">5987</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SwatchColorPicker-mount_base.html">13020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/SwatchColorPicker-mount.html">12973</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TagPicker-mount_base.html">3290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TagPicker-mount.html">3297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TeachingBubble-mount_base.html">106158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TeachingBubble-mount.html">106734</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Text-mount_base.html">1002</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Text-mount.html">988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TextField-mount_base.html">1956</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/TextField-mount.html">2034</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-mount_base.html">1923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-mount.html">1912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-virtual-rerender_base.html">1312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-virtual-rerender.html">1351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2691</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Toggle-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/Toggle-mount.html">1412</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/buttonNative-mount_base.html">672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26078/perf-test/buttonNative-mount.html">664</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## [🕵 FluentUI-v0 Open the Visual Regressions report to inspect the 1 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26078&commitId=056df635268509b63edd3aec51aba9bf2f107a7d&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1259 screenshots unchanged, 0 screenshots with different dimensions and 1 screenshots with visible difference.


  <details><summary><b>unknown</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Dropdown.Dropdown Example Position.Opens a dropdown.chromium.png|811| Changed|

</details>


<div id="vrtCommentFluentUI-v0"/>

**Review by Hotell — APPROVED** [review]

**Pull request merged**
