### PR TITLE
Run local builds with lage

### PR DESCRIPTION
**Pull request by ecraig12345**
Use `lage` to run local builds instead of `lerna` due to `lage`'s built-in caching capabilities: it will only re-run tasks for packages that have changed since the last build (properly handling dependencies).

This will make the local dev experience a lot faster for cases where you have to repeatedly run a build which crosses multiple packages and fix errors as you go.

`lage` CLI options: https://microsoft.github.io/lage/guide/cli.html

### CODE REVIEW

**Review by xugao — APPROVED** [review]

**Review by dzearing — APPROVED** [review]

**Comment by ecraig12345** [comment]
@msft-github-bot Merge in 1 minuet

**Comment by ecraig12345** [comment]
Hmm the bot doesn't want to dance...

@msft-github-bot Merge in 1 minute

**Comment by ecraig12345** [comment]
@msft-github-bot Merge this PR in 1 minute

**Pull request merged**
