### PR TITLE
Changing aria-disabled to disabled to fix a11y bug

### LINKED ISSUE #18686: [DatePicker]- Disabled state of up/down arrow buttons can not be visually identified in High Contrast mode
### Environment Information

- **Package version(s)**: 8.20.2
- **Browser and OS versions**:  Microsoft Edge, Windows 10

### Describe the issue:

In High Contrast Black mode and in High Contrast White mode, the disabled state of  up/down arrow buttons i.e., previous/next arrow buttons can not be visually identified

#### Actual behavior:

The below images show the same datepicker in all the three modes. Here we can observe that the disabled arrow button is visually not varied when compared with enabled arrow button in HC modes.

Normal Mode : 

image

HCB mode : 

image

HCW mode : 

image

#### Expected behavior:

The disabled state of next/previous arrow buttons should follow the similar visual pattern of the other disabled buttons in HC mode

### Please provide a reproduction of the issue in a codepen:

Here is the reproduction of the issue in codepen (the issue can be reproduced in HC mode) - https://codepen.io/bhavana-nimma/pen/bGqPvNy

### PR DESCRIPTION
**Pull request by anowduru**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #18686
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Disabled state of Next month/Next year buttons in calendar should be  notified in High Contrast mode.

The issue here is for the navigation buttons, it is using aria-disabled instead of disabled tag. This is overriding the disabled styles.

#### Focus areas to test
After fix:

image

### CODE REVIEW

**Review by smhigley — COMMENTED** [review]
I believe that was there because `disabled` will prevent focus regardless of `tabindex`. @lorejoh12 I don't know the history behind `allFocusable` -- is it important that the next and previous month/year buttons be included in the tab order when `allFocusable` is true?

**Comment by lorejoh12** [comment]
> I believe that was there because `disabled` will prevent focus regardless of `tabindex`. @lorejoh12 I don't know the history behind `allFocusable` -- is it important that the next and previous month/year buttons be included in the tab order when `allFocusable` is true?

The switch from disabled to aria-disabled was done by you for that reason, yes! https://github.com/microsoft/fluentui/pull/17933. Looks like it was to prevent the case where focus is on the button, then the button becomes disabled, which sends focus back to the root of the page.

Given that, what's your suggestion here? It sounds like we don't want to just have the button become disabled again, as that bug will come back. Would it make more sense to override the disabled styles to fix the High Contrast scenario, but leave it as aria-disabled instead of completely disabled?

As a side note, the whole "allFocusable" thing was a fix for VoiceOver on iOS a few years back. I've never been able to test on iOS, but the fix was submitted by a mobile developer, who was suggesting that having buttons be disabled was breaking the ability to tab to other elements on the page or something.

**Comment by smhigley** [comment]
Haha I forgot I was the one who did that 😂. And yup, it looks like because of that, the fix should be a `forced-colors` media query that sets the disabled text color.

**Comment by anowduru** [comment]
@smhigley and @lorejoh12 , updated the PR as per the suggestions

**Review by smhigley — APPROVED** [review]

**Pull request merged**
