### PR TITLE
feat: allSelectedRows and someSelectedRows should be more reliable

### LINKED ISSUE #28456: [Bug]: Table multi-selection always selects the next item by default when an item above it is been removed
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 14.52 GB / 31.67 GB
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/nameless-monad-mhhn5j?file=/example.tsx

## Actual Behavior
This behavior can be found for multi-selection of table component in flunetV9.
I am able to reproduce it in the codeSandbox by using one of the official example: https://codesandbox.io/s/nameless-monad-mhhn5j?file=/example.tsx
Let's say we have 4 items in the table like this: 
image

and we remove the first item from it by clicking on the delete:
image

After the selected item is been removed, the next item is automatically get selected be default.

## Expected Behavior
After the selected item is been removed, the next item should remain unselected state

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
We took the decision to decouple the selection state from the data. This means that the selection state does not always stay in sync with the data, but the resulting output should be correct.

In this case `allSeletedRows` and `someSelectedRows` were calculated based on the size of the selected rows which was wrong, because there can be outdated values in there. Updates the `useTableSelection` hook to make sure that those states reflect the what is in the data. This will cause extra computation (which is memoized) but there is no other way to maintain consistency.

It might be possible to update `useSelection` accept the set of selectable items, but the extra computation will still need to be there.

Fixes #28456

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Avatar-mount_base.html">585</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Avatar-mount.html">577</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Button-mount_base.html">295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Button-mount.html">302</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Field-mount_base.html">1072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Field-mount.html">1075</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProvider-mount_base.html">666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProvider-mount.html">677</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-mount_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-mount.html">92</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">67</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">71</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">81</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">81</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/InfoButton-mount_base.html">7</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/InfoButton-mount.html">19</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/MakeStyles-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/MakeStyles-mount.html">863</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Persona-mount_base.html">1632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/Persona-mount.html">1629</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/SpinButton-mount_base.html">1281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28577/perf-test-react-components/SpinButton-mount.html">1296</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                     |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :-------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                         | `158.282 kB`<br />`43.276 kB` | `158.637 kB`<br />`43.388 kB` | `355 B` <br />`112 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>         | `132.365 kB`<br />`33.849 kB` | `132.723 kB`<br />`33.982 kB` | `358 B` <br />`133 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr> |  `77.993 kB`<br />`19.245 kB` |  `78.348 kB`<br />`19.364 kB` | `355 B` <br />`119 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `65.175 kB`<br />`17.915 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `210.68 kB`<br />`58.781 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `36.409 kB`<br />`12.003 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                                                            | `44.666 kB`<br />`12.442 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   | `76.978 kB`<br />`18.973 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/ed5b88b0d870a7bdcd890735a9ca2ebf7d7d7265'>ed5b88b0d870a7bdcd890735a9ca2ebf7d7d7265</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by bsunderhus — APPROVED** [review]

**Comment by mhverbakel** [comment]
@ling1726 The algorithm for `allRowsSelected` returns `true` when there are no rows. While technically correct (logic and set theory dictates that for all on an empty set returns true), this gives the counter-intuitive case where an empty data grid/table has the checkbox for selecting all rows checked.

Is this a deliberate choice? Or is this something that was overlooked?

**Pull request merged**
