### PR TITLE
fix: Update IStyleSet type to fix error when using TypeScript 5.3+

### LINKED ISSUE #30714: [Bug]:  Type 'IStyleSet' is not generic.
### Library

`@fluentui/react-file-type-icons`

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 9.89 GB / 15.61 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Bug Description

I only installed the following package. nothing else
`@fluentui/react-file-type-icons`
Then my code cannot compile because of this bug. 
(typescript 5.3.3)

## Actual Behavior
Unable to compile code

```
./node_modules/@fluentui/merge-styles/lib/IStyleFunction.d.ts:7:68
Type error: Type 'IStyleSet' is not generic.

   5 |  * {@docCategory IStyleFunction}
   6 |  */
>  7 | export declare type IStyleFunction<TStylesProps, TStyleSet extends IStyleSet<TStyleSet>> = (props: TStylesProps) => DeepPartial<TStyleSet>;
     |                                                                    ^
   8 | /**
   9 |  * Represents either a style function that takes in style props and returns a partial styleset,
  10 |  * or a partial styleset object
```

### Logs

_No response_

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by behowell**
## Previous Behavior

The type definition of IStyleSet has a circular dependency, which causes an error when used with TypeScript 5.3.

## New Behavior

Create an `IStyleSetBase` type to act as the `extends` constraint for type arguments, and avoid a circular reference.

## Related Issue(s)

- Fixes #30714

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6e6a1bf624e5a682b3607d918793d6f0eeb6b12a'>6e6a1bf624e5a682b3607d918793d6f0eeb6b12a</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/BaseButton-mount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/BaseButton-mount.html">652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Breadcrumb-mount_base.html">1682</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Breadcrumb-mount.html">1678</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Checkbox-mount_base.html">1650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Checkbox-mount.html">1683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/CheckboxBase-mount_base.html">1507</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/CheckboxBase-mount.html">1450</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ChoiceGroup-mount_base.html">2983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ChoiceGroup-mount.html">2981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ComboBox-mount_base.html">658</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ComboBox-mount.html">649</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/CommandBar-mount_base.html">6118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/CommandBar-mount.html">6146</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ContextualMenu-mount_base.html">12935</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ContextualMenu-mount.html">13246</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DefaultButton-mount_base.html">765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DefaultButton-mount.html">753</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRow-mount_base.html">2176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRow-mount.html">2183</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRowFast-mount_base.html">2191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRowFast-mount.html">2145</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRowNoStyles-mount_base.html">2027</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DetailsRowNoStyles-mount.html">2026</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Dialog-mount_base.html">2763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Dialog-mount.html">2764</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DocumentCardTitle-mount_base.html">223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/DocumentCardTitle-mount.html">227</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Dropdown-mount_base.html">1984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Dropdown-mount.html">2009</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/FocusTrapZone-mount_base.html">1133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/FocusTrapZone-mount.html">1162</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/FocusZone-mount_base.html">1087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/FocusZone-mount.html">1066</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-mount_base.html">41305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-mount.html">41419</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-virtual-rerender_base.html">20099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-virtual-rerender.html">20022</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">51130</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedList-virtual-rerender-with-unmount.html">50969</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-mount_base.html">232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-mount.html">236</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-virtual-rerender_base.html">210</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-virtual-rerender.html">214</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">229</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/IconButton-mount_base.html">1099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/IconButton-mount.html">1103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Label-mount_base.html">327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Label-mount.html">326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Layer-mount_base.html">2728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Layer-mount.html">2712</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Link-mount_base.html">399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Link-mount.html">394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/MenuButton-mount_base.html">974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/MenuButton-mount.html">943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/MessageBar-mount_base.html">21278</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/MessageBar-mount.html">21270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Nav-mount_base.html">1949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Nav-mount.html">1916</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/OverflowSet-mount_base.html">796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/OverflowSet-mount.html">786</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Panel-mount_base.html">2045</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Panel-mount.html">1765</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Persona-mount_base.html">735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Persona-mount.html">722</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Pivot-mount_base.html">857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Pivot-mount.html">870</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/PrimaryButton-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/PrimaryButton-mount.html">854</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Rating-mount_base.html">4526</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Rating-mount.html">4581</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SearchBox-mount_base.html">942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SearchBox-mount.html">906</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Shimmer-mount_base.html">1932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Shimmer-mount.html">1840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Slider-mount_base.html">1308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Slider-mount.html">1308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SpinButton-mount_base.html">2874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SpinButton-mount.html">2888</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Spinner-mount_base.html">383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Spinner-mount.html">391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SplitButton-mount_base.html">1840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SplitButton-mount.html">1848</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Stack-mount_base.html">400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Stack-mount.html">404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/StackWithIntrinsicChildren-mount_base.html">875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/StackWithIntrinsicChildren-mount.html">857</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/StackWithTextChildren-mount_base.html">2594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/StackWithTextChildren-mount.html">2596</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SwatchColorPicker-mount_base.html">6152</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/SwatchColorPicker-mount.html">6134</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/TagPicker-mount_base.html">1419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/TagPicker-mount.html">1456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Text-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Text-mount.html">374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/TextField-mount_base.html">938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/TextField-mount.html">934</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-mount_base.html">825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-mount.html">809</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-virtual-rerender_base.html">591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-virtual-rerender.html">584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1268</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Toggle-mount_base.html">626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/Toggle-mount.html">594</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/buttonNative-mount_base.html">190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30753/perf-test/buttonNative-mount.html">190</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Comment by sakgoyal** [comment]
should I expect an update on `react-file-type-icons` package? 
if not, how can i use the main `fluentui` package instead?

**Comment by behowell** [comment]
@sakgoyal This should be in `@fluentui/react-file-type-icons` v8.11.4. Let me know if you're still having issues with that version.

**Pull request merged**
