### PR TITLE
feat(react-avatar): add className to AvatarContext

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
Add className to avatarContext, so components can apply default styles to avatar.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                            |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                 Change |
| :----------------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                      | `93.799 kB`<br />`22.502 kB` | `93.841 kB`<br />`22.515 kB` | `42 B` <br />`13 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                   | `57.564 kB`<br />`14.976 kB` | `57.606 kB`<br />`14.992 kB` | `42 B` <br />`16 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr> | `73.778 kB`<br />`19.491 kB` |  `73.82 kB`<br />`19.505 kB` | `42 B` <br />`14 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                |   `64.485 kB`<br />`16.9 kB` | `64.527 kB`<br />`16.918 kB` | `42 B` <br />`18 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |   `15.632 kB`<br />`6.258 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |   `65.31 kB`<br />`17.931 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `204.34 kB`<br />`57.141 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |    `36.086 kB`<br />`11.9 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.446 kB`<br />`2.186 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 | `147.659 kB`<br />`40.567 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                                                            |  `44.348 kB`<br />`12.347 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `130.218 kB`<br />`33.128 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |  `78.132 kB`<br />`19.127 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |  `77.462 kB`<br />`18.939 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f0b05741d812ad90c52754b0b4035d5554cf2aa0'>f0b05741d812ad90c52754b0b4035d5554cf2aa0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Avatar-mount_base.html">807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Avatar-mount.html">831</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Button-mount_base.html">431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Button-mount.html">439</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Field-mount_base.html">1545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Field-mount.html">1508</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProvider-mount_base.html">1078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProvider-mount.html">1094</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-mount_base.html">134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-mount.html">149</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">114</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">123</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/InfoButton-mount_base.html">21</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/InfoButton-mount.html">25</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/MakeStyles-mount_base.html">1292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/MakeStyles-mount.html">1322</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Persona-mount_base.html">2373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/Persona-mount.html">2292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/SpinButton-mount_base.html">1854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27755/perf-test-react-components/SpinButton-mount.html">1865</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by YuanboXue-Amber** [comment]
close due to CustomStyleHooksProvider

**Pull request closed without merging**
