### PR TITLE
Update filetype mapping and references to non-recommended icon sources

### PR DESCRIPTION
**Pull request by bigbadcapers**
#### Pull request checklist

- [ ] Add PowerBI App and new raw image format extension support to the filetype-icon map
- [ ] Replaced references to filetype icons in documentation pages that use deprecated icons from brand-icons or other non-recommended folders to only use the official ones.
- [ ] Include a change request file using `$ yarn change` 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12363)

### CODE REVIEW

**Comment by aneeshack4** [comment]
@bigbadcapers feel free to ping us when you're ready to promote this to a full PR & let me know if you need any help in getting it there

**Comment by bigbadcapers** [comment]
fyi i have reviewed the pages from the examples site and the experiments package documentation pages that were affected and fixed them. all filetype icons should now be fed off of the correct folder across the different documentation pages (~fabric-cdn/app-min/assets/item-types/...)

**Comment by bigbadcapers** [comment]
@betrue-final-final @dzearing -- any idea why i cant sign in to screener any more? tried github creds and msft creds... nothing.  i wager there are some by-design visual changes found since the filetype icons all should now align to the latest office brand and the previous ones were from 2013.

**Comment by bigbadcapers** [comment]
yup, i just got access to the screener, this delta is by-design:

image

**Comment by bigbadcapers** [comment]
@Vitalius1 can you take a look at this update? a few folks are out, thank you!

**Comment by bigbadcapers** [comment]
Thank you Vitalie, yeah, I do not have Merge rights either. Zearing helped me with the Screener thing this morning.

**Pull request merged**
