### PR TITLE
Re-enable typescript pretty option

### PR DESCRIPTION
**Pull request by ecraig12345**
Despite the typescript docs claiming that the `pretty` option is true by default, for some reason this is NOT the case when `tsc` is invoked via `just-task`. (You can try this by intentionally creating a compiler error in some file in `packages/react` locally, then running `yarn build`.) 

EDIT: This appears to be by design (but undocumented) on typescript's side due to the way the tsc process is created within `just-scripts` `tscTask`, with the child's output captured rather than inherited (which is reasonable enough in general). So using `pretty: true` to force pretty output is probably the "right" solution here.

https://github.com/microsoft/TypeScript/blob/95ef2a503dd0cae9f106948cccee8a041078a472/src/executeCommandLine/executeCommandLine.ts#L70-L72

https://github.com/microsoft/TypeScript/blob/39ff1568e9676d40cf545477e9fd04077eff9b78/src/compiler/sys.ts#L1316-L1318

### CODE REVIEW

**Comment by Hotell** [comment]
> but IMO it's not really worth the time to dig into further, and just adding pretty back to the shared config overrides is a "good enough" workaround.

can we create issue on just repo so its properly resolved by maintainers (as you already start digging into that) ?

**Review by Hotell — COMMENTED** [review]
I'd suggest to create issue on just repo and link that issue here so its transparent and trackable for contributors

**Comment by ecraig12345** [comment]
> > but IMO it's not really worth the time to dig into further, and just adding pretty back to the shared config overrides is a "good enough" workaround.
> 
> can we create issue on just repo so its properly resolved by maintainers (as you already start digging into that) ?

Nobody is going to resolve just issues unless we do. It's basically unmaintained. Can we please just merge this so that the issue is fixed?

**Comment by ecraig12345** [comment]
This appears to be by design (but undocumented) on typescript's side due to the way the `tsc` process is created, with the child's output captured rather than inherited. So using `pretty: true` to force pretty output is probably the "right" solution here.

https://github.com/microsoft/TypeScript/blob/95ef2a503dd0cae9f106948cccee8a041078a472/src/executeCommandLine/executeCommandLine.ts#L70-L72

https://github.com/microsoft/TypeScript/blob/39ff1568e9676d40cf545477e9fd04077eff9b78/src/compiler/sys.ts#L1316-L1318

**Review by Hotell — APPROVED** [review]

**Pull request merged**
