### PR TITLE
Chromatic/9.0.0-rc.4: version switching

### PR DESCRIPTION
**Pull request by PeterDraex**
Branch created for deployment of version switching to Chromatic
#22142

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/Avatar-mount_base.html">944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/Avatar-mount.html">914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/Button-mount_base.html">564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/Button-mount.html">566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProvider-mount_base.html">1942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProvider-mount.html">2213</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-mount_base.html">299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-mount.html">257</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">238</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">293</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/MakeStyles-mount_base.html">1535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22181/perf-test-react-components/MakeStyles-mount.html">1536</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by micahgodbolt** [comment]
when this is close to being ready, can you drop in some screenshots of what it looks like

**Comment by ling1726** [comment]
> when this is close to being ready, can you drop in some screenshots of what it looks like

This PR will never be merged and is only intended to serve as 'backfill' code for previous versions

**Comment by layershifter** [comment]
We don't use Chromatic for deployments, closing for housekeeping 🏡

**Pull request closed without merging**
