### PR TITLE
7.0 - Allow React 17 in peerDependencies

### PR DESCRIPTION
**Pull request by ThomasMichon**
In practice, this PR is a cherry-pick of #17048

So far, React has asserted that they have not released any 'breaking changes' in React between versions 16.8 and 18.1. This means that Fabric 7 should be able to declare that it continues supporting React up to 18.0, giving consuming projects more options in adapting React and Fabric.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/BaseButton-mount_base.html">665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/BaseButton-mount.html">744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Breadcrumb-mount_base.html">35504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Breadcrumb-mount.html">36120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Checkbox-mount_base.html">1249</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Checkbox-mount.html">1261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/CheckboxBase-mount_base.html">1046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/CheckboxBase-mount.html">1112</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ChoiceGroup-mount_base.html">3987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ChoiceGroup-mount.html">4216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ComboBox-mount_base.html">780</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ComboBox-mount.html">769</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/CommandBar-mount_base.html">6683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/CommandBar-mount.html">6793</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ContextualMenu-mount_base.html">12844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/ContextualMenu-mount.html">12492</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DefaultButton-mount_base.html">971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DefaultButton-mount.html">966</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRow-mount_base.html">3043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRow-mount.html">3122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRowFast-mount_base.html">3199</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRowFast-mount.html">3138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRowNoStyles-mount_base.html">2759</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DetailsRowNoStyles-mount.html">2997</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Dialog-mount_base.html">1520</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Dialog-mount.html">1448</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DocumentCardTitle-mount_base.html">1580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/DocumentCardTitle-mount.html">1566</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Dropdown-mount_base.html">2087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Dropdown-mount.html">2083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/FocusTrapZone-mount_base.html">1484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/FocusTrapZone-mount.html">1455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/FocusZone-mount_base.html">1571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/FocusZone-mount.html">1587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/IconButton-mount_base.html">1451</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/IconButton-mount.html">1467</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Label-mount_base.html">297</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Label-mount.html">279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Layer-mount_base.html">1645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Layer-mount.html">1558</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Link-mount_base.html">364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Link-mount.html">369</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/MenuButton-mount_base.html">1221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/MenuButton-mount.html">1149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/MessageBar-mount_base.html">1620</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/MessageBar-mount.html">1769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Nav-mount_base.html">2758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Nav-mount.html">2681</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/OverflowSet-mount_base.html">1173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/OverflowSet-mount.html">1167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Panel-mount_base.html">1179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Panel-mount.html">1171</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Persona-mount_base.html">809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Persona-mount.html">807</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Pivot-mount_base.html">1235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Pivot-mount.html">1152</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/PrimaryButton-mount_base.html">1101</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/PrimaryButton-mount.html">1098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Rating-mount_base.html">6650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Rating-mount.html">6702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SearchBox-mount_base.html">980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SearchBox-mount.html">1053</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Shimmer-mount_base.html">2152</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Shimmer-mount.html">2221</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Slider-mount_base.html">1238</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Slider-mount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SpinButton-mount_base.html">4298</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SpinButton-mount.html">4202</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Spinner-mount_base.html">360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Spinner-mount.html">347</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SplitButton-mount_base.html">2534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SplitButton-mount.html">2550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Stack-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Stack-mount.html">419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/StackWithIntrinsicChildren-mount_base.html">1438</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/StackWithIntrinsicChildren-mount.html">1402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/StackWithTextChildren-mount_base.html">3864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/StackWithTextChildren-mount.html">4025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SwatchColorPicker-mount_base.html">8966</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/SwatchColorPicker-mount.html">8865</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TagPicker-mount_base.html">2265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TagPicker-mount.html">2352</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TeachingBubble-mount_base.html">43814</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TeachingBubble-mount.html">44056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Text-mount_base.html">368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Text-mount.html">365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TextField-mount_base.html">1061</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/TextField-mount.html">1212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Toggle-mount_base.html">633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/Toggle-mount.html">693</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/button-mount_base.html">94</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22921/perf-test/button-mount.html">98</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by micahgodbolt** [comment]
This is a duplicate of https://github.com/microsoft/fluentui/pull/22261

I closed that PR because we felt that setting peer deps to include react 18 meant that we officially supported React 18, which we do not yet do.

**Comment by lejimsft** [comment]
@micahgodbolt If not React 18, can we at least update to support ">=16.8.0 <18.0.0"?

**Comment by lejimsft** [comment]
Hi [dzearing](https://github.com/dzearing), , [ecraig12345](https://github.com/ecraig12345), [khmakoto](https://github.com/khmakoto), [Jahnp](https://github.com/Jahnp), [bigbadcapers](https://github.com/bigbadcapers), [ermercer](https://github.com/ermercer), [evlevy](https://github.com/evlevy), [Raghurk](https://github.com/Raghurk) and [JustSlone](https://github.com/JustSlone), can you review this PR, please? Thanks!

**Comment by micahgodbolt** [comment]
Yes, we should be able to support <18. that's the current support in v8 and v9

https://github.com/microsoft/fluentui/blob/master/packages/react-badge/package.json#L43-L44

**Pull request merged**
