### PR TITLE
Bugfix/fela plugin rtl defaults to rtl

### PR DESCRIPTION
**Pull request by marwan38**
## Current Behavior

The current implementation of the fela engine uses the `fela-plugin-rtl` to handle rtl styles. The RTL props passed through from the highest level, the @fluentui/react-northstar/Provider component, are not passed into the initial theming props of fela.

## New Behavior

Direction is passed down from @fluentui/react-northstar/Provider into fela.

## Related Issue(s)

This issue was found whilst running the test files for `felaRenderer-test`. There were false-negative asserting the output of having the direction set as rtl.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7b6300bec0ab6b1412817fe687dd438de3bcd8de'>7b6300bec0ab6b1412817fe687dd438de3bcd8de</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by layershifter** [comment]
@marwan38 can you please provide a repro on CodeSandbox for this case?

**Comment by marwan38** [comment]
@layershifter While setting up the sandbox, I realise that my mistake was in the implementation of a hook that I created.

```typescript

// This hook is a further abstraction onto the rendering engine to expose
// styling via the rendering engine to the consumer of this dependency.
// See usage example is below
export function useStyles(): {
  css(...rules: StyleRule<T>[]): string;
} {
  const renderer = getRenderer().getOriginalRenderer<IRenderer>(); // exported through a patch to the dependency to expose the renderer. Done for SSR.
  const { theme } = useFluentContext();

  const propsWithTheme = mergePropsWithTheme(props, theme);

  function css(...rules: StyleRule<T>[]) {
    return renderer.renderRule(
      combineRules(...(rules as unknown as TRule[])),
      propsWithTheme
    );
  }

  return {
    css
  };
}

// Example usage in consumer
const Component = () => {
  const { css } = useStyles();
  return <div className={css({ marginLeft: '8px' })}/>
}

```

My mistake was that `theme` exposed via the `useFluentContext()` does not include the `direction` property. This works well with the internal implementation of `useStyles` (not to be confused with the example above) because direction is injected into the fela renderer here: https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.

With all that said and done, I think that there still is a flaw within the rtl implementation of fela that is _proven to be faulty_ by adding this test: https://github.com/microsoft/fluentui/pull/23490/files#diff-975606746da4724d094be9032590d52f9e2f3eeb6cbc8cd66923d40b6cb7de43R106 paired with the (correctly) generated snapshot https://github.com/microsoft/fluentui/pull/23490/files#diff-f916a199f49fa100b725fa676218ba2481d477f987459809e06137052ea25a19R112

**Comment by layershifter** [comment]
> My mistake was that `theme` exposed via the `useFluentContext()` does not include the `direction` property. This works well with the internal implementation of `useStyles` (not to be confused with the example above) because direction is injected into the fela renderer here: https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.

Yeah, that's correct. We call `renderRule()` internally with proper params.

> With all that said and done, I think that there still is a flaw within the rtl implementation of fela that is proven to be faulty by adding this test: https://github.com/microsoft/fluentui/pull/23490/files#diff-975606746da4724d094be9032590d52f9e2f3eeb6cbc8cd66923d40b6cb7de43R106 paired with the (correctly) generated snapshot https://github.com/microsoft/fluentui/pull/23490/files#diff-f916a199f49fa100b725fa676218ba2481d477f987459809e06137052ea25a19R112

Agree, tests and snapshots should be updated. Would you mind to do these changes?

**Comment by marwan38** [comment]
> > My mistake was that `theme` exposed via the `useFluentContext()` does not include the `direction` property. This works well with the internal implementation of `useStyles` (not to be confused with the example above) because direction is injected into the fela renderer here: https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.
> 
> Yeah, that's correct. We call `renderRule()` internally with proper params.
> 
> > With all that said and done, I think that there still is a flaw within the rtl implementation of fela that is proven to be faulty by adding this test: https://github.com/microsoft/fluentui/pull/23490/files#diff-975606746da4724d094be9032590d52f9e2f3eeb6cbc8cd66923d40b6cb7de43R106 paired with the (correctly) generated snapshot https://github.com/microsoft/fluentui/pull/23490/files#diff-f916a199f49fa100b725fa676218ba2481d477f987459809e06137052ea25a19R112
> 
> Agree, tests and snapshots should be updated. Would you mind to do these changes?

@layershifter Not at all, I'd love to contribute to this. This PR includes that exact fix alongside with instantiating the Fela `ThemeProvider` to take in the direction too. This would mean that direction, along with some other of the params (Haven't done it in this pr), can be removed from https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.

Would you prefer that I create another PR to address the tests only rather than taking in this PR? Let me know how you would prefer me to proceed with this.

P.S. I made a silly push that tagged a bunch of contributors on this PR. I've fixed it, but, if you would please clean the list up for me. I don't think I have the permissions do to that. and I apologize for spamming all the others with my silly rebase.

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
AlertMinimalPerf.default | [218](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AlertMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.96:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AlertMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
HeaderMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/HeaderMinimalPerf.default.html) | [257](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.16:1
ChatWithPopoverPerf.default | [316](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatWithPopoverPerf.default.html) | [277](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.14:1
TableMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TableMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.13:1
ListCommonPerf.default | [554](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListCommonPerf.default.html) | [524](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListCommonPerf.default_base.html) | 1.06:1
DividerMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DividerMinimalPerf.default.html) | [282](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.05:1
RefMinimalPerf.default | [209](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RefMinimalPerf.default.html) | [200](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [506](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/IconMinimalPerf.default.html) | [483](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
AnimationMinimalPerf.default | [469](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AnimationMinimalPerf.default.html) | [453](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [452](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonSlotsPerf.default.html) | [436](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [307](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LayoutMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
RosterPerf.default | [947](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RosterPerf.default.html) | [909](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RosterPerf.default_base.html) | 1.04:1
ProviderMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ProviderMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.04:1
AttachmentMinimalPerf.default | [124](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AttachmentMinimalPerf.default.html) | [120](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [658](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DialogMinimalPerf.default.html) | [640](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [233](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/FlexMinimalPerf.default.html) | [227](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
ListNestedPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListNestedPerf.default.html) | [457](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListNestedPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [585](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LoaderMinimalPerf.default.html) | [567](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [719](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/MenuMinimalPerf.default.html) | [701](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [148](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/PortalMinimalPerf.default.html) | [143](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [571](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/StatusMinimalPerf.default.html) | [552](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
AttachmentSlotsPerf.default | [926](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AttachmentSlotsPerf.default.html) | [911](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.02:1
FormMinimalPerf.default | [348](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/FormMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.02:1
ListWith60ListItems.default | [519](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListWith60ListItems.default.html) | [509](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
PopupMinimalPerf.default | [531](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/PopupMinimalPerf.default.html) | [522](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.02:1
SliderMinimalPerf.default | [1455](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SliderMinimalPerf.default.html) | [1428](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [2308](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CustomToolbarPrototype.default.html) | [2261](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
TreeMinimalPerf.default | [693](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TreeMinimalPerf.default.html) | [682](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.02:1
TreeWith60ListItems.default | [138](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TreeWith60ListItems.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [137](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonMinimalPerf.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2266](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2253](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
ListMinimalPerf.default | [435](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListMinimalPerf.default.html) | [429](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1074](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1065](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [375](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [372](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [282](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SkeletonMinimalPerf.default.html) | [280](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3731](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3705](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
AccordionMinimalPerf.default | [122](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AccordionMinimalPerf.default.html) | [122](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1:1
BoxMinimalPerf.default | [283](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/BoxMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1265](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1271](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ChatMinimalPerf.default | [615](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatMinimalPerf.default.html) | [614](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [572](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DropdownManyItemsPerf.default.html) | [572](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3452](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/EmbedMinimalPerf.default.html) | [3451](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [631](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/HeaderSlotsPerf.default.html) | [634](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [998](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [998](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1430](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1427](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
SegmentMinimalPerf.default | [287](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SegmentMinimalPerf.default.html) | [287](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [2638](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DropdownMinimalPerf.default.html) | [2664](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
GridMinimalPerf.default | [273](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/GridMinimalPerf.default.html) | [276](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1078](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/InputMinimalPerf.default.html) | [1089](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
TableManyItemsPerf.default | [1589](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TableManyItemsPerf.default.html) | [1601](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [458](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CardMinimalPerf.default.html) | [466](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.98:1
ChatDuplicateMessagesPerf.default | [233](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [237](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.98:1
DatepickerMinimalPerf.default | [5140](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5219](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.98:1
ImageMinimalPerf.default | [308](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ImageMinimalPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.98:1
ReactionMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ReactionMinimalPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [358](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TextAreaMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
ToolbarMinimalPerf.default | [798](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ToolbarMinimalPerf.default.html) | [814](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.98:1
TooltipMinimalPerf.default | [945](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TooltipMinimalPerf.default.html) | [960](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.98:1
CarouselMinimalPerf.default | [382](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CarouselMinimalPerf.default.html) | [393](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.97:1
AvatarMinimalPerf.default | [149](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AvatarMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.96:1
VideoMinimalPerf.default | [536](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/VideoMinimalPerf.default.html) | [558](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.96:1
LabelMinimalPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LabelMinimalPerf.default.html) | [315](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.94:1
TextMinimalPerf.default | [241](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TextMinimalPerf.default.html) | [282](https://fluentuipr.z22.web.core.windows.net/pull/23490/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.85:1

</details><div id="perfComment9424"/>

**Comment by layershifter** [comment]
> P.S. I made a silly push that tagged a bunch of contributors on this PR. I've fixed it, but, if you would please clean the list up for me. I don't think I have the permissions do to that. and I apologize for spamming all the others with my silly rebase.

No worries, I cleaned up the list of reviewers 😉 

> @layershifter Not at all, I'd love to contribute to this. This PR includes that exact fix alongside with instantiating the Fela ThemeProvider to take in the direction too. This would mean that direction, along with some other of the params (Haven't done it in this pr), can be removed from https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.
>:
> Would you prefer that I create another PR to address the tests only rather than taking in this PR? Let me know how you would prefer me to proceed with this.

There is also `@fluentui/react-northstar-emotion-renderer` that relies on this API, so we can't change `resolveStyles`. Can you please update this PR to include only changes to tests?

**Comment by marwan38** [comment]
> > P.S. I made a silly push that tagged a bunch of contributors on this PR. I've fixed it, but, if you would please clean the list up for me. I don't think I have the permissions do to that. and I apologize for spamming all the others with my silly rebase.
> 
> No worries, I cleaned up the list of reviewers 😉
> 
> > @layershifter Not at all, I'd love to contribute to this. This PR includes that exact fix alongside with instantiating the Fela ThemeProvider to take in the direction too. This would mean that direction, along with some other of the params (Haven't done it in this pr), can be removed from https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-bindings/src/styles/resolveStyles.ts#L131.
> > :
> > Would you prefer that I create another PR to address the tests only rather than taking in this PR? Let me know how you would prefer me to proceed with this.
> 
> There is also `@fluentui/react-northstar-emotion-renderer` that relies on this API, so we can't change `resolveStyles`. Can you please update this PR to include only changes to tests?

Yes, of course. I'll do that tomorrow after work. I'll also look into the styles resolver and then open up a seperate PR later on. Thank you 🙂

**Comment by marwan38** [comment]
@layershifter I've updated this PR to only include the tests. I decided against my initial test change (defaulting direction to ltr) and instead being explicit about the direction to fit in more naturally with what is being tested.

**Comment by layershifter** [comment]
> @layershifter I've updated this PR to only include the tests. I decided against my initial test change (defaulting direction to ltr) and instead being explicit about the direction to fit in more naturally with what is already there. My initial test was "Direction is ltr by default" which is not the case, because, it's rtl by default (at the moment at least).

Actually, `ThemeProvider` in the test should be updated too (as it causes false positive snapshots):

```diff
  ReactDOM.render(
    <RendererProvider renderer={felaRenderer}>
-     <ThemeProvider theme={theme}>{component}</ThemeProvider>
+     <ThemeProvider theme={{ direction: 'ltr', ...theme }}>{component}</ThemeProvider> 
    </RendererProvider>,
    div,
  );
```

**Comment by layershifter** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/fluentui?pullRequest=23490) Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/fluentui?pullRequest=23490) before we can accept your contribution.❌ marwan38 [sign now](https://cla.opensource.microsoft.com/microsoft/fluentui?pullRequest=23490)You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/fluentui?pullRequest=23490) it.

@marwan38 please also sign CLA 😉

**Comment by layershifter** [comment]
image

@marwan38 please also update existing snapshots 🙏

**Comment by marwan38** [comment]
> 

That is odd, I thought it was only failing because of my environment as I was playing around with the deps. It should of not failed here, but, It seems like adding the provider must've changed something. Ah well, it's updated now. Thank you for being so patient with my first PR on github 🙏

**Review by layershifter — APPROVED** [review]

**Comment by marwan38** [comment]
@layershifter Something wrong with the PR bots?

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Comment by layershifter** [comment]
@marwan38 sorry, was sure that it have been already merged...

**Pull request merged**
