### PR TITLE
fix(web-components): Fixed pathing to types for package exports

### PR DESCRIPTION
**Pull request by mohamedmansour**
## Previous Behavior

When typechecking a project that uses package exports, it is throwing an error:
```
src/browser-essentials.ts:3:26 - error TS7016: Could not find a declaration file for module '@fluentui/web-components-v3/theme.js'.
  
 import { setTheme } from '@fluentui/web-components-v3/theme.js';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## New Behavior

The DTS should be correctly resolved since the package exports is pointing to the right one.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c271ab35c7160288de81b27a31627aa199a9afe3'>c271ab35c7160288de81b27a31627aa199a9afe3</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by mohamedmansour** [comment]
Hey @chrisdholt I never submitted a PR here, so I don't know what to do. When I build locally I am getting

``` 
ERR! [!] Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
ERR! https://rollupjs.org/guide/en/#using-untranspiled-config-files
ERR! Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
ERR!     at Object.error (c:\Code\fluentui\node_modules\rollup\dist\shared\rollup.js:198:30)
ERR!     at loadConfigFromBundledFile (c:\Code\fluentui\node_modules\rollup\dist\shared\loadConfigFile.js:630:27)
ERR!     at loadConfigFile (c:\Code\fluentui\node_modules\rollup\dist\shared\loadConfigFile.js:565:11)
ERR!     at Object.loadAndParseConfigFile (c:\Code\fluentui\node_modules\rollup\dist\shared\loadConfigFile.js:545:21)
ERR!     at getConfigs (c:\Code\fluentui\node_modules\rollup\dist\bin\rollup:1691:39)
ERR!     at runRollup (c:\Code\fluentui\node_modules\rollup\dist\bin\rollup:1665:43)
ERR!
ERR! npm ERR! Lifecycle script `build` failed with error:
ERR! npm ERR! Error: command failed
ERR! npm ERR!   in workspace: @fluentui/web-components@3.0.0-beta.0
ERR! npm ERR!   at location: c:\Code\fluentui\packages\web-components
```

**Comment by fabricteam** [comment]
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Review by chrisdholt — APPROVED** [review]
Copy/Paste is a killer - thanks for this fix @mohamedmansour!

**Pull request merged**
