### PR TITLE
chore(deps): bump engine.io from 6.2.0 to 6.2.1

### PR DESCRIPTION
**Pull request by Hotell**
replaces and fixes https://github.com/microsoft/fluentui/pull/26080

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                          |        Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------- | --------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                 |        `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr> |        `554 B`<br />`348 B` |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>   |  `3.153 kB`<br />`1.299 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                    | `23.357 kB`<br />`7.361 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                      | `24.247 kB`<br />`7.643 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                    | `24.001 kB`<br />`7.049 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                              | `16.515 kB`<br />`5.921 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                    | `10.836 kB`<br />`4.283 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                    |   `9.394 kB`<br />`3.88 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                      | `11.862 kB`<br />`4.885 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                            | `11.004 kB`<br />`4.188 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                 | `10.697 kB`<br />`3.938 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                 | `19.868 kB`<br />`7.432 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                              | `20.013 kB`<br />`6.446 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                     | `11.838 kB`<br />`4.625 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                   |  `15.148 kB`<br />`5.06 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>     |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>               | `30.908 kB`<br />`6.714 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>             | `17.776 kB`<br />`5.141 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                    |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/68c1cd93fd2b6250e1b20abf9682812f4467c12a'>68c1cd93fd2b6250e1b20abf9682812f4467c12a</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Avatar-mount_base.html">1564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Avatar-mount.html">1556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Button-mount_base.html">1161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Button-mount.html">1177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProvider-mount_base.html">1940</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProvider-mount.html">1907</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-mount_base.html">750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-mount.html">809</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">707</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">698</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">747</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/MakeStyles-mount_base.html">2367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/MakeStyles-mount.html">2323</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Persona-mount_base.html">3638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/Persona-mount.html">3615</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/SpinButton-mount_base.html">3087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test-react-components/SpinButton-mount.html">3036</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/BaseButton-mount_base.html">1522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/BaseButton-mount.html">1455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Breadcrumb-mount_base.html">3688</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Breadcrumb-mount.html">3714</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Checkbox-mount_base.html">3366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Checkbox-mount.html">3263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/CheckboxBase-mount_base.html">2985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/CheckboxBase-mount.html">2984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ChoiceGroup-mount_base.html">5486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ChoiceGroup-mount.html">5631</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ComboBox-mount_base.html">1600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ComboBox-mount.html">1537</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/CommandBar-mount_base.html">12068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/CommandBar-mount.html">12464</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ContextualMenu-mount_base.html">13959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ContextualMenu-mount.html">14518</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DefaultButton-mount_base.html">1749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DefaultButton-mount.html">1747</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRow-mount_base.html">4540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRow-mount.html">4618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRowFast-mount_base.html">4571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRowFast-mount.html">4605</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRowNoStyles-mount_base.html">4229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DetailsRowNoStyles-mount.html">4360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Dialog-mount_base.html">3875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Dialog-mount.html">3866</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DocumentCardTitle-mount_base.html">705</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/DocumentCardTitle-mount.html">694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Dropdown-mount_base.html">4019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Dropdown-mount.html">4097</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/FocusTrapZone-mount_base.html">2541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/FocusTrapZone-mount.html">2524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/FocusZone-mount_base.html">2489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/FocusZone-mount.html">2463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-mount_base.html">2403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-mount.html">2741</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-virtual-rerender_base.html">1436</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-virtual-rerender.html">1423</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">2164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedList-virtual-rerender-with-unmount.html">2130</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-mount_base.html">731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-mount.html">725</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-virtual-rerender_base.html">719</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-virtual-rerender.html">683</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">741</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/IconButton-mount_base.html">2438</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/IconButton-mount.html">2351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Label-mount_base.html">914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Label-mount.html">922</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Layer-mount_base.html">5491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Layer-mount.html">5445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Link-mount_base.html">1032</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Link-mount.html">1074</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/MenuButton-mount_base.html">2128</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/MenuButton-mount.html">2118</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/MessageBar-mount_base.html">2931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/MessageBar-mount.html">2901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Nav-mount_base.html">4104</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Nav-mount.html">4072</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/OverflowSet-mount_base.html">1709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/OverflowSet-mount.html">1717</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Panel-mount_base.html">3196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Panel-mount.html">3185</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Persona-mount_base.html">1652</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Persona-mount.html">1633</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Pivot-mount_base.html">2082</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Pivot-mount.html">2066</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/PrimaryButton-mount_base.html">1959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/PrimaryButton-mount.html">1904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Rating-mount_base.html">8818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Rating-mount.html">8814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SearchBox-mount_base.html">1853</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SearchBox-mount.html">1908</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Shimmer-mount_base.html">3652</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Shimmer-mount.html">3556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Slider-mount_base.html">2646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Slider-mount.html">2600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SpinButton-mount_base.html">5798</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SpinButton-mount.html">5815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Spinner-mount_base.html">1030</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Spinner-mount.html">1031</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SplitButton-mount_base.html">3797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SplitButton-mount.html">3882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Stack-mount_base.html">1053</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Stack-mount.html">1056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/StackWithIntrinsicChildren-mount_base.html">2950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/StackWithIntrinsicChildren-mount.html">2989</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/StackWithTextChildren-mount_base.html">6073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/StackWithTextChildren-mount.html">6070</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SwatchColorPicker-mount_base.html">13034</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/SwatchColorPicker-mount.html">13091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TagPicker-mount_base.html">3301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TagPicker-mount.html">3260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TeachingBubble-mount_base.html">107906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TeachingBubble-mount.html">108300</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Text-mount_base.html">1005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Text-mount.html">998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TextField-mount_base.html">1986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/TextField-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-mount_base.html">1946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-mount.html">1957</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-virtual-rerender_base.html">1368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-virtual-rerender.html">1371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2738</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2726</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Toggle-mount_base.html">1366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/Toggle-mount.html">1418</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/buttonNative-mount_base.html">698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26084/perf-test/buttonNative-mount.html">685</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUI-v0 No visual regressions between this PR and main
<div id="vrtCommentFluentUI-v0"/>

**Review by khmakoto — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
